
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate implementations of SHA-1 and SHA-2.

=== Test Types

There are three types of tests for SHA-1 and SHA-2: functional tests, Monte Carlo tests and Large Data tests. Each has a specific value to be used in the testType field. The testType field definitions are:

* "AFT" - Algorithm Functional Test. These tests can be processed by the client using a normal 'hash' operation.  AFTs cause the implementation under test to exercise normal operations on a single block, multiple blocks, or partial blocks. In all cases, random data is used. The functional tests are designed to verify that the logical components of the hash function (block chunking, block padding etc.) are operating correctly.

* "MCT" - Monte Carlo Test. These tests exercise the implementation under test under strenuous circumstances. The implementation under test must process the test vectors according to the correct algorithm and mode in this document. MCTs can help detect potential memory leaks over time, and problems in allocation of resources, addressing variables, error handling, and generally improper behavior in response to random inputs. Each MCT processes 100 pseudorandom tests. Each algorithm and mode SHOULD have at least one MCT group. See <<MC_test>> for implementation details.

* "LDT" - Large Data Test. This test performs the hash function on a message that is multiple gigabytes in length. This pushes the bounds of 32-bit data types to ensure an implementation can handle all types of data. See <<LDT>> for more information motivating the LDT. As a multiple gigabyte message cannot be communicated naturally via ACVP, a specific structure is outlined in <<LD_test>>.

[[MC_test]]
=== Monte Carlo tests for SHA-1 and SHA-2

The MCTs start with an initial condition (SEED which is a single message) and perform a series of chained computations. The algorithm is shown below.

NOTE: The MCTs were updated, 7/2023, to support the case where !SupportedMessageLengths.Contains(3*digestSize), a limitation of the original MCT design. As part of this change, a new property, mctVersion, was added to the MCT test group JSON (See <<vs_tg_table>>). When a value of "standard" is provided for mctVersion in the prompt file, the standard MCT test is run. When a value of "alternate" is provided for mctVersion in the prompt file, the alternate MCT test is run. When the standard test is run, the MSG hashed will always be 3 * the length of the SEED. When the alternate test is run, the MSG hashed will always be the length of the SEED.

SHA-1 and SHA-2 Standard Monte Carlo Test:
[source, code]
----
For j = 0 to 99
    A = B = C = SEED
    For i = 0 to 999
        MSG = A || B || C
        MD = SHA(MSG)
        A = B
        B = C
        C = MD
    Output MD
    SEED = MD
----

SHA-1 and SHA-2 Alternate Monte Carlo Test:
[source, code]
----
INITIAL_SEED_LENGTH = LEN(SEED)
For j = 0 to 99
    A = B = C = SEED
    For i = 0 to 999
        MSG = A || B || C
        if LEN(MSG) >= INITIAL_SEED_LENGTH:
            MSG = leftmost INITIAL_SEED_LENGTH bits of MSG
        else:
            MSG = MSG || INITIAL_SEED_LENGTH - LEN(MSG) 0 bits
        MD = SHA(MSG)
        A = B
        B = C
        C = MD
    Output MD
    SEED = MD
----

[[LD_test]]
=== Large Data tests for SHA-1 and SHA-2

The large data tests are intended to test the ability of a module to hash multiple gigabytes of data at once. This much information cannot be communicated via the JSON files as a normal message property. Instead a new type is defined as a large data type. It is an object that contains a small content hex string, a content length in bits, a full length in bits and an expansion technique string. The following is an example of this structure.

[source, json]
----
"largeMsg": {
    "content": "DE26",
    "contentLength": 16,
    "fullLength": 42949672960,
    "expansionTechnique": "repeating"
}
----

The 'contentLength' property describes the number of bits in the 'content' property. The 'content' property is the hex string that can be expanded to the full large message. The 'expansionTechnique' describes the process used to obtain the full large message. The 'fullLength' is the final length of the full large message.

There may be multiple 'expansionTechnique' types defined. Here are the types defined for SHA-1 and SHA-2 testing.

* "repeating" - Append the number of content bits specified in 'contentLength' to itself as many times as needed until a hex string of exactly 'fullLength' bits is acquired. In the example shown, the final large message would have the form "DE26DE26DE26...DE26".

There are multiple ways hash functions can be implemented in an IUT. The most common are via a single Hash() call on the message or via a series of Init(), any number of Update(), Final() calls. As noted in <<LDT>>, the difference between these hashing techniques can have consequences in the cryptographic module. If the hash function is implemented in the IUT via a series of Init(), Update(), and Final() calls, the IUT *MUST* process the large input message in its entirety in a single Update() call.
