
[[caps_reg]]

[[hash_caps_reg]]
=== HASH Algorithm Capabilities Registration

This section describes the constructs for advertising support of hash algorithms to the ACVP server.

[[caps_table]]
.Hash Algorithm Capabilities JSON Values
|===
| JSON Value | Description | JSON type

| algorithm | The hash algorithm and mode to be validated. | string
| revision | The algorithm testing revision to use. | string
| messageLength | The message lengths in bits supported by the IUT. Minimum allowed is 0, maximum allowed is 65536. | domain
| performLargeDataTest | Determines if the server should include the large data test group defined in <<LD_test>>. This property is *OPTIONAL*, and shall include the lengths in GiB being tested. Valid options are {1, 2, 4, 8}. | integer array
|===

The value of the algorithm property *MUST* be one of the elements from the list in <<supported_algs>>.

NOTE: The lengths provided in the 'performLargeDataTest' property are in gibibytes. 1GiB is equivalent to 2^30 bytes. 

NOTE: At least one messageLength > 0 must be supported by an IUT in order to accommodate MCT testing.

The following is a example JSON object advertising support for SHA-256.

[source, json]
----
{
    "algorithm": "SHA2-256",
    "revision": "1.0",
    "messageLength": [{"min": 0, "max": 65535, "increment": 1}],
    "performLargeDataTest": [1, 2]
}
----
