
[[tgjs]]
=== Test Groups

Test vector sets MUST contain one or many test groups, each sharing similar properties.                      For instance, all test vectors that use the same testType would be grouped together.  The testGroups element at the top level of the test vector JSON object SHALL be the array of test groups.  The Test Group JSON object MUST contain meta-data that applies to all test cases within the group.  The following table describes the JSON elements that MAY appear from the server in the Test Group JSON object:


[[vs_tg_table]]

[cols="<,<,<"]
.Test Group JSON Object
|===
| JSON Value| Description| JSON type

| tgId| Numeric identifier for the test group, unique across the entire vector set| integer
| testType| Test category type (AFT or MCT). See <<testtypes>> for more information| string
| tests| Array of individual test case JSON objects, which are defined in	<<tcjs>>| array of testCase objects
|===

All properties described in the previous table MUST appear in the prompt file from the server for every testGroup object.

[[tcjs]]
=== Test Case

Each test group *SHALL* contain an array of one or more test cases.  Each test case is a JSON object that represents a single case to be processed by the ACVP client.  The following table describes the JSON elements for each test case.

[[vs_tc_table]]

[cols="<,<,<"]
.Test Case JSON Object
|===
| JSON Value| Description| JSON type

| tcId| Numeric identifier for the test case, unique across the entire vector set.| integer
| len| Length of the message or MCT seed| integer
| msg| Value of the message or MCT seed in big-endian hex| integer
|===

All properties described in the previous table *MUST* appear in the prompt file from the server for every testCase object.
