
[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC7991,RFC 7991]]]
* [[[RFC8174,RFC 8174]]]

* [[[FIPS180-4,NIST FIPS 180-4]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01

[%bibitem]
=== The Secure Hash Algorithm Validation System (SHAVS)
id:: SHAVS
docid::
  id::: NIST SHAVS

// <reference anchor="SHAVS">
//   <front>
//     <title>The Secure Hash Algorithm Validation System (SHAVS)</title>

//     <author initials="L.E." surname="Bassham III">
//       <organization>NIST</organization>
//     </author>

//     <date year="2014"></date>
//   </front>
// </reference>

[%bibitem]
=== Extending NIST’s CAVP Testing of Cryptographic Hash Function Implementations
id:: LDT
docid::
  id::: LDT
// https://eprint.iacr.org/2019/1421.pdf
