[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS180-4>>.

[[sha-coverage]]
==== SHA Requirements Covered

Section 1 in <<FIPS180-4>> outlines the maximum message sizes for each hash function. Due to the large size (either 2^64 or 2^128 bits) of these maximums, they are tested by special request in this specification. These tests are performed by the optional LDTs.

Sections 3 and 4 in <<FIPS180-4>> outline the core functions used within the hash algorithms. Normal AFTs test these operations.

Section 5 outlines the hash function preprocessing. It is worth noting that not all test cases will cover the message padding process, but through the entire vector set, this operation will be fully tested.

[[sha-not-coverage]]
==== SHA Requirements Not Covered

Section 7 outlines digest truncation for applications where a shortened digest is needed. These operations are not tested via this specification.
