
[#properties]
=== Property Registration

The IKEv1 KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

[#registration]
=== Registration Example

A registration *SHALL* use these properties

.IKEv1 KDF Mode Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ikev1"
| revision | ACVP Test version | string | "1.0"
| capabilities | Array of objects describing capabilities | array | Contains each of the below properties
| authenticationMethod | The mode of authentication used by the IUT | string | "dsa", "psk", or "pke"
| initiatorNonceLength | The supported initiator nonce lengths used by the IUT in bits | domain | Min: 64, Max: 2048
| responderNonceLength | The lengths of data the IUT supports in bits | domain | Min: 64, Max: 2048
| diffieHellmanSharedSecretLength | The lengths of Diffie Hellman shared secrets the IUT supports in bits | domain | Min: 224, Max: 8192
| preSharedKeyLength | The lengths of pre-shared key the IUT supports in bits | domain | Min: 8, Max: 8192. Note this property is only required when "authenticationMethod" is "psk"
| hashAlg | Valid hash algorithms used by the IUT | array | See <<valid-sha>>
|===

An example registration within an algorithm capability exchange looks like this

[source, json]
----
"capability_exchange":
[
    {
        "algorithm": "kdf-components",
        "mode": "ikev1",
        "revision": "1.0",
        "prereqVals": [
            {
                "algorithm": "SHA",
                "valValue": "same"
            }
        ],
        "capabilities": [
            {
                "authenticationMethod": "dsa",
                "initiatorNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "responderNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "diffieHellmanSharedSecretLength": [
                    {
                        "min": 224,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "hashAlg": [
                    "sha-1",
                    "sha2-224",
                    "sha2-256",
                    "sha2-384",
                    "sha2-512"
                ]
            },
            {
                "authenticationMethod": "psk",
                "initiatorNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "responderNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "preSharedKeyLength": [
                    {
                        "min": 8,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "diffieHellmanSharedSecretLength": [
                    {
                        "min": 224,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "hashAlg": [
                    "sha-1",
                    "sha2-224",
                    "sha2-256",
                    "sha2-384",
                    "sha2-512"
                ]
            },
            {
                "authenticationMethod": "pke",
                "initiatorNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "responderNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "diffieHellmanSharedSecretLength": [
                    {
                        "min": 224,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "hashAlg": [
                    "sha-1",
                    "sha2-224",
                    "sha2-256",
                    "sha2-384",
                    "sha2-512"
                ]
            }
        ]
    }
]
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
