
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

[source, json]
----
{
    "tgId": 1,
    "tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| sKeyId | Results of the extraction step | hex
| sKeyIdD | Results of the expansion step | hex
| sKeyIdA | Results of the expansion step | hex
| sKeyIdE | Results of the expansion step | hex
|===

Here is an abbreviated example of the response

[source, json]
----
{
  "vsId": 1,
  "algorithm": "kdf-components",
  "mode": "IKEv1",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "sKeyId": "FC3A8E843CC28415C6113CEAAA763CD486615465",
          "sKeyIdD": "27A3DF58BF1CADF914CDCCB0F975D62486EA12BF",
          "sKeyIdA": "4D49AF6F8F23F4068FDDD53D505667BE54AAB91C",
          "sKeyIdE": "D0A2F20796D66A2875477F33DEA577F98A0C2F7B"
        },
        {
          "tcId": 2,
          "sKeyId": "7E1DB4F5571B9CC856DA9DA442431A50AA9799AD",
          "sKeyIdD": "65D6E37837A89C21D4DE1D6AA36CEBF103BA51F3",
          "sKeyIdA": "B9D7E7DBDBEA0203BFE7EC073BB140FE129A0D72",
          "sKeyIdE": "FCB7F5662704E89F1B151512F5B555D95F29B356"
        }
      ]
    },
    {
      "tgId": 2,
      "tests": [
        {
          "tcId": 3,
          "sKeyId": "1E7A2129CF7D0E3FC22E32BF1DFF414258342BA9",
          "sKeyIdD": "4B2E07B4C446DF40C90C06F294C9F05B2A174A8B",
          "sKeyIdA": "90682451AA897E7F9BC6E670F205929D2EBA2FD8",
          "sKeyIdE": "2B138E6AB5FFCE8D345F9C69313DC4798A14E709"
        },
        {
          "tcId": 4,
          "sKeyId": "DCF270CE93FDD59B903CD60434AF075C8F9547A5",
          "sKeyIdD": "E5DF0DE718321B9C7A0BEB953B05D7B088699F3F",
          "sKeyIdA": "64816D06241E98E0B18945112CBDB17B48BB3310",
          "sKeyIdE": "63E7A74ACD8B9549182C06E37D01CB82B8DC6B44"
        },
      ]
    },
    {
      "tgId": 3,
      "tests": [
        {
          "tcId": 5,
          "sKeyId": "CA0226BF4066CA296DCC3EDB9A84F14A3F2B72B1",
          "sKeyIdD": "77EAE9AAB8E9CD74B5A423A3D3C7D271FB192CA4",
          "sKeyIdA": "5BCFA7A2A116DB14F003DC3EDC169D4FABDE8AF7",
          "sKeyIdE": "27C368F57B4219D989DBB52FDFF0999B34E29787"
        },
        {
          "tcId": 7,
          "sKeyId": "BD7120223435EF4E8A818F1322CC9DDAF9675682",
          "sKeyIdD": "87DB18ED75177847B1F7FE63B0C4C8AB5715EBFF",
          "sKeyIdA": "844EE67A460FF7F0F9EA36A5308DA4108C7A6434",
          "sKeyIdE": "2094E6217E39224B8D2C98BE3FE24959632F1BAF"
        },
      ]
    }
  ]
}
----
