
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KDAs specific to the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KDA capabilities. This section describes the design of the tests used to validate implementations of KDA algorithms. 

=== Test Types
				
There are two test types for KDA testing:

* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Agreement with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to perform a successful key agreement; both the server and IUT *MAY* act as party U/V.

* "VAL" - Validation Test. In the VAL test mode, The ACVP server *MUST* generate a complete (from both party U and party V's perspectives) key agreement, and expects the IUT to be able to determine if that agreement is valid. Various types of errors *MUST* be introduced in varying portions of the key agreement process that the IUT *MUST* be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Cr1>> and <<SP800-56Cr2>>. 

==== Requirements Covered

* SP 800-56C - 4 One-Step Key Derivation.  All functionality described in the specification is covered by ACVP testing.

==== Requirements Not Covered

* SP 800-56Ar3 / SP 800-56Br2 - ASN.1 encoding for the KDA is not currently supported.