[[tgjs]]
=== Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test	groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped	together. The Test Group JSON object contains meta data that applies to all test vectors within	the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group Properties
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Describes the operation the client should perform on the tests data | string
| tests | Array of individual test cases | See <<testCase>>
| kdfConfiguration | Describes the  KDA configuration values used for the group | See <<kdfconfig>>
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' the group is addressing.

[#kdfconfig]
====  kdfConfiguration JSON Schema

Describes the  KDA configuration for use under the test group.

.KdfConfiguration JSON Object
|===
| JSON Value | Description | JSON Type

| kdfType | The type of  KDA to use for the group. | value - onestep
| saltMethod |  The strategy used for salting. | value - default (all 00s), random
| fixedInfoPattern | The pattern used for constructing the fixedInfo. | value - See <<fixedinfopatcon>>.
| fixedInfoEncoding | The pattern used for constructing the fixedInfo. | value - See <<fixedinfopatcon>>.
| auxFunction | The auxiliary function used in the KDA.| value - See <<auxfunc>>.
| l | the bit length of keying material to derive from the  KDA | value
|===

[[testCase]]
=== Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each KAS/KTS ECC test vector.

.Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Numeric identifier for the test case, unique across the entire vector set.| integer
| kdfParameter | Object representing inputs into the  KDA | See <<kdfParameter>>.
| fixedInfoPartyU | Fixed information specific to party U | See <<fixedInfo>>.
| fixedInfoPartyV | Fixed information specific to party V | See <<fixedInfo>>.

|===

[[kdfParameter]]
====  kdfParameter JSON Schema

 KDA specific options used for the test case.

.KDF Parameter JSON Object
|===
| JSON Value | Description | JSON Type

| kdfType | The type of KDA utilized. | value
| salt | The salt used for the test case. | value
| iv | The iv used for the test case. | value
| algorithmId | The random "algorithID" used for the test case when applicable to the fixedInfo pattern. | value
| context | The random "context" used for the test case when applicable to the fixedInfo pattern. | value
| label | The random "label" used for the test case when applicable to the fixedInfo pattern. | value
| z | shared secret z value to be used for the test case. | value
| t | auxiliary shared secret t.  For <<SP800-56Cr2>> only. | value
| l | the bit length of keying material to derive from the KDA | value
|===

[[fixedInfo]]
==== FixedInfo PartyU/V JSON Schema

Fixed information that is included for party U/V for fixed info construction

.Fixed Info JSON Object
|===
| JSON Value | Description | JSON Type

| partyId | The party identifier | value
| ephemeralData | Ephemeral data (randomly) included as a part of the parties fixed info construction | value
|===

[[app-vs-ex]]
=== Example Test Vectors JSON

The following is a example JSON object for  KDA OneStep test vectors sent from the ACVP server to the crypto module.  Note there is no difference in the vector set properties for OneStep testing between <<SP800-56Cr1>> and <<SP800-56Cr2>> aside from the new "t" secondary shared secret that can be used for a <<SP800-56Cr2>> Fixed info pattern (See <<fixedinfopatcon>>).

.Vector Set JSON Example
[source,json]
---- 
{
  "vsId": 0,
  "algorithm": "KDA",
  "mode": "OneStep",
  "revision": "Sp800-56Cr2",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "testType": "AFT",
      "tests": [
        {
          "tcId": 1,
          "kdfParameter": {
            "kdfType": "oneStep",
            "salt": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "t": "F3FB51C366F869E53192CABC5E2F4208",
            "z": "A03F59A0430F6B8A63E8B726304BB4AF6F3DCAA83A5EF513B760AC119892452FF924",
            "l": 1024
          },
          "fixedInfoPartyU": {
            "partyId": "2EC1ABD29DB705FE823170D1F4E36774",
            "ephemeralData": "19E1AADF914B002032C9823F9D48E741C6BEB6B9161C9DA50D2E5D77D3F3A747A154"
          },
          "fixedInfoPartyV": {
            "partyId": "E7FEEFE1E48C63A3976B9380F8F7B74C"
          }
        },
        {
          "tcId": 2,
          "kdfParameter": {
            "kdfType": "oneStep",
            "salt": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "t": "1B7208051A8DB7BEF1722348412B9AAA",
            "z": "692D283394CC8A18D41192C53B7E8414C7B58AC848347B4FF0A7A8C3EAAE55F398F5",
            "l": 1024
          },
          "fixedInfoPartyU": {
            "partyId": "03EE75BCF6D4579982D6BF785CABBE62",
            "ephemeralData": "2FC99BA2181ABD6EA1FCAD544F59DF09E6CB4E26BC13DC38D2D94461D2BA9CEDF33E"
          },
          "fixedInfoPartyV": {
            "partyId": "A8AD9A85A59DED9F1749ECA7CD3F34F5",
            "ephemeralData": "267210D31B561067AF41951D3EFD0EF2C7E4139D30C129A364189F409FEF0B24E48F"
          }
        },
        {
          "tcId": 3,
          "kdfParameter": {
            "kdfType": "oneStep",
            "salt": "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
            "t": "B5ED89A0792F82278F97C5159CC77CE0",
            "z": "F6A6792DC7D162E80A5F4637D05EF455199F79F36696F5A7C0CECC4009C63A9D992E",
            "l": 1024
          },
          "fixedInfoPartyU": {
            "partyId": "B58EC1F8A21E54CEFA3BD7CB74008E5C",
            "ephemeralData": "ED1BD32712BC28E30263B87E4D2A78640AA04E2E9207FBDE21BBDB56615D57F83387"
          },
          "fixedInfoPartyV": {
            "partyId": "53F0C1C6FF5DB61099AA2CFE9EAD45A6"
          }
        }
      ],
      "kdfConfiguration": {
        "kdfType": "oneStep",
        "l": 1024,
        "saltLen": 1312,
        "saltMethod": "default",
        "fixedInfoPattern": "t||uPartyInfo||vPartyInfo||l",
        "fixedInfoEncoding": "concatenation",
        "auxFunction": "KMAC-128"
      }
    }   
  ]
}
----