[#responses]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response Properties
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Test Group Response Properties
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors.  Several algorithms *SHALL* require the client to send back group level properties in their response.  This structure helps accommodate that.

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Response Properties
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| testPassed | Was the provided `dkm` valid? Only valid for the "VAL" test type. | boolean
| dkm | The derived keying material. Provided by the IUT for "AFT" test type test cases. For single expansion tests. | hex
| dkms | The derived keying materials. Provided by the IUT for "AFT" test type test cases. For multi expansion groups. | array of hex

|===

Here is an abbreviated example of the response.  Note there is no difference in the vector set response for OneStep testing between <<SP800-56Cr1>> and <<SP800-56Cr2>>.

=== Example Test Vectors Response JSON
.Example Response JSON SP800-56Cr1
[source,json]
----
{
  "vsId": 0,
  "algorithm": "KAS-KDF",
  "mode": "OneStep",
  "revision": "Sp800-56Cr1",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "dkm": "C91D23ED66A9A9E487FC5608B26F4B66401BCC38A09F52A3DC638D73AFE474CCB70A461CFC68FDBE0C41C406438D49DFD9B0FAC17886542AB3C6204425458958BAD042940919D6AD3D3A7894C19EDEED6DCC56DF775DD609623763D4CA1D048C2396EE204956028EE690110405EB5F3371DBF1C4BC131E7E7FCDEB97D12EED5D"
        },
        {
          "tcId": 2,
          "dkm": "D2DDA9897416B2994EA3C42AC36D0BD18E65A16A8DDA689EB2D1DC6D8830D902BB9D5B4BF9DE247A02E8A6AE3881F1D7CB101E7FED9199E3D4B13C06D7E8A197D55CBA8D412DC85457700FB38FFFB21C597671D19638D850EC37028F11D887E6EF9F6A8059C022D07EB88A505F44F54DEB21AD577633B42031C787C0E96209CA"
        },
        {
          "tcId": 3,
          "dkm": "7C6F142D087D055FEFEB044AF5069E0A12589039FBFEEE2206439B86452EF5591469DD82AB83E8527FA2CFD6DB51C6068D3C046CFCC29B1F8B8CD5F0A3BC4FF0AF5A4D43B66F465B01FA3D255FE6962C06E54421EE5776E822DE4AD03F91F127D2A3113CE4841F1655CF214D5C205AC5EF122EF84502B53EB3A1DC4355A2A982"
        },
        {
          "tcId": 4,
          "dkm": "38702289323D6123CB1F274106DA6F96E9CF6ACBFDEF5A17EA8A7FF07D1019B006E7FBDB454D63E7AF121F13BBACA7B6158E18F9FF582E02B97022A570A1C890457A1EBB0FDE58069FCCB1FCB405CF72E099312A829855C59973D4F58CB9D791F5D40EFEB2F925484BDCE6915B5D6B48E899A35E9FC80A1E356F7BC4D02CE2AF"
        },
        {
          "tcId": 5,
          "dkm": "63179FFD195A08CD0884D0E7556BDE51209686655267CDFADE2C7DB0462246CE2E8305F9B0AC1EA1296B21E9B7F618E9D699B49B8BAA56B30F586D4B3F44440F9AECDB62AAFB9BCFC4DD17E0E74A6F24E8547540619860CDD3E501EAB64C49141726C74B7CA3CEC981401F14BD924F12492B057FD7F86600C081C34649C735D6"
        }
      ]
    },
    {
      "tgId": 62,
      "tests": [
        {
          "tcId": 306,
          "testPassed": true
        },
        {
          "tcId": 307,
          "testPassed": true
        },
        {
          "tcId": 308,
          "testPassed": true
        },
        {
          "tcId": 309,
          "testPassed": true
        },
        {
          "tcId": 310,
          "testPassed": false
        }
      ]
    }    
  ]
}
----

.Example Response JSON SP800-56Cr2
[source,json]
----
{
  "vsId": 0,
  "algorithm": "KAS-KDF",
  "mode": "TwoStep",
  "revision": "Sp800-56Cr2",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "dkm": "172B0AE028CB09306CA6AEFA17AB09BE8425B3F2BDD23EED544E0DB7A0235BDA4B033E943D5D85C32B748BB825AC5DA843966A0E0484BFD1A532F794B20EFB1E"
        },
        {
          "tcId": 2,
          "dkm": "7D354541FAF19904E030ED8D5BDF7F5B0A922782CF7739498D8290245AE4FAD37C8F2D3313F1AE1433BC3E68885D199E73670ABEE5ED460804907E8532EA9EF6"
        }
      ]
    },
    {
      "tgId": 2,
      "tests": [
        {
          "tcId": 6,
          "dkms": [
            "9A78CCE443803B9DDFC24059E9E55322E3A2AC2A610E311B9F09C03F433B2B4DC1B34F82B7A749D6B5F5F1023E4107F981A207F512DA9221B726696C93F9CDEA",
            "DFA32FFC8D7CEF8DB966A060DF3B057C0441BA0BD9F47130E6CBA5FBB70E5052CE073A8CDDED2E246DC31FF16EA84E1D6FA569DFF2516D69D99937C7A9157A6D",
            "5285A2B15C84DF8406ACFE2376AE34D449B9907455E40BE28FC093AC44EF2240AE4ED17ACCEECDB3C862570F451EE3B03C52D477363FCE0AA7143608CBE3180A",
            "850D83899FF9B776669AC2DD4A1B0EE36DFD5BEE64DDB48FC29F30C7CA3070D0AE321283F433913A310B07805041F3632C113FA9A578153BE8A5D61E3A043925"
          ]
        },
        {
          "tcId": 7,
          "dkms": [
            "6D790D62C4FA908C1E5E30A70EC99C02D66CCDDF17F2D2736749FB8BB22BEEB3013546511CA2C7F082AD4F61AB4ADCD88F7350A4D6CDBB3534A7E0E706D494E2",
            "5534529DC884F95AAB14C19075427C7FFF6D897DE187A8C08EF4FC53ECBDA5EADDE0F3CA78A1BD2D7B47C039BD9940100F9E09A502C9CF7770EF5A026E27897E"
          ]
        }
      ]
    },
    {
      "tgId": 65,
      "tests": [
        {
          "tcId": 321,
          "testPassed": true
        },
        {
          "tcId": 322,
          "testPassed": true
        }
      ]
    },
    {
      "tgId": 66,
      "tests": [
        {
          "tcId": 326,
          "testPassed": true
        },
        {
          "tcId": 327,
          "testPassed": false
        }
      ]
    }
  ]
}
----