[[XECDH_SSC_tgjs]]
=== XECDH SSC Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same curve would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the JSON elements of the Test Group JSON object.

The test group for XECDH / SSC / RFC7748 is as follows:

[[XECDH_SSC_vs_tg_table5]]
.XECDH SSC Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| curve | The curve type used for the test vectors | string
| testType | The testType for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<XECDH_SSC_tvjs>> | array
|===

[[XECDH_SSC_tvjs]]
=== XECDH SSC Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each XECDH test vector.

[[XECDH_SSC_vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| publicServer | The (little-endian encoded) server's XECDH public key | hex
|===

NOTE: The client is responsible for generating a single key pair per test case.

The following is an example of a prompt for XECDH / SSC / RFC7748

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1234,
        "algorithm": "XECDH",
        "mode": "SSC",
        "revision": "RFC7748",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "curve": "Curve25519",
                "tests": [
                    {
                        "tcId": 1,
                        "publicServer": "47765AC7B6..."
                    },
                    {
                        "tcId": 2,
                        "publicServer": "F00F87E4CC..."
                    },
                    {
                        "tcId": 3,
                        "publicServer": "8DD0547F17..."
                    }
                ]
            }
        ]
    }
]
----
