[[XECDH_keyGen_responses]]
=== XECDH keyGen Test Group Responses

The following table describes the JSON object that represents a test group response for XECDH / keyGen / RFC7748.

[[XECDH_keyGen_vr_top_table2]]
.XECDH keyGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Unique numeric identifier for the test group | integer
| tests | Array of JSON objects that represent each result, as defined by the table below | array
|===

The following table describes the JSON object that represents a test case response for XECDH / keyGen / RFC7748.

[[XECDH_keyGen_vr_top_table5]]
.XECDH keyGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| privateKey | The (little-endian encoded) private key | hex
| publicKey | The (little-endian encoded) public key | hex
|===

The following is an example of the response for XECDH / keyGen / RFC7748

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1234,
        "testGroups": [
            {
                "tgId": 1,
                "tests": [
                    {
                        "tcId": 1,
                        "privateKey": "9DD56FCF1E...",
                        "publicKey": "9A77B54FE9..."
                    }
                ]
            }
        ]
    }
]
----
