
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate {spec-algorithm} implementations.

=== Test Types

There is only one test type: functional tests. Each has a specific value to be used in the testType field. The testType field definition is:

* "AFT" - Algorithm Functional Test. These tests can be processed by the client using a normal 'derive_key' operation. AFTs cause the implementation under test to exercise normal operations on a single block, multiple blocks, or partial blocks. In all cases, random data is used. The functional tests are designed to verify that the logical components of the key deriviation process are operating correctly.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-135>>.

[[tpm-coverage]]
==== TPM Requirements Covered

In <<SP800-135>>, TBD.

[[tpm-not-coverage]]
==== TPM Requirements Not Covered

Some requirements in the outlined specification are not easily tested. Often they are not ideal for black-box testing such as the ACVP.In <<SP800-135>>, TBD.
