
[[tgjs]]
=== Test Groups JSON Schema
The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set.  For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The KDF test group for TPM is as follows:

[cols="<,<,<,<"]
[[vs_tg_table8]]
.Vector Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| tests | Array of individual test vector JSON objects, which are defined in <<tvjs>> | array
|===

[[tvjs]]
=== Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each SP800-135 TPM KDF test vector.

[[vs_tc_table8]]
[cols="<,<,<,<"]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| auth | Value of the authentication | hex
| nonceEven | Value of the nonce even | hex
| nonceOdd | Value of the nonce odd | hex
|===

An example of the prompt for kdf-components / TPM / 1.0 is the following

[source, json]
----
[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 1564,
    "algorithm": "kdf-components",
    "mode": "tpm",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "tcId": 2170,
            "auth": "fd771b263f6be051a1d7eb0c5138fbfcafbd49de",
            "nonceEven": "6b8790fd56b2b74734ea97db727ac9eb16e69831",
            "nonceOdd": "4fa48de2db65fa7082f4acc9f85ecc81d40d1793"
          }
        ]
      }
    ]
  }
]
----
