
[[vector_responses]]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[vr_top_table]]
[cols="<,<,<"]
.Vector Set Response JSON Object
|===
| JSON Value | Description | JSON type

| acvVersion | Protocol version identifier | string
| vsId | Unique numeric identifier for the vector set | integer
| testGroups | Array of JSON objects that represent each test vector group. See <<vr_group_table>> | array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

[[vr_group_table]]
[cols="<,<,<"]
.Vector Set Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group Id | integer
| tests | The tests associated to the group specified in tgId | array
|===

The following table describes the JSON object that represents a test results response from a TPM crypto module.

[cols="<,<,<"]
[[vr_top_table8]]
.Vector Set Results Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| sKey | Shared key value | hex
|===

An example of the vector set results response is provided below.

[source, json]
----
[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 1564,
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "tcId": 2170,
            "sKey": "c431a158b7b77d7e993515f8ebc2cd6add53b702"
          }
        ]
      }
    ]
  }
]
----
