
[#properties]
=== Property Registration

The SNMP KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

[#registration]
=== Registration Example

A registration *SHALL* use these properties

.SNMP KDF Mode Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "snmp"
| revision | ACVP Test version | string | "1.0"
| engineId | Two distinct engine IDs in hexadecimal | array | hex between 9 and 32 bytes (18-64 characters)
| passwordLength | Password lengths in bits, supported by the IUT, only complete bytes are allowed | domain | Min: 64, Max: 8192, Inc: 8
|===

An example registration within an algorithm capability exchange looks like this

[source, json]
----
{
    "algorithm": "kdf-components",
    "mode": "snmp",
    "revision": "1.0",
    "engineId": [
        "12345678912345678900",
        "abcdef0123456789abcdef1234567890"
    ],
    "passwordLength": [
        64,
        8192
    ]
}
----
