
[#properties]
=== Property Registration

The SSH KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

// [#registration]
// === Registration Example

A registration *SHALL* use these properties

.SSH KDF Mode Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ssh"
| revision | ACVP Test version | string | "1.0"
| cipher | Block ciphers supported | array | TDES, AES-128, AES-192, AES-256
| hashAlg | Valid hash algorithms used by the IUT | array | See <<valid-sha>>
|===

An example registration within an algorithm capability exchange looks like this.

[source, json]
----
"capability_exchange":
[
    {
        "algorithm": "kdf-components",
        "mode": "ssh",
        "revision": "1.0",
        "hashAlg": [
            "SHA-1",
            "SHA2-224",
            "SHA2-256",
            "SHA2-384",
            "SHA2-512"
        ],
        "cipher": [
            "TDES",
            "AES-128",
            "AES-192",
            "AES-256"
        ]
    }
]
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
