
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following.

[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following.

[source, json]
----
{
    "tgId": 1,
    "tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| initialIvClient | Client to server initial IV | hex
| initialIvServer | Server to client initial IV | hex
| encryptionKeyClient | Client to server encryption key | hex
| encryptionKeyServer | Server to client eencryption key | hex
| integrityKeyClient | Client to server integrity key | hex
| integrityKeyServer | Server to client integrity key | hex
|===

Here is an abbreviated example of the response.

[source, json]
----
{
  "vsId": 1,
  "testResults": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "initialIvClient": "D58275F599E68471",
          "encryptionKeyClient": "D1B16D92ED9AB...",
          "integrityKeyClient": "E7F57D7BFFFB58...",
          "initialIvServer": "3F48A283BF85F147",
          "encryptionKeyServer": "289241764AB45...",
          "integrityKeyServer": "9EE185ACDFE192..."
        }
      ]
    }
  ]
}
----
