
[bibliography]
== References

* [[[RFC2119,RFC 2119]]]
* [[[RFC4251,RFC 4251]]]
* [[[RFC8174,RFC 8174]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
    id::: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01

[%bibitem]
=== SP800-135r1 Recommendation for Existing Application-Specific Key Derivation Functions
id:: SP800-135
docid::
    id::: SP800-135
link::
link.type:: src
link.content:: https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-135r1.pdf
contributor::
contributor.role:: author
contributor.person.name.initial:: Q.
contributor.person.name.surname:: Dang
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2011-12
