
[#properties]
=== Property Registration

The SRTP KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

A registration *SHALL* use these properties

.SRTP KDF Mode Capabilities JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values | Optional

| algorithm | Name of the algorithm to be validated | string | "kdf-components" | No
| mode | Mode of the algorithm to be validated | string | "srtp" | No
| revision | ACVP Test version | string | "1.0" | No
| aesKeyLength | AES Key sizes the IUT supports | array | Any non-empty subset of {128, 192, 256} | No
| supportsZeroKdr | Whether or not the IUT supports an empty KDR | boolean | true, false | No 
| kdrExponent | Key Derivation Rate as an exponent of 2 | array | [0, .., 24] | Yes (if none of the valid values are supported)
| supports48BitSrtcpIndex | Whether or not the IUT uses a 48-bit quantity, i.e., `000...0 \|\| 0 \|\| SRTCP
index`, in the SRTCP key derivation vs a 32-bit quantity, i.e., `0 \|\| SRTCP index` | boolean | true, false | Yes
|===

NOTE: In the "kdrExponent" array a supported value of 3 corresponds to an actual KDF of 2\^3 or "04" in hex, as the third least significant bit is a 1. If no elements of this array are supported, then it *MAY* be excluded. If this is the case, then the IUT *MUST* support an empty KDR via "supportsEmptyKdr" set to true.

NOTE: When the "supports48BitSrtcpIndex" property is present and set to true, the tests *SHALL* assume that the IUT uses a 48-bit quantity, i.e., `000...0 || 0 || SRTCP index`, in the SRTCP key derivation in line with IETF RFC Errata ID 3712 and https://csrc.nist.gov/csrc/media/publications/sp/800-135/rev-1/final/documents/sp800-135r1-informative-note-20160919.pdf. When "supports48BitSrtcpIndex" is ommited or set to false, the tests *SHALL* assume that the IUT uses a 32-bit quantity, i.e., `0 || SRTCP index`, in the SRTCP key derivation as per the original RFC 3711.

An example registration within an algorithm capability exchange looks like this.

[align=left,alt=,type=]
[source, json]
----
"capability_exchange":
[
    {
        "algorithm": "kdf-components",
        "mode": "srtp",
        "revision": "1.0",
        "aesKeyLength": [
            128,
            192,
            256
        ],
        "supportsZeroKdr": true,
        "kdrExponent": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24
        ],
        "supports48BitSrtcpIndex": true
    }
]
----
