
[#properties]
=== Property Registration

The SRTP KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

A registration *SHALL* use these properties

.SRTP KDF Mode Capabilities JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "srtp"
| revision | ACVP Test version | string | "1.0"
| aesKeyLength | AES Key sizes the IUT supports | array | Any non-empty subset of {128, 192, 256}
| supportsZeroKdr | Whether or not the IUT supports an empty KDR | boolean | true, false
| kdrExponent | Key Derivation Rate as an exponent of 2 | array | [0, .., 24]
|===

NOTE: In the "kdrExponent" array a supported value of 3 corresponds to an actual KDF of 2\^3 or "04" in hex, as the third least significant bit is a 1. If no elements of this array are supported, then it *MAY* be excluded. If this is the case, then the IUT *MUST* support an empty KDR via "supportsEmptyKdr" set to true.

An example registration within an algorithm capability exchange looks like this.

[align=left,alt=,type=]
[source, json]
----
"capability_exchange":
[
    {
        "algorithm": "kdf-components",
        "mode": "srtp",
        "revision": "1.0",
        "aesKeyLength": [
            128,
            192,
            256
        ],
        "supportsZeroKdr": true,
        "kdrExponent": [
            0,
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24
        ]
    }
]
----
