
[[tgjs]]
=== Test Groups

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Test operations to be performed | string
| aesKeyLength | The AES Key Length used in the CMAC within the test group | integer
| kdr | The Key Derivation Rate used | hex
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case idenfitier | integer
| masterKey | Master key value | hex
| masterSalt | Master salt value | hex
| index | Index value for the SRTP key derivation | hex
| srtcpIndex | Index value for the SRTCP key derivation | hex
|===

Here is an abbreviated yet fully constructed example of the prompt.

[align=left,alt=,type=]
[source, json]
----
{
    "vsId": 1,
    "algorithm": "kdf-components",
    "mode": "srtp",
    "revision": "1.0",
    "testGroups": [
        {
            "tgId": 1,
            "kdr": "00",
            "aesKeyLength": 128,
            "tests": [
                {
                    "tcId": 1,
                    "masterKey": "AD16913E52D9C2A6D8E1D3CB90E4FDAD",
                    "masterSalt": "2AB06C2BCC07C7AF364F3BE6EAEC",
                    "index": "B18C1C4ED637",
                    "srtcpIndex": "000020FB9BB3"
                }
            ]
        }
    ]
}
----
