
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following:

[align=left,alt=,type=]
[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following:

[align=left,alt=,type=]
[source, json]
----
{
    "tgId": 1,
    "tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| srtpKe | SRTP encryption key | hex
| srtpKa | SRTP authentication key | hex
| srtpKs | SRTP salting key | hex
| srtcpKe | SRTCP encryption key | hex
| srtcpKa | SRTCP authentication key | hex
| srtcpKs | SRTCP salting key | hex
|===

Here is an abbreviated example of the response:

[align=left,alt=,type=]
[source, json]
----
{
  "vsId": 1,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "srtpKe": "94AD7DB37D198F049375BD461E90D9E5",
          "srtpKa": "51E18978366B7EFF4E3EE57DCBC50636AAF19F39",
          "srtpKs": "7157797656C383BD69192B036C0A",
          "srtcpKe": "5707D07782D6FE0030635106A487D97C",
          "srtcpKa": "097ECF3E2965DF071180F5F126C2D54A548B902F",
          "srtcpKs": "72DF8546DDB209875A5209786E4B"
        }
      ]
    }
  ]
}
----
