
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the IUT's xofDRBG in order to assess the correctness and robustness of the implementation. A typical ACVP validation session would require multiple tests to be performed for every supported permutation of DRBG capabilities. This section describes the design of the tests used to validate implementations of the xofDRBG algorithms. There is a single test type for xofDRBG testing:

* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *MUST* be capable of injecting the values provided by the ACVP server, into their IUT's implementation. The IUT is *REQUIRED* to run the DRBG function calls, depending on registration options, as defined in <<other_input_table>>

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-90Ar1>>.

[[requirements_covered]]
==== Requirements Covered

TBD - Draft standard not yet published.

[[requirements_not_covered]]
==== Requirements Not Covered

TBD - Draft standard not yet published.