
[[reqpre]]
=== Required Prerequisite Algorithms for SP 800-108r1 KDF Validations

Each SP800-108r1 KDF implementation relies on other cryptographic primitives. For example, the KDF must utilize an underlying MAC algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

.SP800-108r1 KDF Required Prerequisites
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | A prerequisite algorithm | string | AES, DRBG, CMAC, HMAC
| valValue | Algorithm validation number | string | Actual number or "same"
| prereqAlgVal | Prerequisite algorithm validation | object with algorithm and valValue properties | See above
| prereqVals | Prerequisite algorithm validations | array of prereqAlgVal objects | See above
|===

[[kdfreg]]
=== Property Registration

Each algorithm capability advertised is a self-contained JSON object using the following values.

Two algorithm registrations are possible to test SP 800-108r1 KDFs. The first is for the "KDF" / "1.0" which covers the counter, feedback, and double pipeline iteration key derivation functions. The second is for "KDF" / "KMAC" / "Sp800-108r1" which covers the KMAC function when used as a key derivation function, introduced in the new revision, SP 800-108r1. A registration *SHALL* use these properties:

.Registration Properties
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | The KDF to be validated. | string | "KDF"
| mode | The KDF mode to be validated. | string | "KMAC" or ""
| revision | The algorithm testing revision to use. | string | "1.0" when "mode" is not included, or "Sp800-108r1" when "mode" is set to "KMAC"
| prereqVals | Prerequisite algorithm validations | array of prereqAlgVal objects | See <<reqpre>>
| capabilities | Array of JSON objects, each with fields pertaining to the KDF mode identified uniquely by the combination of the "kdfMode" and indicated properties | array of JSON objects | See <<properties>>
|===

[[kdfmodes]]
==== Supported SP 800-108r1 KDF Modes

The following SP800-108 KDF modes or "modes of iteration" may be advertised by the ACVP compliant crypto module as the "kdfMode" property:

* counter
* feedback
* double pipeline iteration

[#properties]
==== Supported KDF Modes Capabilities

The KDF mode capabilities are advertised as JSON objects within the 'capabilities' value of the ACVP registration message - see Table 2. The 'capabilities' value is an array, where each array element is a JSON object corresponding to a particular KDF mode defined in this section. The 'capabilities' value is part of the 'capability_exchange' element of the ACVP JSON registration message. See the ACVP specification <<ACVP>> for details on the registration message.

Each KDF mode's capabilities are advertised as JSON objects.

The following table describes the capabilities that may be advertised by the ACVP compliant crypto module for "KDF" /  / "1.0":

.KDF Mode Capabilities
|===
| JSON Value | Description | JSON Type | Valid Values

| kdfMode | The type of SP800-108r1 KDF or "mode of iteration" | string | See <<kdfmodes>>
| macMode | The MAC or PRF algorithm used | array of string | See <<valid-mac>>
| supportedLengths | The supported derived keying material lengths in bits | domain | Min: 1, Max: 4096
| fixedDataOrder | Describes where the counter appears in the fixed data | array | Any non-empty subset of {"none", "after fixed data", "before fixed  data", "middle fixed data", "before iterator"}
| counterLength | The length of the counter in bits | array | Any non-empty subset of {0, 8, 16, 24, 32}
| supportsEmptyIv | Whether or not the IUT supports an empty IV | boolean | true/false
| requiresEmptyIv | Whether or not the IUT requires an empty IV | boolean | true/false
| customKeyInLength | Optional value used to control the length of the keyIn produced by the ACVP server for the capability.  This field cannot be used to alter the keyIn length for AES/TDES based macModes, as the keyIns expected by those algorithms is fixed. | integer | 112-4096
|===

NOTE: The 'fixedDataOrder' options "none" and "before iterator" are not valid for "counter" KDF. The 'fixedDataOrder' option "middle fixed data" is not valid for "feedback" nor "double pipeline iteration" KDF.

NOTE: A 'counterLength' of 0 describes that there is no counter used. The 0 option is not valid for "counter"  KDF.

NOTE: When 'counterLength' contains a value of "0", 'fixedDataOrder' must contain a value of "none" and vice versus.

The following table describes the capabilities that may be advertisd by the ACVP compliant crypto module for "KDF" / "KMAC" / "Sp800-108r1":

.KDF KMAC Mode Capabilities
|===
| JSON Value | Description | JSON Type | Valid Values

| macMode | The MAC or PRF algorithm used | array of string | See <<valid-mac>>
| keyDerivationKeyLength | The lengths of the key derivation key in bits | domain | Min: 112, Max: 4096, Inc: 8
| contextLength | The lengths of the context field in bits | domain | Min: 8, Max: 4096, Inc: 8
| labelLength | The lengths of the label field in bits. This field can be excluded if no label is used. | domain | Min: 8, Max: 4096, Inc: 8
| derivedKeyLength | The lengths of the derived keys in bits | domain | Min: 112, Max: 4096, Inc: 8
|===


[#valid-mac]
==== Supported SP 800-108r1 KDF MACs

The following MAC or PRF functions *MAY* be advertised by an ACVP compliant client

* CMAC-AES128
* CMAC-AES192
* CMAC-AES256
* CMAC-TDES
* HMAC-SHA1
* HMAC-SHA2-224
* HMAC-SHA2-256
* HMAC-SHA2-384
* HMAC-SHA2-512
* HMAC-SHA2-512/224
* HMAC-SHA2-512/256
* HMAC-SHA3-224
* HMAC-SHA3-256
* HMAC-SHA3-384
* HMAC-SHA3-512
* KMAC-128
* KMAC-256

NOTE: The "KMAC-128" and "KMAC-256" options are only allowed for, and are the only options allowed for, "KDF" / "KMAC" / "Sp800-108r1".

=== Registration Example

The following is a example JSON object advertising support for "KDF" /  / "1.0".

// [align=left,alt=,type=]
....                 
{
    "algorithm": "KDF",
    "revision": "1.0",
    "prereqVals": [
        {
            "algorithm": "SHA",
            "valValue": "123456"
        },
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "capabilities": [
        {
            "kdfMode": "counter",
            "macMode": [
                "CMAC-AES128",
                "CMAC-AES192",
                "CMAC-AES256",
                "CMAC-TDES",
                "HMAC-SHA-1",
                "HMAC-SHA2-224",
                "HMAC-SHA2-256",
                "HMAC-SHA2-384",
                "HMAC-SHA2-512"
            ],
            "supportedLengths": [
                {
                    "min": 8,
                    "max": 1024,
                    "increment": 1
                }
            ],
            "fixedDataOrder": [
                "after fixed data",
                "before fixed data",
                "middle fixed data"
            ],
            "counterLength": [
                8,
                16,
                24,
                32
            ],
            "supportsEmptyIv": false
        },
        {
            "kdfMode": "feedback",
            "macMode": [
                "CMAC-AES128",
                "CMAC-AES192",
                "CMAC-AES256",
                "CMAC-TDES",
                "HMAC-SHA-1",
                "HMAC-SHA2-224",
                "HMAC-SHA2-256",
                "HMAC-SHA2-384",
                "HMAC-SHA2-512"
            ],
            "supportedLengths": [
                {
                    "min": 8,
                    "max": 1024,
                    "increment": 1
                }
            ],
            "fixedDataOrder": [
                "none",
                "after fixed data",
                "before fixed data",
                "before iterator"
            ],
            "counterLength": [
                0,
                8,
                16,
                24,
                32
            ],
            "supportsEmptyIv": true,
            "requiresEmptyIv": false
        },
        {
            "kdfMode": "double pipeline iteration",
            "macMode": [
                "CMAC-AES128",
                "CMAC-AES192",
                "CMAC-AES256",
                "CMAC-TDES",
                "HMAC-SHA-1", 
 			    "HMAC-SHA2-224",
                "HMAC-SHA2-256",
                "HMAC-SHA2-384",
                "HMAC-SHA2-512"
            ],
            "supportedLengths": [
                {
                    "min": 8,
                    "max": 1024,
                    "increment": 1
                } 
            ],
            "fixedDataOrder": [
                "none",
                "after fixed data",
                "before fixed data",
                "before iterator"
            ],
            "counterLength": [
                0,
                8,
                16,
                24,
                32
            ], 
            "supportsEmptyIv": false
        }
    ]
}
....

The following is a example JSON object advertising support for a "KDF" / "KMAC" / "Sp800-108r1".

// [align=left,alt=,type=]
....
{
    "algorithm": "KDF",
    "mode": "KMAC",
    "revision": "Sp800-108r1",
    "macMode": [
        "KMAC-128",
        "KMAC-256"
    ],
    "keyDerivationKeyLength": [
        {
            "min": 112,
            "max": 4096,
            "increment": 8
        }
    ],
    "contextLength": [
        {
            "min": 8,
            "max": 4096,
            "increment": 8
        }
    ],
    "labelLength": [
        {
            "min": 8,
            "max": 4096,
            "increment": 8
        }
    ],
    "derivedKeyLength": [
        {
            "min": 112,
            "max": 4096,
            "increment": 8
        }
    ]
}
....

