
[[tgjs]]
=== Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test	groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped	together. The Test Group JSON object contains meta data that applies to all test vectors within	the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object.

.Test Group JSON Object
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| kdfMode | The kdfMode used for the test group | string
| macMode | Psuedorandom function HMAC or CMAC used | string
| counterLocation | "none", "after fixed data", "before fixed data", "middle fixed data", or "before iterator"| string
| keyOutLength | Expected length of the derived key in bits | integer
| counterLength | Expected length of the counter in bits | integer
| zeroLengthIv | Whether or not the group utilizes a null IV | boolean
| testType | Describes the operation being performed | string | No
| tests | Array of individual test cases | array
|===

NOTE: The feedback mode KDF counter location of "counter after iterator" is referenced with the option "before fixed data" in the 'counterLocation' specification.

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' the group is addressing.

=== Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.Test Case JSON Object
|===
| JSON Values | Description | JSON Type

| tcId | Test case idenfitier | integer
| keyIn | Input key | hex
| iv | The initialization vector used only for feedback KDFs | hex
| deferred | Indicates the client is required to provide additional input values to complete the test case | boolean
|===

NOTE: If the "middle fixed data" option is used for the 'counterLocation', then the test case is deferred from the server. In this case, the client *MUST* provide a 'breakLocation' integer value which is the length of the fixed data before the counter is inserted.

NOTE: If the 'deferred' property is not present, it *MAY* be assumed to be 'false'.

=== Example Test Vector JSON Object

The following is a example JSON object for SP 800-108 KDF test vectors sent from the ACVP server to the crypto module.

// [align=left,alt=,type=]
....
                        
[{
                "acvVersion": "0..54"
        },
        {
                "vsId": 1564,
                "algorithm": "counterMode",
                "revision": "1.0",
                "testGroups": [{
                        "tgId": 1,
                        "kdfMode": "counter",
                        "macMode": "CMAC-AES128",
                        "counterLocation": "after fixed data",
                        "keyOutLength": 1024,
                        "counterLength": 8,
                        "tests": [{
                                        "tcId": 1,
                                        "keyIn": "5DA38931E8D9174BC3279C8942D2DB82",
                                        "deferred": false
                                },
                                {
                                        "tcId": 2,
                                        "keyIn": "58F5426A40E3D5D2C94F0F97EB30C739",
                                        "deferred": false
                                }
                        ]
                }]
        }
]
            
                    
....