
[#responses]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response Properties
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

[source, json]
----
{
	"acvVersion": "version",
	"vsId": 1,
	"testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response Properties
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

[source, json]
----
{
	"tgId": 1,
	"tests": [ ... ]
}
----

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

The following table describes the JSON properties that represent a test case response for a {spec-algorithm}.

.Test Case Results JSON Properties
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| breakLocation | The bit location in the fixed data where the counter is placed. breakLocation is only applicable 
and *SHALL* be included for test cases where counterLocation is "middle fixed data". | integer
| fixedData | The fixed input data used by the IUT | hex
| keyOut | The outputted keying material or key | hex
|===

NOTE: the fixedData or fixed input data string that is used by the IUT is needed by the ACVP server to verify that the IUT correctly derived the keying material. The server does not validate the correct construction of the fixed input data string.  For guidance on constructing a valid fixed input data string, please consult <<SP800-108>> Sections 5, 7.5 and 7.6.

=== Example Test Vector Response JSON

The following is an abbreviated example of a JSON object for SP800-108 KDF test results sent from the crypto module to the ACVP server.

// [align=left,alt=,type=]
....
                        
[{
                "acvVersion": <acvp-version>
        },
        {
                "vsId": 1564,
                "testGroups": [{
                        "tgId": 1,
                        "tests": [{
                                "tcId": 1,
                                "keyOut": "94D58F22FA9092B0375F7EE6841B6775226703E3232BF9CF496E4EF3CDE1037765DDC060C08C9B3A845E288EED171535EBA97D23DCF8F6D2D4CF9D980CB4F6D270D3A7859B1FE2BFCA81F0702B5767E35BE9B96BA65C5263EB0DECD5FA721FFA57CE208F53F910DB6087E93BEE1A24E790E1DF02C140E89E04DF5299A63B71DA",
                                "fixedData": "FBF14DF02EE6C7DABCA6EF9AF59BB9A2"
                        }]
                }]
        }
]
            
                    
....

NOTE: Please note that the values used in the example JSON object are not real values. In particular, the value for the fixedData property is not an example of a validly formed fixed input data string. 