
[[app-reg-ex]]
== Example SP800-108 KDF Capabilities JSON Object

The following is a example JSON object advertising support for KDF.

// [align=left,alt=,type=]
....
                    
	{
       "algorithm": "KDF",
       "revision": "1.0",
       "prereqVals": [
           {
               "algorithm": "SHA",
               "valValue": "123456"
           },
           {
               "algorithm": "DRBG",
               "valValue": "123456"
           }
       ],
       "capabilities": [
           {
               "kdfMode": "counter",
               "macMode": [
                   "CMAC-AES128",
                   "CMAC-AES192",
                   "CMAC-AES256",
                   "CMAC-TDES",
                   "HMAC-SHA-1",
                   "HMAC-SHA2-224",
                   "HMAC-SHA2-256",
                   "HMAC-SHA2-384",
                   "HMAC-SHA2-512"
               ],
               "supportedLengths": [
                   {
                       "min": 8,
                       "max": 1024,
                       "increment": 1
                   }
               ],
               "fixedDataOrder": [
                   "after fixed data",
                   "before fixed data",
                   "middle fixed data"
               ],
               "counterLength": [
                   8,
                   16,
                   24,
                   32
               ],
               "supportsEmptyIv": false
           },
           {
               "kdfMode": "feedback",
               "macMode": [
                   "CMAC-AES128",
                   "CMAC-AES192",
                   "CMAC-AES256",
                   "CMAC-TDES",
                   "HMAC-SHA-1",
                   "HMAC-SHA2-224",
                   "HMAC-SHA2-256",
                   "HMAC-SHA2-384",
                   "HMAC-SHA2-512"
               ],
               "supportedLengths": [
                   {
                       "min": 8,
                       "max": 1024,
                       "increment": 1
                   }
               ],
               "fixedDataOrder": [
                   "none",
                   "after fixed data",
                   "before fixed data",
                   "before iterator"
               ],
               "counterLength": [
                   0,
                   8,
                   16,
                   24,
                   32
               ],
               "supportsEmptyIv": true,
               "requiresEmptyIv": false
           },
           {
               "kdfMode": "double pipeline iteration",
               "macMode": [
                   "CMAC-AES128",
                   "CMAC-AES192",
                   "CMAC-AES256",
                   "CMAC-TDES",
                   "HMAC-SHA-1",
				   "HMAC-SHA2-224",
                   "HMAC-SHA2-256",
                   "HMAC-SHA2-384",
                   "HMAC-SHA2-512"
               ],
               "supportedLengths": [
                   {
                       "min": 8,
                       "max": 1024,
                       "increment": 1
                   }
               ],
               "fixedDataOrder": [
                   "none",
                   "after fixed data",
                   "before fixed data",
                   "before iterator"
               ],
               "counterLength": [
                   0,
                   8,
                   16,
                   24,
                   32
               ],
               "supportsEmptyIv": false
           }
       ]
   }

....


[[app-vs-ex]]
== Example Test Vectors JSON Object

The following is a example JSON object for SP800-108 KDF test vectors sent from the ACVP server to the crypto module.

// [align=left,alt=,type=]
....
                        
[{
                "acvVersion": "0..54"
        },
        {
                "vsId": 1564,
                "algorithm": "counterMode",
                "revision": "1.0",
                "testGroups": [{
                        "tgId": 1,
                        "kdfMode": "counter",
                        "macMode": "CMAC-AES128",
                        "counterLocation": "after fixed data",
                        "keyOutLength": 1024,
                        "counterLength": 8,
                        "tests": [{
                                        "tcId": 1,
                                        "keyIn": "5DA38931E8D9174BC3279C8942D2DB82",
                                        "deferred": false
                                },
                                {
                                        "tcId": 2,
                                        "keyIn": "58F5426A40E3D5D2C94F0F97EB30C739",
                                        "deferred": false
                                }
                        ]
                }]
        }
]
            
                    
....




[[app-resp-ex]]
== Example Test Results JSON Object

The following is a example JSON object for SP800-108 KDF test results sent from the crypto module to the ACVP server.

// [align=left,alt=,type=]
....
                        
[{
                "acvVersion": <acvp-version>
        },
        {
                "vsId": 1564,
                "testGroups": [{
                        "tgId": 1,
                        "tests": [{
                                "tcId": 1,
                                "keyOut": "94D58F22FA9092B0375F7EE6841B6775226703E3232BF9CF496E4EF3CDE1037765DDC060C08C9B3A845E288EED171535EBA97D23DCF8F6D2D4CF9D980CB4F6D270D3A7859B1FE2BFCA81F0702B5767E35BE9B96BA65C5263EB0DECD5FA721FFA57CE208F53F910DB6087E93BEE1A24E790E1DF02C140E89E04DF5299A63B71DA",
                                "fixedData": "FBF14DF02EE6C7DABCA6EF9AF59BB9A2"
                        }]
                }]
        }
]
            
                    
....


