
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified FN-DSA algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of FN-DSA capabilities. This section describes the design of the tests used to validate implementations of the FN-DSA algorithms. The number of tests *MAY* vary but the minimum number required by each test type *SHALL* be included by the server. The test type describes the format of the test rather than the intention of the test. Multiple tests of the same test type *MAY* cover different assurances regarding the implementation. 

==== FN-DSA KeyGen Test Types

* FN-DSA / keyGen / * "AFT" - Algorithm Functional Test.

For each test case provided, the IUT *SHALL* generate a key pair from a provided seed. The key pair is communicated to the ACVP server and compared against the key pair generated by the server. This tests the implementation of Algorithm 6 `FN-DSA.KeyGen_internal()` from <<FIPS206>>. The server *SHALL* provide at least 1000 tests for each combination of capabilities. Since the use of floating points or fixed points can induce differences in the key generation algorithm, a more comprehensive validation is performed.
// TBD for more on that

==== FN-DSA SigGen Test Types

* FN-DSA / sigGen / * "AFT" - Algorithm Functional Test. 


The IUT *SHALL* generate valid signatures based on the ACVP-provided message, mu (for external mu testing), private key, context (for external interface testing), hashAlg (for preHash testing), and randomness (for non-deterministic signature testing). The signature is then compared to the known signature by the ACVP server. This tests the implementation of Algorithm 2 `FN-DSA.Sign()`, Algorithm 4 `HashFN-DSA.Sign()`, and Algorithm 7 `FN-DSA.Sign_internal()` from <<FIPS206>>. 

There are several assurances to obtain from AFTs. First is correctness of the algorithm implementation. The server *SHALL* include at least 15 tests for each combination of capabilities to meet this assurance. The `"hashAlg"` capability *MAY* be excluded from the combination of capabilities due to the number of supported hash functions. Each `"hashAlg"` provided by the IUT *SHALL* be covered within the at least 15 tests generated for each combination of capabilities. 

// The second assurance is correctness under all rejection paths. Within FN-DSA sigGen, the algorithm enters a loop until a valid signature is found. The loop contains two potential reasons to reject a candidate signature: if the L2 norm of (s1, s2) is too large or if the infinity norm of (s1, s2) is too large. These two conditions occur with a rather low probability that can make it difficult to test each error condition with randomized testing. If an implementation adheres strictly to the pseudocode in <<FIPS206>>, the following table provides helpful known answer tests that trigger each rejection case exactly once. If the implementation varies from the pseudocode, it would be prudent to use a debugger or other tooling to ensure that all rejection cases are triggered by testing. TBD


==== FN-DSA SigVer Test Types

* FN-DSA / sigVer / * "AFT" - Algorithm Functional Test. 

The IUT *SHALL* determine the validity of the signature based on the ACVP-provided message, mu (for external mu testing), context (for external interface testing), hashAlg (for preHash testing), public key, and signature. This tests the implementation of Algorithm 3 `FN-DSA.Verify()`, Algorithm 5 `HashFN-DSA.Verify()`, and Algorithm 8 `FN-DSA.Verify_internal()` from <<FIPS206>>. Tests for signature verification are performed by the server modifying a valid signature to obtain specific assurances from the implementation. The server *SHALL* include at least 3 tests for each modification type (including "valid signature") for all combinations of capabilities. The `"hashAlg"` capability *MAY* be excluded from the combination of capabilities due to the number of supported hash functions. Each `"hashAlg"` provided by the IUT *SHALL* be covered within the at least 15 tests generated for each combination of capabilities.

The signature modifications are:

* "valid signature and message - signature should verify successfully" - No modification is made and the signature is valid.
* "modified message" - The message that was signed has been changed. The signature is not valid.
* "modified signature" - The signature has been changed. The signature is not valid.
* "modified signature - encoding minus 0" - A component of the signature, the positive sign bit for an encoded coefficient of 0 in s2, has been changed. The signature is not valid.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS206>>.

[[requirements_covered]]
==== Requirements Covered

* The tests will ensure conformity and correctness of an implementation of the algorithms supported. 

[[requirements_not_covered]]
==== Requirements Not Covered

* FIPS 206 Section 3.5. Additional Requirements. Requirements outlined in this section are not testable by an ACVP server. An ACVP server will not test the zeroization of intermediate values, security strength of the deterministic random bit generators (DRBGs), or incorrect length signatures or public keys.
