[#properties]
=== Property Registration

The ANS x9.42 KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

=== Registration Example

A registration *SHALL* use these properties

.ANS x9.42 Registration JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of algo to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ansix9.42"
| revision | ACVP Test version | string | "1.0"
| prereqVals | Prereqs of the algo | object | See Prerequisites
| kdfType | The type of KDF | array | "DER" and/or "concatenation"
| keyLen | Length of output key - bits | domain | Min:1, Max:4096
| otherInfoLen | Length in bits of other info for "concatentation" kdfTYpe | domain | Min:0, Max:4096, Increment: 8
| suppInfoLen | Length in bits of supplemental public and private info for "DER" kdfType | domain | Min:0, Max:4096, Increment: 8
| zzLen | The length of ZZ in bits | domain | Min: 1, Max: 4096
| hashAlg | The supported hash algorithms | array | See <<valid-sha>>
|===

An example registration within an algorithm capability exchange looks like this

[source, json]
----
{
	"algorithm": "kdf-components",
	"mode": "ansix9.42",
	"revision": "1.0",
	"prereqVals": [
		{
			"algorithm": "SHA",
			"valValue": "same"
		}
	],
	"kdfType": [
		"DER",
		"concatenation"
	],
	"keyLen": [
		256,
		1024
	],
	"otherInfoLen": [
		0,
		1024
	],
	"suppInfoLen": [
		0,
		256
	],
	"zzLen": [
		8,
		1024
	],
	"hashAlg": [
		"sha-1",
		"sha2-224",
		"sha2-256",
		"sha2-384",
		"sha2-512",
		"sha2-512/224",
		"sha2-512/256",
		"sha3-224",
		"sha3-256",
		"sha3-384",
		"sha3-512"
	]
}
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512
