
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the IUT's DRBG in order to assess the correctness and robustness of the implementation. A typical ACVP validation session would require multiple tests to be performed for every supported permutation of DRBG capabilities. This section describes the design of the tests used to validate implementations of the DRBG algorithms. There is a single test type for DRBG testing:

* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *MUST* be capable of injecting the values provided by the ACVP server, into their IUT's implementation. The IUT is *REQUIRED* to run the DRBG function calls, depending on registration options, as defined in <<tests_table>>

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-90A>>.

[[requirements_covered]]
==== Requirements Covered

* SP 800-90A - 7.1 Entropy Input. The IUT is *REQUIRED* to inject the ACVP server's provided entropy for testing.

*  SP 800-90A - 7.2 Other Inputs. The IUT is *REQUIRED* to inject the ACVP server's provided other input information for testing.

*  SP 800-90A - 7.3 Internal State. Indirect testing of the IUT's DRBG internal state *SHALL* be inferred through multiple calls to the DRBG "generate" function.  Multiple calls *SHALL* ensure the internal state is successfully mutated for each "generate" invocation.

* SP 800-90A - 7.4 The DRBG Mechanism Functions. "Instantiate", "Generate", and "Reseed" DRBG functions *SHALL* be tested within the ACVP server's provided tests.

* SP 800-90A - 8 DRBG Mechanism Concepts and General Requirements. The ACVP server *SHALL* validate "Instantiate", "Generate", and "Reseed" are properly implemented. Reseeding is partially tested through ACVP test vectors through an explicit reseed operation.

* SP 800-90A - 9 DRBG Mechanism Functions. "Instantiate", "Generate", and "Reseed" *SHALL* be evaluated as a part of ACVP generated tests.

* SP 800-90A - 10 DRBG Algorithm Specifications. "Instantiate", "Generate", and "Reseed" DRBG functions in scope *SHALL* be tested as per the specifications in this section.

[[requirements_not_covered]]
==== Requirements Not Covered

* SP 800-90A - 7.1 Entropy Input. The ACVP Server *SHALL* provide all instances of randomness to utilize from the IUT's perspective.  Implementation of the IUT's RBG *SHALL NOT* be in scope of testing.

* SP 800-90A - 7.2 Other Inputs. The ACVP server *SHALL* provide all instances of randomness throughout the IUT's testing of the DRBG.

* SP 800-90A - 7.3 Internal State. Though direct testing of the IUT's internal state *SHALL NOT* be not performed, the act of testing multiple "generate" outputs from the IUT DRBG helps to ensure a successful IUT implementation.

* SP 800-90A - 7.4 The DRBG Mechanism Functions. "Uninstantiate", "Health Test" *SHALL NOT* be in scope of testing.

* SP 800-90A - 8 DRBG Mechanism Concepts and General Requirements. The ACVP server *SHALL NOT* directly validate internal DRBG state. Additionally, DRBG boundaries are out of scope of ACVP testing. Seed construction is performed by the ACVP server, the IUT is *REQUIRED* to utilize the ACVP provided seed (via entropy, inputs, etc) to perform validation testing. Reseeds operations that are performed automatically due to a large number of generate operations, *SHALL NOT* be in scope of ACVP testing.

* SP 800-90A - 9 DRBG Mechanism Functions. Error conditions (CATASTROPHIC_ERROR_FLAG or otherwise), reseeding due to end of seed life, uninstantiation, and health checks are out of scope of ACVP tests.

* SP 800-90A - 10 DRBG Algorithm Specifications. All previously mentioned DRBG functions that are not in scope - Uninstantiate, Health check, automatic reseed, error conditions - *SHALL NOT* be tested as part of testing.

* SP 800-90A - 11 Assurances. Health check and error handling testing *SHALL NOT* be performed within the scope of ACVP testing.
