
[#properties]
=== Property Registration

The SP800-90A DRBG mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

=== Default values

ACVP has default values for many of the input parameters for testing the DRBG algorithms.For example, the Entropy Input, Nonce, Personalization String, and Addtional Input parameters have default values. The specific details and restrictions on each of these input lengths is specified in <<value_req_per_option>>, <<capabilities-table>> and the notes following it. To indicate a preference for using a default value for any of these parameters, the value zero (0) should be set. If the implementation does not support one of these defaults, the corresponding supported bit length values shall be set explicitly.

=== Registration Example

A registration *SHALL* use these properties within each object within the 'capabilities' array

[[capabilities-table]]
.Registration Capability Properties
|===
| JSON Value| Description| JSON type| Valid Values

| mode | The algorithm mode to be validated | string | See <<supported>>
| derFuncEnabled | Derivation function option. See <<capabilities-table>> notes below | boolean | true/false
| entropyInputLen | See <<capabilities-table>> notes below | domain | Min: maximum security strength, Max: XXX
| nonceLen | See <<capabilities-table>> notes below | domain | Min: half the maximum security strength, Max: XXX. Set to 0 if not supported
| persoStringLen | Personalization string length. See <<capabilities-table>> notes below | domain | Min: maximum security strength, Max: XXX. Set to 0 if not supported
| additionalInputLen | See <<capabilities-table>> notes below | domain | Min: maximum security strength, Max: XXX. Set to 0 if not supported
| returnedBitsLen | See <<capabilities-table>> notes below | integer | |
|===

Each DRBG algorithm capability advertised is a self-contained JSON object. The following JSON values are used for DRBG algorithm capabilities:

[[caps-table]]
.DRBG Algorithm Capabilities
|===
| JSON Value | Description | JSON type | Valid Values

| algorithm | Name of the algorithm to be validated | string | See <<supported>>
| revision | ACVP Test version | string | "1.0"
| prereqVals | Prerequisites of the algorithm | object | See <<prerequisites>>
| predResistanceEnabled | An implementation that can be used with prediction resistance. See <<capabilities-table>> notes below | array of boolean containing one or two distinct values | [true], [true, false], or [false]
| reseedImplemented | Reseeding of the DRBG shall be performed in accordance with the specification for the given DRBG mechanism. See <<capabilities-table>> notes below | boolean | true or false
| capabilities | An array of objects describing the capabilities of a mode of the algorithm. See <<capabilities-table>> for more information | array
|===

NOTE: 2 If an implementation utilizes a nonce in the construction of a seed during instantiation, the length of the nonce shall be at least half the maximum security strength supported. See Tables 2 and 3 in <<SP800-90A>> for help on choosing appropriate parameter values for the tested DRBG implementation.

NOTE: 3 If an implementation can only be used without prediction resistance, the array 'predResistanceEnabled' shall only contain a single 'false' element. Implementations that either have prediction resistance always ON or always OFF, the array 'predResistanceEnabled' shall contain two distinct elements, 'true' and 'false'. Implementations containing multiple equal array elements for 'predResistanceEnabled' will be rejected.

NOTE: 4 For 'ctrDRBG' implementations, the 'derFuncEnabled' property must be included.

NOTE: 5 All DRBGs are tested at their maximum supported security strength so this is the minimum bit length of the entropy input that ACVP will accept. The maximum supported security strength is also the default value for this input. Longer entropy inputs are permitted, with the following exception: for 'ctrDRBG' with 'derFuncEnabled' set to 'false', the 'entropyInputLen' must equal the seed length. See Tables 2 and 3 in <<SP800-90A>> for help on choosing appropriate parameter values for the DRBG being tested.

NOTE: 6 'ctrDRBG' with 'derFuncEnabled' set to 'false' does not use a nonce; the nonce values, if supplied, will be ignored for this case. The default nonce bit length is one-half the maximum security strength supported by the mechanism/option. See Tables 2 and 3 in <<SP800-90A>> for help on choosing appropriate parameter values for the tested DRBG implementation.

NOTE: 7 ACVP allows bit length values for 'persoString' ranging from the maximum supported security strength except in the case of 'derFuncEnabled' set to 'false', where the second personalization string length must be less than or equal to the seed length. If the implementation only supports one personalization string length, then set only that value as the range min and max and set the step to 0. If the implementation does not use a 'persoString', set all range parameters (min, max, step) to 0. If the implementation can work with and without 'persoString', set the min to 0, set the max to at least the maximum supported strength and set the step equal to at least the maximum supported strength to avoid testing lengths less than that. See Tables 2 and 3 in <<SP800-90A>> for help on choosing appropriate parameter values for the tested DRBG implementation.

NOTE: 8 The 'addtionalInput' configuration and restrictions are the same as those for the 'persoString'.

An example registration within an algorithm capability exchange looks like this

[source, json]
----
{
  "algorithm": "ctrDRBG",
  "revision": "1.0",
  "predResistanceEnabled": [
    true,
    false
  ],
  "reseedImplemented": true,
  "capabilities": [
    {
      "mode": "TDES",
      "derFuncEnabled": true,
      "entropyInputLen": [
        232
      ],
      "nonceLen": [
        232
      ],
      "persoStringLen": [
        232
      ],
      "additionalInputLen": [
        232
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-128",
      "derFuncEnabled": false,
      "entropyInputLen": [
        256
      ],
      "nonceLen": [
        256
      ],
      "persoStringLen": [
        256
      ],
      "additionalInputLen": [
        256
      ],
      "returnedBitsLen": 512
    }
  ]
}
----
