
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[response_vector_set_table]]
.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

[source, json]
----
{
	"acvVersion": "version",
	"vsId": 1,
	"testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

[[response_group_table]]
.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

[source, json]
----
{
	"tgId": 1,
	"tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

[[response_case_table]]
.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| returnedBits | The outputted bits from the DRBG | hex
|===

Here is an abbreviated example of the response

[source, json]
----
{
  "vsId": 1,
  "algorithm": "ctrDRBG",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "returnedBits": "99F0D5740DCAA1ECC4E5329B38B..."
        },
        {
          "tcId": 2,
          "returnedBits": "62A458CA72C19316A1ECBC3211B..."
        }
      ]
    }
  ]
}
----
