[[app-reg-ex]]
== Example DRBG Capabilities JSON Object

The following is a example JSON object advertising support for ctrDRBG with TDES and all key sizes of AES.

....
{
  "algorithm": "ctrDRBG",
  "revision": "1.0",
  "prereqVals":
  [
    {
      "algorithm": "AES",
      "valValue": "1234"
    },
    {
      "algorithm": "TDES",
      "valValue": "5678"
    }
  ],
  "predResistanceEnabled": [
    true,
    false
  ],
  "reseedImplemented": true,
  "capabilities": [
    {
      "mode": "AES-128",
      "derFuncEnabled": true,
      "entropyInputLen": [
        256
      ],
      "nonceLen": [
        256
      ],
      "persoStringLen": [
        256
      ],
      "additionalInputLen": [
        256
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-192",
      "derFuncEnabled": true,
      "entropyInputLen": [
        320
      ],
      "nonceLen": [
        320
      ],
      "persoStringLen": [
        320
      ],
      "additionalInputLen": [
        320
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-256",
      "derFuncEnabled": true,
      "entropyInputLen": [
        384
      ],
      "nonceLen": [
        384
      ],
      "persoStringLen": [
        384
      ],
      "additionalInputLen": [
        384
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "TDES",
      "derFuncEnabled": true,
      "entropyInputLen": [
        232
      ],
      "nonceLen": [
        232
      ],
      "persoStringLen": [
        232
      ],
      "additionalInputLen": [
        232
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-128",
      "derFuncEnabled": false,
      "entropyInputLen": [
        256
      ],
      "nonceLen": [
        256
      ],
      "persoStringLen": [
        256
      ],
      "additionalInputLen": [
        256
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-192",
      "derFuncEnabled": false,
      "entropyInputLen": [
        320
      ],
      "nonceLen": [
        320
      ],
      "persoStringLen": [
        320
      ],
      "additionalInputLen": [
        320
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "AES-256",
      "derFuncEnabled": false,
      "entropyInputLen": [
        384
      ],
      "nonceLen": [
        384
      ],
      "persoStringLen": [
        384
      ],
      "additionalInputLen": [
        384
      ],
      "returnedBitsLen": 512
    },
    {
      "mode": "TDES",
      "derFuncEnabled": false,
      "entropyInputLen": [
        232
      ],
      "nonceLen": [
        232
      ],
      "persoStringLen": [
        232
      ],
      "additionalInputLen": [
        232
      ],
      "returnedBitsLen": 512
    }
  ]
}
....


The following is a example JSON object advertising support for hashDRBG with various SHA sizes. Note that in this example the implementation works with or without additional input and personalization data.

....
{
  "algorithm": "hashDRBG",
  "revision": "1.0",
  "prereqVals":
  [
    {
      "algorithm": "AES",
      "valValue": "1234"
    },
    {
      "algorithm": "SHA",
      "valValue": "5678"
    }
  ],
  "predResistanceEnabled": [
    true,
    false
  ],
  "reseedImplemented": true,
  "capabilities": [
    {
      "mode": "SHA-1",
      "derFuncEnabled": false,
      "entropyInputLen": [
        160
      ],
      "nonceLen": [
        160
      ],
      "persoStringLen": [
        160
      ],
      "additionalInputLen": [
        160
      ],
      "returnedBitsLen": 640
    },
    {
      "mode": "SHA2-224",
      "derFuncEnabled": false,
      "entropyInputLen": [
        224
      ],
      "nonceLen": [
        224
      ],
      "persoStringLen": [
        224
      ],
      "additionalInputLen": [
        224
      ],
      "returnedBitsLen": 896
    },
    {
      "mode": "SHA2-256",
      "derFuncEnabled": false,
      "entropyInputLen": [
        256
      ],
      "nonceLen": [
        256
      ],
      "persoStringLen": [
        256
      ],
      "additionalInputLen": [
        256
      ],
      "returnedBitsLen": 1024
    },
    {
      "mode": "SHA2-384",
      "derFuncEnabled": false,
      "entropyInputLen": [
        384
      ],
      "nonceLen": [
        384
      ],
      "persoStringLen": [
        384
      ],
      "additionalInputLen": [
        384
      ],
      "returnedBitsLen": 1536
    },
    {
      "mode": "SHA2-512",
      "derFuncEnabled": false,
      "entropyInputLen": [
        512
      ],
      "nonceLen": [
        512
      ],
      "persoStringLen": [
        512
      ],
      "additionalInputLen": [
        512
      ],
      "returnedBitsLen": 2048
    },
    {
      "mode": "SHA2-512/224",
      "derFuncEnabled": false,
      "entropyInputLen": [
        224
      ],
      "nonceLen": [
        224
      ],
      "persoStringLen": [
        224
      ],
      "additionalInputLen": [
        224
      ],
      "returnedBitsLen": 896
    },
    {
      "mode": "SHA2-512/256",
      "derFuncEnabled": false,
      "entropyInputLen": [
        256
      ],
      "nonceLen": [
        256
      ],
      "persoStringLen": [
        256
      ],
      "additionalInputLen": [
        256
      ],
      "returnedBitsLen": 1024
    }
  ]
}
....



[[app-vs-ex]]
== Example Test Vectors JSON Object

The following is a example JSON object for ctrDRBG test vectors sent from the ACVP server to the crypto module.

....
[
  { "acvVersion": <acvp-version> },
  { "vectorSetId": 1133,
    "algorithm": "ctrDRBG",
    "mode": "TDES",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "derFunc": true,
        "predResistance": true,
        "reSeed": true,
        "entropyInputLen": 112,
        "nonceLen": 56,
        "persoStringLen": 112,
        "additionalInputLen": 112,
        "returnedBitsLen": 256,
        "tests": [
          {
            "tcId": 1815,
            "entropyInput":"78aac2cb444594e2...",
            "nonce":"41ef9c67ffe438",
            "persoString":"b8e84de200a9239a0...",
            "otherInput" : [
               { "intendedUse" : "generate",
                 "additionalInput":"f1e8edf0...",
                 "entropyInput": "6cd4096638..."},
              { "intendedUse" : "generate",
                "additionalInput" : "f535773...",
                "entropyInput" : "a0cdf5c1c6..."}
              ]
            },
          {
            "tcId": 1816,
            "entropyInput" : "b8ab88b9c5fda8...",
            "nonce": "f1bcc6ff60dd37",
            "persoString" : "018c1f9d22f3c7f...",
            "otherInput" : [
               {"intendedUse" : "generate",
                "additionalInput" : "356a6e9...",
                "entropyInput" : "bed693401b..."},
               {"intendedUse" : "generate",
                "additionalInput" : "4321b3a...",
                "entropyInput" : "a632ef16f2..."}
            ]
          }
        ]
      }
    ]
  }
]
....


The following is a example JSON object for hmacDRBG test vectors sent from the ACVP server to the crypto module.

[align=left,alt=,type=]
....
[
  { "acvVersion": <acvp-version> },
  { "vectorSetId": 1146,
    "algorithm": "hmacDRBG",
    "mode": "AES-256",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "predResistance": true,
        "reSeed": false,
        "entropyInputLen": 256,
        "nonceLen": 128,
        "persoStringLen": 256,
        "additionalInputLen": 256,
        "returnedBitsLen": 1024,
        "tests": [
          {
            "tcId": 2111,
            "entropyInput": "ee3392c5f3de6f3...",
            "nonce": "b991a820fac75fd02642ad...",
            "persoString": "30f3a50b0e2309da...",
            "otherInput" : [
               {"intendedUse" : "generate",
                 "additionalInput":"4ea46abe...",
                 "entropyInput": "e4413a2e40..."},
               {"intendedUse" : "generate",
                "additionalInput" : "61b7204...",
                "entropyInput" : "968ea185d1..."}
              ]
            },
          {
            "tcId": 2112,
            "entropyInput" : "a0ace75784b972...",
            "nonce": "b671308068fc7909a360c7...",
            "persoString" : "338d5f2bd93262d...",
            "otherInput" : [
               {"intendedUse" : "generate",
                "additionalInput" : "7acd8bf...",
                "entropyInput" : "47b26bbe93..."},
               {"intendedUse" : "generate",
                "additionalInput" : "d4b24c7...",
                "entropyInput" : "acb63f3b59..."}
            ]
          }
        ]
      }
    ]
  }
]
....


The following is a example JSON object for hashDRBG test vectors sent from the ACVP server to the crypto module. In this example the implementation is tested without additional input and personalization data.

....
[
  { "acvVersion": <acvp-version> },
  { "vectorSetId": 1156,
    "algorithm": "hashDRBG",
    "mode": "SHA2-256",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "predResistance": true,
        "reSeed": false,
        "entropyInputLen": 256,
        "nonceLen": 128,
        "persoStringLen": 0,
        "additionalInputLen": 0,
        "returnedBitsLen": 1024,
        "tests": [
          {
            "tcId": 2151,
            "entropyInput": "ae0a3acd541d0d5...",
            "nonce": "786f03ad697332d74fad7a...",
            "persoString": "",
            "otherInput" : [
                 {"intendedUse" : "generate",
                  "additionalInput": "",
                  "entropyInput": "4852aed7c..."},
                 {"intendedUse" : "generate",
                  "additionalInput" : "",
                  "entropyInput" : "8b8a35a1..."}
              ]
            },
          {
            "tcId": 2152,
            "entropyInput" : "26d8c9a9b982cd...",
            "nonce": "36dff124f908a95a022edf...",
            "persoString" : "",
            "otherInput" : [
               {"intendedUse" : "generate",
                "additionalInput" : "",
                "entropyInput" : "648bbdc4d4..."},
               {"intendedUse" : "generate",
                "additionalInput" : "",
                "entropyInput" : "fff51d05b1..."}
            ]
          }
        ]
      }
    ]
  }
]
....


The following is a example JSON object for hashDRBG test vectors sent from the ACVP server to the crypto module. In this example the implementation is tested with "predResistance": false, "reSeed": true options.

....
[
  { "acvVersion": <acvp-version> },
  { "vectorSetId": 1157,
    "algorithm": "hashDRBG",
    "mode": "SHA2-256",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "predResistance": false,
        "reSeed": true,
        "entropyInputLen": 256,
        "nonceLen": 128,
        "persoStringLen": 256,
        "additionalInputLen": 256,
        "returnedBitsLen": 1024,
        "tests": [
          {
            "tcId": 3151,
            "entropyInput": "860d051cedbb935...",
            "nonce": "5813070f9774d21e644d64...",
            "persoString": "545ba29faf1bb1bf...",
            "otherInput" : [
                 {"intendedUse" : "reSeed",
                   "additionalInput": "95b08...",
                  "entropyInput": "2e92955b1..."},
                 {"intendedUse" : "generate",
                   "additionalInput" : "ddfa...",
                  "entropyInput" : ""},
                 {"intendedUse" : "generate",
                  "additionalInput" : "edb88...",
                  "entropyInput" : ""}
              ]
            },
          {
            "tcId": 3152,
            "entropyInput" : "371d2944c9ace6...",
            "nonce": "4bb34ab1e882d97687c3f8...",
            "persoString" : "c5b03354a9fad34...",
            "otherInput" : [
               {"intendedUse" : "reSeed",
                "additionalInput" : "6e3fa8e...",
                "entropyInput" : "afd7e6b0b4..."},
               {"intendedUse" : "generate",
                "additionalInput" : "deb8ed5...",
                "entropyInput" : ""},
               {"intendedUse" : "generate",
                "additionalInput" : "a554bb9...",
                "entropyInput" : ""}
            ]
          }
        ]
      }
    ]
  }
]
....


The following is a example JSON object for hashDRBG test vectors sent from the ACVP server to the crypto module. In this example the implementation is tested with "predResistance": false, "reSeed": false options.

....
[
  { "acvVersion": <acvp-version> },
  { "vectorSetId": 1167,
    "algorithm": "hashDRBG",
    "mode": "SHA2-256",
    "revision": "1.0",
    "testGroups": [
      {
        "tgId": 1,
        "predResistance": false,
        "reSeed": false,
        "entropyInputLen": 256,
        "nonceLen": 128,
        "persoStringLen": 256,
        "additionalInputLen": 256,
        "returnedBitsLen": 1024,
        "tests": [
          {
            "tcId": 4151,
            "entropyInput": "090db63c22de171...",
            "nonce": "6f7c6bec9825079cabd947...",
            "persoString": "c2f1a59806197792...",
            "otherInput" : [
                 {"intendedUse" : "generate",
                  "additionalInput": "3fc72d...",
                  "entropyInput": ""},
                 {"intendedUse" : "generate",
                  "additionalInput" : "968a3...",
                  "entropyInput" : ""}
              ]
            },
          {
            "tcId": 4152,
            "entropyInput" : "bd0e2dbba872bb...",
            "nonce": "a97dfbaea505a3e36210a8...",
            "persoString" : "7d0de87d097551f...",
            "otherInput" : [
               {"intendedUse" : "generate",
                "additionalInput" : "fe1adf1...",
                "entropyInput" : ""},
               {"intendedUse" : "generate",
                "additionalInput" : "1df719a...",
                "entropyInput" : ""}
            ]
          }
        ]
      }
    ]
  }
]
....



[[app-results-ex]]
== Example Test Results JSON Object

The following is a example JSON object for ctrDRBG with TDES test results sent from the crypto module to the ACVP server.

....
[{
    "acvVersion": <acvp-version>
  },
  {
    "vectorSetId": 1133,
    "testGroups": [{
        "tgId": 1,
        "tests": [{
            "tcId": 1815,
            "returnedBits ": "4565e85447af71..."
          },
          {
            "tcId": 1816,
            "returnedBits": "b67acc3b2231ec5..."
          }
        ]
      }
    ]
  }
]
....


The following is a example JSON object for HMAC_DRBG test results sent from the crypto module to the ACVP server.

....
[{
    "acvVersion": <acvp-version>
  },
  {
    "vectorSetId": 1146,
    "testGroups": [{
      "tgId": 1,
      "tests": [{
          "tcId": 2111,
          "returnedBits": "e42130fd1d920a2bc..."
        },
        {
          "tcId": 2112,
          "returnedBits": "495b2a0de6b5fc454..."
        }
      ]
    }]
  }
]
....


The following is a example JSON object for hashDRBG test results sent from the crypto module to the ACVP server.

....
[{
    "acvVersion": <acvp-version>
  },
  {
    "vectorSetId": 1156,
    "testGroups": [{
      "tgId": 1,
      "tests": [{
          "tcId": 2151,
          "returnedBits ": "1af967534c670271..."
        },
        {
          "tcId": 2152,
          "returnedBits": "8a74a8c31ea4e6e62..."
        }
      ]
    }]
  }
]
....


The following is a example JSON object for hashDRBG test results sent from the crypto module to the ACVP server.

....
[{
    "acvVersion": <acvp-version>
  },
  {
    "vectorSetId": 1157,
    "testGroups": [{
      "tgId": 1,
      "tests": [{
          "tcId": 3151,
          "returnedBits ": "0eadc82746890ee0..."
        },
        {
          "tcId": 3152,
          "returnedBits": "6452be2ee730d7245..."
        }
      ]
    }]
  }
]
....


The following is a example JSON object for hashDRBG test results sent from the crypto module to the ACVP server.

....
[{
    "acvVersion": <acvp-version>
  },
  {
    "vectorSetId": 1167,
    "testGroups": [{
      "tgId": 1,
      "tests": [{
          "tcId": 4151,
          "returnedBits ": "5dbfd26651bc7159..."
        },
        {
          "tcId": 4152,
          "returnedBits": "ff3cce0b5585172b1..."
        }
      ]
    }]
  }
]
....
