[[ML-DSA_sigGen_test_vectors]]
=== ML-DSA sigGen Test Vectors

[[ML-DSA_sigGen_tgjs]]
==== ML-DSA sigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for ML-DSA / sigGen / FIPS204 is as follows:

[[ML-DSA_sigGen_vs_tg_table]]
.ML-DSA sigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| parameterSet | The ML-DSA parameter set used | string
| deterministic | Whether the signatures should be generated using the deterministic or non-deterministic routine | boolean
| tests | Array of individual test vector JSON objects, which are defined in <<ML-DSA_sigGen_tvjs>> | array
|===

[[ML-DSA_sigGen_tvjs]]
==== ML-DSA sigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-DSA test vector.

[[ML-DSA_sigGen_vs_tc_table]]
.ML-DSA sigGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
| sk | When the test group property `"testType": "AFT"`, the secret key that should be used to generate a signature | hex
| rnd | When the test group properties `"testType": "AFT"` and `"deterministic": false`, the random value used to generate the signature | hex
|===

The following is an example JSON object sent from the server to the client for ML-DSA / sigGen / FIPS204.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "ML-DSA",
        "mode": "sigGen",
        "revision": "FIPS204",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "GDT",
                "parameterSet": "ML-DSA-44",
                "deterministic": true,
                "tests": [
                    {
                        "tcId": 1,
                        "message": "0D873AEFD..."
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "parameterSet": "ML-DSA-44",
                "deterministic": true,
                "tests": [
                    {
                        "tcId": 61,
                        "sk": "E94EB...",
                        "message": "00E959E..."
                    }
                ]
            },
            {
                "tgId": 3,
                "testType": "AFT",
                "parameterSet": "ML-DSA-44",
                "deterministic": false,
                "tests": [
                    {
                        "tcId": 71,
                        "sk": "D4E36A5...",
                        "message": "34F4B...",
                        "rnd": "7AFF2F22A..."
                    }
                ]
            }
        ]
    }
]
----
