[[ML-DSA_sigVer_test_vectors]]
=== ML-DSA sigVer Test Vectors

[[ML-DSA_sigVer_tgjs]]
==== ML-DSA sigVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for ML-DSA / sigVer / FIPS204 is as follows:

[[ML-DSA_sigVer_vs_tg_table]]
.ML-DSA sigVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| testType | The test operation performed | string
| parameterSet | The ML-DSA parameter set used | string
| pk | The public key used to generate the signature | hex
| tests | Array of individual test vector JSON objects, which are defined in <<ML-DSA_sigVer_tvjs>> | array
|===

[[ML-DSA_sigVer_tvjs]]
==== ML-DSA sigVer Test Groups JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-DSA test vector.

[[ML-DSA_sigVer_vs_tc_table]]
.ML-DSA sigVer Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to verify with the signature | hex
| signature | THe signature to verify | hex
|===

The following is an example JSON object sent from the server to the client for ML-DSA / sigVer / FIPS204.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "ML-DSA",
        "mode": "sigVer",
        "revision": "FIPS204",
        "isSample": false,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "parameterSet": "ML-DSA-44",
                "publicKey": "3FE65294...",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "4F0D7...",
                        "signature": "C29A11B6C..."
                    },
                    {
                        "tcId": 2,
                        "message": "84793...",
                        "signature": "6A99215FC2..."
                    }
                ]
            }
        ]
    }
]
----
