[[ML-DSA_sigGen_vector_responses]]
=== ML-DSA sigGen Test Vector Responses

The test groups for ML-DSA / sigGen / FIPS204 contain public key properties. The groups can be described using the following table.

[[ML-DSA_sigGen_group_table]]
.ML-DSA sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| pk | The public key the IUT used when the prompt test group property `"testType": "GDT"` | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-DSA / sigGen / FIPS204 test vector.

[[ML-DSA_sigGen_vs_tr_table]]
.ML-DSA sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| signature | The generated signature | hex
|===

The following is an example JSON test vector response object for ML-DSA / sigGen / FIPS204.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "pk": "A9ADC1E82...",
                "tests": [
                    {
                        "tcId": 1,
                        "signature": "D7D4275..."
                    }
                ]
            },
            {
                "tgId": 2,
                "tests": [
                    {
                        "tcId": 2,
                        "signature": "75300EBBB6C..."
                    }
                ]
            }
        ]
    }
]
----
