
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KAS capabilities. This section describes the design of the tests used to validate implementations of KAS algorithms. 

=== Test Types

There are two test types for KAS testing:

* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Agreement with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to perform a successful key agreement; both the server and IUT MAY act as party U/V, as well as recipient/provider to key confirmation.

* "VAL" - Validation Test. In the VAL test mode, The ACVP server MUST generate a complete (from both party U and party V's perspectives) key agreement, and expects the IUT to be able to determine if that agreement is valid. Various types of errors *MUST* be introduced in varying portions of the key agreement process (changed DKM, changed key, changed hash digest, etc), that the IUT *MUST* be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Ar2>>. 

[[requirements_covered_kas_ecc]]
==== KAS-ECC Requirements Covered
                        
* SP 800-56Ar2 - 4.1 Key Establishment Preparations. The ACVP server is responsible for generating domain parameters as per the IUT's capability registration.

* SP 800-56Ar2 - 4.2 Key-Agreement Process. Both the ACVP server and IUT participate in the Key Agreement process. The server and IUT can both take the roles of party U/V, and as such the "performer" of steps depicted in "Figure 2: Key Agreement process" can vary.

* SP 800-56Ar2 - 5.1 Cryptographic Hash Functions. All modes of performing KAS SHALL make use of a hash function. The hash function *MAY* be used for validation of a successfully generated shared secret Z (noKdfNoKc), or as a primitive within the KDF being tested (kdfNoKc and kdfKc).

* SP 800-56Ar2 - 5.2 Message Authentication Code (MAC) Algorithm. A MAC is utilized for confirmation of success for kdfNoKc and kdfKc modes of KAS. Note - a MAC prerequisite is *REQUIRED* only for kdfKc, though is utilized for both kdfNoKc and kdfKc.

* SP 800-56Ar2 - 5.4 Nonce. Nonces are made use of in various KAS schemes - both the ACVP server and IUT SHALL be expected to generate nonces.

* SP 800-56Ar2 - 5.5 Domain Parameters. Domain Parameter Generation *SHALL* be performed solely from the ACVP server, with constraints from the IUTs capabilities registration. The same set of domain parameters *SHALL* generate all keypairs (party U/V, static/ephemeral) for a single test case.

* SP 800-56Ar2 - 5.6 Key-Pair Generation. While Key-Pairs are used in each KAS scheme, the generation of said key-pairs is out of scope for KAS testing. Random tests from the VAL groups, *MAY* inject bad keypairs that the IUT *MUST* be able detect. These random tests are only present in groups given appropriate assurance functions see: <<supported_functions>>
                            
* SP 800-56Ar2 - 4.3 DLC-based Key-Transport Process / 5.7 DLC Primitives. Depending on the scheme used, either Diffie Hellman or MQV *SHALL* be used to negotiate a shared secret of z. Testing and validation of such key exchanges is covered under their respective schemes.

* SP 800-56Ar2 - 5.8 Key-Derivation Methods for Key-Agreement Schemes. All schemes/modes save noKdfNoKc (component) *MUST* make use of a KDF. KDF construction *SHALL* utilize <<oiPatternConstruction>> for its pattern. 

* SP 800-56Ar2 - 5.9 Key Confirmation. Most KAS schemes *MAY* allow for a Key Confirmation process, the ACVP server and IUT *MAY* be Providers or Recipients of said confirmation. Additionally, key confirmation *MAY* be performed on one or both parties (depending on scheme).

* SP 800-56Ar2 - 6 Key Agreement Schemes. All schemes specified in referenced document are supported for validation with the ACVP server.

[[requirements_not_covered_kas_ecc]]
==== KAS-ECC Requirements Not Covered
                        
* SP 800-56Ar2 - 4.1 Key Establishment Preparations. The ACVP server *SHALL NOT* make a distinction between IUT generated keys via a trusted third party and the IUT itself.

* SP 800-56Ar2 - 5.3 Random Number Generation. The IUT *MUST* perform all random number generation with a validated random number generator. A DRBG is *REQUIRED* as a prerequisite to KAS, but *SHALL NOT* be in the scope testing assurances. 

* SP 800-56Ar2 - 5.4 Nonce. Nonce generation is utilized for several schemes. The various methods of generating a nonce described in section 5.4 *MUST* be used, however their generation *SHALL NOT* be in scope of KAS testing assurances.

* SP 800-56Ar2 - 5.5.2 Assurances of Domain-Parameter Validity. The ACVP server *SHALL* generate all domain parameters, IUT validation of such parameters is *SHALL NOT* be in scope for KAS testing.

* SP 800-56Ar2 - 5.5.3 Domain Parameter Management. Domain Parameter Management *SHALL NOT* be in scope for KAS testing.

* SP 800-56Ar2 - 5.6 Key-Pair Generation. While Key-Pairs *MUST* be used in each KAS scheme, the generation, assurances, and management of said key-pairs *SHALL NOT* be in scope of KAS testing.

* SP 800-56Ar2 - 5.8 Key-Derivation Methods for Key-Agreement Schemes. Two-step Key-Derivation (Extraction-then-Expansion) *SHALL NOT* be utilized in KAS testing.

* SP 800-56Ar2 - 5.7 Rationale for Selecting a Specific Scheme. It is expected that the IUT registers all schemes it supports in its capabilities registration. Selecting specific schemes from a KAS testing perspective *SHALL NOT* be in scope.

* SP 800-56Ar2 - 8 Key Recovery. Key Recovery *SHALL NOT* be in scope of KAS testing.