[[tgjs]]
=== Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for KAS ECC is as follows:

[[vs_tg_table5]]
.Vector Group JSON Object
|===
| JSON Value| Description| JSON type| Optional
| tgId| Numeric identifier for the test group, unique across the entire vector set.| value| No
| scheme| The scheme for the test vectors. See <<supported_schemes>> for possible values | value| No
| testType|  The type of testCases expected within the group. AFT (Functional) tests produce test cases where the prompt file delivers only the needed public server information in which the IUT is expected to perform KAS. VAL (Validity) tests produce inputs/outputs from both server and IUT perspectives of a KAS negotiation. The expectation of the IUT on such tests is to determine if the KAS negotiation was successful or not. | AFT, VAL| No
| kasRole| The KAS role| initiator, responder| No
| kasMode| The KAS mode| noKdfNoKc, kdfNoKc, kdfKc| No
| parmSet| Parameter set value to use| eb, ec, ed, ee| No
| hashAlg| hashAlg values being used| See <<supported_hashAlg>>| No
| macType| The MAC being used. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| See <<supported_macOption>>| Yes
| keyLen| The key length of the MAC. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| See <<supported_macOption>>| Yes
| nonceAesCcmLen| The nonce length of the MAC (applies only to AES-CCM). *REQUIRED* for "kdfNoKc" and "kdfKc" modes using a AES-CCM MAC.| See  <<supported_macOption>>| Yes
| macLen| The mac length. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| See <<supported_macOption>>| Yes
| kdfType| The KDF being used. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| concatenation, asn1| Yes
| idServerLen| The length of the server ID. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| value| Yes
| idServer| The server ID. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| value| Yes
| idIutLen| The length of the server ID. *REQUIRED* for "kdfNoKc" and "kdfKc" modes. Provided in response by IUT for AFT tests.| value| Yes
| idIut| The server ID. *REQUIRED* for "kdfNoKc" and "kdfKc" modes. Provided in response by IUT for AFT tests.| value| Yes
| oiPattern| The oiPattern used in the KDF. *REQUIRED* for "kdfNoKc" and "kdfKc" modes.| See <<oiPatternConstruction>>| Yes
| kcRole| Key confirmation roles supported. *REQUIRED* for "kdfKc" modes.| provider, recipient| Yes
| kcType| Key confirmation types supported. *REQUIRED* for "kdfKc" modes.| unilateral and/or bilateral| Yes
| curve| The curve useds for keypair generation| value| No
| tests| Array of individual test vector JSON objects, which are defined in <<tvjs>>| array| No
|===

[[tvjs]]
=== Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each test vector.

[[vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value| Description| JSON type| Optional

| tcId| Numeric identifier for the test case, unique across the entire vector set.| value| No
| staticPublicServerX| The ECDSA static public key X coordinate| value| Yes
| staticPublicServerY| The ECDSA static public key Y coordinate| value| Yes
| ephemeralPublicServerX| The ECDSA ephemeral public key X coordinate| value| Yes
| ephemeralPublicServerY| The ECDSA ephemeral public key Y coordinate| value| Yes
| nonceEphemeralServer| nonceEphemeralServer ONLY USED BY C(1,2) and C(0,2) schemes with KC. nonce to be used in the MacData field| value| Yes
| nonceNoKc| The 16 byte nonce concatenated to the "Standard Test Message". Used for No Key Confirmation tests only.| value| Yes
| nonceDkm| The nonce supplied by the initiator to be used in the OI field in the PartyUInfo field.| value| Yes
| staticPrivateIut| The IUT ECDSA static private key| value| Yes
| staticPublicIutX| The IUT ECDSA static public key X coordinate| value| Yes
| staticPublicIutY| The IUT ECDSA static public key Y coordinate| value| Yes
| ephemeralPrivateIut| The IUT ECDSA ephemeral private key| value| Yes
| ephemeralPublicIutX| The IUT ECDSA ephemeral public key X coordinate| value| Yes
| ephemeralPublicIutY| The IUT ECDSA ephemeral public key Y coordinate| value| Yes
| oiLen| Length of the OtherInfo field| value| Yes
| oi| OtherInfo field| value| Yes
| dkm| Derived Keying Material.| value| Yes
| tagIut| The tag (or MAC) GENERATED BY THE SERVER/IUT by using the DKM to MAC the Message with the specified method | value| Yes
| nonceEphemeralIut| nonceEphemeralIut ONLY USED BY C(1,2) and C(0,2) schemes with KC. nonce to be used in the MacData field| value| Yes
| nonceDkmIut| ONLY USED BY STATIC SCHEME. The nonce supplied by the initiator to be used in the OI field in the PartyUInfo field| value| Yes
| nonceLenDkm| ONLY USED BY STATIC SCHEME. The length of the nonce supplied by the initiator to be used in the OI field in the PartyUInfo field.| value| Yes
| nonceEphemeralDkm| ONLY USED BY C(1,2) and C(0,2) schemes with KC. nonce to be used in the MacData field| value| Yes
| nonceEphemralDkmLen| length of nonceEphemeralIut value.| value| Yes
| nonceAesCcm| Nonce used by the CCM function, if CCM is used to generate the Tag.| value| Yes
| macData| The message to be MAced.| value| Yes
| z| A shared secret that is used to derive secret keying material using a key derivation function.| value| Yes
| hashZServer| The hashed shared secret, only provided in noKdfNoKc modes of operation.| value| Yes
| hashZIut| The hashed shared secret, only provided in noKdfNoKc modes of operation.| value| Yes
| testPassed| Pass Fail indicating if the IUT agrees with the Tag generated by the server.| boolean| Yes
|===

[[app-vs-ex]]
=== Example Test Vectors JSON Object

The following is a example JSON object for KAS ECC test vectors sent from the ACVP server to the crypto module.

[source,json]
----
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1564,
		"algorithm": "KAS-ECC",
		"revision": "1.0",
		"testGroups": [
			{
                "tgId": 1,
				"scheme": "ephemeralUnified",
				"testType": "AFT",
				"kasRole": "initiator",
				"kasMode": "kdfNoKc",
				"parmSet": "ec",
				"hashAlg": "SHA2-256",
				"macType": "AES-CCM",
				"keyLen": 128,
				"aesCcmNonceLen": 64,
				"macLen": 128,
				"kdfType": "asn1",
				"idServerLen": 48,
				"idServer": "434156536964",
				"curve": "P-256",
				"tests": [{
					"tcId": 151,
					"ephemeralPublicServerX": "CBC9AF2F0FCE0F06643D7524DCCA96C78564BA77196C5F5F65DC0A119409A1F3",
					"ephemeralPublicServerY": "B619EBE85F2EC5E0A9B542CC77539D698C96CA5D0BDFCA224787C30CF971E3F4",
					"nonceNoKc": "BBDF1A42C9405B58B8329D583C437331",
					"nonceAesCcm": "FF5B0FD5F295257B"
				}]
			},
			{
                "tgId": 2,
				"scheme": "ephemeralUnified",
				"testType": "AFT",
				"kasRole": "responder",
				"kasMode": "kdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"macType": "HMAC-SHA2-224",
				"keyLen": 128,
				"macLen": 128,
				"kdfType": "asn1",
				"idServerLen": 48,
				"idServer": "434156536964",
				"curve": "P-224",
				"tests": [{
					"tcId": 161,
					"ephemeralPublicServerX": "FFAD4CDB4293F61C2A74566FD4323A03C6BB3F9D6526D8E0506B2186",
					"ephemeralPublicServerY": "0D614DAA05395A5FDF51BC769AEC355C9688ECEFCF2FE10E6DC1030E",
					"nonceNoKc": "BEAB1A2CB8406A7083105EC234603A80"
				}]
			},
			{
                "tgId": 3,
				"scheme": "ephemeralUnified",
				"testType": "VAL",
				"kasRole": "initiator",
				"kasMode": "kdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"macType": "HMAC-SHA2-224",
				"keyLen": 128,
				"macLen": 128,
				"kdfType": "asn1",
				"idServerLen": 48,
				"idServer": "434156536964",
				"idIutLen": 0,
				"curve": "P-224",
				"tests": [{
					"tcId": 181,
					"ephemeralPublicServerX": "D489605D37C4F555E50D8F010BEE3165B93F7C749263C4BF3E9A4808",
					"ephemeralPublicServerY": "23C8167ACFB24DC62D6747960330471B28DC646E04E593DBE6F8F1A4",
					"nonceNoKc": "6BBFEECEBBD5200C5FAE050526A77342",
					"ephemeralPrivateIut": "343936401C5F88E658E2C9C47C2EB48DDE10506684D8B55027C05A15",
					"ephemeralPublicIutX": "14AA2C1ECDC258FE8AD035E9A2872CD14466783F82F5F3F8D757133A",
					"ephemeralPublicIutY": "8DD3D48BF9115EA5AB7A479FB1DAB0A46BCD6B4D1A306D5CAC254EC1",
					"oiLen": 376,
					"otherInfo": "A1B2C3D4E5434156536964CAFECAFE2D822B413172BB3012AA986AFFAE95B46360E00AAD0D0548104C1F946389B97D",
					"tagIut": "5EEE5D912191984D89DF074B9A885411"
				}]
			},
			{
                "tgId": 4,
				"scheme": "ephemeralUnified",
				"testType": "VAL",
				"kasRole": "responder",
				"kasMode": "kdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"macType": "AES-CCM",
				"keyLen": 128,
				"aesCcmNonceLen": 64,
				"macLen": 128,
				"kdfType": "asn1",
				"idServerLen": 48,
				"idServer": "434156536964",
				"idIutLen": 0,
				"curve": "P-224",
				"tests": [{
					"tcId": 231,
					"ephemeralPublicServerX": "A0457CF2F5D38B72FF1BF3A2CF4C7CE30F215B5E52A53C39193B1639",
					"ephemeralPublicServerY": "38CA7951888E462D6C5F4E46FA953FF231F43D5A4F3FEBAEEBF3D52B",
					"nonceNoKc": "A889762176F5F02F8C1E4BBC0C669805",
					"ephemeralPrivateIut": "5F76009454AE9158797467C297229569C6E2027D6AFC226A63489444",
					"ephemeralPublicIutX": "1060CEE336B183738952CF13760D542E2F3AA60124D560EFA10F392C",
					"ephemeralPublicIutY": "216EA3B35E630A1EA4A91C430E5B63306A83624F0FFD8ADFF63A380E",
					"oiLen": 376,
					"otherInfo": "454156536964A1B2C3D4E5CAFECAFE9EF1EA2DC20EE820E7562CDD4DBCD5FD8CD57DB1F54961D8B0C83342C09B7D72",
					"nonceAesCcm": "BD79B8A8D5559128",
					"tagIut": "5CC10EF2564B0CD23D746A47DB5B98A2"
				}]
			}
		]
	}
]
----

[[app-vs-component-ex]]
=== Example Test Vectors Component JSON Object

The following is a example JSON object for KAS ECC Component test vectors sent from the ACVP server to the crypto module.

[source,json]
----                
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1565,
		"algorithm": "KAS-ECC",
		"mode": "Component",
		"revision": "1.0",
		"testGroups": [{
                "tgId": 1,
				"scheme": "ephemeralUnified",
				"testType": "AFT",
				"kasRole": "initiator",
				"kasMode": "noKdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"curve": "P-224",
				"tests": [{
					"tcId": 1,
					"ephemeralPublicServerX": "DACE4B35FD720DDD6B307777EBAFE53859C5FC2D330755B05B061CEB",
					"ephemeralPublicServerY": "195344DE0C79898C5C060BFACE1D24FDE1127ECF503EA04B08FFB9F1"
				}]
			}, {
                "tgId": 2,
				"scheme": "ephemeralUnified",
				"testType": "AFT",
				"kasRole": "responder",
				"kasMode": "noKdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"curve": "P-224",
				"tests": [{
					"tcId": 21,
					"ephemeralPublicServerX": "747EDBB8F62E1F06BD542FC2DD93169CB24DA6EF9E2FED4FE60FCBE6",
					"ephemeralPublicServerY": "C7FB2C3C9B95E70D908B9992C8018B785F7BCD3E5967E37EFB18A422"
				}]
			},
			{
                "tgId": 3,
				"scheme": "ephemeralUnified",
				"testType": "VAL",
				"kasRole": "initiator",
				"kasMode": "noKdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"curve": "P-224",
				"tests": [{
					"tcId": 41,
					"ephemeralPublicServerX": "866BD81E951787AA1130CB67BA48E22F8A9E7EFF0713418B4FB8A31C",
					"ephemeralPublicServerY": "050C9E3DB4560313979FE465AC8624E93BC0D97E7C68AC589840BCF7",
					"ephemeralPrivateIut": "0C9AE6286544FED81921E6495B946C6AF39DF90EC68379CEF2F7C69D",
					"ephemeralPublicIutX": "CA296A5C86EC39C4EA626A8D9AB39DE5D5092FAA3AE2F241D7791497",
					"ephemeralPublicIutY": "F768358D14A428C61A3229FB4BB752F02ECC1F54763CA98655A8412C",
					"hashZIut": "FC6268A34B63B5A82AF03A6CABE61C69CC57317E5E8C8F508FCB82D0"
				}]
			},
			{
                "tgId": 4,
				"scheme": "ephemeralUnified",
				"testType": "VAL",
				"kasRole": "responder",
				"kasMode": "noKdfNoKc",
				"parmSet": "eb",
				"hashAlg": "SHA2-224",
				"curve": "P-224",
				"tests": [{
					"tcId": 91,
					"ephemeralPublicServerX": "7A2EBA553C4DC0E4D7A19A3648BA9713496EB462B1B7D83D375F7FFD",
					"ephemeralPublicServerY": "5972BF3B114612AA5BBA14D0BE956DED03359F52ADDF0B9C2D0314E1",
					"ephemeralPrivateIut": "9AEDA69CE438C6F8592CE3B8E14E92BE9143E82B3EED42CF62E45BF7",
					"ephemeralPublicIutX": "941DAF3C527D2B76AA907F60C208F8987681972E466529CA8BD962FD",
					"ephemeralPublicIutY": "F381EC5DBEA7F6EA3A09D2D75372C014C3DE3ECABBBBC00DDFB97359",
					"hashZIut": "BB61FA1DCA5D93A6FBB43317AABCAE22A3EDF7F72216516115935D4E"
				}]
			}
		]
	}
]
----