[[vector_responses]]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[vr_top_table]]
=== Vector Set Response JSON Object

.Vector Set Response JSON Object
|===
| JSON Value| Description| JSON type

| acvVersion| Protocol version identifier| value
| vsId| Unique numeric identifier for the vector set| value
| testGroups| Array of JSON objects that represent each test vector group. See <<vr_group_table>>| array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the  client to send back group level properties in their response. This structure helps accommodate that.

[[vr_group_table]]
=== Vector Set Group Response JSON Object

.Vector Set Group Response JSON Object
|===
| JSON Value| Description| JSON type

| tgId| The test group Id| value
| tests| The tests associated to the group specified in tgId| value
|===

[[app-results-ex]]
=== Example Test Results JSON Object

The following is a example JSON object for KAS ECC test results sent from the crypto module to the ACVP server.

[source,json]
----                
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1564,
		"testGroups": [{
				"tgId": 1,
				"tests": [{
					"tcId": 151,
					"nonceNoKc": "BBDF1A42C9405B58B8329D583C437331",
					"ephemeralPublicIutX": "F90FE5B7D5DA0F7849B0849D780143F4CC7E9F080465AA05DBD3E610D6B24763",
					"ephemeralPublicIutY": "1D746A8F960AE8425C63DE17618362F7040365D9168F21A0762526ECCC556084",
					"idIutLen": 40,
					"idIut": "A1B2C3D4E5",
					"oiLen": 376,
					"oi": "A1B2C3D4E5434156536964CAFECAFEA0988C0EB862E29CBFBD0B087D3223B9052811800B2D1ADF1D42AE73BAAD162A",
					"nonceAesCcm": "FF5B0FD5F295257B",
					"tagIut": "FF1ADCA06E582AD9E4A8B7FE3D7D9C28"
				}]
			},
			{
				"tgId": 2,
				"tests": [{
					"tcId": 161,
					"nonceNoKc": "BEAB1A2CB8406A7083105EC234603A80",
					"ephemeralPublicIutX": "C5D934686BAB0E156D4F5CF1BDA7B044128C803E4C8AA2D9B0024FC0",
					"ephemeralPublicIutY": "E2D8973A51A9CE0FA7FAD8A444ECAB518C672C65313BEE4150CFD50E",
					"idIutLen": 40,
					"idIut": "A1B2C3D4E5",
					"oiLen": 376,
					"oi": "434156536964A1B2C3D4E5CAFECAFE9D9E4AB0A187C117158C9A234F4AEE8328714003BFED6C08A7F191E61DCA2B6A",
					"tagIut": "77587ED9D13B811F200214FD5E1F864A"
				}]
			},
			{
				"tgId": 3,
				"tests": [{
					"tcId": 181,
					"testPassed": false
				}]
			},
			{
				"tgId": 4,
				"tests": [{
					"tcId": 231,
					"testPassed": false
				}]
			}
		]
	}
]
----

[[app-results-component-ex]]
=== Example Test Results Component JSON Object

The following is a example JSON object for KAS ECC Component test results sent from the crypto module to the ACVP server.

[source,json]
----                
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1564,
		"testGroups": [{
				"tgId": 1,
				"tests": [{
					"tcId": 1,
					"ephemeralPublicIutX": "50471CE7F6FE2CAD6C901F85BF258E84571D3C88F59356B91DDBF286",
					"ephemeralPublicIutY": "5B8A7BC07BE15F28D34AA8324DEE93C715F569D3AF4820209F6452E7",
					"hashZIut": "96DCAF87127AB615896CCD0479C8BEAFD7EE111F384C962687D28ACC"
				}]
			},
			{
				"tgId": 2,
				"tests": [{
					"tcId": 21,
					"ephemeralPublicIutX": "3E95CE4241A63C4ECBDC12CF2A3FB9E56222C0D395885CF0B51B04F7",
					"ephemeralPublicIutY": "F8865F76DE98CFCFBBAD2E99A317636F48AC874847E0A489C96631EC",
					"hashZIut": "3B7721F7514C09DD38D62E72E20D0375A7B3AC5BD837A7B860BC65FA"
				}]
			},
			{
				"tgId": 3,
				"tests": [{
					"tcId": 41,
					"testPassed": false
				}]
			},
			{
				"tgId": 4,
				"tests": [{
					"tcId": 91,
					"testPassed": true
				}]
			}
		]
	}
]
----