
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified LMS algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of LMS capabilities. This section describes the design of the tests used to validate implementations of the LMS algorithms.

* LMS / keyGen / * "AFT" - Algorithm Functional Test. The IUT is *REQUIRED* for each test case provided, to generate a key pair based on an approved tree structure. This information is then communicated to the ACVP server and validated.

* LMS / sigGen / * "AFT" - Algorithm Functional Test. This testing mode expects the IUT to generate valid signatures based on the ACVP provided message. The signature is then validated with the ACVP server given the IUT's communicated tree structure, public key, and signature.

* LMS / sigVer / * "AFT" - Algorithm Functional Test. The ACVP server generates a series of signatures to communicate to the IUT. The IUT is *REQUIRED* to determine the validity of the signature given the tree structure, key, and message.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-208>>.

[[requirements_covered]]
==== Requirements Covered

* SP 800-208 Section 8. Conformance. The tests provided by ACVP are only able to provide a correctness assertion of an implementation. 
* Due to the randomized nature of generating LMS trees, the ACVP server *MAY* test implementations against the pseudorandom key generation process defined in <<RFC8554>> Appendix A. 

[[requirements_not_covered]]
==== Requirements Not Covered

* SP800-208 Section 8. Conformance. Many requirements outlined in this section are not testable by ACVP. ACVP does not test the inability of an implementation to export a private key. ACVP does not provide any guarantees on the inability to reuse private OTS pairs of an implementation.
