[[LMS_sigVer_test_vectors]]
=== LMS sigVer Test Vectors

[[LMS_sigVer_tgjs]]
==== LMS sigVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for LMS / sigVer / 1.0 is as follows:

[[LMS_sigVer_vs_tg_table]]
.LMS sigVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| lmsMode | The LMS tree structure used | string
| lmOtsMode | The LMOTS tree structure used | string
| publicKey | The public key of the LMS tree | hex
| tests | Array of individual test vector JSON objects, which are defined in <<LMS_sigVer_tvjs>> | array
|===

[[LMS_sigVer_tvjs]]
==== LMS sigVer Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each LMS test vector.

[[LMS_sigVer_vs_tc_table]]
.LMS sigVer Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to verify with the signature | hex
| signature | THe signature to verify | hex
|===

The following is an example JSON object sent from the server to the client for LMS / sigVer / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "LMS",
        "mode": "sigVer",
        "revision": "1.0",
        "isSample": false,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "lmsMode": "LMS_SHA256_M24_H10",
                "lmOtsMode": "LMOTS_SHA256_N24_W1",
                "publicKey": "0000000B00000005FA5F14B9EEA8886576EF0E190A96F12D16734708776A2BB1D7F53610343D3B2F9361CB6F315E8860",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "4F0D7...",
                        "signature": "0000026300000005EE3..."
                    },
                    {
                        "tcId": 2,
                        "message": "84793...",
                        "signature": "8000017000000005E00..."
                    }
                ]
            }
        ]
    }
]
----
