[[LMS_sigGen_test_vectors]]
=== LMS sigGen Test Vectors

[[LMS_sigGen_tgjs]]
==== LMS sigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for LMS / sigGen / 1.0 is as follows:

[[LMS_sigGen_vs_tg_table]]
.LMS sigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| lmsMode | The LMS tree structure used | string
| lmOtsMode | The LMOTS tree structure used | string
| tests | Array of individual test vector JSON objects, which are defined in <<LMS_sigGen_tvjs>> | array
|===

[[LMS_sigGen_tvjs]]
==== LMS sigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each LMS test vector.

[[LMS_sigGen_vs_tc_table]]
.LMS sigGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
|===

The following is an example JSON object sent from the server to the client for LMS / sigGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "LMS",
        "mode": "sigGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "lmsMode": "LMS_SHA256_M24_H5",
                "lmOtsMode": "LMOTS_SHA256_N24_W2",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "2C4719..."
                    },
                    {
                        "tcId": 2,
                        "message": "4F0E7D..."
                    }
                ]
            }
        ]
    }
]
----
