[[LMS_sigGen_vector_responses]]
=== LMS sigGen Test Vector Responses

The test groups for LMS / sigGen / 1.0 contain public key properties. The groups can be described using the following table.

[[LMS_sigGen_group_table]]
.LMS sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| publicKey | The public key of the tree the IUT used | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each LMS / sigGen / 1.0 test vector.

[[LMS_sigGen_vs_tr_table]]
.LMS sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| signature | The generated signature | hex
|===

The following is an example JSON test vector response object for LMS / sigGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "publicKey": "0000000A000000064D2A698120B6AAF7FED6EA4E...",
                "tests": [
                    {
                        "tcId": 1,
                        "signature": "0000000F00000006D789CF...",
                    }
                ]
            },
            {
                "tgId": 2,
                "publicKey": "0000000B000000055FF5A7FD9CC554B3...",
                "tests": [
                    {
                        "tcId": 2,
                        "signature": "00000008000000053659BCB1079...",
                    }
                ]
            }
        ]
    }
]
----
