
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KAS capabilities. This section describes the design of the tests used to validate implementations of KAS algorithms.


=== Test Types
				
There are two test types for KAS testing:
 
* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Agreement with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to compute a shared secret `z`; both the server and IUT *MAY* act as party U/V.

* "VAL" - Validation test. In the VAL test mode, The ACVP server *MUST* generate a complete (from both party U and party V's perspectives) shared secret `z`, and expects the IUT to be able to determine if that shared secret is valid. Various types of conditions/errors *MUST* be introduced in varying portions of the key agreement process (changed Z, Z with leading zero nibble, etc), that the IUT *MUST* be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Br2>>. 


[[requirements_covered]]
==== Requirements Covered
                        
* SP 800-56Br2 - 5.3 Random Bit Generators.  Though random values are used, the testing of the construction of those random values
*SHALL NOT* be in scope of ACVP testing.

* SP 800-56Br2 - 6.2 Criteria for RSA Key Pairs for Key Establishment.  The ACVP server *SHALL* support the three key generation methods of "basic", "prime factor", and "CRT".

* SP 800-56Br2 - 6.3 RSA Key-Pair Generators.  The ACVP server *SHALL* utilize IUT provided RSA public keys, and generate key pairs to
accommodate testing.  The ACVP server *SHALL* support both fixed and random public exponents.

* SP 800-56Br2 - 7 Primitives and Operations.  7.1 Encryption and Decryption primitives as well as 7.2 Encryption and Decryption Operations *SHALL* be used for the calculation/validation of the shared secret `z`.

* SP 800-56Br2 - 8 Key-Agreement Schemes.  ACVP server testing will make use of "KAS1" and "KAS2" for testing of shared secret `z`. These exact schemes are not specified in the document, as "-basic" and "*-confirmation" make use of at least a KDF, if not also Key Confirmation.  The intention of testing against the algorithm described in this document is specifically around the calculation of the shared secret `z`.

[[requirements_not_covered]]
==== Requirements Not Covered
 
* SP 800-56Br2 - 5.3 Random Bit Generators.  Though random values are used, the testing of the construction of those random values
*SHALL NOT* be in scope of ACVP testing.

* KAS SSC testing only covers testing of SP800-56Br2 through the computation of a shared secret `z`.  Additional functions of KAS as a whole such as KDF, KC, etc. *MAY* be covered within the scope of the full KAS testing; please see that document for further details.
    