
[#properties]
=== Property Registration

The TLS KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

[#registration]
=== Registration Example

A registration *SHALL* use these properties

.TLS KDF Mode Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "tls"
| revision | ACVP Test version | string | "1.0"
| tlsVersion | The version of TLS supported | array | "v1.0/1.1", "v1.2"
| hashAlg | SHA functions supported if TLS Version "v1.2" is included in the registration | array | See <<valid-sha>>
|===

Note that the "hashAlg" field is *REQUIRED* when "v1.2" is present within the "tlsVersion" array.

An example registration within an algorithm capability exchange looks like this

[align=left,alt=,type=]
[source, json]
----
{
    "algorithm": "kdf-components",
    "mode": "tls",
    "revision": "1.0",
    "tlsVersion": [
        "v1.0/1.1",
        "v1.2"
    ],
    "hashAlg": [
        "SHA2-256",
        "SHA2-384",
        "SHA2-512"
    ]
}
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA2-256
* SHA2-384
* SHA2-512
