
[#properties]
=== Property Registration

The TLS KDF mode capabilities are advertised as JSON objects within a root "algorithm" object.

A registration *SHALL* use these properties

.TLS KDF Mode Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components", "TLS-v1.2"
| mode | Mode of the algorithm to be validated | string | "tls", "KDF"
| revision | ACVP Test version | string | "1.0", "RFC7627"
| tlsVersion | The version of TLS supported | array | "v1.0/1.1", "v1.2".  Note TLS v1.2 w/ extended master secret testing, i.e., TLS-v1.2 / KDF / RFC7627, does not use this property.
| hashAlg | SHA functions supported if TLS Version "v1.2" is included in the registration | array | See <<valid-sha>>
| keyBlockLength | The length of the key block in bits. If omitted from the registration, a default value of 1024 will be used for TLS v1.2 w/ extended master secret testing, i.e., TLS-v1.2 / KDF / RFC7627. If omitted from the registration, default values of 832 and 1024 will be used for kdf-components / tls / 1.0 tlsVersion v1.0/1.1 and kdf-components / tls / 1.0 tlsVersion v1.2 respectively.  | domain | {"Min": 512, "Max": 1024, "Increment": 8}
|===

NOTE: the "hashAlg" field is *REQUIRED* when "v1.2" is present within the "tlsVersion" array.

NOTE: when the keyBlockLength registration property is supplied for a kdf-components / tls / 1.0 registration, the values supplied for keyBlockLength will be tested across each value supplied to the the tlsVersion property.

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA2-256
* SHA2-384
* SHA2-512

[#registration]
=== Registration Example

An example registration within an algorithm capability exchange looks like this

[align=left,alt=,type=]
[source, json]
----
{
    "algorithm": "kdf-components",
    "mode": "tls",
    "revision": "1.0",
    "tlsVersion": [
        "v1.0/1.1",
        "v1.2"
    ],
    "hashAlg": [
        "SHA2-256",
        "SHA2-384",
        "SHA2-512"
    ]
},
{
    "algorithm": "TLS-v1.2",
    "mode": "KDF",
    "revision": "RFC7627",
    "hashAlg": [
        "SHA2-256",
        "SHA2-384",
        "SHA2-512"
    ]
}
----

