
[[tgjs]]
=== Test Groups

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Test operations to be performed | string
| tlsVersion | The version of TLS used in the test group. Not included for TLS-v1.2 / KDF / RFC7627 testing. | string
| hashAlg | SHA version used | string
| preMasterSecretLength | Pre-master secret length in bits | integer
| keyBlockLength | Key block length in bits | integer
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. 

=== Test Cases

==== Revision 1.0 Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.1.0 Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case idenfitier | integer
| preMasterSecret | Pre-master secret value | hex
| serverHelloRandom | Server Hello random value | hex
| clientHelloRandom | Client Hello random value | hex
| serverRandom | Server random value | hex
| clientRandom | Client random value | hex
|===

Here is an abbreviated yet fully constructed example of the prompt.

[align=left,alt=,type=]
[source, json]
----
{
    "vsId": 1,
    "algorithm": "kdf-components",
    "mode": "tls",
    "revision": "1.0",
    "testGroups": [
        {
            "tgId": 1,
            "hashAlg": "SHA-1",
            "tlsVersion": "v1.0/1.1",
            "keyBlockLength": 832,
            "preMasterSecretLength": 384,
            "testType": "AFT",
            "tests": [
                {
                    "tcId": 1,
                    "preMasterSecret": "2F0D26CC2487169D83D9...",
                    "clientHelloRandom": "00D5EDFC0A7D8B0913...",
                    "serverHelloRandom": "14D06FC8F2792762BA...",
                    "clientRandom": "DDFB77CB1304A0541C6CC07...",
                    "serverRandom": "D59EB4E444005709409C572..."

                }
            ]
        }
    ]
}
----

==== Revision RFC7627 Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.RFC7627 Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case idenfitier | integer
| preMasterSecret | Pre-master secret value | hex
| sessionHash | the hash value of the concatenated handshake messages | hex
| serverRandom | Server random value | hex
| clientRandom | Client random value | hex
|===

Here is an abbreviated yet fully constructed example of the prompt.

[align=left,alt=,type=]
[source, json]
----
{
    "vsId": 1,
    "algorithm": "TLS-v1.2",
    "mode": "KDF",
    "revision": "RFC7627",
    "testGroups": [
        {
            "tgId": 1,
            "hashAlg": "SHA2-256",
            "keyBlockLength": 1024,            
            "preMasterSecretLength": 384,
            "testType": "AFT",
            "tests": [
                {
                    "tcId": 1,
                    "preMasterSecret": "2F0D26CC2487169D83D9...",
                    "sessionHash": "00D5EDFC0A7D8B0913...",
                    "clientRandom": "DDFB77CB1304A0541C6CC07...",
                    "serverRandom": "D59EB4E444005709409C572..."
                }
            ]
        }
    ]
}
----
