
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified SPDM algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of SPDM capabilities. This section describes the design of the tests used to validate implementations of the SPDM algorithms. The number of tests *MAY* vary but the minimum number required by each test type *SHALL* be included by the server. The test type describes the format of the test rather than the intention of the test. Multiple tests of the same test type *MAY* cover different assurances regarding the implementation. 

==== SPDM Test Types

* KDF / SPDM / * "AFT" - Algorithm Functional Test. 

For each test case provided the IUT *SHALL* perform the key schedule. The IUT *SHALL* use the provided key, th1, and th2 values. The IUT-computed requestHandshakeSecret, responseHandshakeSecret, requestDataSecret, responseDataSecret, and exportMasterSecret are communicated to the ACVP server and compared to the requestHandshakeSecret, responseHandshakeSecret, requestDataSecret, responseDataSecret, and exportMasterSecret. This tests the implementation of Section 12 `Key schedule` from <<DSP0274 1.4.0>>. The server *SHALL* provide at least 20 tests for each combination of capabilities. 

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<DSP0274 1.4.0>> section 12.

[[requirements_covered]]
==== Requirements Covered

* The tests will support ensuring the conformity and correctness of an implementation of the algorithms supported. 

[[requirements_not_covered]]
==== Requirements Not Covered

*  DSP0274 Section 12.7. Encryption key and IV derivation. Requirements outlined in this section are not required for the derivation of key schedule secrets.
*  DSP0274 Section 12.8. finished_key derivation. Requirements outlined in this section are not required for the derivation of key schedule secrets.
*  DSP0274 Section 12.9. Deriving additional keys from the Export Master Secret. Requirements outlined in this section are not required for the derivation of key schedule secrets.
*  DSP0274 Section 12.10. Major secrets update. Requirements outlined in this section are not required for the derivation of key schedule secrets.

