[[SPDM_keySchedule_test_vectors]]
=== SPDM Key Schedule (KDF) Test Vectors

[[SPDM_keySchedule_tgjs]]
==== SPDM Key Schedule (KDF) Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for KDF / SPDM / 1.0 is as follows:

[[SPDM_keySchedule_vs_tg_table]]
.SPDM Key Schedule Test Group JSON Object
|===
| JSON Value | Description | JSON type
| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| hashFunction | The hash function being used | string
| version | The version of SPDM being used | string
| usesPSK | Boolean to indicate a pre-shared key was used | boolean
| tests | Array of individual test vector JSON objects, which are defined in <<SPDM_keySchedule_tvjs>> | array
|===

[[SPDM_keySchedule_tvjs]]
==== SPDM Key Schedule Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each KDF / SPDM / 1.0 test vector.

[[SPDM_keySchedule_vs_tc_table]]
.SPDM Key Schedule Test Case JSON Object
|===
| JSON Value | Description | JSON type
| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| key | Key value | hex
| th1 | th1 value | hex
| th2 | th2 value | hex
|===

The following is an example JSON object sent from the server to the client for KDF / SPDM / 1.0. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
      "tgId": 1,
      "testType": "AFT",
      "hashFunction": "SHA2-256",
      "version": "spdm1.1",
      "usesPSK": true,
      "tests": [
        {
          "tcId": 1,
          "key": "C12739BD0F96486D191A9FC600DAD916",
          "th1": "69113EA14402509B67E702202A4A7F2DD86C23C47990F17F0A50A1C7235BF166",
          "th2": "40690C9E7787F30A63A0FDEE3DE2BDDB4A54A10ED481D089746AA225A9E41EE3",
        }
      ]
    }
]
----
