[[SPDM_keySchedule_vector_responses]]
=== SPDM Key Schedule (KDF) Test Vector Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents the results of an ACVP client processing a single test vector. The following table describes the JSON elements for each KDF / SPDM / 1.0 test vector.

[[SPDM_keySchedule_vs_tr_table]]
.SPDM Key Schedule Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| requestHandshakeSecret | requestHandshakeSecret value | hex
| responseHandshakeSecret | responseHandshakeSecret value | hex
| requestDataSecret | requestDataSecret value | hex
| responseDataSecret | responseDataSecret value | hex
| exportMasterSecret | exportMasterSecret value| hex
|===

The following is an example JSON test vector response object for KDF / SPDM / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "KDF",
        "mode": "SPDM",
        "revision": "1.0",
        "isSample": false,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "hashFunction": "SHA2-256",
                "version": "spdm1.1",
                "usesPSK": true,
                "tests": [
                    {
                        "tcId": 1,
                        "requestHandshakeSecret": "91EC543847C46D5F49DBBA2D97B44702321BCE7CBA2F47A7E31A094804B5C0B6",
                        "responseHandshakeSecret": "7F79607B96752A924F1121E1616CB668597511C3B34A05465071CA8A03729D46",
                        "requestDataSecret": "3AC23CC538C7E3A6B62AAEF1AC91177928510A9E082E6F450FCBD1EB6D9188CD",
                        "responseDataSecret": "EDBFC7466F6BADD78306719AA041A300C164F65614D33C2F642C2ED8923DE6E9",
                        "exportMasterSecret": "05A487949D88F4CBA940EF740A0DE4583A6DD7D38E1B486FEAECD3F270BC09C6"
                    }
                ]
            }
        ]
    }
]
----
