
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified ECDSA algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of ECDSA capabilities. This section describes the design of the tests used to validate implementations of the ECDSA algorithms.

* ECDSA / keyGen / * "AFT" - Algorithm Functional Test. The IUT is *REQUIRED* for each test case provided, to generate a key pair based on an approved curve. This information is then communicated to the ACVP server and validated.

* ECDSA / keyVer / * "AFT" - Algorithm Functional Test. The ACVP server is *REQUIRED* to generate a series of keys based on the IUT provided NIST curve(s). The keys generated by the server *MAY* or *MAY NOT* be valid, the IUT is *REQUIRED* to determine if the keys provided in the test cases are valid or invalid keys as they relate to the curve.

* ECDSA / sigGen / * "AFT" - Algorithm Functional Test. This testing mode expects the IUT to generate valid signatures based on the ACVP provided message. The signature is then validated with the ACVP server given the IUT's communicated curve, public key, and signature.

* ECDSA / sigVer / * "AFT" - Algorithm Functional Test. The ACVP server generates a series of signatures to communicate to the IUT. The IUT is *REQUIRED* to determine the validity of the signature given the curve, key, and message.

* DetECDSA / sigGen / FIPS186-5 "AFT" - Algorithm Functional Test. This testing mode expects the IUT to generate valid signatures based on the ACVP provided message. The signature is then validated with the ACVP server given the IUT's communicated curve, public key, and signature. The random value used in the signature is generated according to the Deterministic ECDSA algorithm in <<FIPS186-5>>.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS186-4>>, <<FIPS186-5>>, <<SP800-89>>, and <<SP800-106>>.

[[requirements_covered]]
==== Requirements Covered

* FIPS 186-4 - Section 3. General Discussion. Domain parameter generation, key generation, signature generation, and signature validation are all within scope of ACVP server testing.

* FIPS 186-4 - Section 6. The Eliliptic Curve Digital Signature Algorithm (ECDSA). The ACVP server *SHALL* allow testing with the recommended NIST curves. The ACVP server *SHALL* support a variety of curves/hash function for creation and delivery to/from the IUT. Key pair generation/verification testing *SHALL* be provided by the ACVP server. Both Signature Generation and Validation testing mechanmisms *SHALL* be provided by the ACVP server.

* SP800-106 - Sections 3. Randomized Hashing and 4. Digital Signatures Using Randomized Hashing. The IUT *SHALL* be provided or provide a random value that should be used to "randomize" a message prior to signing and/or verifying an original message.

[[requirements_not_covered]]
==== Requirements Not Covered

* FIPS 186-4 - Section 3. General Discussion. Assurances of private key secrecy and ownership *SHALL NOT* be within scope of ACVP testing.

* FIPS 186-4 - Section 6. The Elliptic Curve Digital Signature Algorithm (ECDSA). Though the ACVP server *SHALL* support a variety of parameter sizes/hash functions, the IUT's selection of these is out of scope of testing. The ACVP server *SHALL NOT* provide testing for the validity of domain parameters as testing is (currently) limited to approved NIST curves. Testing *SHALL NOT* provide assurances the IUT has validated a set of domain parameters prior to their use. Domain parameter and key pair management *SHALL NOT* be within scope of ACVP testing.

* SP800-106 - Section 3.3. The Random Value. DSA, ECDSA, and RSA have random values generated as per their signing process, this random value can be used as the input to the message randomization function, doing so however is out of scope of this testing.
