
[[ecdsa_detsigGen_capabilities]]
==== The Deterministic ECDSA sigGen Mode Capabilities

The ECDSA sigGen mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each ECDSA sigGen mode capability set is advertised as a self-contained JSON object.

[[mode_detsigGenFIPS186-5]]
===== Deterministic ECDSA sigGen Capabilities For Revision "FIPS186-5"

The complete list of DetECDSA / sigGen / FIPS186-5 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[detsigGen_table_FIPS186-5]]
.Deterministic ECDSA sigGen FIPS186-5 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curves supported with a particular set of hash algorithms. | array | Any non-empty subset of {"P-224", "P-256", "P-384", "P-521", "B-233", "B-283", "B-409", "B-571", "K-233", "K-283", "K-409", "K-571"}
| hashAlg | The hash functions supported when signing a message for a particular set of curves. | array | Any non-empty subset of {"SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256", "SHA3-224", "SHA3-256", "SHA3-384", "SHA3-512"}
|===

NOTE: Separate capability JSON objects in the array *MAY* represent different groupings of curves and hash algorithms. For example if one object in the 'capabilities' array has 'curve' "P-224" and 'hashAlg' "SHA2-224" while the next object has 'curve' "P-256" and 'hashAlg' "SHA2-256", then the tests generated will maintain those relations. A test group will be generated with cases for signatures over "P-224" using "SHA2-224" and a test group will be generated with cases for signatures over "P-256" using "SHA2-256".

Below is an example of the registration for detECDSA / sigGen / FIPS186-5

[source, json]
----
{
    "algorithm": "DetECDSA",
    "mode": "sigGen",
    "revision": "FIPS186-5",
    "prereqVals": [{
            "algorithm": "SHA",
            "valValue": "123456"
        },
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "componentTest": false,
    "capabilities": [
    {
        "curve": [
            "P-224",
            "P-256"
        ],
        "hashAlg": [
            "SHA2-224",
            "SHA2-256"
        ]
    },
    {
        "curve": [
            "P-512"
        ],
        "hashAlg": [
            "SHA3-512"
        ]
    }],
    "conformances": [
        "SP800-106"
    ]
}
----
