
[[ecdsa_keyVer_capabilities]]
==== The keyVer Mode Capabilities

The ECDSA keyVer mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each ECDSA keyVer mode capability set is advertised as a self-contained JSON object.

[[mode_keyVer1.0]]
===== keyVer Capabilities For Revision "1.0"

The complete list of ECDSA / keyVer / 1.0 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[keyVer_table_1.0]]
.ECDSA keyVer 1.0 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curve names supported for the IUT in keyVer. | array | Any non-empty subset of {"P-192", "P-224", "P-256", "P-384", "P-521", "B-163", "B-233", "B-283", "B-409", "B-571", "K-163", "K-233", "K-283", "K-409", "K-571"}
|===

Below is an example of the registration for ECDSA / keyVer / 1.0

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "keyVer",
    "revision": "1.0",
    "prereqVals": [
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "curve": [
        "P-192",
        "P-224",
        "P-256",
        "P-384",
        "P-521",
        "B-163",
        "B-233",
        "B-283",
        "B-409",
        "B-571",
        "K-163",
        "K-233",
        "K-283",
        "K-409",
        "K-571"
    ]
}
----

[[mode_keyVerFIPS18605]]
===== keyVer Capabilities For Revision "FIPS186-5"

The complete list of ECDSA / keyVer / FIPS186-5 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[keyVer_table_FIPS186-5]]
.ECDSA keyVer FIPS186-5 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curve names supported for the IUT in keyVer. | array | Any non-empty subset of {"P-224", "P-256", "P-384", "P-521", "B-233", "B-283", "B-409", "B-571", "K-233", "K-283", "K-409", "K-571"}
|===

Below is an example of the registration for ECDSA / keyVer / FIPS186-5

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "keyVer",
    "revision": "FIPS186-5",
    "prereqVals": [
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "curve": [
        "P-224",
        "P-256",
        "P-384",
        "P-521"
    ]
}
----
