
[[ecdsa_keyGen_capabilities]]
==== The keyGen Mode Capabilities

The ECDSA keyGen mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each ECDSA keyGen mode capability set is advertised as a self-contained JSON object.

[[mode_keyGen1.0]]
===== keyGen Capabilities For Revision "1.0"

The complete list of ECDSA / keyGen / 1.0 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[keyGen_table_1.0]]
.ECDSA keyGen 1.0 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curve names supported for the IUT in keyGen. | array | Any non-empty subset of {"P-224", "P-256", "P-384", "P-521", "B-233", "B-283", "B-409", "B-571", "K-233", "K-283", "K-409", "K-571"}
| secretGenerationMode | The method used to generate the randomness incoporated in the key. | array | Any non-empty subset of {"extra bits", "testing candidates"}
|===

NOTE: The 'secretGenerationMode' can be found in <<FIPS186-4>> Appendix B.4.

Below is an example of the registration for ECDSA / keyGen / 1.0

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "keyGen",
    "revision": "1.0",
    "prereqVals": [
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "curve": [
        "P-224",
        "P-256",
        "P-384",
        "P-521",
        "B-233",
        "B-283",
        "B-409",
        "B-571",
        "K-233",
        "K-283",
        "K-409",
        "K-571"
    ],
    "secretGenerationMode": [
        "extra bits",
        "testing candidates"
    ]
}
----

[[mode_keyGenFIPS186-5]]
===== keyGen Capabilities For Revision "FIPS186-5"

The complete list of ECDSA / keyGen / FIPS186-5 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[keyGen_table_FIPS186-5]]
.ECDSA keyGen FIPS186-5 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curve names supported for the IUT in keyGen. | array | Any non-empty subset of {"P-224", "P-256", "P-384", "P-521", "B-233", "B-283", "B-409", "B-571", "K-233", "K-283", "K-409", "K-571"}
| secretGenerationMode | The method used to generate the randomness incoporated in the key. | array | Any non-empty subset of {"extra bits", "testing candidates"}
|===

NOTE: The 'secretGenerationMode' can be found in <<FIPS186-5>> Appendix A.2.

Below is an example of the registration for ECDSA / keyGen / FIPS186-5

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "keyGen",
    "revision": "FIPS186-5",
    "prereqVals": [
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "curve": [
        "P-224",
        "P-256",
        "P-384",
        "P-521"
    ],
    "secretGenerationMode": [
        "extra bits",
        "testing candidates"
    ]
}
----
