
[[ecdsa_sigVer_capabilities]]
==== The sigVer Mode Capabilities

The ECDSA sigVer mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each ECDSA sigVer mode capability set is advertised as a self-contained JSON object.

[[mode_sigVer1.0]]
===== sigVer Capabilities For Revision "1.0"

The complete list of ECDSA / sigVer / 1.0 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[sigVer_table_1.0]]
.ECDSA sigVer Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curves supported with a particular set of hash algorithms. | array | Any non-empty subset of {"P-192", "P-224", "P-256", "P-384", "P-521", "P-224", "P-256", "P-384", "P-521", "B-163", "B-233", "B-283", "B-409", "B-571", "K-163", "K-233", "K-283", "K-409", "K-571"}
| hashAlg | The hash functions supported when signing a message for a particular set of curves. | array | Any non-empty subset of {"SHA-1", "SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256", "SHA3-224", "SHA3-256", "SHA3-384", "SHA3-512"}
|===

NOTE: Separate capability JSON objects in the array *MAY* represent different groupings of curves and hash algorithms. For example if one object in the 'capabilities' array has 'curve' "P-224" and 'hashAlg' "SHA2-224" while the next object has 'curve' "P-256" and 'hashAlg' "SHA2-256", then the tests generated will maintain those relations. A test group will be generated with cases for signatures over "P-224" using "SHA2-224" and a test group will be generated with cases for signatures over "P-256" using "SHA2-256".

Below is an example of the registration for ECDSA / sigVer / 1.0

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "sigVer",
    "revision": "1.0",
    "prereqVals": [{
            "algorithm": "SHA",
            "valValue": "123456"
        },
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "componentTest": false,
    "capabilities": [
    {
        "curve": [
            "P-224",
            "P-256"
        ],
        "hashAlg": [
            "SHA2-224",
            "SHA2-256"
        ]
    },
    {
        "curve": [
            "P-512"
        ],
        "hashAlg": [
            "SHA3-512"
        ]
    }],
    "conformances": [
        "SP800-106"
    ]
}
----

[[mode_sigVerFIPS186-5]]
===== sigVer Capabilities For Revision "FIPS186-5"

The complete list of ECDSA / sigVer / FIPS186-5 capabilities *MAY* be advertised by the ACVP compliant crypto module:

[[sigVer_table_FIPS186-5]]
.ECDSA sigVer Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curves supported with a particular set of hash algorithms. | array | Any non-empty subset of {"P-224", "P-256", "P-384", "P-521", "B-233", "B-283", "B-409", "B-571", "K-233", "K-283", "K-409", "K-571"}
| hashAlg | The hash functions supported when signing a message for a particular set of curves. | array | Any non-empty subset of {"SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256", "SHA3-224", "SHA3-256", "SHA3-384", "SHA3-512", "SHAKE-128", "SHAKE-256"}
|===

NOTE: Separate capability JSON objects in the array *MAY* represent different groupings of curves and hash algorithms. For example if one object in the 'capabilities' array has 'curve' "P-224" and 'hashAlg' "SHA2-224" while the next object has 'curve' "P-256" and 'hashAlg' "SHA2-256", then the tests generated will maintain those relations. A test group will be generated with cases for signatures over "P-224" using "SHA2-224" and a test group will be generated with cases for signatures over "P-256" using "SHA2-256".

Below is an example of the registration for ECDSA / sigVer / FIPS186-5

[source, json]
----
{
    "algorithm": "ECDSA",
    "mode": "sigVer",
    "revision": "FIPS186-5",
    "prereqVals": [{
            "algorithm": "SHA",
            "valValue": "123456"
        },
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "componentTest": false,
    "capabilities": [
    {
        "curve": [
            "P-224",
            "P-256"
        ],
        "hashAlg": [
            "SHA2-224",
            "SHA2-256"
        ]
    },
    {
        "curve": [
            "P-512"
        ],
        "hashAlg": [
            "SHA3-512"
        ]
    }],
    "conformances": [
        "SP800-106"
    ]
}
----
