[[ecdsa_keyGen_test_vectors]]
=== ECDSA keyGen Test Vectors

[[ecdsa_keyGen_tgjs]]
==== ECDSA keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for ECDSA / keyGen / * is as follows:

[[ecdsa_keyGen_vs_tg_table]]
.ECDSA keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| curve | The curve type used for the test group | string
| secretGenerationMode | The secret generation mode used for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<ecdsa_keyGen_tvjs>> | array
|===

[[ecdsa_keyGen_tvjs]]
==== ECDSA keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ECDSA test vector.

[[ecdsa_keyGen_vs_tc_table]]
.ECDSA keyGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
|===

The following is an example JSON object sent from the server to the client for ECDSA / keyGen. While the example will specify a revision, the format is identical for both revisions available.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "ECDSA",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "curve": "P-224",
                "secretGenerationMode": "extra bits",
                "tests": [
                    {
                        "tcId": 1
                    }
                ]
            }
        ]
    }
]
----
