[[ecdsa_sigGen_vector_responses]]
=== ECDSA sigGen Test Vector Responses

The test groups for ECDSA / sigGen / * contain public key properties. The groups can be described using the following table.

[[ecdsa_sigGen_group_table]]
.ECDSA sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| qx | The x component of the public key | hex
| qy | The y component of the public key | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ECDSA / sigGen / * test vector.

[[ecdsa_sigGen_vs_tr_table]]
.ECDSA sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| r | The signature component R | hex
| s | The signature component S | hex
| randomValue | The random value to be used as an input into the message randomization function as described in <<SP800-106>> | hex
| randomValueLen | The random value's bit length | integer
|===

NOTE: The properties 'randomValue' and 'randomValueLen' *SHALL* only be present in test groups where the corresponding test group in the prompt had the 'conformance' property set to "SP800-106".

The following is an example JSON test vector response object for ECDSA / sigGen. While the example will not specify a revision, the format is identical for both revisions available.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "qx": "3B1D9E4D986F651C3C213B2A1304693BDB...",
                "qy": "E56F7B7C9E6355E573B7B3B6C0E1ECD70E...",
                "tests": [
                    {
                        "tcId": 1,
                        "r": "3E2A9588DF3D3F11B16368A30C8...",
                        "s": "C6E4A8C51E0A0E11C4C6D6F8F3C..."
                    }
                ]
            },
            {
                "tgId": 2,
                "qx": "A1304693BDBA632CB93A3B8BA632CB93A3...",
                "qy": "ECD70E4ABBA632CB93A3BA632CB93A3DF1...",
                "tests": [
                    {
                        "tcId": 2,
                        "r": "3E2A9588DF3D3F11B16368A30C8...",
                        "s": "C6E4A8C51E0A0E11C4C6D6F8F3C...",
                        "randomValue": "0A0E11C4C6D6F8F3C..."
                        "randomValueLen": 1024
                    }
                ]
            }
        ]
    }
]
----
