
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate {spec-algorithm} implementations.

=== Test Types

There are multiple test types depending on the algorithm and mode. Each has a specific value to be used in the testType field. The testType field definitions are:

"AFT" - Algorithm Functional Test. These tests can be processed by the client using a normal 'generate_key', 'sign', 'verify' or 'decrypt' operation depending on the mode. AFTs cause the implementation under test to exercise normal operations. In all cases, random data is used. The functional tests are designed to verify that the logical components of the process are operating correctly.

"GDT" - Generated Data Test. These tests require the client to generate all inputs and outputs in order to demonstrate their full capabilities in cases where input from the server might not be applicable.

"KAT" - Known Answer Test. These tests are staticly defined and are included in every vector set that matches their capabilities.

=== Test Types Per Mode

As each mode requires different tests, how each test type is processed may change depending on the mode.

ACVP servers that support RSA keyGen *MAY* support AFTs, GDTs, and KATs. The AFTs and GDTs *REQUIRE* the client to generate RSA key pairs based on the test group properties provided. The KATs *REQUIRE* the client to attempt to generate a key with specific starting 'p' and 'q' values via the Random Probable Prime method defined in <<FIPS186-4>> and <<FIPS186-5>>.

ACVP servers that support RSA sigGen *MAY* support GDTs. The GDTs *REQUIRE* the client to generate a key pair and sign a message provided by the server based on the test group properties provided. The client provides the signature and public key to the server for verification.

ACVP servers that support RSA sigVer *MAY* support GDTs. The GDTs *REQUIRE* the client to verify provided signatures given a message and public key. The client provides the verification result back to the server.

ACVP servers that support RSA LegacysigVer *MAY* support GDTs. The GDTs *REQUIRE* the client to verify provided signatures given a message and public key. The client provides the verification result back to the server.

ACVP servers that support RSA SignaturePrimitive *MAY* support AFTs. The AFTs *REQUIRE* the client to determine whether or not the provided message can be signed with the provided public key. If so, also provide the signature for verification.

ACVP servers that support RSA DecryptionPrimitive *MAY* support AFTs. The AFTs *REQUIRE* the client to determine whether or not the provided ciphertext can be decrypted with the provided public key. If so, also provide the plaintext for verification.
