[[rsa_decprim_capabilities]]

Note: RSA DecryptionPrimitive 1.0 should be used for PIV card testing, and RSA DecryptionPrimitive Sp800-56Br2 for comforming to Sp800-56Br2 requirements.

=== RSA DecryptionPrimitive v1.0 Mode Capabilities

The RSA decryptionPrimitive mode capabilities are advertised as JSON objects within the array of 'capabilities' as part of the 'capability_exchange' element of the ACVP JSON registration message. A single property is allowed in the registration, 'modulo' with the only approved value of 2048. In this mode, the only tested capability is the correct exponentiation 's = cipherText\^d mod n', where 'cipherText' is a cipherText to be decrypted, 'd' is the private exponent and 'n' is the modulus. See <<SP800-56B>>, Section 7.1.2 for details.

In testing, only 'cipherText' is supplied by the ACVP server. The client is responsible for generating RSA key pairs of modulus 'n', private key 'd', and calculates 's'. If a client does not support decryption with a standard RSA private exponent 'd', the equivalent Chinese Remainder Theorem (CRT) private key values are allowed to be used. Only 2048-bit RSA keys are allowed for this capability.

See <<rsa_decprim_tgjs>> for additional details on constraints for 'cipherText' and 'n'. The client provides the public exponent 'e', modulus 'n' and the computed result 's' in its response to the ACVP - see <<rsa_decprim_responses>>. The client must first check if '0 < cipherText < n-1' and return an error if this is not the case. The client returns a value 's' only when 'cipherText' is in the proper range for the size of the selected modulus 'n'. See the ACVP specification for details on the registration message.

An example registration is the following

[source, json]
----
{
    "algorithm": "RSA",
    "mode": "decryptionPrimitive",
    "revision": "1.0",
    "prereqVals":
    [
        {"algorithm": "DRBG", "valValue": "123456"},
        {"algorithm": "DRBG", "valValue": "654321"},
        {"algorithm": "SHA", "valValue": "7890"}
    ]
}
----

=== RSA DecryptionPrimitive Sp800-56Br2 Mode Capabilities

The RSA decryptionPrimitive mode capabilities are advertised as JSON objects within the array of 'capabilities' as part of the 'capability_exchange' element of the ACVP JSON registration message. Two properties are supported in the registration, A Modulus array that supports three modulo values of 2048, 3072, and 4096. For Private Key Modes, we support "Standard/AFT" and "CRT" (Chinese Remainder Theorom). For the Standard/AFT mode see <<Sp800-56Br2>>, Section 7.1.2.1 for details, and for CRT mode, we provide a see <<Sp800-56Br2>>, Section 7.1.2.3 for details.

In testing in Standard mode, a 'cipherText', along with key parameters 'P', 'Q', and 'D' values are provided, see <<Sp800-56Br2>>, Section 7.1.2.1 for details. When testing for Chinese Remainder Theorom, a 'cipherText', 'dp', 'dQ', and 'qInv' are provided, see <<S800-56Br2>>, Section 7.1.2.1 for details. 
See the ACVP specification for details on the registration message.

An example registration is the following

[source, json]
----
{
  "algorithm": "RSA",
  "mode": "DecryptionPrimitive",
  "revision": "Sp800-56Br2",
  "isSample": true,
  "keyFormat": [
    "standard",
    "crt"
  ],
  "modulus": [
    2048,
    3072,
    4096
  ]
}
----