[[rsa_decprim_capabilities]]

=== RSA DecryptionPrimitive v1.0 Mode Capabilities

Note: RSA DecryptionPrimitive v1.0 should be used for PIV card testing, and RSA DecryptionPrimitive Sp800-56Br2 for comforming to Sp800-56Br2 requirements.

The RSA decryptionPrimitive mode capabilities are advertised as JSON objects within the array of 'capabilities' as part of the 'capability_exchange' element of the ACVP JSON registration message. A single property is allowed in the registration, 'modulo' with the only approved value of 2048. In this mode, the only tested capability is the correct exponentiation 's = cipherText\^d mod n', where 'cipherText' is a cipherText to be decrypted, 'd' is the private exponent and 'n' is the modulus. See <<SP800-56B>>, Section 7.1.2 for details.

In testing, only 'cipherText' is supplied by the ACVP server. The client is responsible for generating RSA key pairs of modulus 'n', private key 'd', and calculates 's'. If a client does not support decryption with a standard RSA private exponent 'd', the equivalent Chinese Remainder Theorem (CRT) private key values are allowed to be used. Only 2048-bit RSA keys are allowed for this capability.

See <<rsa_decprim_tgjs>> for additional details on constraints for 'cipherText' and 'n'. The client provides the public exponent 'e', modulus 'n' and the computed result 's' in its response to the ACVP - see <<rsa_decprim_responses>>. The client must first check if '0 < cipherText < n-1' and return an error if this is not the case. The client returns a value 's' only when 'cipherText' is in the proper range for the size of the selected modulus 'n'. See the ACVP specification for details on the registration message.

An example registration is the following

[source, json]
----
{
    "algorithm": "RSA",
    "mode": "decryptionPrimitive",
    "revision": "1.0",
    "prereqVals":
    [
        {"algorithm": "DRBG", "valValue": "123456"},
        {"algorithm": "DRBG", "valValue": "654321"},
        {"algorithm": "SHA", "valValue": "7890"}
    ]
}
----

=== RSA DecryptionPrimitive SP800-56Br2 Mode Capabilities

The RSA decryptionPrimitive mode capabilities are advertised as JSON objects within the array of 'capabilities' as part of the 'capability_exchange' element of the ACVP JSON registration message. Two properties are supported in the registration. A 'modulo' array supports three modulus values of 2048, 3072, and 4096. For private 'keyFormat', the "standard" and "crt" (Chinese Remainder Theorem) private key formats are supported. "standard" equates to the prime-factor private key format described in <<SP800-56Br2>>. See the descriptions of basic, CRT, and prime-factor private key formats in Section 3.2 of <<SP800-56Br2>>.

When testing the "standard"/prime-factor private key format, a ciphertext (ct), along with private key p, q and d component values are provided, see <<SP800-56Br2>>, Section 7.1.2.2 for details. If an IUT supports the basic private key format, the p and q values provided by the "standard"/prime-factor testing can be multiplied to produce the needed n value.  When testing for the Chinese Remainder Theorem private key format, a ciphertext (ct), the p, q, n, dmp1 (dP), dmq1 (dQ), and iqmp (qInv) values are provided, see <<SP800-56Br2>>, Section 7.1.2.3 for details. 
See the ACVP specification for details on the registration message.

Support was added for fixed public exponents, this is done through two settings, 'pubExpMode' and fixedPubExp'. When 'pubExpMode' is set to 'fixed', a 'fixedPubExp' is required. An omitted pubExpMode will default to random.

[[DecryptionPrimitive2-0]]
.Supported RSA DecryptionPrimitive 2.0 JSON Values
|===
| JSON value | Description | JSON type | Valid values

| modulo | supported RSA moduli for signature generation - see <<FIPS186-4>>, Section 5 | array of integer | any of the supported modulus sizes {2048, 3072, 4096}
| keyFormat | The format by which the client expects the private key to be communicated. Standard refers to the default p, q, d values. Chinese Remainder Theorem uses decomposed values for optimized decryption p, q, dmp1, dmq1, iqmp | array of string | "standard", "crt"
| pubExpMode | Whether the IUT can handle a random or fixed public exponent | string | "random", "fixed"
| fixedPubExp | The fixed public exponent e | hex | Any value supported by <<FIPS186-4>>: 65537 - 2^256-1, odd
|===

An example registration is the following

 ----
 {
   "algorithm": "RSA",
   "mode": "decryptionPrimitive",
   "revision": "Sp800-56Br2",
   "pubExpMode": "fixed",
   "fixedPubExp": "010001",
   "keyFormat": [
     "standard",
     "crt"
   ],
   "modulo": [
     2048,
     3072,
     4096
   ]
 }
 ----
