[[rsa_keyGen_capabilities]]
=== Property Registration RSA keyGen FIPS186-4

The RSA keyGen FIPS186-4 capabilities are advertised as JSON objects within the 'capabilities' property.

[[mode_keyGenFullSet]]
==== keyGen Registration Table

A registration for RSA / keyGen / FIPS186-4 *SHALL* use these properties

[[keyGen_table_fips186-4]]
.RSA keyGen FIPS186-4 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| randPQ | Key Generation mode to be validated. Random P and Q primes generated as (see <<FIPS186-4>>): provable primes (Appendix B.3.2); probable primes (Appendix B.3.3); provable primes with conditions (Appendix B.3.4); provable/probable primes with conditions (Appendix B.3.5); probable primes with conditions (Appendix B.3.6) | string | "B.3.2", "B.3.3", "B.3.4", "B.3.5", "B.3.6"
| properties | An array of objects containing properties for all supported moduli, primality test, and hash algorithms for a single key generation mode | array |
| modulo | supported RSA modulo for the randPQ mode - see <<FIPS186-4>>, Appendix B.3 | integer | 2048, 3072 or 4096
| hashAlg | Supported hash algorithms for the randPQ mode - see <<FIPS186-4>>, Appendix B.3. Needed for "B.3.2", "B.3.4" and "B.3.5" | array | any non-empty subset of {"SHA-1", "SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256"}
| primeTest | Primality test rounds of Miller-Rabin from Table C.2 or Table C.3 in <<FIPS186-4>>, Appendix C.3 | array | any non-empty subset of {"tblC2", "tblC3"}. Needed for "B.3.3", "B.3.5" and "B.3.6"
|===

An example of this is the following

[source, json]
----
{
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "FIPS186-4",
    "prereqVals": [{"algorithm": "DRBG", "valValue": "1234"}, {"algorithm": "SHA", "valValue": "5678"}],
    "infoGeneratedByServer": false,
    "pubExpMode": "random",
    "keyFormat": "crt",
    "capabilities": [
        {
            "randPQ": "B.3.2",
            "properties": [
                {
                    "modulo": 2048,
                    "hashAlg": [
                        "SHA2-224"
                    ]
                }
            ]
        },
        {
            "randPQ": "B.3.4",
            "properties": [
                {
                    "modulo": 3072,
                    "hashAlg": [
                        "SHA2-224"
                    ]
                }
            ]
        },
        {
            "randPQ": "B.3.3",
            "properties": [
                {
                    "modulo": 2048,
                    "primeTest": [
                        "tblC2"
                    ]
                }
            ]
        },
        {
            "randPQ": "B.3.6",
            "properties": [
                {
                    "modulo": 3072,
                    "primeTest": [
                        "tblC2",
                        "tblC3"
                    ]
                }
            ]
        },
        {
            "randPQ" : "B.3.5",
            "properties" : [
                {
                    "modulo" : 4096,
                    "hashAlg" : [
                        "SHA2-512"
                    ],
                    "primeTest": [
                        "tblC3"
                    ]
                }
            ]
        }
    ]
}
----


=== Property Registration RSA keyGen FIPS186-5

The RSA / keyGen / FIPS186-5 capabilities are advertised as JSON objects within the 'capabilities' property.

==== keyGen Registration Table

A registration for RSA / keyGen / FIPS186-5 *SHALL* use these properties

[[keyGen_table_fips186-5]]
.RSA keyGen FIPS186-5 Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| randPQ | Key Generation mode to be validated. Random P and Q primes generated as (see <<FIPS186-5>>): provable primes; probable primes; provable primes with auxiliary provable primes; probable primes with auxiliary provable primes; probable primes with auxiliary probable primes | string | "provable", "probable", "provableWithProvableAux", "probableWithProvableAux", "probableWithProbableAux"
| properties | An array of objects containing properties for all supported moduli, primality test, and hash algorithms for a single key generation mode | array |
| modulo | supported RSA modulo for the randPQ mode - see <<FIPS186-5>> | integer | 2048, 3072, 4096, 6144, or 8192
| hashAlg | Supported hash algorithms for the randPQ mode - see <<FIPS186-5>>. Needed for any 'randPQ' with provable primes | array | any non-empty subset of {"SHA-1", "SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256"}
| primeTest | Primality test rounds of Miller-Rabin from <<FIPS186-5>>. Needed for any 'randPQ' with probable primes | array | any non-empty subset of {"2pow100", "2powSecStr"}
| pMod8 | The result of the evaluation of the generated p prime, p % 8 | integer | 0, 1, 3, 5, 7
| qMod8 | The result of the evaluation of the generated q prime, q % 8 | integer | 0, 1, 3, 5, 7
|===

NOTE: While 15360 is supported for modulo in 186-5, at this time, it's not supported in ACVP due to system contraints. We apologize for any inconvenience.

NOTE: The properties 'pMod8' and 'qMod8' with a value of 0, means that no modulus check will be performed on the generated primes p and q.

The following is an example

[source, json]
----
{
    "algorithm": "RSA",
    "mode": "keyGen",
    "revision": "FIPS186-5",
    "prereqVals": [{"algorithm": "DRBG", "valValue": "1234"}, {"algorithm": "SHA", "valValue": "5678"}],
    "infoGeneratedByServer": false,
    "pubExpMode": "random",
    "keyFormat": "crt"
    "capabilities": [
        {
            "randPQ": "provable",
            "properties": [
                {
                    "modulo": 2048,
                    "hashAlg": [
                        "SHA2-224"
                    ],
                    "pMod8": 1,
                    "qMod8": 1
                }
            ]
        },
        {
            "randPQ": "probable",
            "properties": [
                {
                    "modulo": 2048,
                    "primeTest": [
                        "2pow100"
                    ],
                    "pMod8": 0,
                    "qMod8": 3
                }
            ]
        }
    ]
}
----
