[[rsa_decprim_tgjs]]
=== Test Groups for RSA Decryption Primitive 1.0

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.RSA Decryption Primitive 1.0 Test Group Properties
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Describes the operation the client should perform on the tests data | string
| totalTests | The total number of elements in the "resultsArray" | integer
| totalFailingTests | The number of tests that the client should force to fail in the "resultsArray" | integer
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases for RSA Decryption Primitive 1.0

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / DecryptionPrimitive / 1.0 test vector.

.RSA Decryption Primitive 1.0 Test Case Properties
|===
| JSON Values | Description | JSON Type

| tcId | Test case identifier | integer
| resultsArray | An array of ciphertexts | array
| ciphertext | An individual ciphertext | hex
|===

NOTE: A failing ciphertext is one such that the ciphertext is greater than the n the client provides

Here is an abbreviated yet fully constructed example of the prompt

[source, json]
----
[
    { "acvVersion": "{acvp-version}" },
    {
        "vsId": 1194,
        "algorithm": "RSA",
        "mode": "decryptionPrimitive",
        "revision": "1.0",
        "testGroups" : [
            {
                "tgId": 1,
                "testType": "AFT",
                "totalTests": 2,
                "totalFailingTests": 1,
                "tests" : [
                    {
                        "tcId" : 1,
                        "resultsArray": [
                            {
                                "cipherText" : "097e82fec72465e..."
                            },
                            {
                                "cipherText" : "ffd5aa3f0c7c787..."
                            }
                        ]
                    }
                ]
            }
        ]
    }
]
----
