
[[rsa_keyGen_tgjs]]
=== RSA keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the RSA / keyGen / * JSON elements of the Test Group JSON object.

[[rsa_keyGen_vs_tg_table]]
.RSA keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| modulo | RSA modulus size | integer
| hashAlg | the hash algorithm | string
| primeTest | Miller-Rabin constraint bound | string
| randPQ | keyGen mode used | string
| infoGeneratedByServer | Whether or not the test inputs are generated by the server | boolean
| keyFormat | The RSA private key format used | string
| pubExp | Fixed or random public exponent e | string
| testType | Describes the operation the client should perform on the test data | string
| tests | Array of individual test cases, see <<rsa_keyGen_tvjs>> | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

The impact of the 'infoGeneratedByServer' property depends on the other properties identified in the keyGen registration.  For 'randPQs' of B.3.2, B.3.4, B.3.5, and B.3.6 (or the corresponding FIPS186-5 values), 'infoGeneratedByServer' set to true will provide the client with ALL the inputs and expect them to arrive at the same output the server has already arrived at.

In the case of 'infoGeneratedByServer' being set to false during the registration, the client will be provided with SOME of the inputs, like an already agreed upon fixed public exponent.  However, in general the server will send mostly empty test cases.  It is the responsibility of the client to generate both the input properties and output properties comprising the test cases and communicate ALL of those back to the server.  The server will try to reach the same output key.

For B.3.3 (or the corresponding FIPS186-5 value of probable), 'infoGeneratedByServer' set to true enables the KAT test groups if the client supports a random public exponent.  The GDT are always enabled as a bare minimum test for B.3.3 (or probable), independent of the 'infoGeneratedByServer' setting.

[[rsa_keyGen_tvjs]]
=== RSA keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / keyGen / * test vector.

The difference between revision "FIPS186-4" and "FIPS186-5" within the prompts lies in the strings used by the server to refer to the various "randPQ", and "primeTest" modes. Revision "FIPS186-4" utilizes the section number from <<FIPS186-4>> to refer to the algorithm used while revision "FIPS186-5" utilizes a description of the algorithm.

.RSA keyGen Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case identifier | integer
| e | the public exponent | hex
| seed | the seed used in prime generation | hex
| bitlens | the length of p1, p2, q1, and q2 for prime generation | array of integers
| xP1 | xP1 from <<FIPS186-4>> B.3.6, step 4 | hex
| xP2 | xP2 from <<FIPS186-4>> B.3.6, step 4 | hex
| xP | the random number used in auxiliary prime generation for p | hex
| xQ1 | xQ1 from <<FIPS186-4>> B.3.6, step 5 | hex
| xQ2 | xQ2 from <<FIPS186-4>> B.3.6, step 5 | hex
| xQ | the random number used in auxiliary prime generation for q | hex
| pRand | the random P for testing probable primes according to <<FIPS186-4>> or <<FIPS186-5>> | hex
| qRand | the random Q for testing probable primes according to <<FIPS186-4>> or <<FIPS186-5>> | hex
|===

Here is an abbreviated yet fully constructed example of the prompt for RSA / keyGen / FIPS186-5

[source, json]
----
{
  "vsId": 2,
  "algorithm": "RSA",
  "mode": "keyGen",
  "revision": "FIPS186-5",
  "testGroups": [
    {
      "tgId": 1,
      "infoGeneratedByServer": true,
      "modulo": 2048,
      "testType": "AFT",
      "keyFormat": "crt",
      "randPQ": "provable",
      "pubExp": "random",
      "hashAlg": "SHA2-224",
      "tests": [
        {
          "tcId": 1,
          "seed": "5B174CA160...",
          "e": "07D196B84395"
        }
      ]
    },
    {
      "tgId": 3,
      "infoGeneratedByServer": true,
      "modulo": 2048,
      "testType": "AFT",
      "keyFormat": "crt",
      "primeTest": "2powSecStr",
      "randPQ": "probableWithProvableAux",
      "pubExp": "random",
      "tests": [
        {
          "tcId": 7,
          "seed": "B392CFFD8E...",
          "bitlens": [
            142,
            419,
            400,
            334
          ],
          "xp": "F06825A6B...",
          "xq": "BD106DBE5...",
          "e": "3691C632C2BBE7"
        }
      ]
    },
    {
      "tgId": 5,
      "infoGeneratedByServer": false,
      "modulo": 3072,
      "testType": "GDT",
      "keyFormat": "crt",
      "primeTest": "2pow100",
      "randPQ": "probable",
      "pubExp": "random",
      "tests": [
        {
          "tcId": 13
        }
      ]
    }
  ]
}
----
