[[rsa_sigprim_tgjs]]
=== Test Groups for RSA Signature Primitive 1.0

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the RSA / signaturePrimitive / 1.0 JSON elements of the Test Group JSON object

.RSA Signature Primitive 1.0 Test Group Properties
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Describes the operation the client should perform on the tests data | string
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases for RSA Signature Primitive 1.0

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / signaturePrimitive / 1.0 test vector.

.RSA Signature Primitive 1.0 Test Case Properties
|===
| JSON Values | Description | JSON Type

| tcId | Test case idenfitier | integer
| n | Modulus | hex
| d | Private key exponent, when the keyFormat is "standard" | hex
| dmp1 | d mod p - 1, when the keyFormat is "crt" | hex
| dmq1 | d mod q - 1, when the keyFormat is "crt" | hex
| iqmp | q\^-1 mod p, when the keyFormat is "crt" | hex
| p | prime p, when the keyFormat is "crt" | hex
| q | prime q, when the keyFormat is "crt" | hex
| message | The message to sign | hex
|===

NOTE: Each test for which 'message' is not between '0' and 'n - 1' should fail.

NOTE: Many private key properties are dependent on the 'keyFormat' property from the registration.

Here is an abbreviated yet fully constructed example of the prompt

[source, json]
----
[
    { "acvVersion": "{acvp-version}" },
    {
        "vsId": 1193,
        "algorithm": "RSA",
        "mode": "signaturePrimitive",
        "revision": "1.0",
        "keyFormat": "standard",
        "testGroups" : [
            {
                "tgId": 1,
                "tests" : [
                    {
                        "tcId" : 1194,
                        "n" : "d0c112f0bee36235d9f...",
                        "d" : "2cde66ea08797aad3cf...",
                        "e": "010001",
                        "message" : "097e82fec7246..."
                    },
                    {
                        "tcId" : 1195,
                        "n" : "9cd5aa3f0c7c787ee38...",
                        "d" : "0c520729a48d1728ada...",
                        "e" : "010001",
                        "message" : "ffd5aa3f0c7c7..."
                    }
                ]
            }
        ]
    }
]
----

=== Test Groups for RSA Signature Primitive v2.0

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the RSA / signaturePrimitive / v2.0 JSON elements of the Test Group JSON object

.RSA Signature Primitive v2.0 Test Group Properties
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Describes the operation the client should perform on the tests data | string
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases for RSA Signature Primitive 2.0

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / signaturePrimitive / v2.0 test vector.

.RSA Signature Primitive v2.0 Test Case Properties
|===
| JSON Values | Description | JSON Type

| tcId | Test case idenfitier | integer
| n | Modulus | hex
| d | Private key exponent, when the keyFormat is "standard" | hex
| dmp1 | d mod p - 1, when the keyFormat is "crt" | hex
| dmq1 | d mod q - 1, when the keyFormat is "crt" | hex
| iqmp | q\^-1 mod p, when the keyFormat is "crt" | hex
| p | prime p, when the keyFormat is "crt" | hex
| q | prime q, when the keyFormat is "crt" | hex
| message | The message to sign | hex
|===

NOTE: Each test for which 'message' is not between '0' and 'n - 1' should fail.

NOTE: Many private key properties are dependent on the 'keyFormat' property from the registration.

Here is an abbreviated yet fully constructed example of the prompt

[source, json]
----
[
    { "acvVersion": "{acvp-version}" },
    {
        "vsId": 0,
        "algorithm": "RSA",
        "mode": "signaturePrimitive",
        "revision": "2.0",
        "isSample": false,
        "testGroups":
        {
            "tgId": 1,
            "modulo": 2048,
            "testType": "AFT",
            "keyMode": "standard",
            "tests": [
                {
                    "tcId": 1,
                    "message": "610EB23035CBF80373F282D9FCD8FCDAA411519BD9C2C889A6CDE09C1C8D4A188DF9781F1AA14...",
                    "p": "EC7C9A50B4C9DC6D5CBED336D42FCB0F669A5D98EE16F01A2BE8AB5EDACADEAC5827F30E50AA4CC9C6F...",
                    "q": "E1905BABFCA4135C62F4457FA9BD2ABA93FE1CE9401BF2F5708081752E8C962DE94CDCF9A35748DB4820...",
                    "d": "0167BACAD1034759CF8B36C19C1B92A50E37703208E9F75291383478A58A65879A6578938B4FBBF80015BA3...",
                    "n": "9A2C09A1A33F30802B872A1594CADBC6E182C62304027940C64601A9FD56ED171576DCC84F1C0DCC8359...",
                    "e": "010001"
                }
            ]
        },
        {
            "tgId": 2,
            "modulo": 4096,
            "testType": "AFT",
            "keyMode": "crt",
            "tests": [
                {
                    "tcId": 2,
                    "message": "95B5BCDCCAE9802BFFB562D5CA8CC027C33178952CD02AECCA122D1AAF24CD703930EA511E27BD1393C...",
                    "dmp1": "D69E5464B2DFD07BBA23B90684BAEC522EE997F3F805077EB00BB76FFD3FF5D053C39384035C75D6CDA6FC0...",
                    "dmq1": "A5A23DC4E454DEB6CB2466910BB65BAD1EA65FD2E1CAADD3FB83AB0DCE407B25F4257A038EACC5909AD...",
                    "iqmp": "4B3702BB2BDAD984047633F0B0DD4C6C619791CD7B280D15E1DADB08FDDBFFA546EC926F40A54D38E682B90B...",
                    "p": "BE16AAAF143547FBFB7EDE29B113FE372CB5A41D801AAB69A1AED4A525586792688ECDD651443A602FB7321AA48B...",
                    "q": "EBFF6C434973F5FBDBAE74D59C6AF26B2CBD2BCBB815E78FAC87B1C86FE8252F7DE499D966A362D9209685A98D08...",
                    "n": "AF3C77A6426D2401164839FE93AF3F0227EDA4675434BD5785EE7A4F44E687E714B63E99F143B1A28E28DB06B3...",
                    "e": "010001"
                }
            ]
        }
    }
]
----