[[rsa_decprim_responses]]
=== RSA Decryption Primitive Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / Decryption Primitive / * test vector.

The following table describes the JSON elements for the test case responses for RSA / Decryption Primitive / * .

[[rsa_decprim_vs_tr_table]]
.RSA Decryption Primitive v1.0 Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| e | The public exponent | hex
| n | The modulus | hex
| plainText | If the ciphertext could be decrypted, the result | hex
| testPassed | If the ciphertext could not be decrypted | boolean
|===

The following is an example of the response for RSA / Decryption Primitive / * .

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "decryptionPrimitive",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "resultsArray": [
            {
              "e": "60BDBEF656869D",
              "n": "8FA73CF9CAD37456B...",
              "testPassed": false
            },
            {
              "plainText": "009EDAE2D5934F...",
              "e": "D6AA5EF807",
              "n": "A86A73D47F605DCF...",
              "testPassed": true
            }
          ]
        }
      ]
    }
  ]
}
----

=== RSA Decryption Primitive Sp800-56Br2 Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / Decryption Primitive Sp800-56Br2 / * test vector.

The following table describes the JSON elements for the test case responses for RSA / Decryption Primitive / * .

[[rsa_decprim_sp800_56br2_vs_tr_table]]
.RSA Decryption Primitive Sp800-56Br2 Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| testPassed | If the ciphertext could not be decrypted | boolean
| plainText | If the ciphertext could be decrypted, the result | hex
|===

The following is an example of the response for RSA / Decryption Primitive / * .

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "DecryptionPrimitive",
  "revision": "Sp800-56Br2",
  "isSample": false,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "testPassed": true,
          "pt": "0098C4B9AC11B94F1625F7C75318AB84F130013CE8157915824D64..."
        },
        {
          "tcId": 3,
          "testPassed": false,
        },
        {
          "tcId": 2,
          "testPassed": true,
          "pt": "7DC72AEE9BEA72A52386FC325EBEFD2E20BC8BF9AE4856AF5C36E2D8..."
        },
      ]
    }
  ]
}
----