
[[vector_responses]]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data, see <<response_group_table>> | array
|===

An example of this is the following

[source, json]
----
{
	"acvVersion": "version",
	"vsId": 1,
	"testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that. The following is a skeleton for the test group structure. Additional properties may be included at this level depending on the algorithm, mode and revision.

[[response_group_table]]
.Response Test Group JSON Objects
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data, depending on the algorithm see <<rsa_keyGen_vs_tr_table>>, <<rsa_sigGen_vs_tr_table>>, <<rsa_sigVer_vs_tr_table>>, <<rsa_sigprim_vs_tr_table>>, <<rsa_sigprimV2_0_vs_tr_table>>, <<rsa_decprim_vs_tr_table>> or <<rsa_decprim_sp800_56br2_vs_tr_table>> | array
|===

An example of this is the following

[source, json]
----
{
	"tgId": 1,
	"tests": [ ... ]
}
----
