[[rsa_sigGen_responses]]
=== RSA sigGen Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / sigGen / * test vector.

The following table describes the JSON elements for the test group responses to a RSA / sigGen / * test vector.

[[rsa_sigGen_vs_tr_table]]
.RSA sigGen Test Group Results JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group | integer
| n | The generated modulus for the group | hex
| e | The generated public exponent for the group | hex
| tests | The individual test cases for the group | array
|===

The following table describes the JSON elements for the test case responses for RSA / sigGen / * .

.RSA sigGen Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| signature | The computed signature | hex
|===

The following is an example of the response for RSA / sigGen / *

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "sigGen",
  "revision": "FIPS186-4",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "n": "A31AFF9A3266E5A215C487...",
      "e": "CC288CE6A02AFD",
      "tests": [
        {
          "tcId": 1,
          "signature": "053F1CBA53..."
        },
        {
          "tcId": 2,
          "signature": "04236E8357..."
        },
        {
          "tcId": 3,
          "signature": "4A45C5E696..."
        }
      ]
    }
  ]
}
----
