[[rsa_sigGen_responses]]
=== RSA sigGen Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / sigGen / * test vector.

The following table describes the JSON elements for the test group responses to a RSA / sigGen / * test vector.

[[rsa_sigGen_vs_tr_table]]
.RSA sigGen Test Group Results JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group | integer
| conformance | Signifies all test cases within the group should utilize random message hashing as described in <<SP800-106>> | string
| n | The generated modulus for the group | hex
| e | The generated public exponent for the group | hex
| tests | The individual test cases for the group | array
|===

The following table describes the JSON elements for the test case responses for RSA / sigGen / * .

.RSA sigGen Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| randomValue | The random value to be used as an input into the message randomization function as described in <<SP800-106>> | hex
| randomValueLen | The random value's bit length | integer
| signature | The computed signature | hex
|===

NOTE: The 'randomValue' and 'randomValueLen' properties will only be present in test groups for the SP800-106 conformance.

The following is an example of the response for RSA / sigGen / * .

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "sigGen",
  "revision": "FIPS186-4",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "n": "A31AFF9A3266E5A215C487...",
      "e": "CC288CE6A02AFD",
      "tests": [
        {
          "tcId": 1,
          "signature": "053F1CBA53..."
        },
        {
          "tcId": 2,
          "signature": "04236E8357..."
        },
        {
          "tcId": 3,
          "signature": "4A45C5E696..."
        }
      ]
    },
	{
      "tgId": 2,
      "conformance": "SP800-106",
      "n": "A730E346899141F8B550C...",
      "e": "302D7F30CFCE55",
      "tests": [
        {
          "tcId": 4,
          "randomValue": "C44BAE0830813A8E8F989217C967E68A74EDADD9B14128EC877685E6CB631E5F",
          "randomValueLen": 256,
          "signature": "1612B11D9C..."
        },
        {
          "tcId": 5,
          "randomValue": "7FBB4BDA3C7C2F67E04583A631000EF783D67ED1BFE7620E9BE897A0270E411C",
          "randomValueLen": 256,
          "signature": "37387D5C64..."
        },
        {
          "tcId": 6,
          "randomValue": "8EF77DED2EB53357BAD523AD16C171221FCF24C0CE15E2FC7F9FBE589A64BEFC",
          "randomValueLen": 256,
          "signature": "4114A93A82..."
        }
      ]
    }
  ]
}
----
