[[rsa_sigprim_responses]]
=== RSA Signature Primitive Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / Signature Primitive / * test vector.

The following table describes the JSON elements for the test case responses for RSA / Signature Primitive / * .

[[rsa_sigprim_vs_tr_table]]
.RSA Signature Primitive Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| signature | If the message can be signed, the signature | hex
| testPassed | If the message could not be signed | boolean
|===

The following is an example of the response for RSA / Signature Primitive / * .

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "signaturePrimitive",
  "revision": "1.0",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "signature": "a60b879a8fa382fdf4..."
        },
        {
          "tcId": 2,
          "testPassed": false
        },
        {
          "tcId": 3,
          "testPassed": false
        }
      ]
    }
  ]
}
----
