[[rsa_sigprim_responses]]
=== RSA Signature Primitive Test Group Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each RSA / Signature Primitive / * test vector.

The following tables describe the JSON elements for the test case responses for RSA / Signature Primitive / v1.0 .

[[rsa_sigprim_vs_tr_table]]
.RSA Signature Primitive v1.0 Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| signature | If the message can be signed, the signature. If the encoded value is shorter than the key modulus it should be padded at the front with zero bytes. | hex
| testPassed | If the message could not be signed | boolean
|===

The following is an example of the response for RSA / Signature Primitive / v1.0.

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "signaturePrimitive",
  "revision": "1.0",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "testPassed": true,
          "signature": "a60b879a8fa382fdf4..."
        },
        {
          "tcId": 2,
          "testPassed": false
        },
        {
          "tcId": 3,
          "testPassed": false
        }
      ]
    }
  ]
}
----

[[rsa_sigprimV2_0_vs_tr_table]]
.RSA Signature Primitive v2.0 Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| testPassed | If the message could not be signed | boolean
| signature | If the message can be signed, the signature. If the encoded value is shorter than the key modulus it should be padded at the front with zero bytes. | hex
|===

The following is an example of the response for RSA / Signature Primitive / v2.0.

[source, json]
----
{
  "vsId": 0,
  "algorithm": "RSA",
  "mode": "signaturePrimitive",
  "revision": "2.0",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "testPassed": true,
          "signature": "a60b879a8fa382fdf4..."
        },
        {
          "tcId": 2,
          "testPassed": false
        },
        {
          "tcId": 3,
          "testPassed": false
        },
        {
          "tcId": 4,
          "testPassed": true,
          "signature": "a60b879a8fa382fdf4..."
        }
      ]
    }
  ]
}
----