
[[app-reg-ex]]
== Example RSA Capabilities JSON Objects

This appendix contains example JSON object advertising support for the verious RSA modes:keyGen, sigGen, sigVer, legacySigVer, compRSASP1. Note that all binary HEX representations are in big-endian format.


[[app-testVect-ex]]
== Example Test Vectors JSON Objects

This appendix contains example JSON objects for test vectors sent from the ACVP server to the crypto module.


[[app-testVectProvProvPrime-ex]]
=== Example Test Vectors for keyGen JSON Objects

[align=left,alt=,type=]
....

 [
   { "acvVersion": <acvp-version> },
   { "vsId": 1133,
     "algorithm": "RSA",
     "mode": "keyGen",
     "revision": "1.0",
     "infoGeneratedByServer": false,
     "pubExpMode" : "random",
     "keyFormat": "standard",
     "testGroups" : [
             {
                 "tgId": 1,
                 "randPQ" : "B.3.2",
                 "modulo" : 2048,
                 "hashAlg" : "SHA2-256",
                 "testType": "AFT",
                 "tests" : [
                    {
                      "tcId" : 1145
                    },
                    {
                      "tcId" : 1146
                    }
                 ]
             },
             {
                "tgId": 2,
                "randPQ": "B.3.2",
                "modulo" : 3072,
                "hashAlg" : "SHA2-256",
                "testType": "AFT",
                "tests": [
                  {
                    "tcId": 1147
                  },
                  {
                    "tcId": 1148
                  }
                ]
              },
             {
                 "tgId": 3,
                 "randPQ" : "B.3.4",
                 "modulo" : 2048,
                 "hashAlg" : "SHA2-256",
                 "testType": "AFT",
                 "tests" : [
                    {
                      "tcId" : 1149
                    },
                    {
                      "tcId" : 1150
                    }
                 ]
             },
             {
                "tgId": 4,
                "randPQ": "B.3.4",
                "modulo" : 3072,
                "hashAlg" : "SHA2-256",
                "testType": "AFT",
                "tests": [
                  {
                    "tcId": 1151
                  },
                  {
                    "tcId": 1152
                  }
                ]
              },
             {
                 "tgId": 5,
                 "randPQ" : "B.3.5",
                 "modulo" : 2048,
                 "hashAlg" : "SHA2-256",
                 "testType": "AFT",
                 "tests" : [
                    {
                      "tcId" : 1153
                    },
                    {
                      "tcId" : 1154
                    }
                 ]
             },
             {
                "tgId": 6,
                "randPQ": "B.3.5",
                "modulo" : 3072,
                "hashAlg" : "SHA2-256",
                "testType": "AFT",
                "tests": [
                  {
                    "tcId": 1155
                  },
                  {
                    "tcId": 1156
                  }
                ]
              },
             {
                 "tgId": 7,
                 "randPQ" : "B.3.6",
                 "modulo" : 2048,
                 "hashAlg" : "SHA2-256",
                 "testType": "AFT",
                 "tests" : [
                    {
                      "tcId" : 1157
                    },
                    {
                      "tcId" : 1158
                    }
                 ]
             },
             {
                "tgId": 8,
                "randPQ": "B.3.6",
                "modulo" : 3072,
                "hashAlg" : "SHA2-256",
                "testType": "AFT",
                "tests": [
                  {
                    "tcId": 1159
                  },
                  {
                    "tcId": 1160
                  }
                ]
              },
             {
                 "tgId": 9,
                 "randPQ" : "B.3.3",
                 "primeTest" : "tblC2",
                 "testType": "KAT",
                 "modulo" : 2048,
                 "tests" : [
                    {
                      "tcId" : 1119,
                      "e" : "df28ab",
                      "pRand" : "e021757c777288dacfe67cb2e59dc02c70a8cebf56262336592c18dcf466e0a4ed405318ac406bd79eca29183901a557db556dd06f7c6bea175dcb8460b6b1bc05832b01eedf86463238b7cb6643deef66bc4f57bf8ff7ec7c4b8a8af14f478980aabedd42afa530ca47849f0151b7736aa4cd2ff37f322a9034de791ebe3f51",
                      "qRand" : "ed1571a9e0cd4a42541284a9f98b54a6af67d399d55ef888b9fe9ef76a61e892c0bfbb87544e7b24a60535a65de422830252b45d2033819ca32b1a9c4413fa721f4a24ebb5510ddc9fd6f4c09dfc29cb9594650620ff551a62d53edc2f8ebf10beb86f483d463774e5801f3bb01c4d452acb86ecfade1c7df601cab68b065275"
                    },
                    {
                      "tcId" : 1120,
                      "e" : "85a4cf",
                      "pRand" : "e534f4a4eb86ff9ace08a0b446faf3e20c22a0166057507e4f5f07332d5c0878a50798857d5e9946e3f8ef8a1021481bb0c94631f9ad8427df620ec9ca585cab3082222279f41bc40e2ccdc160dbc410c52662699ae16b27b2c9d2bf14e99083920a448ba4e5d3d11e1ab7777613959c07fb213be26f2cb7ea8a759af082f6c5",
                      "qRand" : "ed1571a9e0cd4a42541284a9f98b54a6af67d399d55ef888b9fe9ef76a61e892c0bfbb87544e7b24a60535a65de422830252b45d2033819ca32b1a9c4413fa721f4a24ebb5510ddc9fd6f4c09dfc29cb9594650620ff551a62d53edc2f8ebf10beb86f483d463774e5801f3bb01c4d452acb86ecfade1c7df601cab68b065275"
                    }
                 ]
             },
             {
                 "tgId": 10,
                 "randPQ" : "B.3.3",
                 "primeTest" : "tblC2",
                 "testType": "KAT",
                 "modulo" : 3072,
                 "tests" : [
                    {
                      "tcId" : 1121,
                      "e" : "535c97",
                      "pRand" : "b9c53dd71792a98fd35eaa569079dfc1f0f6dad9a4a50ca589cccdd80b7810c00c4c0b0a74d3c6ead42c2fa3478c5bfde09ffcad4cb793564fc83977ef1de96a11b16e5eb58590720715c10ac620b862cee5081934c5ddd3e3765fb848781af882558cc4f79663d7fff0263401adc832bc29d396a0c9916ed96005b79bf0dbead4158a3139c855f8d9ae83433410ef5fbdbbe9082ccb3b266c374a08ecca3a2d51bca0495766109ef471c9e07e098a809c9fdbdcada5aaeb11dfa36ca59991b5",
                      "qRand" : "ed98c73529938fb891869c7ecc7de069af00abc5896e4ec1b32528feac69f29bfc93c707aec4921ac8191e7dde69272b97eebcd568641edf7dde60632ed075b93712870e4eccbeceefa06bade9d4fe2dc7c8ce6277371f3471f42d201831e9f95c8a6ac3d63dd47058e13b7d8e420d9790a17bc58470b5c130f84fdc39a7cfac3453f3706cc4118900710bed26deca871bfee3aa6c59263d314b969ef228b7d08ecec99acaba3466d25b99ecfa48388cc53b19ca74deefc6dfd3d1a80804f4c5"
                    }
                 ]
             },
             {
                 "tgId": 11,
                 "randPQ" : "B.3.3",
                 "primeTest" : "tblC3",
                 "testType": "KAT",
                 "modulo" : 2048,
                 "tests" : [
                    {
                      "tcId" : 1122,
                      "e" : "df28ab",
                      "pRand" : "e021757c777288dacfe67cb2e59dc02c70a8cebf56262336592c18dcf466e0a4ed405318ac406bd79eca29183901a557db556dd06f7c6bea175dcb8460b6b1bc05832b01eedf86463238b7cb6643deef66bc4f57bf8ff7ec7c4b8a8af14f478980aabedd42afa530ca47849f0151b7736aa4cd2ff37f322a9034de791ebe3f51",
                      "qRand" : "ed1571a9e0cd4a42541284a9f98b54a6af67d399d55ef888b9fe9ef76a61e892c0bfbb87544e7b24a60535a65de422830252b45d2033819ca32b1a9c4413fa721f4a24ebb5510ddc9fd6f4c09dfc29cb9594650620ff551a62d53edc2f8ebf10beb86f483d463774e5801f3bb01c4d452acb86ecfade1c7df601cab68b065275"
                    },
                    {
                      "tcId" : 1123,
                      "e" : "85a4cf",
                      "pRand" : "e534f4a4eb86ff9ace08a0b446faf3e20c22a0166057507e4f5f07332d5c0878a50798857d5e9946e3f8ef8a1021481bb0c94631f9ad8427df620ec9ca585cab3082222279f41bc40e2ccdc160dbc410c52662699ae16b27b2c9d2bf14e99083920a448ba4e5d3d11e1ab7777613959c07fb213be26f2cb7ea8a759af082f6c5",
                      "qRand" : "ed1571a9e0cd4a42541284a9f98b54a6af67d399d55ef888b9fe9ef76a61e892c0bfbb87544e7b24a60535a65de422830252b45d2033819ca32b1a9c4413fa721f4a24ebb5510ddc9fd6f4c09dfc29cb9594650620ff551a62d53edc2f8ebf10beb86f483d463774e5801f3bb01c4d452acb86ecfade1c7df601cab68b065275"
                    }
                 ]
             },
             {
                 "tgId": 12,
                 "randPQ" : "B.3.3",
                 "primeTest" : "tblC3",
                 "testType": "KAT",
                 "modulo" : 3072,
                 "tests" : [
                    {
                      "tcId" : 1124,
                      "e" : "535c97",
                      "pRand" : "b9c53dd71792a98fd35eaa569079dfc1f0f6dad9a4a50ca589cccdd80b7810c00c4c0b0a74d3c6ead42c2fa3478c5bfde09ffcad4cb793564fc83977ef1de96a11b16e5eb58590720715c10ac620b862cee5081934c5ddd3e3765fb848781af882558cc4f79663d7fff0263401adc832bc29d396a0c9916ed96005b79bf0dbead4158a3139c855f8d9ae83433410ef5fbdbbe9082ccb3b266c374a08ecca3a2d51bca0495766109ef471c9e07e098a809c9fdbdcada5aaeb11dfa36ca59991b5",
                      "qRand" : "ed98c73529938fb891869c7ecc7de069af00abc5896e4ec1b32528feac69f29bfc93c707aec4921ac8191e7dde69272b97eebcd568641edf7dde60632ed075b93712870e4eccbeceefa06bade9d4fe2dc7c8ce6277371f3471f42d201831e9f95c8a6ac3d63dd47058e13b7d8e420d9790a17bc58470b5c130f84fdc39a7cfac3453f3706cc4118900710bed26deca871bfee3aa6c59263d314b969ef228b7d08ecec99acaba3466d25b99ecfa48388cc53b19ca74deefc6dfd3d1a80804f4c5"
                    }
                 ]
             }
         ]
      }
   ]

....


Note that this example has "infoGeneratedByServer" set to false. This means the client is responsible for providing the details by running an instance of the appropriate
      Key Generation method for each test. The information returned should match all applicable data in the table in <<vs_tr_keyGen_table>>. For Key Generation method 2 (Appendix B.3.3                     <<FIPS186-4>>) if the public exponent is random, there are two test types. One is a known answer test (KAT) provided by the server resulting in a "pass"/"fail"
    response determining if the input forms a valid key pair. The other, which exists for a fixed public exponent as well, asks the client to generate 10 key pairs ('e', 'p', 'q', 'n', and 'd')
    and the server validates that this pair matches the requirements. Below is an example set of test vectors that would come from the server when the registration includes "infoGeneratedByServer" set to true.



[[app-testVectorsKeygenB34-ex]]
=== Example Test Vectors for keyGen when infoGeneratedByServer is true

[align=left,alt=,type=]
....

[
    { "acvVersion" : <acvp-version> },
    {
        "vsId" : 172,
        "algorithm" : "RSA",
        "mode" : "keyGen",
        "revision": "1.0",
        "testGroups" : [
            {
                "tgId": 1,
                "modulo" : 2048,
                "testType" : "AFT",
                "randPQ" : "B.3.4",
                "pubExpMode" : "fixed",
                "keyFormat" : "standard",
                "fixedPubExp" : "010001",
                "infoGeneratedByServer" : true,
                "hashAlg" : "SHA2-256",
                "tests" : [
                    {
                        "tcId" : 1,
                        "bitlens" : [ 143, 160, 235, 249 ],
                        "seed" : "3CE2DBBFFE28316F8E21BD73201E2D2B060EB14B53C4327627800E07"
                    }, {
                        "tcId" : 2,
                        "bitlens" : [ 169, 316, 277, 168 ],
                        "seed" : "9B6882E5D57519A07042BD7C92192B511E09B07B08941F86C711A1A2"
                    }, {
                        "tcId" : 3,
                        "bitlens" : [ 308, 147, 225, 174 ],
                        "seed" : "03E13C2C88EB9C7789C04FC193AC0A28BE131929539A561C896482A5"
                    }
                ]
            }, {
                "tgId": 2,
                "modulo" : 3072,
                "testType" : "AFT",
                "randPQ" : "B.3.4",
                "pubExpMode" : "fixed",
                "keyFormat" : "standard",
                "fixedPubExp" : "010001",
                "infoGeneratedByServer" : true,
                "hashAlg" : "SHA2-256",
                "tests" : [
                    {
                        "tcId" : 4,
                        "bitlens" : [ 195, 507, 204, 478 ],
                        "seed" : "1C575DDA6CD0B687727C5F1DAC1584C0F7A3869D73AC5FC8D911B6431EC2D9DB"
                    }, {
                        "tcId" : 5,
                        "bitlens" : [ 345, 323, 477, 181 ],
                        "seed" : "802490076AFFA5E58D97505D7C1521A8FFF163296430A1C919B0B8075CE81CAB"
                    }, {
                        "tcId" : 6,
                        "bitlens" : [ 310, 348, 206, 500 ],
                        "seed" : "7017D3909F2B1C01CAF95D2782B66A9D7DA275767E38C125ED32D1EFBCC0E5C0"
                    }
                ]
            }
        ]
    }
]


....
