
=== Test Coverage

The tests described in this document are intended to ensure an implementation conformant with the requirements listed below.  For clarity, related requirements not covered are also provided.

[[requirements_covered]]
==== Requirements Covered

* FIPS 186-4 Section 3 General Discussion. Key generation, signature generation, and signature validation are all within scope of ACVP server testing.

* FIPS 186-4 Section 5 The RSA Digital Signature Algorithm. The ACVP server provides a means of testing the generation of RSA keys. The ACVP server *SHALL* support a variety of RSA capabilities functionS for the creation and delivery of tests to/from the IUT. Key pair generation testing *SHALL* be provided by the ACVP server. Both Signature Generation and Validation testing mechanisms *SHALL* be provided by the ACVP server.

* FIPS 186-2. The ACVP server MAY provide a means of testing legacy RSA functions such as RSA sigVer. This testing is provided to ensure an IUT is capable of verifying a signature that is no longer approved for generation, given the same capabilities.

* SP800-106 Section 3 Randomized Hashing and Section 4 Digital Signatures Using Randomized Hashing. The IUT *SHALL* be provided or provide a random value that should be used to "randomize" a message prior to signing and/or verifying an original message.

[[requirements_not_covered]]
==== Requirements Not Covered

* FIPS 186-4 Section 3 General Discussion. Assurances of private key secrecy and ownership *SHALL NOT* be within scope of ACVP testing.

* FIPS 186-4 Section 5 The RSA Digital Signature Algorithm. Though the ACVP server *SHALL* support a variety of parameter sizes hash functions, the IUT's selection of these is out of scope of testing. Key pair management *SHALL NOT* be within scope of ACVP testing.

* SP800-106 Section 3.3 The Random Value. DSA, ECDSA, and RSA have random values generated as per their signing process, this random value can be used as the input to the message randomization function, doing so however is out of scope of this testing.
