
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate implementations of SHA3 and SHAKE.

=== Test Types

There are three types of tests for these hash functions: functional tests, Monte Carlo tests and Variable Output tests. Each has a specific value to be used in the testType field.  The testType field definitions are:

* "AFT" - Algorithm Functional Test. These tests can be processed by the client using a normal 'hash' operation.  AFTs cause the implementation under test to exercise nomral operations on a single block, multiple blocks, or partial blocks. In all cases,random data is used. The functional tests are designed to verify that the logical components of the hash function (block chunking, block padding etc.) are operating correctly.

* "MCT" - Monte Carlo Test. These tests exercise the implementation under test under stenuous circumstances. The implementation under test must process the test vectors according to the correct algorithm and mode in this document. MCTs can help detect potential memory leaks over time, and problems in allocation of resources, addressing variables, error handling, and generally improper behavior in response to random inputs. Each MCT processes 100 pseudorandom tests. Each algorithm and mode SHOULD have at least one MCT group. See <<MC_test>> for implementation details.

* "VOT" - Variable Output Test. XXX

[[MC_test]]
=== Monte Carlo tests for SHA3 and SHAKE

[[SHA3-MCT]]
==== SHA3 Monte Carlo Test

[[SHAKE-MCT]]
==== SHAKE Monte Carlo Test

