[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS202>>.

[[sha3-coverage]]
==== SHA3 Requirements Covered

Sections 3 through 6 in <<FIPS202>> outline the Keccak construction and strucures needed to form a valid SHA3 implementation. Normal AFTs test these operations by running the algorithm.

Section 7 in <<FIPS202>> states that any input sizes may be used within a SHA3 hash implementation. The input sizes tested in this document range from 0 bits to 65536 bits. In addition a large data test is available by special request which tests messages that are multiple gigabytes in size.

[[sha3-not-coverage]]
==== SHA3 Requirements Not Covered

It is noted that <<FIPS202>> states that "different procedures that produce the correct output for every input are permitted" and thus the internal states discussed in Sections 3 through 6 *SHALL NOT* be tested or tracked.

[[shake-coverage]]
==== SHAKE Requirements Covered

Sections 3 through 6 in <<FIPS202>> outline the Keccak construction and strucures needed to form a valid SHAKE implementation. Normal AFTs test these operations by running the algorithm. VOTs exercise the ability of the implementation to perform the algorithm as well by focusing on the sponge construction.

Section 7 in <<FIPS202>> states that any input sizes or output sizes may be used within a SHAKE implementation. The input sizes tested in this document range from 0 bits to 65536 bits. The output sizes tested in this document range from 16 bits to 65536 bits.

[[shake-not-coverage]]
==== SHAKE Requirements Not Covered

Again, the internal states discussed in Sections 3 through 6 *SHALL NOT* be tested or tracked.
