
.Reports on Computer Systems Technology
The Information Technology Laboratory (ITL) at the National Institute of
Standards and Technology (NIST) promotes the U.S. economy and public welfare by
providing technical leadership for the Nation's measurement and standards
infrastructure. ITL develops tests, test methods, reference data, proof of
concept implementations, and technical analyses to advance the development and
productive use of information technology. ITL's responsibilities include the
development of management, administrative, technical, and physical standards and
guidelines for the cost-effective security and privacy of other than national
security-related information in federal information systems. The Special
Publication 800-series reports on ITL's research, guidelines, and outreach
efforts in information system security, and its collaborative activities with
industry, government, and academic organizations.

[preface]
== Acknowledgements

This document is produced by the Security Testing, Validation and Measurement
group under the Automated Cryptographic Validation Testing (ACVT) program.

[preface]
== Audience

This document is intended for the users and developers of ACVP.

[executive-summary]
== Executive Summary

The Automated Crypto Validation Protocol (ACVP) defines a mechanism to
automatically verify the cryptographic implementation of a software or hardware
crypto module. The ACVP specification defines how a crypto module communicates
with an ACVP server, including crypto capabilities negotiation, session
management, authentication, vector processing and more. The ACVP specification
does not define algorithm specific JSON constructs for performing the crypto
validation. A series of ACVP sub-specifications define the constructs for
testing individual crypto algorithms. Each sub-specification addresses a
specific class of crypto algorithms. This sub-specification defines the JSON
constructs for testing {spec-algorithm} implementations using ACVP.

[preface]
== Conventions

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD",
"SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in this
document are to be interpreted as described in BCP 14 of <<RFC2119>> and
<<RFC8174>> when, and only when, they appear in all capitals, as shown here.
