[#prerequisites]
=== Prerequisites

Each algorithm implementation *MAY* rely on other cryptographic primitives.	For example, RSA Signature algorithms depend on an underlying hash function. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

Prerequisites, if applicable, *MUST* be submitted in the registration as the `prereqVals` JSON property array inside each element of the `algorithms` array. Each element in the `prereqVals` array *MUST* contain the following properties

.Prerequisite Properties
|===
| JSON Property | Description | JSON Type

| algorithm | a prerequisite algorithm | string
| valValue | algorithm validation number | string
|===

A "valValue" of "same" *SHALL* be used to indicate that the prerequisite is being met by a different algorithm in the capability exchange in the same registration.

An example description of prerequisites within a single algorithm capability exchange looks like this

[source,json]
----
"prereqVals":
[
  {
    "algorithm": "Alg1",
    "valValue": "Val-1234"
  },
  {
    "algorithm": "Alg2",
    "valValue": "same"
  }
]
----
