
[%bibitem]
[[ACVP]]
=== Automatic Cryptographic Validation Protocol
docid::
docid.id:: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: C.
contributor.person.name.surname:: Celi
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: R.
contributor.person.name.surname:: Hammett
contributor.person.affiliation.organization.name:: Huntington Ingalls Industries
contributor.person.affiliation.organization.abbreviation:: HII
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01
