
[#properties]
=== Property Registration

The IKEv2 KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

[#registration]
=== Registration Example

A registration *SHALL* use these properties

.IKEv2 KDF Mode Capabilities JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ikev2"
| revision | ACVP Test version | string | "1.0"
| capabilities | Array of objects describing capabilities | array | Contains each of the below properties
| initiatorNonceLength | The supported initiator nonce, Ni, length(s) used by the IUT in bits | domain | Min: 64, Max: 2048
| responderNonceLength | The length(s) of data the IUT supports in bits, Nr | domain | Min: 64, Max: 2048
| diffieHellmanSharedSecretLength | The length(s) of Diffie Hellman shared secrets, g^ir, the IUT supports in bits | domain | Min: 224, Max: 8192
| derivedKeyingMaterialLength | The length(s) of the IKE SA derived keying material the IUT supports in bits | domain | Min: 160, Max: 16384
| derivedKeyingMaterialChildLength | The length(s) of the CHILD SA derived keying material the IUT supports in bits | domain | Min: 160, Max: 16384
| hashAlg | Valid hash algorithms used by the IUT | array | See <<valid-sha>>
|===

NOTE: if a derivedKeyingMaterialChildLength is not provided, derivedKeyingMaterialChildLength will be assumed to equal derivedKeyingMaterialLength.

An example registration within an algorithm capability exchange looks like this

[source, json]
----
"capability_exchange":
[
    {
        "algorithm": "kdf-components",
        "mode": "IKEv2",
        "revision": "1.0",
        "capabilities": [
            {
                "hashAlg": [
                    "sha-1",
                    "sha2-224",
                    "sha2-256"
                ],
                "initiatorNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "responderNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "diffieHellmanSharedSecretLength": [
                    {
                        "min": 224,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "derivedKeyingMaterialLength": [
                    {
                        "min": 384,
                        "max": 16384,
                        "increment": 1
                    }
                ],
                 "derivedKeyingMaterialChildLength": [
                    {
                        "min": 384,
                        "max": 16384,
                        "increment": 1
                    }
                ]
            },
            {
                "hashAlg": [
                    "sha2-384",
                    "sha2-512"
                ],
                "initiatorNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "responderNonceLength": [
                    {
                        "min": 64,
                        "max": 2048,
                        "increment": 1
                    }
                ],
                "diffieHellmanSharedSecretLength": [
                    {
                        "min": 224,
                        "max": 8192,
                        "increment": 1
                    }
                ],
                "derivedKeyingMaterialLength": [
                    {
                        "min": 1024,
                        "max": 16384,
                        "increment": 1
                    }
                ],
                "derivedKeyingMaterialChildLength": [
                    {
                        "min": 1024,
                        "max": 16384,
                        "increment": 1
                    }
                ]
            }
        ]
    }
]
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
