
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

[source, json]
----
{
    "tgId": 1,
    "tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

[[test_case_results_table]]
.Test Case Results JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | The test case identifier | integer
| sKeySeed | Results of the extraction step, SKEYSEED | hex
| sKeySeedReKey | The SKEYSEED value created when using the CREATE_CHILD_SA exchange to rekey an existing IKE SA | hex
| derivedKeyingMaterial | Derived key Material from expansion step  | hex
| derivedKeyingMaterialChild | Expansion step results for CHILD SA | hex
| derivedKeyingMaterialDh | Expansion step results for CHILD SA DH | hex
|===

Here is an abbreviated example of the response

[source, json]
----
{
  "vsId": 1,
  "algorithm": "kdf-components",
  "mode": "IKEv2",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "sKeySeed": "B5B0B203F931C2BD06D9...",
          "derivedKeyingMaterial": "C807976...",
          "derivedKeyingMaterialChild": "BA...",
          "derivedKeyingMaterialDh": "4A222...",
          "sKeySeedReKey": "7076E7DB098CE1A..."
        },
        {
          "tcId": 2,
          "sKeySeed": "DAF33468A586B7E705CA...",
          "derivedKeyingMaterial": "5659749...",
          "derivedKeyingMaterialChild": "2A...",
          "derivedKeyingMaterialDh": "4554A...",
          "sKeySeedReKey": "CF78ADF8EE17348..."
        }
      ]
    }
  ]
}
----
