[#properties]

[[prereq_algs]]
=== Required Prerequisite Algorithms for KDA Validations

Some algorithm implementations rely on other cryptographic primitives. For example, IKEv2 uses an underlying SHA algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

.Prerequisite Algorithms
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | a prerequisite algorithm | value | DRBG, HMAC, SHA
| valValue | algorithm validation number | value | actual number or "same"
| prereqAlgVal | prerequisite algorithm validation | object with algorithm and valValue properties| see above
|===

=== Property Registration

The {spec-algorithm} mode capabilities are advertised as JSON objects within a root "algorithm" object.

A registration *SHALL* use these properties:

.Registration Properties
|===
| JSON Value| Description| JSON Type| Valid Values

| algorithm | The algorithm under test | value | KDA
| mode | The mode under test | value | HKDF
| revision | The algorithm testing revision to use. | value | "Sp800-56Cr1" or "Sp800-56Cr2"
| prereqVals | Prerequisite algorithm validations | array of prereqAlgVal objects | See <<prereq_algs>>
| fixedInfoPattern | The pattern used for fixedInfo construction. | string | See <<fixedinfopatcon>>
| encoding | The encoding type to use with fixedInfo construction.  Note concatenation is currently supported.  ASN.1 should be coming. | array of string | concatenation 
| hmacAlg | The HMAC modes supported by the KDA. | array of string | See <<hmacAlg>>
| macSaltMethods | How the salt is determined (default being all 00s, random being a random salt). | array of string | default, random
| z | The length(s) of the shared secret, Z, the IUT supports in bits. | Domain | Min: 224, Max: 65536, Increment: 8
| usesHybridSharedSecret | Whether the IUT uses a hybrid shared secret. Only applicable for <<SP800-56Cr2>>. This property is required and must be set to 'true' for IUTs that implement a hybrid shared secret. Omit this property for "SP800-56Cr1" testing. If omitted for "SP800-56Cr2" testing, a value of 'false' will be assumed. | Boolean | true or false
| auxSharedSecretLen | The length(s) of the auxiliary shared secret, T, the IUT supports in bits. Only applicable for <<SP800-56Cr2>>. This property is required for IUTs that implement a hybrid shared secret. Omit this property for "SP800-56Cr1" testing or for "SP800-56Cr2" testing without a hybrid shared secret. | Domain | Min: 112, Max: 65536, Increment: 8
| l | The length (in bits) of the largest derived keying material the implementation can produce (up to a max of 2048). | number | Min: 112; Max: 2048
| performMultiExpansionTests | Should multi expansion runs of the KDA be tested (in addition to the single expansion tests)? Only applicable for <<SP800-56Cr2>> | boolean | true, false 
|===

[[fixedinfopatcon]]
==== FixedInfoPatternConstruction

IUTs *MUST* be capable of specifying how the FixedInfo is constructed for the KDA construction. Note that for the purposes of testing against the ACVP system, both uPartyInfo and vPartyInfo are *REQUIRED* to be registered within the fixed info pattern.  Also, when l is used for fixedInfo it is expected to be and is processed as a big endian byte string.

Pattern candidates:

* literal[0123456789ABCDEF]
  ** uses the specified hex within "[]". literal[0123456789ABCDEF]
substitutes "0123456789ABCDEF" in place of the field

* uPartyInfo
  ** uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* vPartyInfo
  ** vPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* context
  ** Random value chosen by ACVP server to represent the context.

* algorithmId
  ** Random value chosen by ACVP server to represent the
algorithmId.

* label
  ** Random value chosen by ACVP server to represent the label.

* l
  ** The length of the derived keying material in bits, *MUST* be represented in 32 bits for ACVP testing.

* t
  ** A random value used to represent a secondary shared secret. Only applicable to <<SP800-56Cr2>>.

Example (Note that party U is the server in this case "434156536964", party V is the IUT "a1b2c3d4e5"):

* "concatenation" :
"literal[123456789CAFECAFE]||uPartyInfo||vPartyInfo"

Evaluated as:

* "123456789CAFECAFE434156536964a1b2c3d4e5"

[[hmacAlg]]
==== Valid HMAC Functions

The following hash functions MAY be advertised by an ACVP compliant client under the 'hmacAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512

=== Registration Example

.Registration JSON Example SP800-56Cr1
[source,json]
----
{
  "algorithm": "KDA",
  "mode": "HKDF",
  "revision": "Sp800-56Cr1",
  "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
  "encoding": [
    "concatenation"
  ],
  "hmacAlg": [
    "SHA2-224",
    "SHA2-256",
    "SHA2-384",
    "SHA2-512",
    "SHA2-512/224",
    "SHA2-512/256",
    "SHA3-224",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512"
  ],
  "macSaltMethods": [
    "default",
    "random"
  ],
  "l": 1024,
  "z": [
    {
      "min": 224,
      "max": 65336,
      "increment": 8
    }
  ]
}
----

.Registration JSON Example SP800-56Cr2
[source,json]
----
{
  "algorithm": "KDA",
  "mode": "HKDF",
  "revision": "Sp800-56Cr2",
  "fixedInfoPattern": "uPartyInfo||vPartyInfo||t||l",
  "performMultiExpansionTests": true,
  "encoding": [
    "concatenation"
  ],
  "hmacAlg": [
    "SHA2-224",
    "SHA2-256",
    "SHA2-384",
    "SHA2-512",
    "SHA2-512/224",
    "SHA2-512/256",
    "SHA3-224",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512"
  ],
  "macSaltMethods": [
    "default",
    "random"
  ],
  "l": 1024,
  "z": [
    {
      "min": 224,
      "max": 65336,
      "increment": 8
    }
  ]
}
----
