[#properties]
=== Property Registration

The {spec-algorithm} mode capabilities are advertised as JSON objects within a root "algorithm" object.

A registration *SHALL* use these properties:

.Registration Properties
|===
| JSON Value| Description| JSON Type| Valid Values

| algorithm| The algorithm under test| value| KAS-KDF
| mode| The mode under test| value| OneStep
| revision| The algorithm testing revision to use.| value| "Sp800-56Cr1"
| prereqVals| Prerequisite algorithm validations| array of prereqAlgVal objects| See <<prereq_algs>>
| capabilities | The two step configuration objects | array of <<twostepkdf>> | See <<twostepkdf>>
| z| The domain of values representing the min/max lengths of Z the implementation can support.| Domain
| l| The largest DKM the implementation can produce (up to a max of 2048).| number
|===

[[prereq_algs]]
==== Prerequisite Algorithms for KAS KDF Validations

Some algorithm implementations rely on other cryptographic primitives. For example, IKEv2 uses an underlying SHA algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

.Prerequisite Algorithms
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | a prerequisite algorithm | value | CMAC, DRBG, HMAC, SHA
| valValue | algorithm validation number | value | actual number or "same"
| prereqAlgVal | prerequisite algorithm validation | object with algorithm and valValue properties| see above
|===

[[twostepkdf]]
==== Two Step KDF Capabilities

.TwoStepCapabilities Options
|===
| JSON Value | Description | JSON Type | Valid Values

| macSaltMethod | How the salt is determined (default being all 00s, random being a random salt). | array of string | default, randombased auxiliary functions.
| fixedInfoPattern | The pattern used for fixedInfo construction. | string | See <<fixedinfopatcon>>
| encoding | The encoding type to use with fixedInfo construction.  Note concatenation is currently supported.  ASN.1 should be coming. | array of string | concatenation 
| kdfMode | The strategy for running the KDF. | string | counter, feedback, double pipeline iteration
| macMode | The macMode supported by the KDF. | array of string | CMAC-AES128, CMAC-AES192, CMAC-AES256, HMAC-SHA-1, HMAC-SHA2-224, HMAC-SHA2-256, HMAC-SHA2-384, HMAC-SHA2-512, HMAC-SHA2-512/224, HMAC-SHA2-512/256, HMAC-SHA3-224, HMAC-SHA3-256, HMAC-SHA3-384, HMAC-SHA3-512
| fixedDataOrder | The counter locations supported by the KDF. | array of string| none, before fixed data, after fixed data, before iterator
| counterLength | The counter lengths supported for the KDF. | array of integer | 8, 16, 24, 32
| supportedLengths | The supported derivation lengths. | domain| Single range (of literal) expected.  Registered value must support the L value provided.
| supportsEmptyIv | The KDF supports an empty IV (feedback mode). | boolean | true, false
| requiresEmptyIv | The KDF requires an empty IV (feedback mode). | boolean | true, false
|===

Note this capabilities object is very similar to the capability object from SP800-108.

[[fixedinfopatcon]]
==== FixedInfoPatternConstruction

IUTs *MUST* be capable of specifying how the FixedInfo is constructed for the KDF construction. Note that for the purposes of testing against the ACVP system, both uPartyInfo and vPartyInfo are *REQUIRED* to be registered within the fixed info pattern.

Pattern candidates:

* literal[0123456789ABCDEF]
  ** uses the specified hex within "[]". literal[0123456789ABCDEF]
substitutes "0123456789ABCDEF" in place of the field

* uPartyInfo
  ** uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* vPartyInfo
  ** vPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* context
  ** Random value chosen by ACVP server to represent the context.

* algorithmId
  ** Random value chosen by ACVP server to represent the
algorithmId.

* label
  ** Random value chosen by ACVP server to represent the label.

* l
  ** The length of the derived keying material in bits, *MUST* be represented in 32 bits for ACVP testing.

Example (Note that party U is the server in this case "434156536964", party V is the IUT "a1b2c3d4e5"):

* "concatenation" :
"literal[123456789CAFECAFE]||uPartyInfo||vPartyInfo"

Evaluated as:

* "123456789CAFECAFE434156536964a1b2c3d4e5"

=== Registration Example

.Registration JSON Example
[source,json]
----
{
  "algorithm": "KAS-KDF",
  "mode": "TwoStep",
  "revision": "Sp800-56Cr1",
  "prereqVals": [
    {
      "algorithm": "DRBG",
      "valValue": "123456"
    },
    {
      "algorithm": "SHA",
      "valValue": "123456"
    },
    {
      "algorithm": "HMAC",
      "valValue": "123456"
    }
  ],
  "capabilities": [
    {
      "macSaltMethods": [
        "random",
        "default"
      ],
      "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
      "encoding": [
        "concatenation"
      ],
      "kdfMode": "feedback",
      "macMode": [
        "HMAC-SHA3-224",
        "HMAC-SHA2-512"
      ],
      "supportedLengths": [
        512
      ],
      "fixedDataOrder": [
        "after fixed data",
        "before iterator"
      ],
      "counterLength": [
        32
      ],
      "requiresEmptyIv": false,
      "supportsEmptyIv": false
    }
  ],
  "l": 2048,
  "z": [
    512
  ]
}
----