
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified Ascon algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of Ascon capabilities. This section describes the design of the tests used to validate implementations of the Ascon algorithms. The number of tests *MAY* vary but the minimum number required by each test type *SHALL* be included by the server. The test type describes the format of the test rather than the intention of the test. Multiple tests of the same test type *MAY* cover different assurances regarding the implementation. 

==== Ascon AEAD Test Types

* Ascon / AEAD128 / * "AFT" - Algorithm Functional Test. 

For each test case provided the IUT *SHALL* perform either encryption or decryption. In the case of encryption, the IUT *SHALL* use the provided key, nonce, associated data, payload, payload bit length, associated data bit length, tag length, and second key values. The IUT-computed ciphertext and tag are communicated to the ACVP server and compared to the expected ciphertext and tag. This tests the implementation of Algorithm 3 `Ascon-AEAD128.enc()` from <<SP800-232>> Section 4.1.1. The server *SHALL* provide at least 60 tests for each combination of capabilities. In the case of decryption, the IUT *SHALL* use the provided key, nonce, associated data, ciphertext, tag, ciphertext bit length, associated data bit length, tag length, and second key values. The IUT-computed payload is communicated to the ACVP server and compared to the expected payload. In some decrypt cases, the server may provide a modified tag value which will cause the server to expect a "failure" response. This tests the implementation of Algorithm 4 `Ascon-AEAD128.dec()` from <<SP800-232>> Section 4.1.2. The server *SHALL* provide at least 60 tests for each combination of capabilities.

The decypt modifcations are:

* "valid input - ciphertext should decrypt successfully" - No modifcations to the inputs are made and decryption will complete successfully.

* "modified tag" - The tag is modified and decryption will fail.

==== Ascon Hash Test Types

* Ascon / Hash256 / * "AFT" - Algorithm Functional Test. 

For each test case provided the IUT *SHALL* generate a valid digest given the ACVP-provided message and message bit length. The digest is then compared to the known result by the ACVP server. This tests the implementation of Algorithm 5 `Ascon-Hash256()` from <<SP800-232>> Section 5.1. The server *SHALL* provide at least 60 tests generated for each combination of capabilities.

==== Ascon XOF Test Types

* Ascon / XOF128 / * "AFT" - Algorithm Functional Test. 

For each test case provided the IUT *SHALL* generate a valid digest given the ACVP-provided message, message bit length, and digest bit length. The digest is then compared to the known result by the ACVP server. This tests the implementation of Algorithm 6 `Ascon-XOF128()` from <<SP800-232>> Section 5.2. The server *SHALL* provide at least 60 tests generated for each combination of capabilities.

==== Ascon CXOF Test Types

* Ascon / CXOF128 / * "AFT" - Algorithm Functional Test. 

For each test case provided the IUT *SHALL* generate a valid digest given the ACVP-provided message, message bit length, customization string, customization string bit length, and digest bit length. The digest is then compared to the known result by the ACVP server. This tests the implementation of Algorithm 7 `Ascon-CXOF128()` from <<SP800-232>> Section 5.3. The server *SHALL* provide at least 60 tests generated for each combination of capabilities.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-232>>.

[[requirements_covered]]
==== Requirements Covered

* The tests will support ensuring the conformity and correctness of an implementation of the algorithms supported. 

[[requirements_not_covered]]
==== Requirements Not Covered

* SP800-232 Section 4.3. Additional Requirements. Requirements outlined in this section are not testable by an ACVP server.
