
[[Ascon_CXOF128_registration]]
=== Ascon CXOF128 Registration Properties

Each Ascon CXOF128 algorithm capability advertised is a self-contained JSON object using the following values.

[[Ascon_CXOF128_caps_table]]
.Ascon CXOF128 Algorithm Capabilities JSON Values
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | The algorithm to be validated | string | "Ascon"
| mode | The Ascon mode to be validated | string | "CXOF128"
| revision | The algorithm testing revision to use | string | "SP800-232"
| messageLength | The supported message lengths in bits | Domain | {"Min": 0, "Max": 65536, "Inc": any}
| digestLength | The supported digest lengths in bits | Domain | {"Min": 1, "Max": 65536, "Inc": any}
| customizationStringLengthLength | The supported customization string lengths in bits | Domain | {"Min": 0, "Max": 2048, "Inc": any}
|===

[[Ascon_CXOF128_capabilities]]
==== Ascon CXOF128 Mode Capabilities Example

Below is an example of the registration for Ascon / CXOF128 / SP800-232

[source, json]
----
{
  "vsId": 42,
  "algorithm": "Ascon",
  "mode": "CXOF128",
  "revision": "SP800-232",
  "isSample": true,
  "messageLength": [
    {
      "min": 0,
      "max": 65536,
      "increment": 1
    }
  ],
  "digestLength": [
    {
      "min": 1,
      "max": 65536,
      "increment": 1
    }
  ],
  "customizationStringLength": [
    {
      "min": 0,
      "max": 2048,
      "increment": 1
    }
  ]
}
----
