[[Ascon_AEAD128_test_vectors]]
=== Ascon AEAD128 Test Vectors

[[Ascon_AEAD128_tgjs]]
==== Ascon AEAD128 Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for Ascon / AEAD128 / SP800-232 is as follows:

[[Ascon_AEAD128_vs_tg_table]]
.Ascon AEAD128 Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| tests | Array of individual test vector JSON objects, which are defined in <<Ascon_AEAD128_tvjs>> | array
|===

[[Ascon_AEAD128_tvjs]]
==== Ascon AEAD128 Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each Ascon / AEAD128 / FIPS205 test vector.

[[Ascon_AEAD128_vs_tc_table]]
.Ascon AEAD128 Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| key | Key value | hex
| nonce | Nonce value | hex
| ad | Associated data value | hex
| pt | Payload | hex
| ptBitLength | Payload bit length | integer
| adBitLength | Assoicated data bit length | integer
| tagLength | Tag bit length | integer
| secondKey | Second key value | hex
|===

The following is an example JSON object sent from the server to the client for Ascon / AEAD128 / FIPS205 in the encrypt direction. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 42,
        "algorithm": "Ascon",
        "mode": "AEAD128",
        "revision": "SP800-232",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 3,
                        "key": "CE1F4612A82B507BC8C3E9E9628F879F",
                        "nonce": "1FAEAE936AFF885DF41A8CD5F2F01B46",
                        "ad": "DC11EA34AC6B55ADCD5E0FA0DDCE6633296B1209989FF4E98CA5A2AE2C67BD5CD86ECC005BEB21D9277A0140A65A0C72",
                        "pt": "D489319F0B6E243D1D01A707C8A78065A1B2C86E",
                        "payloadBitLength": 159,
                        "adBitLength": 383,
                        "tagLength": 64,
                        "secondKey": "A3D9B0983143B39D1DE1394A3DD76602"
                    }
                ]
            }
        ]
    }
]
----

The following is an example JSON object sent from the server to the client for Ascon / AEAD128 / FIPS205 in the decrypt direction. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 42,
        "algorithm": "Ascon",
        "mode": "AEAD128",
        "revision": "SP800-232",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 3,
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 171,
                        "key": "A9B685BE3FB712E8D577B9197025BE31",
                        "nonce": "1B226E39535EDB4E74321E907C48EECD",
                        "ad": "CE189800",
                        "tag": "FA1267454C135F88",
                        "payloadBitLength": 23,
                        "adBitLength": 25,
                        "tagLength": 64,
                        "secondKey": "369D9368059840532564477056F6FA1D",
                        "ct": "378F3B"
                    }
                ]
            }
        ]
    }
]
----
