[[Ascon_AEAD128_test_vectors]]
=== Ascon AEAD128 Test Vectors

[[Ascon_AEAD128_tgjs]]
==== Ascon AEAD128 Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for Ascon / AEAD128 / SP800-232 is as follows:

[[Ascon_AEAD128_vs_tg_table]]
.Ascon AEAD128 Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| direction | The direction the block cipher operates in | string
| supportsNonceMasking | Boolean to determine if test group uses a second key for nonce masking | boolean
| tests | Array of individual test vector JSON objects, which are defined in <<Ascon_AEAD128_tvjs>> | array
|===

[[Ascon_AEAD128_tvjs]]
==== Ascon AEAD128 Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each Ascon / AEAD128 / FIPS205 test vector.

[[Ascon_AEAD128_vs_tc_table]]
.Ascon AEAD128 Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| key | Key value | hex
| nonce | Nonce value | hex
| ad | Associated data value | hex
| tag | Tag in the decrypt case | hex
| pt | Payload in the encrypt case | hex
| ct | Payload in the decrypt case | hex
| payloadLen | Payload bit length | integer
| adLen | Assoicated data bit length | integer
| tagLen | Tag bit length | integer
| secondKey | Second key value | hex
|===

The following is an example JSON object sent from the server to the client for Ascon / AEAD128 / FIPS205. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 42,
        "algorithm": "Ascon",
        "mode": "AEAD128",
        "revision": "SP800-232",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "direction": "encrypt",
                "supportsNonceMasking": true,
                "tests": [
                    {
                        "tcId": 60,
                        "key": "FD49918ED109AF4237047633E899B574",
                        "nonce": "B6B6598FFA6317E896945E69FBC05591",
                        "ad": "47E62206F92A652B",
                        "pt": "F2C255",
                        "payloadLen": 23,
                        "adLen": 64,
                        "tagLeng": 64,
                        "secondKey": "016FBC19B1FAF20FBC6C051B6B8543A7"
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "direction": "encrypt",
                "supportsNonceMasking": false,
                "tests": [
                    {
                        "tcId": 107,
                        "key": "66D31B340B8B4D8C82CDF4C1B76DC4A6",
                        "nonce": "51224C04CC0D79B992826F3478DF6C95",
                        "ad": "63BEEE9E4B971FEFABEAEBBADBF512194EB04E0E",
                        "pt": "9596D2",
                        "payloadLen": 24,
                        "adLen": 160,
                        "tagLen": 64
                    }
                ]
            },
            {
                "tgId": 3,
                "testType": "AFT",
                "direction": "decrypt",
                "supportsNonceMasking": true
                "tests": [
                    {
                        "tcId": 125,
                        "key": "F381BF2A2CCC344C07E30DB6D93C43A5",
                        "nonce": "538AB0C0748FA21B4841329C640E5B8C",
                        "ad": "6421B70D86E8CA3D80C0708F72C840717BAB0D4900",
                        "tag": "EB8DDC8F7B32334D",
                        "payloadLen": 63,
                        "adLen": 161,
                        "tagLen": 64,
                        "secondKey": "89ADE7BE07136C740708C8F10CF58970",
                        "ct": "EA2649C1EDEA2F4A"
                    }
                ]
            },
            {
                "tgId": 4,
                "testType": "AFT",
                "direction": "decrypt",
                "supportsNonceMasking": false
                "tests": [
                    {
                        "tcId": 184,
                        "key": "E37C0BB570A0F742C72E0F26C2A72BDD",
                        "nonce": "49F8A80BCCCA888D053F41EE35842A78",
                        "ad": "55D138A7B7A84454D7217121446BA4AF1050B988",
                        "tag": "6497C727EC4CBF8F",
                        "payloadLen": 383,
                        "adLen": 160,
                        "tagLen": 64,
                        "ct": "C20807710C919109AC1618D872ABCD1D8D2B3372136BB90A309F55804C0856A6FB213C2FB3CB7B58D5DEA5FDFC208673"
                    }
                ]
            },
        ]
    }
]
----
