[[Ascon_CXOF128_test_vectors]]
=== Ascon CXOF128 Test Vectors

[[Ascon_CXOF128_tgjs]]
==== Ascon CXOF128 Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for Ascon / CXOF128 / SP800-232 is as follows:

[[Ascon_CXOF128_vs_tg_table]]
.Ascon CXOF128 Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| tests | Array of individual test vector JSON objects, which are defined in <<Ascon_CXOF128_tvjs>> | array
|===

[[Ascon_CXOF128_tvjs]]
==== Ascon CXOF128 Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each Ascon / CXOF128 / FIPS205 test vector.

[[Ascon_CXOF128_vs_tc_table]]
.Ascon CXOF128 Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| msg | Message value | hex
| len | Length of message in bits | integer
| outLen | Length of the digest in bits | integer
| cs | Customization string value | hex
| csLen | Length of the customization string in bits | integer
|===

The following is an example JSON object sent from the server to the client for Ascon / CXOF128 / FIPS205. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 42,
        "algorithm": "Ascon",
        "mode": "CXOF128",
        "revision": "SP800-232",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "tests": [
                    {
                    "tcId": 3,
                    "msg": "380F97464AB9E035024C9B5F8D1AF3D0763BE9A7FB795B0FAE6EF5455249E93A4807D046F9BA97916E7EF9639483F4308BC8CAD3E385AEBEB38797DBC49BE2B9636017854AACD7BCA458397D80F87A2B7AC4B98A7E1657C25811937222BBCDD39B3F00346C6EE6DFF10E2F8A4C313E3A",
                    "len": 895,
                    "outLen": 26524,
                    "cs": "0C6C61FFE1573A4D09542C",
                    "csLen": 88
                    }
                ]
            }
        ]
    }
]
----
