[[Ascon_AEAD128_vector_responses]]
=== Ascon AEAD128 Test Vector Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents the results of an ACVP client processing a single test vector. The following table describes the JSON elements for each Ascon / AEAD128 / SP800-232 test vector.

[[Ascon_AEAD128_vs_tr_table]]
.Ascon AEAD128 Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| tag | The computed tag in an encrypt case | hex
| ct | The computed ciphertext in an encrypt case| hex
| testPassed | Boolean to indicate if a test case should have failed an authentication check in the decrypt case | boolean
| pt | The computed plaintext in a decrypt case | hex
|===

The following is an example JSON test vector response object for Ascon / AEAD128 / SP800-232.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 42,
        "algorithm": "Ascon",
        "mode": "AEAD128",
        "revision": "SP800-232",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 1,
                "tests": [
                    {
                        "tcId": 1,
                        "tag": "E2D95B2EF1A1E75AF11EF398CD5BE0E8",
                        "ct": "BF6CEC4E476E0CBC47287ED9B07847785D6096332CE2D249D5A0455E3BEB24C92183609FD1A0AB77F6C2730E0A85ADEC"
                    },
                ]
            },
            {
                "tgId": 2,
                "tests": [
                    {
                        "tcId": 61,
                        "tag": "3616EB39EE11827740EBB60E4A936CC8",
                        "ct": "195CCB04AC6232B400"
                    },
                ]
            },
            {
                "tgId": 3,
                "tests": [
                    {
                        "tcId": 124,
                        "testPassed": true,
                        "pt": "66348919F866C983AAE911B3F556524216672E6A"
                    },
                    {
                        "tcId": 125,
                        "testPassed": false
                    },
                ]
            },
            {
                "tgId": 4,
                "tests": [
                    {
                        "tcId": 191,
                        "testPassed": true,
                        "pt": "9ED0960B1BFDDA16"
                    },
                    {
                        "tcId": 192,
                        "testPassed": false
                    },
                ]
            },
        ]
    }
]
----
