
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KAS capabilities. This section describes the design of the tests used to validate implementations of KAS algorithms.


=== Test Types
				
There are two test types for KAS testing:
 
* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Agreement with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to perform a successful key agreement; both the server and IUT *MAY* act as party U/V, as well as recipient/provider to key confirmation.

* "VAL" - Validation Test (KAS only). In the VAL test mode, The ACVP server *MUST* generate a complete (from both party U and party V's perspectives) key agreement, and expects the IUT to be able to determine if that agreement is valid. Various types of errors *MUST* be introduced in varying portions of the key agreement process (changed DKM, changed key, changed hash digest, etc), that the IUT *MUST* be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Br2>>. 


[[requirements_covered_kas_ecc]]
==== KAS-IFC Requirements Covered
                        
* SP 800-56Br2 - 5.1 Cryptographic Hash Functions.  SHA1, SHA2, and SHA3 hash functions *SHALL* be available for the various pieces of
KAS/KTS requiring use of a hash function.

* SP 800-56Br2 - 5.2 Message Authentication Code (MAC) Algorithms.  AES-CMAC, HMAC, and KMAC algorithms *SHALL* be available for testing
under KDFs and KC as the specification states.

* SP 800-56Br2 - 5.3 Random Bit Generators.  Though random values are used, the testing of the construction of those random values
*SHALL NOT* be in scope of ACVP testing.

* SP 800-56Br2 - 5.4 Nonces.  Though nonces are used, the testing of the construction of those nonces *SHALL NOT* be in scope of ACVP
testing.

* SP 800-56Br2 - 5.5 Key-Derivation Methods for Key-Establishment Schemes.  The ACVP server *SHALL* make various KDFs available for
testing.  The KDFs covered under ACVP server testing *SHALL* include the KDFs specified in SP800-56B, SP800-56C, SP800-108, and
SP800-135 (where applicable).

* SP 800-56Br2 - 5.6 KeyConfirmation.  The ACVP server *SHALL* support key confirmation for applicable KAS and KTS schemes.

* SP 800-56Br2 - 6.2 Criteria for RSA Key Pairs for Key Establishment.  The ACVP server *SHALL* support the three key generation methods of "basic", "prime factor", and "CRT".

* SP 800-56Br2 - 6.3 RSA Key-Pair Generators.  The ACVP server *SHALL* utilize IUT provided RSA public keys, and generate key pairs to
accomodate testing.  The ACVP server *SHALL* support both fixed and random public exponents.

* SP 800-56Br2 - 7 Primitives and Operations.  All primitives (save the previously mentioned RBG) *SHALL* be in the scope of the ACVP
server testing.  There are several situations where errors *MAY* be injected into varying portions of inputs for these primitives, the
IUT is expected to be able to detect these errors.

* SP 800-56Br2 - 8 Key-Agreement Schemes.  The ACVP server *SHALL* support testing for all KAS schemes specified in the SP800-56b
document.

* SP 800-56Br2 - 9 Key-Transport Schemes.  The ACVP server *SHALL* support testing for all KTS schemes specified in the SP800-56b
document.

* SP 800-56Br2 - 10 Implementation Validation.  The ACVP server *SHALL* support the testing of the specification described in this
section.

* SP 800-56Cr1 - 4 One-Step Key Derivation.  One-Step Key Derivation testing *SHALL* be supported by the ACVP server.  FixedInfo
construction is covered within the ACVP specification, and can be tailored to the IUTs needs.  ASN.1 format of fixedInfo
construction (currently) is *NOT* supported.

* SP 800-56Cr1 - 5 Two-Step Key Derivation.  Two-Step Key Derivation testing *SHALL* be supported by the ACVP server.  FixedInfo
construction is covered within the ACVP specification, and can be tailored to the IUTs needs.  ASN.1 format of fixedInfo
construction (currently) is *NOT* supported.

* SP 800-56Cr1 - 6 Application-Specific Key-Derivation Methods.  Several additional from SP800-135 KDFs *SHALL* be available for
testing with the ACVP server.

* SP 800-108 - 4 Pseudorandom Function (PRF).  All iterations of the KDF described in SP800-108 use a separate PRF.  All
implementations of the PRF *SHALL* be available for testing through the ACVP server generated tests.

* SP 800-108 - 5 Key Derivation Functions (KDF).  The three implementations of KDFs in SP800-108 *SHALL* be available for
testing through the ACVP Server.

[[requirements_not_covered_kas_ecc]]
==== KAS-IFC Requirements Not Covered
 
* SP 800-56Br2 - 5.3 Random Bit Generators.  Though random values are used, the testing of the construction of those random values
*SHALL NOT* be in scope of ACVP testing.

* SP 800-56Br2 - 5.4 Nonces.  Though nonces are used, the testing of the construction of those nonces *SHALL NOT* be in scope of ACVP
testing.

* SP 800-56Br2 - 5.5.2.1.2 The ASN.1 Format for FixedInfo.  The ACVP server (currently) *SHALL NOT* support the testing of this format of
fixed info.

* SP 800-56Br2 - 6.1 (RSA Key Pairs) General Requirements.  Testing for unauthorized modification of key information and other
protections *SHALL NOT* be within scope of ACVP testing.

* SP 800-56Br2 - 6.3 RSA Key-Pair Generators.  The ACVP server *SHALL* utilize IUT provided RSA public keys, and generate key pairs to
accomodate testing, though the key pair generation process itself's testing *SHALL NOT* be in scope of testing covered under
this document.

* SP 800-56Br2 - 6.3 RSA Key-Pair Generators.  Though key pairs are used and generated for testing, the key pair generation process
itself's testing *SHALL NOT* be in scope of testing covered under this document.

* SP 800-56Br2 - 6.4 Required Assurances.  Assurances of key pair validity *SHALL NOT* be within scope of testing under this document
testing.

* SP 800-56Br2 - 7 Primitives and Operations.  The RBG *SHALL* be used, but testing of the RBG's validity *SHALL NOT* be within the
scope of testing.

* SP 800-56Br2 - 8 Key-Agreement Schemes.  The ASN.1 format of FixedInfo *SHALL NOT* be in the scope of ACVP testing.

* SP 800-56Br2 - 10 Rationale for Selecting a Specific Scheme.  There is no testing associated with the IUT's choice of selecting
a specific scheme.

* SP 800-56Br2 - 11 Key Recovery.  Key Recovery *SHALL NOT* be within the scope of ACVP testing.

* SP 800-56Cr1 - 4 One-Step Key Derivation.  ASN.1 format of fixedInfo construction (currently) is *NOT* supported.

* SP 800-56Cr1 - 5 Two-Step Key Derivation.  ASN.1 format of fixedInfo construction (currently) is *NOT* supported.

* SP 800-56Cr1 - 7 Selecting Hash Functions and MAC Algorithms.  The process that goes into the selection of Hash functions and MAC
algorithms *SHALL NOT* be in scope of ACVP testing, though the ACVP server *SHALL* support all indicated Hash and MAC functions.

* SP 800-56Cr1 - 7 Selecting Hash Functions and MAC Algorithms.  The process that goes into the selection of Hash functions and MAC
algorithms *SHALL NOT* be in scope of ACVP testing, though the ACVP server *SHALL* support all indicated Hash and MAC functions.
    