[[XMSS_sigGen_test_vectors]]
=== XMSS sigGen Test Vectors

[[XMSS_sigGen_tgjs]]
==== XMSS sigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for XMSS / sigGen / SP800-208 is as follows:

[[XMSS_sigGen_vs_tg_table]]
.XMSS sigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| xmssMode | The XMSS parameter set used | string
| tests | Array of individual test vector JSON objects, which are defined in <<XMSS_sigGen_tvjs>> | array
|===

[[XMSS_sigGen_tvjs]]
==== XMSS sigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each XMSS test vector.

[[XMSS_sigGen_vs_tc_table]]
.XMSS sigGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
| messageLength | The bitlength of the message to sign | integer
|===

The following is an example JSON object sent from the server to the client for XMSS / sigGen / SP800-208.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "XMSS",
        "mode": "sigGen",
        "revision": "SP800-208",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "xmssMode": "XMSS-SHA2_10_256",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "2C4719...",
                        "messageLength": 32
                    },
                    {
                        "tcId": 2,
                        "message": "4F0E7D...",
                        "messageLength": 1024
                    }
                ]
            }
        ]
    }
]
----
