[[XMSS_sigVer_test_vectors]]
=== XMSS sigVer Test Vectors

[[XMSS_sigVer_tgjs]]
==== XMSS sigVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for XMSS / sigVer / SP800-208 is as follows:

[[XMSS_sigVer_vs_tg_table]]
.XMSS sigVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| xmssMode | The XMSS parameter set used | string
| publicKey | The public key of the XMSS tree, encoded as OID \|\| root \|\| SEED | hex
| tests | Array of individual test vector JSON objects, which are defined in <<XMSS_sigVer_tvjs>> | array
|===

[[XMSS_sigVer_tvjs]]
==== XMSS sigVer Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each XMSS test vector.

[[XMSS_sigVer_vs_tc_table]]
.XMSS sigVer Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to verify with the signature | hex
| messageLength | The bitlength of the message used to generate the signature | integer
| signature | The signature to verify | hex
|===

The following is an example JSON object sent from the server to the client for XMSS / sigVer / SP800-208.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "XMSS",
        "mode": "sigVer",
        "revision": "SP800-208",
        "isSample": false,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "xmssMode": "XMSS-SHA2_10_256",
                "publicKey": "000000019D898033E37AF48E6A116F8B15651CC26773467007AD19375D38C23C690C3483404142434445464748494A4B4C4D4E4F505152535455565758595A5B5C5D5E5F",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "4F0D7...",
                        "messageLength": 1024,
                        "signature": "000002008FF0300BE485DEA7E5AE2C56080302FEBC91B41318C504F895BAAB0B068968F2..."
                    },
                    {
                        "tcId": 2,
                        "message": "84793...",
                        "messageLength": 65536,
                        "signature": "0000017C4A1B33..."
                    }
                ]
            }
        ]
    }
]
----
