[[XMSS_sigGen_vector_responses]]
=== XMSS sigGen Test Vector Responses

The test groups for XMSS / sigGen / SP800-208 contain public key properties. The groups can be described using the following table.

[[XMSS_sigGen_group_table]]
.XMSS sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| publicKey | The public key of the tree the IUT used, encoded as OID \|\| root \|\| SEED | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each XMSS / sigGen / SP800-208 test vector.

[[XMSS_sigGen_vs_tr_table]]
.XMSS sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| signature | The generated signature | hex
|===

The following is an example JSON test vector response object for XMSS / sigGen / SP800-208.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "publicKey": "000000019D898033E37AF48E6A116F8B15651CC2...",
                "tests": [
                    {
                        "tcId": 1,
                        "signature": "000000078A2C41B7D2..."
                    }
                ]
            },
            {
                "tgId": 2,
                "publicKey": "0000000D51BA80F2B84E217D93C1A6E48D...",
                "tests": [
                    {
                        "tcId": 2,
                        "signature": "0000001F40E2C9A17B..."
                    }
                ]
            }
        ]
    }
]
----
