
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KAS capabilities. This section describes the design of the tests used to validate implementations of KAS algorithms. 

=== Test Types
				
There are two test types for KAS testing:
 
* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Agreement with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to perform a successful key agreement; both the server and IUT *MAY* act as party U/V, as well as recipient/provider to key confirmation.

* "VAL" - Validation Test. In the VAL test mode, The ACVP server *MUST* generate a complete (from both party U and party V's perspectives) key agreement, and expects the IUT to be able to determine if that agreement is valid. Various types of errors *MUST* be introduced in varying portions of the key agreement process (changed DKM, changed key, changed hash digest, etc), that the IUT *MUST* be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Ar3>>. 

[[requirements_covered_kas_ffc]]
==== KAS-FFC Requirements Covered
                        
* SP 800-56Ar3 - 5.1 Cryptographic Hash Functions.  SHA1, SHA2, and SHA3 hash functions *SHALL* be available for the various pieces of KAS requiring use of a hash function; such as approved MACs and OneStep KDF.

* SP 800-56Ar3 - 5.2 Message Authentication Code (MAC) Algorithms.  AES-CMAC, HMAC, and KMAC algorithms *SHALL* be available for testing under KDFs and KC as the specification states.

* SP 800-56Ar3 - 5.3 Random Number Generation.  Though random values are used, the testing of the construction of those random values *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 - 5.4 Nonces.  Though nonces are used, the testing of the construction of those nonces *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 - 5.5 Domain Parameters.  Domain Parameters *SHALL* be used in the testing of KAS as per the specification, though the generation of those parameters is outside the scope of testing.

* SP 800-56Ar3 - 5.6 Key-Pair Generation.  Each KAS scheme from one or both parties utilizes a key pair for arriving at a shared secret, and deriving a key.  Though a key pair(s) are utilized in ACVP testing, the testing of the generation of said key pairs is outside the scope of this testing.

* SP 800-56Ar3 - 5.7 DLC Primitives.  Diffie Hellman and MQV *SHALL* be tested under their respective KAS schemes.

* SP 800-56Ar3 - 5.8 Key-Derivation Methods for Key-Establishment Schemes.  The ACVP server *SHALL* make various KDFs available for testing.  The KDFs covered under ACVP server testing *SHALL* include the KDFs specified in SP800-56B, SP800-56C, SP800-108, and SP800-135 (where applicable).

* SP 800-56Ar3 - 5.9 KeyConfirmation.  The ACVP server *SHALL* support key confirmation for applicable KAS and KTS schemes.

* SP 800-56Ar3 - 6 Key Agreement Schemes. The ACVP server *SHALL* support testing for all KAS schemes specified in the SP800-56Ar3 document.	

* SP 800-56Cr1 - 4 One-Step Key Derivation.  One-Step Key Derivation testing *SHALL* be supported by the ACVP server.  FixedInfo construction is covered within the ACVP specification, and can be tailored to the IUTs needs.  ASN.1 format of fixedInfo construction (currently) is NOT supported.

* SP 800-56Cr1 - 5 Two-Step Key Derivation.  Two-Step Key Derivation testing *SHALL* be supported by the ACVP server.  FixedInfo construction is covered within the ACVP specification, and can be tailored to the IUTs needs.  ASN.1 format of fixedInfo construction (currently) is NOT supported.

* SP 800-108 - 4 Pseudorandom Function (PRF).  All iterations of the KDF described in SP800-108 use a separate PRF.  All
implementations of the PRF *SHALL* be available for testing through the ACVP server generated tests.

* SP 800-108 - 5 Key Derivation Functions (KDF).  The three implementations of KDFs in SP800-108 *SHALL* be available for testing through the ACVP Server.

[[requirements_not_covered_kas_ffc]]
==== KAS-FFC Requirements Not Covered
 
* SP 800-56Ar3 - 4.3 DLC-based Key-Transport Process.  KeyWrapping is not incorporated into ACVP testing.

* SP 800-56Ar3 - 5.3 Random Number Generation.  Though random values are used, the testing of the construction of those random values *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 - 5.4 Nonces.  Though nonces are used, the testing of the construction of those nonces *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 - 5.5 Domain Parameters.  Domain Parameters *SHALL* be used in the testing of KAS as per the specification, though the generation of those parameters is outside the scope of testing. 

* SP 800-56Ar3 - 5.6 Key-Pair Generation.  Each KAS scheme from one or both parties utilizes a key pair for arriving at a shared secret, and deriving a key.  Though a key pair(s) are utilized in ACVP testing, the testing of the generation of said key pairs is outside the scope of this testing.

* SP 800-56Ar3 - 5.6.2 Required Assurances.  IUT assurance testing is outside the scope of ACVP testing.

* SP 800-56Ar3 - 5.6.2 Key Pair Management.  Testing the IUT's management of Key Pairs is outside the scope of ACVP testing.

* SP 800-56Ar3 - 5.8.1.2 The ASN.1 Format for FixedInfo.  The ACVP server (currently) *SHALL NOT* support the testing of this format of fixed info.

* SP 800-56Ar3 - 7 Rationale for Selecting a Specific Scheme.  There is no testing associated with the IUT's choice of selecting a specific scheme.

* SP 800-56Ar3 - 8 Key Recovery.  Key Recovery *SHALL NOT* be within the scope of ACVP testing.

* SP 800-56Cr1 - 4 One-Step Key Derivation.  ASN.1 format of fixedInfo construction (currently) is NOT supported.

* SP 800-56Cr1 - 5 Two-Step Key Derivation.  ASN.1 format of fixedInfo construction (currently) is NOT supported.

* SP 800-56Cr1 - 7 Selecting Hash Functions and MAC Algorithms.  The process that goes into the selection of Hash functions and MAC algorithms *SHALL NOT* be in scope of ACVP testing, though the ACVP server *SHALL* support all indicated Hash and MAC functions.

* SP 800-56Cr1 - 7 Selecting Hash Functions and MAC Algorithms.  The process that goes into the selection of Hash functions and MAC algorithms *SHALL NOT* be in scope of ACVP testing, though the ACVP server *SHALL* support all indicated Hash and MAC functions.