[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC3526,RFC 3526]]]
* [[[RFC7919,RFC 7919]]]
* [[[RFC7991,RFC 7991]]]
* [[[RFC8174,RFC 8174]]]

* [[[FIPS186-4,NIST FIPS 186-4]]]
* [[[SP800-108,NIST SP 800-108]]]
* [[[SP800-56Ar3,NIST SP 800-56A Rev. 3]]]
* [[[SP800-56Cr1,NIST SP 800-56C Rev. 1]]]


[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: R.
contributor.person.name.surname:: Hammett
contributor.person.affiliation.organization.name:: HII
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01
