[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the specified SafePrimes algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of SafePrimes capabilities. This section describes the design of the tests used to validate implementations of the SafePrimes algorithms.

=== Test Types

* SafePrimes / keyGen / 1.0 "AFT" - Algorithm Functional Test. The IUT is *REQUIRED* for each test case provided, to generate a key pair based on a SafePrime group. This information is then communicated to the ACVP server and validated.

* SafePrimes / keyVer / 1.0 "AFT" - Algorithm Functional Test. The ACVP server generates a series of keys to communicate to the IUT. The IUT is *REQUIRED* to determine the validity of the given the key pair, and safe prime group.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Ar3>>, <<RFC3526>>, and <<RFC7919>>.

[[safeprime-coverage]]
==== SafePrime Requirements Covered

* SP800-56Ar3 - Section 5.6.1.1.1 Using the Approved Safe-Prime Groups. This ACVP server specification makes testing available/validatable for use in Safe-Prime Groups key generation for KAS-FFC as specified in <<SP800-56Ar3>>.
* RFC3526 - All safe prime groups defined in this document are made available for testing via the ACVP server.
* RFC7919 - All safe prime groups defined in this document are made available for testing via the ACVP server.

[[safeprime-not-coverage]]
==== SafePrime Requirements Not Covered

N/A
