
[[safe-prime-capabilities]]
=== SafePrime Prerequisites

Each safePrimes / * / * implementation relies on other cryptographic primitives. For example, safePrimes / * / * uses an underlying SHA algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

[[rereqs_table]]
.Required SafePrime Prerequisite Algorithms JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| algorithm | a prerequisite algorithm | string | DRBG, SHA, SHA_OPT2
| valValue | algorithm validation number | string | actual number or "same"
| prereqAlgVal | prerequistie algorithm validation | object with algorithm and valValue properties | see above
| prereqVals | prerequistie algorithm validations | array of prereqAlgVal objects | see above
|===

=== SafePrime Capabilities

Each algorithm capability advertised is a self-contained JSON object using the following values.

[[capabilities_table]]
.SafePrime Capabilities JSON Properties
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | The algorithm under test | string | "safePrimes"
| mode | The SafePrimes mode to be validated | string | "keyGen" or "keyVer"
| revision | The algorithm testing revision to use | string | "1.0"
| prereqVals | Prerequisite algorithm validations | array of prereqAlgVal objects | See <<rereqs_table>>
| safePrimeGroups | Safe prime groups to test with | array of string | Any non-empty subset of {"MODP-2048", "MODP-3072", "MODP-4096", "MODP-6144", "MODP-8192", "ffdhe2048", "ffdhe3072", "ffdhe4096", "ffdhe6144", "ffdhe8192"}
|===

=== Safe Prime Example Registrations

A safePrime / keyGen / 1.0 registration looks like the following

[source, json]
----
{
	"algorithm": "safePrimes",
	"mode": "keyGen",
	"revision": "1.0",
	"prereqVals": [{
		"algorithm": "DRBG",
		"valValue": "123456"
	}],
	"safePrimeGroups": [
		"ffdhe2048",
		"MODP-2048"
	]
}
----

A safePrime / keyVer / 1.0 registration looks like the following

[source, json]
----
{
    "algorithm": "safePrimes",
    "mode": "keyVer",
    "revision": "1.0",
    "prereqVals": [{
        "algorithm": "DRBG",
        "valValue": "123456"
    }],
    "safePrimeGroups": [
        "ffdhe2048",
        "MODP-2048"
    ]
}
----
