[[keyGen_test_vectors]]
=== SafePrime keyGen Test Vectors

[[keyGen_tgjs]]
==== SafePrime keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for safePrime / keyGen / 1.0 is as follows:

[[keyGen_vs_tg_table]]
.Safe Prime keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| testType | The test operation performed | string
| safePrimeGroup | The safe prime group that the IUT should use for generating keys | string
| tests | Array of individual test vector JSON objects, which are defined in <<keyGen_tvjs>> | array
|===

[[keyGen_tvjs]]
==== SafePrime keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each safePrime / keyGen / 1.0 test vector.

[[keyGen_vs_tc_table]]
.SafePrime keyGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| deferred | States that the values are generated by the client | boolean
|===

NOTE: The client is responsible for generating a key to be verified by the server.

The following is an example JSON object sent from the server to the client for safePrimes / keyGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "safePrimes",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "safePrimeGroup": "ffdhe2048",
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 1
                    },
                    {
                        "tcId": 2
                    },
                    {
                        "tcId": 3
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "safePrimeGroup": "MODP-2048",
                "tests": [
                    {
                        "tcId": 4
                    },
                    {
                        "tcId": 5
                    },
                    {
                        "tcId": 6
                    }
                ]
            }
        ]
    }
]
----
