[[keyVer_test_vectors]]
=== SafePrime keyVer Test Vectors

[[keyVer_tgjs]]
==== SafePrime keyVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for safePrime / keyVer / 1.0 is as follows:

[[keyVer_vs_tg_table]]
.Safe Prime keyVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| testType | The test operation performed | string
| safePrimeGroup | The safe prime group that the IUT should use for validating keys | string
| tests | Array of individual test vector JSON objects, which are defined in <<keyVer_tvjs>> | array
|===

[[keyVer_tvjs]]
==== SafePrime keyVer Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each safePrime / keyVer / 1.0 test vector.

[[keyVer_vs_tc_table]]
.SafePrime keyVer Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| x | The private key component X | hex
| y | The public key component Y | hex
|===

The following is an example JSON object sent from the server to the client for safePrimes / keyVer / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "safePrimes",
        "mode": "keyVer",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "safePrimeGroup": "ffdhe2048",
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 1,
                        "x": "399C088E4A1E1A03...",
                        "y": "FADA8667E9126779..."
                    },
                    {
                        "tcId": 2,
                        "x": "1DB3138EF400DDA7...",
                        "y": "70AACAB9A69AFE62..."
                    },
                    {
                        "tcId": 3,
                        "x": "099B19789CF2239F...",
                        "y": "C8F7038CB275E50F..."
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "safePrimeGroup": "MODP-2048",
                "tests": [
                    {
                        "tcId": 4,
                        "x": "248091D90CB00F58EF...",
                        "y": "C08BF18980879C066E..."
                    },
                    {
                        "tcId": 5,
                        "x": "74B61CE8B689BAA23B...",
                        "y": "8EE385FFA770C9C9BF..."
                    },
                    {
                        "tcId": 6,
                        "x": "1B73FF75B0A20D99D0...",
                        "y": "4BF4509C0258E8E484..."
                    }
                ]
            }
        ]
    }
]
----
