
[[tgjs]]
== Test Vectors

The ACVP server provides test vectors to the ACVP client, which are then processed and returned to the ACVP server for validation. A typical ACVP validation session would require multiple test vector sets to be downloaded and processed by the ACVP client. Each test vector set represents an individual crypto algorithm, such as SafePrimes / keyVer / 1.0, etc. This section describes the JSON schema for a test vector set used with Safe Primes crypto algorithms.

The test vector set JSON schema is a multi-level hierarchy that contains meta data for the entire vector set as well as individual test vectors to be processed by the ACVP client. The following table describes the JSON elements at the top level of the hierarchy.

[[rsa_vs_top_table]]
.Safe Primes Vector Set JSON Object
|===
| JSON Value | Description | JSON type

| acvVersion | Protocol version identifier | string
| vsId | Unique numeric identifier for the vector set | integer
| algorithm | The algorithm used for the test vectors | string
| mode | The mode used for the test vectors | string
| revision | The algorithm testing revision to use | string
| testGroups | Array of test group JSON objects, which are defined in <<keyGen_test_vectors>>, or <<keyVer_test_vectors>> depending on the algorithm | array
|===
