[[keyGen_vector_responses]]
=== Safe Primes keyGen Test Vector Responses

The test groups for SafePrimes / keyGen / 1.0 contain public key properties. The groups can be described using the following table.

[[keyGen_group_table]]
.Safe Primes keyGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each safePrimes / keyGen / 1.0 test vector.

[[keyGen_vs_tr_table]]
.Safe Primes keyGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| x | The private key component X | hex
| y | The public key component Y | hex
|===

The following is an example JSON test vector response object for safePrimes / keyGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "testGroups": [
          {
            "tgId": 1,
            "tests": [
              {
                "tcId": 1,
                "x": "6316A9021906CB3F9F6...",
                "y": "8520DE9F113D659F708..."
              }
            ]
          }
        ]
    }
]
----
