
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate {spec-algorithm} implementations.

=== Test Types

* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT SHALL act as a party in the Key Agreement with the ACVP server. The server SHALL generate and provide all necessary information for the IUT to compute a shared secret `z`; both the server and IUT MAY act as party U/V.
* "VAL" - Validation test. In the VAL test mode, The ACVP server MUST generate a complete (from both party U and party V's perspectives) shared secret `z`, and expects the IUT to be able to determine if that shared secret is valid. Various types of conditions/errors MUST be introduced in varying portions of the key agreement process (changed Z, Z with leading zero nibble, etc), that the IUT MUST be able to detect and report on.

=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to SP800-56Ar3 KAS Shared Secret Computation (SSC).

==== Requirements Covered

* SP 800-56Ar3 - 4.1 Key Establishment Preparations. The ACVP server is responsible for generating domain parameters as per the IUT's capability registration.
* SP 800-56Ar3 - 4.2 Key-Agreement Process. Both the ACVP server and IUT participate in the shared secret computation. The server and IUT can both take the roles of party U/V, and as such the "performer" of steps depicted in "Figure 2: Key Agreement process" can vary.
* SP 800-56Ar3 - 5.6 Domain Parameters. Domain Parameter Generation SHALL be performed solely from the ACVP server, with constraints from the IUTs capabilities registration. The same set of domain parameters SHALL generate all keypairs (party U/V, static/ephemeral) for a single test case.
* SP 800-56Ar3 - 5.6 Key-Pair Generation. While Key-Pairs are used in each KAS scheme, the generation of said key-pairs is out of scope for KAS testing.
* SP 800-56Ar3 - 4.3 DLC-based Key-Transport Process / 5.7 DLC Primitives. Depending on the scheme used, either Diffie Hellman or MQV SHALL be used to negotiate a shared secret of z. Testing and validation of such key exchanges is covered under their respective schemes.
* SP 800-56Ar3 - 6 Key Agreement Schemes. All schemes specified in referenced document are supported for validation with the ACVP server.

==== Requirements Not Covered

* KAS SSC testing only covers testing of SP800-56Ar3 through the computation of a shared secret `z`.  Additional functions of KAS as a whole such as KDF, KC, etc. MAY be covered within the scope of the full KAS testing; please see that document for further details.
