
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response Properties
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Test Group Response Properties
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Response Properties
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| testPassed | Was the provided `z` or `hashZ` valid? Only valid for the "VAL" test type. | boolean
| staticPublicIutX | The IUT static public key X. Optional depending on scheme and test type. | hex
| staticPublicIutY | The IUT static public key Y. Optional depending on scheme and test type. | hex
| ephemeralPublicIutX | The IUT ephemeral public key X. Optional depending on scheme and test type. | hex
| ephemeralPublicIutY | The IUT ephemeral public key Y. Optional depending on scheme and test type. | hex
| z | The shared secret `z`.  Only included for "AFT" test type when a `hashFunctionZ` is not in use. | hex
| hashZ | The shared secret `z` run through a hash function.  Only included for "AFT" test type when a `hashFunctionZ` is in use. | hex
|===

Here is an abbreviated example of the response

.Example Response JSON
[source,json]
----
{
  "vsId": 1,
  "algorithm": "KAS-ECC-SSC",
  "revision": "Sp800-56Ar3",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "staticPublicIutX": "01ED7A443C08F1C9BDE87DB3658C10CAA4056E0B333CDEC2D65E2C15A982",
          "staticPublicIutY": "01F81685DFB8444F6EF21D98ECCFA18E368C278DEA95C08CC9D2C68BB701",
          "ephemeralPublicIutX": "001ACA6CE2243C5D3A43FFD0B4AC46997519D53AE7B0D9A5D235A5E1361B",
          "ephemeralPublicIutY": "013A61A2174371DA0DAC4CE323D90F118717B2F7BC58B35F3AEAF22413B2",
          "tcId": 1,
          "z": "0157C230E9CF02BFD5BC8D5113E10C17C9E06187413950120B0BD617BB9B"
        },
        {
          "staticPublicIutX": "00CE26A621F2E6D1B609A378F1E808BF56B6C3693B89624E6913F55B80AF",
          "staticPublicIutY": "01402453E700A4CF284403E2F4137EDBBE82D0462E7EA0AFEC57C65D328E",
          "ephemeralPublicIutX": "01B5A9002B1EDAE4F318068E60F35550C7EDFBA715A5CE3DDAD46ECF156E",
          "ephemeralPublicIutY": "011EBCC4657C8B89243A21984110603BB259B25DC7728414EC53ECE01806",
          "tcId": 2,
          "z": "00A3410290DC37BD32169B3817222D90D4CD644A0EEE44BA9F32EBE71761"
        }
      ]
    },
    {
      "tgId": 2,
      "tests": [
        {
          "tcId": 6,
          "testPassed": true
        },
        {
          "tcId": 7,
          "testPassed": true
        },
        {
          "tcId": 8,
          "testPassed": false
        },
        {
          "tcId": 9,
          "testPassed": true
        },
        {
          "tcId": 10,
          "testPassed": true
        }
      ]
    }
  ]
}
----
