
[bibliography]
== References

* [[[RFC2119,RFC 2119]]]
* [[[RFC8174,RFC 8174]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
    id::: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01

[%bibitem]
=== SP800-185 SHA-3 Derived Functions: cSHAKE, KMAC, TupleHash and ParallelHash
id:: SP800-185
docid::
    id::: SP800-185
link::
link.type:: src
link.content:: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf
contributor::
contributor.role:: author
contributor.person.name.initial:: S.
contributor.person.name.surname:: Chang
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: J.
contributor.person.name.surname:: Kelsey
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: R.
contributor.person.name.surname:: Perlner
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2016-12
