
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified ML-KEM algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of ML-KEM capabilities. This section describes the design of the tests used to validate implementations of the ML-KEM algorithms.

* ML-KEM / keyGen / * "AFT" - Algorithm Functional Test. The IUT is *REQUIRED* for each test case provided, to generate a key pair from a provided seed. The key pair is communicated to the ACVP server and validated. This tests the implementation of Algorithm 16 ML-KEM.KeyGen_internal() from <<FIPS203>> Section 6.1.

* ML-KEM / encapDecap / * "AFT" - Algorithm Functional Test. The server will generate a random `m` and encapsulation key `ek`. The IUT *SHALL* generate the corresponding shared secret `k` and ciphertext `c`. This tests the implementation of Algorithm 17 ML-KEM.Encaps_internal() from <<FIPS203>> Section 6.2.

* ML-KEM / encapDecap / * "VAL" - Validation Test. There are several variations for this test type depending on the function being tested. 
    ** For decapsulation, the server will generate a decapsulation key `dk` and a potentially valid or invalid ciphertext `c`. The IUT *SHALL* generate the corresponding shared secret `k` whether the `k` is provided from the valid decapsulation route or from the implicit rejection present in <<FIPS203>> Algorithm 17. This tests the implementation of Algorithm 18 ML-KEM.Decaps_internal() from <<FIPS203>> Section 6.3.
    ** For the encapsulation key check, the server will generate a potentially valid or invalid encapsulation key `ek`. The IUT *SHALL* determine if the provided `ek` is valid based on <<FIPS203>> Section 7.2. 
    ** For the decapsulation key check, the server will generate a potentially valid or invalid decapsulation key `dk`. The IUT *SHALL* determine if the provided `dk` is valid based on <<FIPS203>> Section 7.3. 

The decapsulation modifications are: 

* "valid decapsulation" - No modification to the ciphertext is made and the decapsulation will follow the valid path to generate a shared key `k`.
* "modified ciphertext" - The ciphertext is randomly modified and the decapsulation will follow the implicit rejection path to geenrate a shared key `k`.

The encapsulation key check modifications are:

* "valid encapsulation key" - No modification to the encapsulation key is made. The encapsulation key will pass the encapsulation key check.
* "noisy linear system values too large" - The encapsulation key is modified such that a value in the noisy linear system is encoded into the key as a value greater than Q. This encapsulation key will not pass the encapsulation key check. 

The decapsulation key check modifications are:

* "valid decapsulation key" - No modification to the decapsulation key is made. The decapsulation key will pass the decapsulation key check.
* "modified H" - The decapsulation key is modified such that the concatenated values ek || H(ek) will no longer match by modifying H(ek) to be a different value. This decapsulation key will not pass the decapsulation key check. 

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS203>>.

[[requirements_covered]]
==== Requirements Covered

* The tests will ensure conformity and correctness of an implementation of the algorithms supported. 

[[requirements_not_covered]]
==== Requirements Not Covered

* FIPS 203 Section 3.3. Requirements for ML-KEM Implementations. Requirements outlined in this section are not testable by an ACVP server. An ACVP server will not test the zeroization of intermediate values, security strength of the deterministic random bit generators (DRBGs), or incorrect length signatures or public keys.
