[[ML-KEM_encapDecap_test_vectors]]
=== ML-KEM encapDecap Test Vectors

[[ML-KEM_encapDecap_tgjs]]
==== ML-KEM encapDecap Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for ML-KEM / encapDecap / FIPS203 is as follows:

[[ML-KEM_encapDecap_vs_tg_table]]
.ML-KEM encapDecap Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| parameterSet | The ML-KEM parameter set used | string
| function | Whether the tests are running encapsulation or decapsulation | string
| dk | The decapsulation key when `"testType": "VAL"` | hex
| tests | Array of individual test vector JSON objects, which are defined in <<ML-KEM_encapDecap_tvjs>> | array
|===

[[ML-KEM_encapDecap_tvjs]]
==== ML-KEM encapDecap Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-KEM test vector.

[[ML-KEM_encapDecap_vs_tc_table]]
.ML-KEM encapDecap Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| ek | The encapsulation key when `"testType": "AFT"` | hex
| m | The random value used to derive the shared key when `"testType": "AFT"` | hex
| c | The cipher text when `"testType": "VAL"` | hex
|===

The following is an example JSON object sent from the server to the client for ML-KEM / encapDecap / FIPS203.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "ML-KEM",
        "mode": "encapDecap",
        "revision": "FIPS203",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "parameterSet": "ML-KEM-512",
                "function": "encapsulation",
                "tests": [
                    {
                        "tcId": 1,
                        "ek": "75A72D...",
                        "m": "013FD9A..."
                    },
                ]
            },
            {
                "tgId": 2,
                "testType": "VAL",
                "parameterSet": "ML-KEM-512",
                "function": "decapsulation",
                "dk": "DF479939FAA...",
                "tests": [
                    {
                        "tcId": 76,
                        "c": "49D873A9..."
                    }
                ]
            }
        ]
    }
]
----
