[[ML-KEM_keyGen_test_vectors]]
=== ML-KEM keyGen Test Vectors

[[ML-KEM_keyGen_tgjs]]
==== ML-KEM keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for ML-KEM / keyGen / FIPS203 is as follows:

[[ML-KEM_keyGen_vs_tg_table]]
.ML-KEM keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| parameterSet | The ML-KEM parameter set used | string
| tests | Array of individual test vector JSON objects, which are defined in <<ML-KEM_keyGen_tvjs>> | array
|===

[[ML-KEM_keyGen_tvjs]]
==== ML-KEM keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-KEM test vector.

[[ML-KEM_keyGen_vs_tc_table]]
.ML-KEM keyGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| d | The seed d used to generate the key pair | hex
| z | The seed z used to generate the key pair | hex
|===

The following is an example JSON object sent from the server to the client for ML-KEM / keyGen / FIPS203. 

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "ML-KEM",
        "mode": "keyGen",
        "revision": "FIPS203",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "parameterSet": "ML-KEM-512",
                "tests": [
                    {
                        "tcId": 1,
                        "d": "C105DC2...",
                        "z": "AD310AB..."
                    }
                ]
            }
        ]
    }
]
----
