
== Test Vectors

The ACVP server provides test vectors to the ACVP client, which are then processed and returned to the ACVP server for validation. A typical ACVP validation test session would require multiple test vector sets to be downloaded and processed by the ACVP client. Each test vector set represents an individual cryptographic algorithm defined during the capability exchange. This section describes the JSON schema for a test vector set used with {spec-algorithm} algorithms.

The test vector set JSON schema is a multi-level hierarchy that contains meta data for the entire vector set as well as individual test vectors to be processed by the ACVP client. The following table describes the JSON elements at the top level of the hierarchy.

.Top Level Test Vector JSON Elements
|===
| JSON Values | Description | JSON Type

| acvVersion | Protocol version identifier | string
| vsId | Unique numeric vector set identifier | integer
| algorithm | Algorithm defined in the capability exchange | string
| mode | Mode defined in the capability exchange | string
| revision | Protocol test revision selected | string
| testGroups | Array of test group JSON objects. Depending on the algorithm, see <<ML-KEM_keyGen_tgjs>> or <<ML-KEM_encapDecap_tgjs>> | array
|===

An example of this would look like this

[source,json]
----
[
  {
    "acvVersion": <version>
  },
  {
    "vsId": 1,
    "algorithm": "Alg1",
    "mode": "Mode1",
    "revision": "Revision1.0",
    "testGroups": [ ... ]
  }
]
----
