[[ML-KEM_encapDecap_vector_responses]]
=== ML-KEM encapDecap Test Vector Responses

The test groups for ML-KEM / encapDecap / FIPS203 contain public key properties. The groups can be described using the following table.

[[ML-KEM_encapDecap_group_table]]
.ML-KEM encapDecap Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ML-KEM / encapDecap / FIPS203 test vector.

[[ML-KEM_encapDecap_vs_tr_table]]
.ML-KEM encapDecap Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| c | The generated ciphertext only for `"testType": "AFT"` | hex
| k | The generated shared secret | hex
|===

The following is an example JSON test vector response object for ML-KEM / encapDecap / FIPS203.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "tests": [
                    {
                        "tcId": 1,
                        "c": "7DFC404E2...",
                        "k": "5C82A1AB3..."
                    }
                ]
            },
            {
                "tgId": 2,
                "tests": [
                    {
                        "tcId": 76,
                        "k": "87B9103AA..."
                    }
                ]
            }
        ]
    }
]
----
