
[[caps_reg]]
== Overview

ACVP has the following goals:

* To work in situations where the testing system is remote from the cryptographic module, e.g. running as a process on a separate device.
* To enable automated testing that can take place with a minimum of human interaction.
* To enable the testing system to discover the capabilities of the module being tested; that is, the particular algorithms and parameters that the module supports.
* To provide extensibility that can be used to introduce tests for new algorithms, and new tests for existing algorithms.
* To be compatible with emerging automated validation systems wherever possible, especially the FIPS-140 Cryptographic Algorithm Validation Program.
* To provide a standard communication method so that vendors can utilize the same testing service for FIPS-140, 3rd party crypto verification and product FCS readiness testing.

ACVP defines how to communicate a request (to execute a cryptographic operation) to a cryptographic module, and how to communicate the corresponding response (containing the output of that operation) back to a testing system. It defines a transport (based on HTTP or HTTPS  <<RFC7230>>), an JSON message structure(which is negotiated), and a set of message exchanges. Each vector test set corresponds to a single message exchange driven from the client associated with the module under test. ACVP does not define the cryptographic algorithms, nor does it detail the precise conditions for a response to be acceptable. Instead, it references existing specifications for those algorithms, and defines a mapping between the data on the wire and the algorithm testing specification. ACVP does not define detailed conformance criteria, such as those in FIPS-140. Instead, it aims to be independent of particular conformance criteria, so that it can be used in multiple domains with different (even potentially conflicting) conformance criteria. ACVP does not define an interface that can be used to manage or control a cryptographic module.

=== Audience

This document is written to address multiple audiences:

* Crypto module developers who require validation testing
* Crypto module developers who require runtime crypto assessment testing
* Crypto validation organizations who will perform validation testing
* Crypto module customers that desire validation testing results or verifiable artifacts of testing

=== Goals

The goals for this document are to provide a messaging protocol that can be used with existing authentication and communication protocols to provide a way to test crypto modules. The following functions are outside the scope of this document:

* The API to the cryptographic module
* How the tests are generated
* How the results/artifacts are stored or managed
* Authentication used
* Scalability
* Management interface

With that in mind there are several expectations when building a server used as a validation authority. A validation authority *SHALL* use a combination of HTTPS <<RFC7230>>, TLS 1.2 <<RFC5246>> or greater and mutual authentication. Therefore a client that expects to be used with a validation authority *SHALL* have the same requirements. A server, proxy or client developed for the purposes of internal organizational testing only *MAY* choose not to include some of those features.
