
== Security Considerations

It is *RECOMMENDED* that HTTPS and TLS 1.2 or greater be used in order to enforce a secure communication method. Not all environments will have TLS so HTTP with some level of authentication may be the only option.

=== Authentication

It is *RECOMMENDED* that an authentication scheme be used. Typically, a JSON Web Token (JWT) is created by the
server upon successful client authentication and returned to the client to use as an authorization mechanism for accessing the server resources - see <<jwtToken>> below for more information. Depending on the target environment and usage objectives, the authentication can be as weak as basic HTTP authentication or as strong as TLS mutual certificate authentication. Definition of an authentication scheme will not be discussed here, but should be agreed upon between the client and server owning entities including the servers owned by the validation authorities. The <<login>> endpoint will be discussed for the purposes of establishing a test session but how a client is authenticated to the server is not prescribed.
