
[[login]]
== Login

A login endpoint is mentioned throughout the document and although how to authenticate is left up to the server the following description is an example of the login endpoint to establish a session and obtain a <<jwtAuthFlows>>. See <<largeSubmission>> for more information on how to handle data which exceeds the `sizeConstraint` in the event the value of `largeEndpointRequired` is `true`.

* *password* - `string`, a property for providing a password value
* *accessToken* - `string`, a JWT associated with the current user for which renewal of the expiration is desired
* *largeEndpointRequired* - `boolean`, true if the server requires the large endpoint for submissions with a size that exceeds the value found in *sizeConstraint*.
* *sizeConstraint* - `number`, provides the maximum value, in bytes, of a submission not required to use the <<largeSubmission>> or -1 if `largeEndpointRequired` is `false`.

=== Request

There are two forms of a login request. There is the initial form which just provides the authentication
information without any JWT, and there is a renewal login that allows a user to obtain a new JWT containing the
claims from an expired JWT in order to access a resource protected with those claims.

*POST /login* (Initial)

[align=center,alt=,type=]
....
[
  {"acvVersion": <acvp-version>},
  {
 "password": "<password>"
  }
]

....

*POST /login* (Renewal)

[align=center,alt=,type=]
....
[
  {"acvVersion": <acvp-version>},
  {
 "password": "<password>",
 "accessToken": "<jwt value>"
  }
]

....

=== Response

[align=center,alt=,type=]
....
[
  {"acvVersion": <acvp-version>},
    {
        "accessToken": "<jwt value>",
        "largeEndpointRequired": false,
        "sizeConstraint": -1
    }
]

....
