
[[largeSubmission]]
== Large Submission

When clients have a response which exceeds the `sizeConstraint` in <<login>>, this endpoint *MUST* be used to obtain a URI in order to submit the results. The URI *MAY* be a one-time use URI and clients *SHOULD* only attempt to use this URI once regardless of success or failure in submitting. If resubmission is required clients *MUST* re-POST to the /large endpoint in order to obtain the URI to use.

The available properties for large submissions:

* *submissionSize* - `number`, the maximum size in bytes of the desired submission.
* *vectorSetUrl* - `string`, an identifier of the vector set that will be uploaded as a large submission.
* *url* - `string`, a one-time use url value to use for a large submission.
* *accessToken* - `string`, an optional JWT, that if provided, clients *MUST* use when accessing the `url`. If not provided, clients *MUST* use their current `accessToken` when accessing the `url`.

=== Request

*POST /large*

[source,json]
....
[
  {"acvVersion": "{acvp-version}"},
  {
      "submissionSize": 5000000,
      "vectorSetUrl" : "/acvp/v1/testSessions/1/vectorSets/10"
  }
]
....

=== Response

[source,json]
....
[
  {"acvVersion": "{acvp-version}"},
  {
      "url": "https://acvts.authority.org:3954/large/QWERTY123",
      "accessToken" : "<jwt token>"
  }
]
....
