
[[app-reg-ex]]
== JSON Formatting Guidelines

All JSON keywords *SHALL* use lower camelCase format with no underscores or hyphens and use the following characters only a-z, A-Z, 0-9. Keywords SHALL abbreviate common words and phrases wherever possible for brevity.

For example: password length - pwLen plain text length - ptLen

Keywords *SHOULD* be chosen such that they are informative and brief, for example:

[source, json]
----
[ 
    { "acvVersion": "{acvp-version}" }, 
    { "results" : { "disposition" : "incomplete" } } 
]
----

Metadata assigned to the keyword may use any format which best reflects the information being represented including hyphens, underscores alternating case, numbers, etc. However, brevity should be a major consideration, for example:

[source, json]
----
{ 
    "algorithms" : [ 
        { "algorithm" : "ACVP-AES-GCM", "mode" : "modes", "ivGen" : "internal", "ivGenMode" : "8.2.1" }
    ]
}
----

All metadata representing strings or big numbers *SHALL* use double quotes at both ends. Big numbers require conversion from strings to whatever format is used by the DUT. Numerical values of integer size or with decimal points may use quotations if those values are generally used as a string, for example the acvVersion would generally be used in displaying information not in any mathematical operations. Something like keyLen or ptLen values would be better used without quotes to avoid having to convert the string to an integer for use in the code.

[[app-reg-ex2]]
== Error Messages

General or registration errors detected by the server *SHALL* result in an HTML error and description of the problem, for example:

[align=center,alt=,type=]
....

    HTTP response: 400
    "error" : "Incorrectly formatted JSON (51:18):
               expected field name was not provided: inBit"
....

Errors detected by the client *SHOULD* trigger an indication of the operation that failed and a detailed error description. This information can be sent to the clients local logging facility to provide traceability of communication issues, for example:

[align=center,alt=,type=]
....
    ACV Operation: SHA-512
    Error: Unsupported hash algorithm
....
