
== Test Vectors

The ACVP server provides test vectors to the ACVP client, which are then processed by the IUT and returned to the ACVP server for validation. A typical ACVP validation test session *MAY* require multiple test vector sets to be downloaded and processed by the ACVP client. Each test vector set represents an individual cryptographic algorithm and mode defined during the capabilities registration. 

For X-WING, test vector sets are provided for the keyGen and encapDecap modes described in this specification.  This section describes the JSON schema for a test vector set used with {spec-algorithm} algorithms.

.Top level Test Vector JSON Elements
|===
| JSON Values | Description | JSON Type

| acvVersion 
| Protocol version identifier
| string

| vsId
| Unique numeric identifier for the vector set
| integer

| algorithm
| Algorithm defined in the capability exchange
| string

| mode
| Mode defined in the capability exchange
| string

| revision
| Protocol test revision selected
| string

| testGroups
| Array of test group JSON objects, which are defined in <<X-WING_keyGen_tgjs>> and <<X-WING_encapDecap_tgjs>>
| array
|===

An example X-WING test vector set is shown below.

[source,json]
----
[
 {
   "acvVersion": "<version>"
  },
  {
    "vsId": 1,
    "algorithm": "Alg1",
    "mode": "Mode1",
    "revision": "Revision1.0",
    "testgroups": [ "..."]
   }
]
----
