[[X-WING_keyGen_test_vectors]]
=== X-WING keyGen Test Vectors

[[X-WING_keyGen_tgjs]]
==== X-WING keyGen Test Groups JSON Schema

The Test Groups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains metadata that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for X-WING / keyGen / 1.0 is as follows:

[[X-WING_keyGen_vs_tg_table]]
.X-WING keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId
| Numeric identifier for the test group, unique across the entire vector set
| integer

| testType
| The test operation performed
| string

| tests
|Array of individual test vector JSON objects, which are defined in <<X-WING_keyGen_tvjs>>
| array

|===
[[X-WING_keyGen_tvjs]]
==== X-WING keyGen Test Case JSON Schema

[[X-WING_keyGen_vs_tc_table]]
.X-WING keyGen test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId
| Numeric identifier for the test case, unique across the entire vector set
| integer

| seed
| THe 32-byte decapsulation key used to deterministically generate the X-WING key pair
| hex
|===

The following is an example JSON object sent from the server to the client for X-WING/ keyGen / 1.0

.Prompt JSON
[source,json]
----
[
 {
   "acvVersion": "<acvp-version>"
  },
  {
     "vsId": 1564,
     "algorithm": "X-WING",
      "mode" : "keyGen",
      "revision": "1.0",
      "testGroups": [
    {
       "tgId": 1,
       "testType": "AFT",
        "tests": [
      {
        "tcId": 1,
         "seed": "0123456789ABCDEF..."
       }
     ]
    }
   ]
  }
]
----
