[[X-WING_encapDecap_test_vectors]]
=== X-WING encapDecap Test Vectors

[[X-WING_encapDecap_tgjs]]
==== X-WING encapDecap test groups JSON Schema

The test groups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The test group JSON object contains metadata that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the test group JSON object.

The test group for X-WING / encapDecap / 1.0 is as follows:

[[X-WING_encapDecap_vs_tg_table]]
X-WING encapDecap Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId
| Numeric identifier for the test group, unique across the entire vector set
| integer

| testType
| The test operation performed
| string

| tests
|Array of individual test vector JSON objects, which are defined in <<X-WING_encapDecap_tvjs>>
| array
|===

[[X-WING_encapDecap_tvjs]]
==== X-WING encapDecap Test Case JSON Schema

Each test group contains an array of one or more test cases.  Each test case is a JSON object that represents a single test vector to be processed by the CVP client.  The following table describes the JSON elements for each X-WING test vector.

[[X-WING_encapDecap_vs_tc_table]]
X-WING encapDecap test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId
| Numeric identifier for the test case, unique across the entire vector set
| integer

| pk
| The 1216-byte encapsulation key when the function is encapsulation
| hex

| eseed
| 64-byte deterministic encapsulation seed when the function is encapsulation
| hex

| sk
| The 32-byte decapsulation key when the function is decapsulation
| hex

| ct
| The 1120-byte ciphertext when the function is decapsulation
| hex
|===

The following is an example JSON object sent from the server to the client for X-WING/ encapDecap / 1.0

[source,json]
----
[
 {
   "acvVersion": "<acvp-version>"
  },
  {
    "vsId": 0,
     "algorithm": "X-WING",
     "mode" : "encapDecap",
     "revision": "1.0",
     "testGroups": [
    {
       "tgId": 1,
       "testTypes": "AFT",
       "function": "encapsulation",
        "tests": [
      {
         "tcId": 1,
         "pk": "0123456789ABCDEF...",
         "eseed": "01A12B34C..."
       }
     ]
    },
    {
      "tgId": 2,
       "testType": "VAL",
       "function": "decapsulation",
       "tests": [
         {
           "tcId": 2,
           "sk":  "012345ABCDEF...",
           "ct":  "0123456ABCDEFG..."
          }
        ]
      }
    ]
  }
]
----

