[[X-WING_encapDecap_vector_responses]]
=== X-WING encapDecap Test Vector Responses

The test groups for X-WING / encapDecap / 1.0 contain th responses produced by the IUT for the requested encapsulation or decapsulation operation.  The groups can be described using the following table.

[[X-WING_encapDecap_group_table]]
.X-WING encapDecap Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId 
| The test group identifier 
| integer

| tests 
| The individual test cases for the group 
| array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each X-WING / encapDecap / 1.0.

[[X-WING_encapDecap_vs_tr_table]]
.X-WING encapDecap Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId 
| The test case identifier 
| integer

| ct
| The generated 1120-byte ciphertext when function is "encapsulation" 
| hex

| ss 
| The generated 32-byte shared secret
| hex
|===

The following is an example JSON test vector response object for X-WING / encapDecap / 1.0.

[source, json]
----
[
    {
        "acvVersion": "<acvp-version>"
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "tests": [
                    {
                        "tcId": 1,
                        "ct": "7DFC404E2...",
                        "ss": "5C82A1AB3..."
                    }
                ]
            },
            {
                "tgId": 2,
                "tests": [
                    {
                        "tcId": 76,
                        "ss": "87B9103AA..."
                    }
                ]
            }
        ]
    }
]  

----







