
[bibliography]
== Normative References

* [[[XWING, repo:(IETF D.connolly-cfrg-xwing-kem)]]], IETF Internet-Draft: X-Wing Hybrid Key Encapsulation Mechanism
* [[[RFC2119,RFC 2119]]]
* [[[RFC8174,RFC 8174]]]
* [[[RFC9180, RFC 9180]]]
* [[[RFC7748,IETF(RFC 7748)]]]
* [[[FIPS203,NIST FIPS 203]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01