
[[test_types_coverage]]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the MAC algorithms in order to assess the correctness and robustness of the implementation. A typical ACVP validation session would require multiple tests to be performed for every supported cryptographic algorithm, such as CMAC-AES, CMAC-TDES, HMAC-SHA-1, HMAC-SHA2-256, etc. This section describes the design of the tests used to validate implementations of MAC algorithms.

[[test_types]]
=== Test Types

There is a single test type for MACs (broken into subsections for CMACs). the single test type, algorithm functional test (AFT) can be described as follows:

* "AFT" - Algorithm Function Test. The IUT processes all of HMAC, GMAC and the "gen" direction of CMAC by running the randomly chosen key and message data (with constraints as per the IUT's capabilities registration) through the MAC algorithm. CMAC has an additional "ver" direction present in its testing to ensure the IUT can successfully determine when a MAC does not match its originating message/key combination.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-38B>> and <<FIPS-198-1>>.

[[requirements_covered_cmac]]
==== CMAC Requirements Covered

*  SP 800-38B Section 6.2 Mac Generation. ACVP server creates random sets of keys and messages for the IUT to process, then compares the IUT's result to the ACVP result.

*  SP 800-38B Section 6.3 Mac Verification. ACVP server creates random sets of keys, messages, and macs. These test vectors are then randomly altered to ensure the MAC will not match the given key and message. Using the provided test case, the IUT is expected to validate the mac against the provided key and message.

[[requirements_not_covered_cmac]]
==== CMAC Requirements Not Covered

* SP 800-38B Section 5.4 Sub-keys. While sub-keys are computed, as they are intermediate values, are not validated via current testing.

* SP 800-38B Section 5.5 Input and Output Data. The 'mlen' is provided and not inferred.

* SP 800-38B Appendix A. Length of MAC. The ACVP server will generate vectors as per the IUT's specified criteria. The IUT *SHOULD* register its entire range of supported MAC lengths, regardless of security strength. The ACVP server will test a random sampling of valid MAC lengths as per the IUT registration - this generally includes the minimum and maximum MAC length.

[[requirements_covered_gmac]]
==== GMAC Requirements Covered

* SP 800-38D Section 5.1 Block Cipher. ACVP testing *SHALL* make use of the AES block cipher when testing GMAC.

* SP 800-38D Section 5.2 Two Gcm Functions. ACVP testing *MAY* test both the generate and verify functions of GCM (without making use of a payload) to help ensure a proper implementation. The ACVP and IUT *MAY* test the encrypt (generate) and decrypt (verify) utilizing a key, IV/nonce, and AAD as described in this document section.

* SP 800-38D Section 6 Mathematical Components of GCM. GHASH and GCTR produce intermediate values and *SHALL* be (indirectly) evaluated for correctness via the ACVP generated GMAC test vectors.

* SP 800-38D Section 7 GCM Specification.  When the IUT registers a direction capability of "encrypt", the ACVP server *MUST* generate vectors for the GCM-AE function.  When the IUT registers a capability of "decrypt", the ACVP server *MUST* generate test vectors for the GCM-AD function.

[[requirements_not_covered_gmac]]
==== GMAC Requirements Not Covered

* SP 800-38D Section 5.2.1.1 Input Data. GMAC *MUST NOT* make use of a plaintext.

* SP 800-38D Section 5.2.1.2 Output Data. GMAC *MUST NOT* make use of a ciphertext.

* SP 800-38D Section 7 GCM Specification. The ACVP server *MUST NOT* make use of a plaintext or ciphertext for the generation of test vectors for use in GMAC testing.

* SP 800-38D Section 8 Uniqueness Requirement on IVs and Keys. Key establishment, IV construction, or number of invocations for a specific key/IV *SHALL NOT* be tested under the scope of the ACVP testing.

[[requirements_covered_hmac]]
==== HMAC Requirements Covered

* FIPS 198-1 Section 3 Cryptographic Keys. The ACVP server will test, depending on the nature of the IUT capabilities registration, keys that are below, at, or above the hashing algorithm block size.

* FIPS 198-1 Section 4 HMAC Specification. Mac Generation. ACVP server creates random sets of keys and messages for the IUT to process, then compares the IUT's result to the ACVP result.

* FIPS 198-1 Section 5 Truncation. The ACVP server is capable of generating MACs as per the capability registration of the IUT. Groups will be created containing a random sampling of valid MAC lengths from the IUT registration.

[[requirements_not_covered_hmac]]
==== HMAC Requirements Not Covered

N/A
