[[cmac_tdes_root]]
== CMAC-TDES

[[cmac_tdes_caps_reg]]
=== CMAC-TDES Algorithm Capabilities Registration

Each CMAC-TDES algorithm capability advertised is a self-contained JSON object using <<mac_caps_table>>. Each capability object describes a separate permutation of direction and key length.

[[cmac_tdes_capabilities]]
==== CMAC-TDES Capability Details

[[cmac_tdes_caps_table]]
.CMAC-TDES Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| direction | The MAC direction(s) to test | array | "gen", "ver"
| keyingOption | The Keying Option used in TDES. Keying option 1 (1) is 3 distinct keys (K1, K2, K3). Keying Option 2 (2) is 2 distinct only suitable for decrypt (K1, K2, K1). Keying option 3 (No longer valid for testing, save TDES KATs) is a single key, now deprecated (K1, K1, K1). | array | 1, 2
| msgLen | The CMAC message lengths supported in bits, values *MUST* be mod 8 | Domain | Min: 0, Max: 524288, Inc: 8
| macLen | The supported mac sizes | Domain | Min: 32, Max: 64
|===

'macLen' for CMAC contains a Domain of values, the server may choose values defined by these rules:

* The smallest CMAC length supported
* A second CMAC length supported
* The largest CMAC length supported

'msgLen' for CMAC contains a Domain of values, the server may choose values defined by these rules:

* The smallest message length supported
* Two message lengths divisible by block size
* Two message lengths NOT divisible by block size
* The largest message length supported

[[cmac_tdes_app-reg-ex]]
==== Example CMAC-TDES Capabilities JSON Object

The following is an example JSON object advertising support for CMAC-TDES.

[source, json]
----
{
  "algorithm": "CMAC-TDES",
  "revision": "1.0",
  "capabilities": [
    {
      "direction": ["gen", "ver"],
      "keyingOption": [1],
      "msgLen": [
        {
          "min": 0,
          "max": 65536,
          "increment": 8
        }
      ],
      "macLen": [
        {
          "min": 32,
          "max": 64,
          "increment": 8
        }
      ]
    }
  ]
}
----
