[[cmac_tdes_test_vectors]]
=== CMAC-TDES Test Vectors

[[cmac_tdes_tgjs]]
==== CMAC-TDES Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure CMAC-TDES JSON elements of the Test Group JSON object.

[[cmac_tdes_vs_tg_table]]
.CMAC-TDES Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | Test category type | string
| direction | The direction of the tests - gen or ver | string
| msgLen | Length of message in bits | integer
| macLen | Length of MAC in bits to generate/verify | integer
| keyingOption | The Keying Option used in TDES. Keying option 1 (1) is 3 distinct keys (K1, K2, K3). Keying Option 2 (2) is 2 distinct only suitable for decrypt (K1, K2, K1). Keying option 3 (No longer valid for testing, save TDES KATs) is a single key, now deprecated (K1, K1, K1). | array | 1, 2
| tests | Array of individual test vector JSON objects, which are defined in <<cmac_tdes_tvjs>> | array
|===

[[cmac_tdes_tvjs]]
==== CMAC-TDES Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each secure MAC test vector.

[[cmac_tdes_vs_tc_table2]]
.CMAC-TDES Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | Value of the message | hex
| mac | MAC value, for CMAC verify | hex
| key1, key2, key3 | Encryption keys to use for TDES | hex
|===

[[cmac_tdes_test_vector_json]]
==== Example CMAC-TDES Test Vector JSON Object

The following is an example JSON test vector object for CMAC-TDES, truncated for brevity.

[source, json]
----
{
    "vsId": 1,
    "algorithm": "CMAC-TDES",
    "revision": "1.0",
    "testGroups": [{
            "tgId": 4,
            "testType": "AFT",
            "direction": "gen",
            "msgLen": 752,
            "macLen": 32,
            "keyingOption": 1,
            "tests": [{
                    "tcId": 25,
                    "message": "4D2D07AE0224289BE111...",
                    "key1": "7FFDB31A3A06BF0D",
                    "key2": "5201FFE83CC5253E",
                    "key3": "BBECA60F1D631BB8"
                },
                {
                    "tcId": 26,
                    "message": "7A70F3CE17598AC3553F...",
                    "key1": "82E572E29C84009E",
                    "key2": "28390918155E4891",
                    "key3": "A0D24C94C306FE56"
                },
                {
                    "tcId": 27,
                    "message": "2DAF1E213A6AE9E88FEB...",
                    "key1": "662A89E47D86F6A0",
                    "key2": "CB9D612E199B4AD2",
                    "key3": "AE3AEBA19FAB4340"
                }
            ]
        },
        {
            "tgId": 10,
            "testType": "AFT",
            "direction": "ver",
            "msgLen": 0,
            "macLen": 32,
            "keyingOption": 1,
            "tests": [{
                    "tcId": 73,
                    "message": "",
                    "mac": "D78010B3",
                    "key1": "D127F902CFF69A82",
                    "key2": "785D99EF117E5B56",
                    "key3": "36D4CB2C34A3AF30"
                },
                {
                    "tcId": 74,
                    "message": "",
                    "mac": "5313D9E8",
                    "key1": "9D5DAC4D75E0A349",
                    "key2": "6A55855C62D8C767",
                    "key3": "CBD9FC7CCBDA8BE9"
                },
                {
                    "tcId": 75,
                    "message": "",
                    "mac": "07B1926F",
                    "key1": "B711BA268A1F3663",
                    "key2": "AA83B2195E85BFC6",
                    "key3": "AA1CFBC128AAE0FD"
                }
            ]
        }
    ]
}
----
