[[gmac_test_vectors]]
=== AES-GMAC Test Vectors

[[gmac_tgjs]]
==== AES-GMAC Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure GMAC JSON elements of the Test Group JSON object.

[[gmac_vs_tg_table]]
.AES-GMAC Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | Test category type | string
| direction | The direction of the tests - encrypt or decrypt | string
| keyLen | Length of key in bits to use | integer
| ivLen | Length of IV in bits | integer
| ivGen | IV Generation (internal or external) | string
| ivGenMode | The mode an internal IV has been generated using | string
| aadLen | Length of AAD in bits | integer
| tagLen | Length of tag/MAC in bits to generate/verify | integer
| tests | Array of individual test vector JSON objects, which are defined in <<gmac_tcjs>> | array
|===

[[gmac_tcjs]]
==== AES-GMAC Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON
elements for each secure MAC test vector.

[[gmac_vs_tc_table]]
.AES-GMAC Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| key | Encryption key to use | hex
| iv | Value of the IV | hex
| aad | Value of the AAD | hex
| tag | MAC/tag value, for validating on a decrypt operation | hex
|===


[[gmac_test_vec_ex]]
==== Example AES-GMAC Test Vector JSON Object

The following is an example JSON test vector object for AES-GMAC, truncated for brevity

[source, json]
----
   {
     "vsId": 0,
     "algorithm": "ACVP-AES-GMAC",
     "revision": "1.0",
     "testGroups": [{
         "tgId": 1,
         "testType": "AFT",
         "direction": "encrypt",
         "keyLen": 128,
         "ivLen": 96,
         "ivGen": "external",
         "aadLen": 0,
         "tagLen": 32,
         "tests": [{
           "tcId": 1,
           "key": "B1E9747F9E016F0376B1F379CD345B8A",
           "aad": "",
           "iv": "6294CEEDFCC3037A023100E8"
         }]
       },
       {
         "tgId": 2,
         "testType": "AFT",
         "direction": "decrypt",
         "keyLen": 128,
         "ivLen": 96,
         "ivGen": "external",
         "aadLen": 0,
         "tagLen": 32,
         "tests": [{
           "tcId": 2,
           "key": "CD345B8AE016F03765E9747F9B1F379A",
           "aad": "",
           "iv": "6207CEEDFA094CC3032310E8",
           "tag": "AB1254CE"
         }]
       }
     ]
   }
----
