[[gmac_vector_responses]]
=== AES-GMAC Test Vector Responses

==== AES-GMAC Vector Set Group Responses

Each test group contains an array of one or more test cases.  Each test case is a JSON object that represents a single test vector to be processed by the ACVP client.  The following table describes the JSON
elements for each GMAC test vector.

[[gmac_vs_tr_table]]
.AES-GMAC Test Case Results JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| tag | Value of the computed tag/MAC output, for 'encrypt' direction groups | hex
| testPassed | The result of decrypt verify, for 'decrypt' direction groups | boolean
|===

[[gmac_test_vector_response_json]]
==== Example AES-GMAC Test Vector Response JSON Object

The following is an example JSON test vector response object for AES-GMAC.

[source, json]
----
{
 "vsId": 1,
 "algorithm": "ACVP-AES-GMAC",
 "revision": "1.0",
 "testGroups": [{
     "tgId": 1,
     "tests": [{
       "tcId": 1,
       "tag": "6FA27FDC"
     }]
   },
   {
     "tgId": 2,
     "tests": [{
       "tcId": 2,
       "testPassed": true
     }]
   }
 ]
}
----
