
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified DSA algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of DSA capabilities. This section describes the design of the tests used to validate implementations of the DSA algorithms.

* DSA / keyGen / 1.0 "AFT" - Algorithm Functional Test. The IUT is REQUIRED for each test case provided, to generate a key pair based on a generated group level PQG. This information is then communicated to the ACVP server and validated.

* DSA / pqgGen / 1.0 "GDT" - Generated Data Test. The IUT in this test mode is *REQUIRED* to generate PQ or G as a response to the ACVP provided test vector set.

* DSA / pqgVer / 1.0 "GDT" - Generated Data Test. In this test mode, the ACVP server is *REQUIRED* to generate domain parameters for transmission  to the IUT. The IUT is expected to evaluate the validity of the domain parameters.

* DSA / sigGen / 1.0 "AFT" - Algorithm Functional Test. This testing mode expects the IUT to generate valid signatures based on the ACVP provided message. The IUT communicates the PQG, public key, and signature to the ACVP server, and the signature is then validated.

* DSA / sigVer / 1.0 "AFT" - Algorithm Functional Test. The ACVP server generates a series of signatures to communicate to the IUT. The IUT is *REQUIRED* to determine the validity of the signature given the PQG, key, and message.

[[test_coverage]]
=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<FIPS186-4>> and <<SP800-89>>.

[[requirements_covered]]
==== Requirements Covered

* FIPS186-4 Section 3 General Discussion. Domain parameter generation, key generation, signature generation, and signature validation are all within scope of ACVP server testing.

* FIPS186-4 Section 4 The Digital Signature Algorithm (DSA). The ACVP server provides a means of the generation and validation of domain parameters. The ACVP server is *SHALL* support a variety of parameter sizes/hash function for creation and delivery to/from the IUT. The ACVP server *SHALL* allow for the testing of the validity of domain parameters.  Key pair generation testing *SHALL* be provided by the ACVP server. Both Signature Generation and Validation testing mechanmisms *SHALL* be provided by the ACVP server.

* SP800-106 Section 3 Randomized Hashing and Section 4 Digital Signatures Using Randomized Hashing.  The IUT *SHALL* be provided or provide a random value that should be used to "randomize" a message prior to signing and/or verifying an original message.

[[requirements_not_covered]]
==== Requirements Not Covered

* FIPS186-4 Section 3 General Discussion. Assurances of private key secrecy and ownership *SHALL NOT* be within scope of ACVP testing.

* FIPS186-4 Section 4 The Digital Signature Algorithm (DSA). The IUT's selection of parameter sizes and hash functions *SHALL NOT* be within scope of ACVP server testing.  Though the ACVP server *SHALL* support a variety of parameter sizes/hash functions, the IUT's selection of these is out of scope of testing. The ACVP server *MAY* provide testing for the validity of domain parameters, but testing *SHALL NOT* provide assurances the IUT has validated a set of domain parameters prior to their use. Domain parameter and key pair management *SHALL NOT* be within scope of ACVP testing.

* SP800-106 Section 3.3 The Random Value. DSA, ECDSA, and RSA have random values generated as per their signing process, this random value can be used as the input to the message randomization function, doing so however is out of scope of this testing.
