[[mode_pqggen]]
=== DSA pqgGen Mode Capabilities

The DSA / pqgGen / 1.0 mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each DSA / pqgGen / 1.0 mode capability set is advertised as a self-contained JSON object.

The complete list of DSA PQ and G generation capabilities may be advertised by the ACVP compliant crypto module:

[[pqgGen_table]]
.DSA pqgGen Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| l | The length in bits of the field and the length in bits of prime p. | value | 2048, or 3072
| n | The length in bits of q which is a prime factor of (p-1). | value | 224, or 256 when L is 2048. Otherwise 256.
| pqGen | The methods supported to generate p and q. | array | Any non-empty subset of {"probable", "provable"}.
| gGen | The methods supported to generate g. | array | Any non-empty subset of {"unverifiable", "canonical"}.
| hashAlg | The hash functions supported when generating p, q and g. | array | Any non-empty subset of {"SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256"}. Note that the digest size of the hash function *MUST* be equal to or greater than N.
|===

An example of the DSA / pqgGen / 1.0 registration is the following

[source, json]
----
{
  "algorithm": "DSA",
  "mode": "pqgGen",
  "revision": "1.0",
  "prereqVals": [
    {
      "algorithm": "SHA",
      "valValue": "123456"
    },
    {
      "algorithm": "DRBG",
      "valValue": "123456"
    }
  ],
  "capabilities": [
    {
      "pqGen": [
        "probable",
        "provable"
      ],
      "gGen": [
        "unverifiable",
        "canonical"
      ],
      "l": 2048,
      "n": 224,
      "hashAlg": [
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/224",
        "SHA2-512/256"
      ]
    },
    {
      "pqGen": [
        "probable",
        "provable"
      ],
      "gGen": [
        "unverifiable",
        "canonical"
      ],
      "l": 2048,
      "n": 256,
      "hashAlg": [
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/256"
      ]
    },
    {
      "pqGen": [
        "probable",
        "provable"
      ],
      "gGen": [
        "unverifiable",
        "canonical"
      ],
      "l": 3072,
      "n": 256,
      "hashAlg": [
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/256"
      ]
    }
  ]
}
----
