[[mode_sigVer]]
==== DSA sigVer Mode Capabilities

The DSA / sigVer / 1.0 mode capabilities are advertised as JSON objects, which are elements of the 'capabilities' array in the ACVP registration message. See the ACVP specification for details on the registration message.

Each DSA / sigVer / 1.0 mode capability set is advertised as a self-contained JSON object.

The complete list of DSA signature verification capabilities may be advertised by the ACVP compliant crypto module:

[[sigVer_table]]
.DSA sigVer Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| l | The length in bits of the field and the length in bits of prime p. | value | 1024, 2048, or 3072
| n | The length in bits of q which is a prime factor of (p-1). | value | 160 when L is 1024. 224, or 256 when L is2048. Otherwise 256.
| hashAlg | The hash functions supported when verifying a message. | array | Any non-empty subset of {"SHA-1","SHA2-224", "SHA2-256", "SHA2-384", "SHA2-512", "SHA2-512/224", "SHA2-512/256"}.
|===

An example of this is the following

[source, json]
----
{
  "algorithm": "DSA",
  "mode": "sigVer",
  "revision": "1.0",
  "prereqVals": [
    {
      "algorithm": "SHA",
      "valValue": "123456"
    },
    {
      "algorithm": "DRBG",
      "valValue": "123456"
    }
  ],
  "capabilities": [
    {
      "n": 160,
      "l": 1024,
      "hashAlg": [
        "SHA-1",
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/224",
        "SHA2-512/256"
      ]
    },
    {
      "n": 224,
      "l": 2048,
      "hashAlg": [
        "SHA-1",
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/224",
        "SHA2-512/256"
      ]
    },
    {
      "n": 256,
      "l": 2048,
      "hashAlg": [
        "SHA-1",
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/224",
        "SHA2-512/256"
      ]
    },
    {
      "n": 256,
      "l": 3072,
      "hashAlg": [
        "SHA-1",
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA2-512/224",
        "SHA2-512/256"
      ]
    }
  ],
  "conformances": [
    "SP800-106"
  ]
}
----
