[[dsa_keyGen_test_vectors]]
=== DSA keyGen Test Vectors

[[dsa_keyGen_tgjs]]
==== DSA keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for DSA / keyGen / * is as follows:

[[dsa_keyGen_vs_tg_table]]
.DSA keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| testType | The test operation performed | string
| l | Length in bits of prime modulus p | integer
| n | Length in bits of prime divisor q | integer
| tests | Array of individual test vector JSON objects, which are defined in <<dsa_keyGen_tvjs>> | array
|===

[[dsa_keyGen_tvjs]]
==== DSA keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / keyGen / 1.0 test vector.

[[dsa_keyGen_vs_tc_table]]
.DSA keyGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
|===

NOTE: The client is responsible for generating domain parameters and a key to be verified by the server.

The following is an example JSON object sent from the server to the client for DSA / keyGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "DSA",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
          {
            "tgId": 1,
            "l": 2048,
            "n": 224,
            "tests": [
              {
                "tcId": 1
              },
            ]
          }
        ]
    }
]
----
