[[dsa_sigGen_test_vectors]]
=== DSA sigGen Test Vectors

[[dsa_sigGen_tgjs]]
==== DSA sigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for DSA / sigGen / * is as follows:

[[dsa_sigGen_vs_tg_table]]
.DSA sigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| testType | The test operation performed | string
| l | Length in bits of prime modulus p | integer
| n | Length in bits of prime divisor q | integer
| hashAlg | The hash algorithm used in the test group | string
| conformance | Signifies all test cases within the group should utilize random message hashing as described in <<SP800-106>>. | string
| tests | Array of individual test vector JSON objects, which are defined in <<dsa_sigGen_tvjs>> | array
|===

[[dsa_sigGen_tvjs]]
==== DSA sigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / sigGen / 1.0 test vector.

[[dsa_sigGen_vs_tc_table]]
.DSA sigGen Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate signature or verify signature | hex
|===

The following is an example JSON object sent from the server to the client for DSA / sigGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "DSA",
        "mode": "sigGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "l": 2048,
                "n": 224,
                "hashAlg": "SHA-1",
                "tests": [
                    {
                        "tcId": 1,
                        "message": "C1FEBB069145F..."
                    }
                ]
            },
            {
                "tgId": 2,
                "l": 2048,
                "n": 224,
                "hashAlg": "SHA-1",
                "conformance": "SP800-106",
                "tests": [
                    {
                        "tcId": 2,
                        "message": "C1FEBB069145F..."
                    }
                ]
            }
        ]
    }
]
----
