[[dsa_keyGen_vector_responses]]
=== DSA keyGen Test Vector Responses

The test groups for DSA / keyGen / 1.0 contain public key properties. The groups can be described using the following table.

[[dsa_keyGen_group_table]]
.DSA keyGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| p | The prime modulus | hex
| q | The prime divisor of p - 1 | hex
| g | The generator | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / keyGen / 1.0 test vector.

[[dsa_keyGen_vs_tr_table]]
.DSA keyGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| x | The private key component X | hex
| y | The public key component Y | hex
|===

The following is an example JSON test vector response object for DSA / keyGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
          {
            "tgId": 1,
            "p": "9D75F12AD16C09A618F3D25...",
            "q": "F9146BFEC592547B8C69737...",
            "g": "96A7DD911D076093EBBA4D9...",
            "tests": [
              {
                "tcId": 1,
                "x": "6316A9021906CB3F9F6...",
                "y": "8520DE9F113D659F708..."
              }
            ]
          }
        ]
    }
]
----
