[[dsa_pqggen_vector_responses]]
=== DSA PQGGen Test Vector Responses

The test groups for DSA / pqgGen / 1.0 contain public key properties. The groups can be described using the following table.

[[dsa_pqggen_group_table]]
.DSA PQGGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / pqgGen / 1.0 test vector.

[[dsa_pqggen_vs_tr_table]]
.DSA PQGGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| p | The prime modulus | hex
| q | The prime divisor of p - 1 | hex
| g | The generator | hex
| domainSeed | The seed used to generate p and q in the probable method | hex
| counter | The counter used to generate p and q in the probable method | integer
| pSeed | The seed used to generate p in the provable method | hex
| qSeed | The seed used to generate q in the provable method | hex
| pCounter | The counter used to generate p in the provable method | integer
| qCounter | The counter used to generate q in the provable method | integer
|===

NOTE: The properties 'p', 'q', 'domainSeed' and 'counter' are only required in test groups generating p and q using the probable generation method in <<FIPS186-4>>. An example of this is 'tgId' 1 in the following example.

NOTE: The properties 'p', 'q', 'domainSeed', 'pSeed', 'qSeed', 'pCounter' and 'qCounter' are only required in test groups generating p and q using the provable generation method in <<FIPS186-4>>. An example of this is 'tgId' 2 in the following example.

NOTE: The property 'g' is only required in test groups generating g under both allowed modes of generation, canonical and unverifiable. An example of this is 'tgId' 3 and 4 in the following example.

The following is an example JSON test vector response object for DSA / pqgGen / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
              "tgId": 1,
              "tests": [
                {
                  "tcId": 1,
                  "p":"E0BB55A249993FE4...",
                  "q":"C0074BDDC42F22F5...",
                  "domainSeed":"01AA98A...",
                  "counter":379
                }
              ]
            },
            {
              "tgId": 2,
              "tests": [
                {
                  "tcId": 2,
                  "p":"84B73C1CE8E8C10F8...",
                  "q":"A0B7917C9020F2332...",
                  "domainSeed":"98179EF2...",
                  "pSeed":"98179EF2D7FD0...",
                  "qSeed":"98179EF2D7FD0...",
                  "pCounter":596,
                  "qCounter":255
                }
              ]
            },
            {
              "tgId": 3,
              "tests": [
                {
                  "tcId": 3,
                  "g": "01098AD5E87869EF..."
                }
              ]
            },
            {
              "tgId": 4,
              "tests": [
                {
                  "tcId": 4,
                  "g": "5C4AB5D4C901A375..."
                }
              ]
            }
        ]
    }
]
----
