[[dsa_pqgver_vector_responses]]
=== DSA PQGVer Test Vector Responses

The test groups for DSA / pqgVer / 1.0 contain public key properties. The groups can be described using the following table.

[[dsa_pqgver_group_table]]
.DSA PQGVer Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / pqgVer / 1.0 test vector.

[[dsa_pqgver_vs_tr_table]]
.DSA PQGVer Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| testPassed | Whether or not the pq pair or g verified | boolean
|===

The following is an example JSON test vector response object for DSA / pqgVer / 1.0.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
          {
            "tgId": 1,
            "tests": [
              {
                "tcId": 1,
                "testPassed": false,
              }
            ]
          },
          {
            "tgId": 2,
            "tests": [
              {
                "tcId": 36,
                "testPassed": false,
              }
            ]
          },
          {
            "tgId": 3,
            "tests": [
              {
                "tcId": 211,
                "testPassed": true,
              }
            ]
          },
          {
            "tgId": 4,
            "tests": [
              {
                "tcId": 246,
                "testPassed": true,
              }
            ]
          }
        ]
    }
]
----
