[[dsa_sigVer_vector_responses]]
=== DSA sigVer Test Vector Responses

The test groups for DSA / sigVer / 1.0 contain public key properties. The groups can be described using the following table.

[[dsa_sigVer_group_table]]
.DSA sigVer Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / sigVer / 1.0 test vector.

[[dsa_sigVer_vs_tr_table]]
.DSA sigVer Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| testPassed | Whether or not the pq pair or g verified | boolean
|===

The following is an example JSON test vector response object for DSA / sigVer / 1.0.

[source, json]
----
[
  {
    "acvVersion": <acvp-version>
  },
  {
    "vsId": 1564,
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "tcId": 1,
            "testPassed": true
          },
          {
            "tcId": 2,
            "testPassed": true
          }
        ]
      }
    ]
  }
]
----
