[[dsa_sigGen_vector_responses]]
=== DSA sigGen Test Vector Responses

The test groups for DSA / sigGen / 1.0 contain public key properties. The groups can be described using the following table.

[[dsa_sigGen_group_table]]
.DSA sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| p | The prime modulus | hex
| q | The prime divisor of p - 1 | hex
| g | The generator | hex
| y | The public key component Y | hex
| tests | The individual test cases for the group | array
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DSA / sigGen / 1.0 test vector.

[[dsa_sigGen_vs_tr_table]]
.DSA sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| r | The signature component R | hex
| s | The signature component S | hex
| randomValue | The random value to be used as an input into the message randomization function as described in <<SP800-106>>. | hex
| randomValueLen | The random value's bit length. | integer
|===

NOTE: The properties 'randomValue' and 'randomValueLen' are only required for groups that had the 'conformance' property set to "SP800-106".

The following is an example JSON test vector response object for DSA / sigGen / 1.0.

[source, json]
----
[
  {
    "acvVersion": <acv-version>
  },
  {
    "vsId": 1564,
    "testGroups": [
      {
        "tgId": 1,
        "p": "C8DC6C77CC31ADAE68F3221D59C7...",
        "q": "B1B7BCF2467F8CC46FCDD2A41327...",
        "g": "6C07130A6F6D05AAC9350936EE06...",
        "y": "79143F63ECCC06B3D35C61DA2FB8...",
        "tests": [
          {
            "tcId": 1,
            "r": "4E7F70A92EC0E6871E2EA278...",
            "s": "641A74C54A0B642DED9FE6EE..."
          }
        ]
      },
      {
        "tgId": 2,
        "p": "77CC31ADAE68F3221D59C75538F6...",
        "q": "82E17546E564816AFB54987C879A...",
        "g": "B1303035FE460CEBF21DDA00CC08...",
        "y": "D699C3B6E150E60443BA461C2564...",
        "tests": [
          {
            "tcId": 2,
            "r": "4E7F70A92EC0E6871E2EA275...",
            "s": "641A74C54A0B642DED9FE6EE...",
            "randomValue": "23678643ACB728...",
            "randomValueLen": 1024
          }
        ]
      }
    ]
  }
]
----
