
[#testtypes]
== Test Types and Test Coverage

[#ttypes]
=== Test Types

The ACVP server performs a set of tests on the specified EDDSA algorithm in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of EDDSA capabilities. This section describes the design of the tests used to validate implementations of the EDDSA algorithms.

* EDDSA / keyGen / 1.0 "AFT" - Algorithm Functional Test. The IUT is *REQUIRED* for each test case provided, to generate a key pair based on an approved curve. This information is then communicated to the ACVP server and validated.

* EDDSA / keyVer / 1.0 "AFT" - Algorithm Functional Test. The ACVP server is *REQUIRED* to generate a series of keys based on the IUT provided NIST curve(s). The keys generated by the server *MAY* or *MAY NOT* be valid, the IUT is *REQUIRED* to determine if the keys provided in the test cases are valid or invalid keys as they relate to the curve.

* EDDSA / sigGen / 1.0 "AFT" - Algorithm Functional Test. This testing mode expects the IUT to generate valid signatures based on the ACVP provided message. The signature is then validated with the ACVP server given the IUT's communicated curve, public key, and signature.

* EDDSA / sigGen / 1.0 "BFT" - Bit Flip Test. This testing mode produces a single message and flips individual bits in the message to ensure a client is able to produce distinct signatures for each message.

* EDDSA / sigVer / 1.0 "AFT" - Algorithm Functional Test. The ACVP server generates a series of signatures to communicate to the IUT. The IUT is *REQUIRED* to determine the validity of the signature given the curve, key, and message.

[[test_coverage]]
=== Test Coverage

* TBD...

[[requirements_covered]]
==== Requirements Covered

* TBD...

[[requirements_not_covered]]
==== Requirements Not Covered

* TBD...
