[[mode_sigGen]]
==== The sigGen Mode Capabilities

Each EDDSA sigGen mode capability set is advertised as a self-contained JSON object.

[[mode_sigGenFullSet]]
===== sigGen Full Set of Capabilities

The complete list of EDDSA signature generation capabilities may be advertised by the ACVP compliant crypto module:

[[sigGen_table]]
.EDDSA sigGen Capabilities JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| curve | The curve names supported for the IUT in sigGen | array | Any non-empty subset of {"ED-25519", "ED-448"}
| pure | If the IUT supports normal 'pure' EdDSA signature generation functionality | bool | true/false
| preHash | If the IUT supports Prehash EdDSA, i.e., HashEdDSA, signature generation functionality | bool | true/false
| contextLength | The lengths the IUT supports in octets for generated context strings | domain | Min: 0, Max: 255
|===

The following is an example

[source, json]
----
{
    "algorithm": "EDDSA",
    "mode": "sigGen",
    "revision": "1.0",
    "prereqVals": [{
            "algorithm": "SHA",
            "valValue": "123456"
        },
        {
            "algorithm": "DRBG",
            "valValue": "123456"
        }
    ],
    "pure": true,
    "preHash": true,
    "contextLength": [
        {
            "min": 0,
            "max": 255,
            "increment": 1
        }
    ],
    "curve": [
        "ED-25519",
        "ED-448"
    ]
}
----
