[[EDDSA_sigGen_tgjs]]
=== EDDSA sigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the JSON elements of the Test Group JSON object.

The test group for EDDSA / sigGen / 1.0 is as follows:

[[EDDSA_sigGen_vs_tg_table5]]
.EDDSA sigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| curve | The curve type used for the test vectors | string
| prehash | Whether or not Prehash EdDSA/HashEdDSA (vs normal/'pure' EdDSA) should be used for the test vectors | boolean
| testType | The testType for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<EDDSA_sigGen_tvjs>> | array
|===

[[EDDSA_sigGen_tvjs]]
=== EDDSA sigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each EDDSA test vector.

[[EDDSA_sigGen_vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
| context | The context string defined in FIPS 186-5 sections 7.6 and 7.8 | hex
| contextLength | The lengths the IUT supports in octets for generated context strings | domain | Min: 0, Max: 255
|===

NOTE: The 'context' property will only be present for 1) normal/'pure' EdDSA signature generation tests that use Ed448 and 2) Prehash EdDSA/HashEdDSA signature generation tests that use Ed448 or Ed25519.

The following is an example of a prompt for EDDSA / sigGen / 1.0

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "sigGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "curve": "ED-25519",
                "preHash": true,
                "tests": [
                    {
                        "tcId": 1,
                        "message": "A81C8A22735A260...",
                        "context": "12CBEF869A08BCD..."
                    }
                ]
            },
            {
                "tgId": 5,
                "testType": "BFT",
                "curve": "ED-25519",
                "preHash": false,
                "tests": [
                    {
                        "tcId": 41,
                        "message": "F27E9F9D"
                    },
                    {
                        "tcId": 42,
                        "message": "F27E9F9C"
                    },
                    {
                        "tcId": 43,
                        "message": "F27E9F9F"
                    }
                ]
            }
        ]
    }
]
----
