[[eddsa_siggen_tgjs]]
=== EdDSA SigGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for EdDSA / SigGen / 1.0 is as follows:

[[eddsa_siggen_vs_tg_table5]]
.EdDSA SigGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| curve | The curve type used for the test vectors | string
| prehash | Whether or not the message is pre-hashed entering the signature function | boolean
| testType | The testType for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<eddsa_siggen_tvjs>> | array
|===

[[eddsa_siggen_tvjs]]
=== EdDSA SigGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each EdDSA test vector.

[[eddsa_siggen_vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
| context | The context used to generate the signature | hex
|===

NOTE: The 'context' property will only be present if the 'prehash' group property is set to true.

The following is an example of a prompt for EdDSA / SigGen / 1.0

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EdDSA",
        "mode": "SigGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "curve": "ED-25519",
                "preHash": true,
                "tests": [
                    {
                        "tcId": 1,
                        "message": "A81C8A22735A260...",
                        "context": "12CBEF869A08BCD..."
                    }
                ]
            },
            {
                "tgId": 5,
                "testType": "BFT",
                "curve": "ED-25519",
                "preHash": false,
                "tests": [
                    {
                        "tcId": 41,
                        "message": "F27E9F9D"
                    },
                    {
                        "tcId": 42,
                        "message": "F27E9F9C"
                    },
                    {
                        "tcId": 43,
                        "message": "F27E9F9F"
                    }
                ]
            }
        ]
    }
]
----
