[[EDDSA_keyGen_tgjs]]
=== EDDSA keyGen Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the JSON elements of the Test Group JSON object.

The test group for EDDSA / keyGen / 1.0 is as follows:

[[EDDSA_keyGen_vs_tg_table5]]
.EDDSA keyGen Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| curve | The curve type used for the test vectors | string
| testType | The testType for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<EDDSA_keyGen_tvjs>> | array
|===

[[EDDSA_keyGen_tvjs]]
=== EDDSA keyGen Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each EDDSA test vector.

[[EDDSA_keyGen_vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
|===

NOTE: The client is responsible for generating a single key per test case.

The following is an example of a prompt for EDDSA / keyGen / 1.0

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "algorithm": "EDDSA",
        "mode": "keyGen",
        "revision": "1.0",
        "testGroups": [
            {
                "tgId": 1,
                "curve": "ED-25519",
                "testType": "AFT",
                "tests": [
                    {
                        "tcId": 1
                    }
                ]
            }
        ]
    }
]
----
