[[EDDSA_sigVer_tgjs]]
=== EDDSA sigVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the JSON elements of the Test Group JSON object.

The test group for EDDSA / sigVer / 1.0 is as follows:

[[EDDSA_sigVer_vs_tg_table5]]
.EDDSA sigVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The test group identifier | integer
| curve | The curve type used for the test vectors | string
| prehash | Whether or not Prehash EdDSA/HashEdDSA (vs normal/'pure' EdDSA) should be used for the test vectors | boolean
| testType | The testType for the group | string
| tests | Array of individual test vector JSON objects, which are defined in <<EDDSA_sigVer_tvjs>> | array
|===

[[EDDSA_sigVer_tvjs]]
=== EDDSA sigVer Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each EDDSA test vector.

[[EDDSA_sigVer_vs_tc_table5]]
.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| message | The message used to generate the signature | hex
| q | The encoded public key | hex
| signature | The signature to verify | hex
|===

// NOTE: The 'context' property will only be present if the 'prehash' group property is set to true.

The following is an example of a prompt for EDDSA / sigVer / 1.0

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "EDDSA",
        "mode": "sigVer",
        "revision": "1.0",
        "isSample": true,
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "curve": "ED-25519",
                "preHash": false,
                "tests": [
                    {
                        "tcId": 1,
                        "message": "61524B41E89736DEE...",
                        "q": "14FB8D71A6CEDFC7B33109F...",
                        "signature": "283877CFDAFE61A..."
                    },
                    {
                        "tcId": 2,
                        "message": "43529BD72351015CA...",
                        "q": "99E318DCAD59F37DD3355EE...",
                        "signature": "F21BCB4898B32B6..."
                    }
                ]
            }
        ]
    }
]
----
