[[EDDSA_sigGen_responses]]
=== EDDSA sigGen Test Group Responses

The following table describes the JSON object that represents a test group response for EDDSA / sigGen / 1.0.

[[EDDSA_sigGen_vr_top_table2]]
.EDDSA sigGen Test Group Response JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Unique numeric identifier for the test group | integer
| q | The encoded public key point used for signatures in the group | hex
| tests | Array of JSON objects that represent each result, as defined by the table below | array
|===

The following table describes the JSON object that represents a test case response for EDDSA / sigGen / 1.0.

[[EDDSA_sigGen_vr_top_table5]]
.EDDSA sigGen Test Case Response JSON Object
|===
| JSON Value | Description | JSON type

| tcId | The test case identifier | integer
| signature | The computed signature | hex
|===

The following is an example of the response for EDDSA / sigGen / 1.0

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 1564,
        "testGroups": [
            {
                "tgId": 1,
                "q": "4BA34FE699DBDC89750FF006...",
                "tests": [
                    {
                        "tcId": 1,
                        "signature": "772990B0..."
                    }
                ]
            },
            {
                "tgId": 5,
                "q": "ADD51513B67540E3A392721...",
                "tests": [
                    {
                        "tcId": 41,
                        "signature": "6EA857E..."
                    },
                    {
                        "tcId": 42,
                        "signature": "883B033..."
                    },
                    {
                        "tcId": 43,
                        "signature": "E402705..."
                    }
                ]
            }
        ]
    }
]
----
