
[#supported]
== Supported Conditioning Components

Conditioning is an optional process during entropy collection shown in Section 2.2.2 of <<SP800-90B>>. There are two types of conditioning components supported by <<SP800-90B>>: vetted and non-vetted. A vetted conditioning component comes from a specific list of options. All <<SP800-90B>> vetted conditioning components are available via ACVP. This document rounds out the list with options not covered in other algorithm testing.

The following conditioning components *MAY* be advertised by the ACVP compliant cryptographic module:

* ConditioningComponents / AES-CBC-MAC / SP800-90B
* ConditioningComponents / BlockCipher_DF / SP800-90B
* ConditioningComponents / Hash_DF / SP800-90B

[[hash_supported]]
=== Supported Hash Functions for Hash_DF

For the Hash Derivation Function, Hash_DF, the following hash functions *MAY* be advertised by the ACVP compliant cryptographic module:

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
