
[[cbc_mac_tgjs]]
=== Conditioning Component AES-CBC-MAC Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the ConditioningComponent / AES-CBC-MAC / SP800-90B JSON elements of the Test Group JSON object.

[[cbc_mac_vs_tg_table]]
.Conditioning Component AES-CBC-MAC Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The unique group identifier | integer
| testType | Describes the operation the client should perform on the test data | string
| keyLen | The length of the key used in the group | integer
| tests | Array of individual test cases, see <<cbc_mac_tvjs>> | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt.

[[cbc_mac_tvjs]]
=== Conditioning Component AES-CBC-MAC Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ConditioningComponent / AES-CBC-MAC / SP800-90B test vector.

.Conditioning Component AES-CBC-MAC Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case identifier | integer
| pt | The plaintext | hex
| key | The key | hex
|===

Here is an abbreviated yet fully constructed example of the prompt for ConditioningComponent / AES-CBC-MAC / SP800-90B

[source, json]
----
{
  "vsId": 42,
  "algorithm": "ConditioningComponent",
  "mode": "AES-CBC-MAC",
  "revision": "SP800-90B",
  "testGroups": [
    {
      "tgId": 1,
      "testType": "AFT",
      "keyLen": 128,
      "tests": [
        {
          "tcId": 1,
          "pt": "FE44418EF94E5DA8...",
          "key": "E618ADF7E7CEBB46465C0B18A924768A"
        },
        {
          "tcId": 2,
          "pt": "6ABEED30F813C137D47BF1E9E837DAEE",
          "key": "D1C1B7FFB2CCE0BBF13D4F7B4A246A8D"
        }
      ]
    }
  ]
}
----
