
[[hash_df_tgjs]]
=== Conditioning Component Hash_DF Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the ConditioningComponent / Hash_DF / SP800-90B JSON elements of the Test Group JSON object.

[[hash_df_vs_tg_table]]
.Conditioning Component Hash_DF Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | The unique group identifier | integer
| testType | Describes the operation the client should perform on the test data | string
| hashAlg | The hash algorithm used in the derivation function | string
| tests | Array of individual test cases, see <<hash_df_tvjs>> | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt.

[[hash_df_tvjs]]
=== Conditioning Component Hash_DF Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ConditioningComponent / Hash_DF / SP800-90B test vector.

.Conditioning Component Hash_DF Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case identifier | integer
| payload | The input into the derivation function | hex
| payloadLen | The length in bits of the input | integer
|===

Here is an abbreviated yet fully constructed example of the prompt for ConditioningComponent / Hash_DF / SP800-90B

[source, json]
----
{
  "vsId": 42,
  "algorithm": "ConditioningComponent",
  "mode": "Hash_DF",
  "revision": "SP800-90B",
  "testGroups": [
    {
      "tgId": 1,
      "hashAlg": "SHA2-256",
      "testType": "AFT",
      "tests": [
        {
          "tcId": 1,
          "payload": "2874215320DADAC...",
          "payloadLen": 54112
        },
        {
          "tcId": 2,
          "payload": "36",
          "payloadLen": 8
        }
      ]
    }
  ]
}
----
