[[bc_df_responses]]
=== Conditioning Component BlockCipher_DF Test Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ConditioningComponent / BlockCipher_DF / SP800-90B test vector.

The following table describes the JSON elements for the test case responses for ConditioningComponent / BlockCipher_DF / SP800-90B.

[[bc_df_vs_tr_table]]
.Conditioning Component BlockCipher_DF Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| requestedBits | The output of the derivation function | hex
|===

The following is an example of the response for ConditioningComponent / BlockCipher_DF / SP800-90B .

[source, json]
----
{
  "vsId": 42,
  "algorithm": "ConditioningComponent",
  "mode": "BlockCipher_DF",
  "revision": "SP800-90B",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "requestedBits": "4A8575F3EA300812C60B19678620CA9F"
        },
        {
          "tcId": 2,
          "requestedBits": "2F85CD9748F4CEE2F9BAE939874D8321"
        }
      ]
    }
  ]
}
----
