[[cbc_mac_responses]]
=== Conditioning Component AES-CBC-MAC Test Responses

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each ConditioningComponent / AES-CBC-MAC / SP800-90B test vector.

The following table describes the JSON elements for the test case responses for ConditioningComponent / AES-CBC-MAC / SP800-90B.

[[cbc_mac_vs_tr_table]]
.Conditioning Component AES-CBC-MAC Test Case Results JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case | integer
| ct | The ciphertext output | hex
|===

NOTE: In the case of AES-CBC-MAC, the output is always 128-bits regardless of the size of the input.

The following is an example of the response for ConditioningComponent / AES-CBC-MAC / SP800-90B .

[source, json]
----
{
  "vsId": 42,
  "algorithm": "ConditioningComponent",
  "mode": "AES-CBC-MAC",
  "revision": "SP800-90B",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "ct": "4A8575F3EA300812C60B19678620CA9F"
        },
        {
          "tcId": 2,
          "ct": "2F85CD9748F4CEE2F9BAE939874D8321"
        }
      ]
    }
  ]
}
----
