[#responses]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response Properties
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Test Group Response Properties
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors.  Several algorithms *SHALL* require the client to send back group level properties in their response.  This structure helps accommodate that.

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Response Properties
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| testPassed | Was the provided `dkm` valid? Only valid for the "VAL" test type. | boolean
| dkm | The derived keying material. Provided by the IUT for "AFT" test type test cases. For single expansion tests. | hex
| dkms | The derived keying materials. Provided by the IUT for "AFT" test type test cases. For multi expansion groups. | array of hex

|===

Here is an abbreviated example of the response.

=== Example Test Vectors Response JSON
.Example Response JSON
[source,json]
----
{
  "vsId": 0,
  "algorithm": "KDA",
  "mode": "OneStepNoCounter",
  "revision": "Sp800-56Cr2",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "dkm": "703574C2B2959324555C0E42DAB1AA8E83E8A590C27C4C949B594ABDBADB9722"
        },
        {
          "tcId": 2,
          "dkm": "8F0A2955B8B08B5D26D9B242B2D45ECF019EC45D839D74CC8640F238A6CCD422"
        },
        {
          "tcId": 3,
          "dkm": "79EB275B415B038D5F8AC446D52153C3287B2552DEF878B2BAAAADEEF753AE9C"
        },
        {
          "tcId": 4,
          "dkm": "C6BA73A759927701125CA2D1D26B1909799813FFF77387F8B24AC29A4B4B17EB"
        },
        {
          "tcId": 5,
          "dkm": "3C60B5EC3315E248C6361BDEF27BB9BFA560B8F30375AB7C27142858D51AF3B4"
        }
      ]
    },
    {
      "tgId": 62,
      "tests": [
        {
          "tcId": 141,
          "testPassed": true
        },
        {
          "tcId": 142,
          "testPassed": false
        },
        {
          "tcId": 143,
          "testPassed": true
        },
        {
          "tcId": 144,
          "testPassed": true
        },
        {
          "tcId": 145,
          "testPassed": true
        }
      ]
    }    
  ]
}
----