[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC7991,RFC 7991]]]
* [[[RFC8174,RFC 8174]]]

* [[[SP800-56Ar3,NIST SP 800-56A Rev. 3]]]
* [[[SP800-56Br2,NIST SP 800-56B Rev. 2]]]
* [[[SP800-56Cr2,NIST SP 800-56C Rev. 2]]]


[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01
