[[SLH-DSA_sigVer_test_vectors]]
=== SLH-DSA sigVer Test Vectors

[[SLH-DSA_sigVer_tgjs]]
==== SLH-DSA sigVer Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {algo-short-name} JSON elements of the Test Group JSON object.

The test group for SLH-DSA / sigVer / FIPS205 is as follows:

[[SLH-DSA_sigVer_vs_tg_table]]
.SLH-DSA sigVer Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Numeric identifier for the test group, unique across the entire vector set | integer
| testType | The test operation performed | string
| parameterSet | The SLH-DSA parameter set used | string
| signatureInterface | Whether the signature is generated using the internal or external routine | string
| preHash | Whether the signature is generated using the prehash or pure routine | string
| tests | Array of individual test vector JSON objects, which are defined in <<SLH-DSA_sigVer_tvjs>> | array
|===

NOTE: The "preHash" property will only be present if "signatureInterface" is set to "external". 

[[SLH-DSA_sigVer_tvjs]]
==== SLH-DSA sigVer Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each SLH-DSA / sigVer / FIPS205 test vector.

[[SLH-DSA_sigVer_vs_tc_table]]
.SLH-DSA sigVer Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Numeric identifier for the test case, unique across the entire vector set | integer
| pk | The public key to use to verify the signature | hex
| message | The message used to verify with the signature | hex
| context | When the test group property `"signatureInterface": "external"`, the context used to construct the signed message | hex
| hashAlg | When the test group property `"preHash": "preHash"`, the hash function used to construct the signed message | string
| signature | The signature to verify | hex
|===

The following is an example JSON object sent from the server to the client for SLH-DSA / sigVer / FIPS205.

[source, json]
----
[
    {
        "acvVersion": <acvp-version>
    },
    {
        "vsId": 0,
        "algorithm": "SLH-DSA",
        "mode": "sigVer",
        "revision": "FIPS205",
        "testGroups": [
            {
                "tgId": 1,
                "testType": "AFT",
                "parameterSet": "SLH-DSA-SHA2-192s",
                "signatureInterface": "internal",
                "tests": [
                    {
                        "tcId": 1,
                        "pk": "6CB59...",
                        "message": "4F0D7...",
                        "signature": "C29A11B6C..."
                    },
                    {
                        "tcId": 2,
                        "pk": "123ABC...",
                        "message": "8479",
                        "signature": "6A99215FC2..."
                    }
                ]
            },
            {
                "tgId": 2,
                "testType": "AFT",
                "parameterSet": "SLH-DSA-SHA2-192s",
                "signatureInterface": "external",
                "preHash": "preHash",
                "tests": [
                    {
                        "tcId": 3,
                        "pk": "6CB59...",
                        "message": "4F0D7...",
                        "context": "ABCD",
                        "hashAlg": "SHA2-256",
                        "signature": "C29A11B6C..."
                    },
                    {
                        "tcId": 4,
                        "pk": "123ABC...",
                        "message": "8479",
                        "context": "ABCD",
                        "hashAlg": "SHA2-256",
                        "signature": "6A99215FC2..."
                    }
                ]
            },
            {
                "tgId": 3,
                "testType": "AFT",
                "parameterSet": "SLH-DSA-SHA2-192s",
                "signatureInterface": "external",
                "preHash": "pure",
                "tests": [
                    {
                        "tcId": 5,
                        "pk": "6CB59...",
                        "message": "4F0D7...",
                        "context": "ABCD",
                        "signature": "C29A11B6C..."
                    },
                    {
                        "tcId": 6,
                        "pk": "123ABC...",
                        "message": "8479",
                        "context": "ABCD",
                        "signature": "6A99215FC2..."
                    }
                ]
            }
        ]
    }
]
----
