
[#responses]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[response_table]]
.Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The ACVP version used | string
| vsId | The vector set identifier | integer
| testGroups | The test group objects in the response, see <<response_group_table>> | array
|===

An example of this is the following

[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The 'testGroups' section is used to organize the ACVP client response in a similar manner to how it distributes vectors.

[[response_group_table]]
.Response Group Objects
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case objects in the response. Depending on the algorithm, see <<SLH-DSA_keyGen_vs_tr_table>>, <<SLH-DSA_sigGen_vs_tr_table>>, or <<SLH-DSA_sigVer_vs_tr_table>> | array
|===

An example of this is the following

----
{
    "tgId": 1,
    "tests": [ ... ]
}
----
