
[#testtypes]
== Test Types and Test Coverage

The ACVP server performs a set of tests on the KAS protocol in order to assess the correctness and robustness of the implementation. A typical ACVP validation session *SHALL* require multiple tests to be performed for every supported permutation of KAS capabilities. This section describes the design of the tests used to validate implementations of KAS algorithms. 

=== Test Types
				
There are two test types for KAS testing:
 
* "AFT" - Algorithm Function Test. In the AFT test mode, the IUT *SHALL* act as a party in the Key Confirmation with the ACVP server. The server *SHALL* generate and provide all necessary information for the IUT to perform a successful key confirmation; both the server and IUT *MAY* act as party U/V, as well as recipient/provider to key confirmation.

=== Test Coverage 

The tests described in this document have the intention of ensuring an implementation is conformant to <<SP800-56Ar3>> and <<SP800-56Br2>> Key Confirmation. 

[[requirements_covered]]
==== Requirements Covered
                        
* SP 800-56Ar3 / SP 800-56Br2 - 5.1 Cryptographic Hash Functions.  SHA1, SHA2, and SHA3 hash functions *SHALL* be available for the various pieces of KAS requiring use of a hash function; such as approved MACs and OneStep KDF.

* SP 800-56Ar3 / SP 800-56Br2 - 5.2 Message Authentication Code (MAC) Algorithms.  AES-CMAC, HMAC, and KMAC algorithms *SHALL* be available for testing under Key Confirmation as the specification states.

* SP 800-56Ar3 - 5.3 Random Number Generation / SP800-56Br2 - 5.3 Random Bit Generators.  Though random values are used, the testing of the construction of those random values *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 / SP800-56Br2 - 5.4 Nonces.  Though nonces are used, the testing of the construction of those nonces *SHALL NOT* be in scope of ACVP testing.

* SP 800-56Ar3 - 5.9 KeyConfirmation / SP 800-56Br2 - 5.6 Key Confirmation.  The ACVP server *SHALL* support key confirmation for applicable KAS and KTS schemes.

[[requirements_not_covered]]
==== KAS-FFC Requirements Not Covered
 
* SP 800-56Ar3 / SP 800-56Br2 Sections that aren't applicable to Key Confirmation *SHALL NOT* be in the scope of testing covered under this document, for this algorithm.