[[tgjs]]
=== Test Groups JSON Schema

The testGroups element at the top level in the test vector JSON object is an array of test groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors
that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the secure hash JSON elements of the Test Group JSON object.

The test group for KAS/KTS FFC is as follows:

[[vs_tg_table5]]
.Vector Group JSON Object
|===
| JSON Value| Description| JSON type| Optional

| tgId| Numeric identifier for the test group, unique across the entire vector set. | value| No
| testType|  The type of test for the group (AFT or VAL). | value| No

| kasRole| The group role from the perspective of the IUT.| value| No
| keyConfirmationDirection| The key confirmation direction. | value| No
| keyConfirmationRole| The key confirmation role. | value| No
| keyAgreementMacType| The MAC being used for key confirmation. | value| No
| keyLen| The length of the key to be used as the macKey. | value| No
| macLen| The length of the MAC to be produced. | value| No
| tests| The tests for the group.| Array of objects, See <<tvjs>>.| No
|===


[[tvjs]]
=== Test Case JSON Schema

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each test vector.

[[vs_tc_table5]]

.Test Case JSON Object
|===
| JSON Value| Description| JSON type| Optional

| tcId| Numeric identifier for the test case, unique across the entire vector set.| value| No
| macDataServer| The partyId and ephemeral data to be used from the ACVP server perspective. | value| No
| macDataIut| The partyId and ephemeral data to be used from the IUT perspective. | value| No
| macKey| The macKey portion of the key confirmation. | value| No
| tag| The tag generated as a part of key confirmation (from the IUT perspective). | value| Yes
|===

[[app-vs-ex]]
=== Example Test Vectors JSON Object

The following is a example JSON object for test vectors sent from the ACVP server to the crypto module.

[source,json]
----                         
{
  "vsId": 0,
  "algorithm": "KAS-KC",
  "revision": "Sp800-56",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "testType": "AFT",
      "kasRole": "initiator",
      "keyConfirmationDirection": "bilateral",
      "keyConfirmationRole": "provider",
      "keyAgreementMacType": "CMAC",
      "keyLen": 256,
      "macLen": 64,
      "tests": [
        {
          "tcId": 1,
          "macDataServer": {
            "partyId": "3590EA2B8D8EE994684A0CE4385DD2D2",
            "ephemeralData": "3139B09E09434C5F294F20115C7EE97B5716C9188CA39D08807F3809ADD8AD05"
          },
          "macDataIut": {
            "partyId": "910C6FE518C33A22380BCD33EAA34A79",
            "ephemeralData": "AA380D7E3E49563B006DE8F224336B421137D3CB50BD69472FDD5299885F9637"
          },
          "macKey": "08E276F4BC4EAE5DE47C4DB92402E7338D2373CA4BE9A4B43338635E25C5C212"
        },
        {
          "tcId": 2,
          "macDataServer": {
            "partyId": "C19FE731C14EBB0EDE8ECF2C60086CEA"
          },
          "macDataIut": {
            "partyId": "88E6C06D57E5EAC600DDE7246AAF7408"
          },
          "macKey": "234ADECE1B99695BD1E539BED042ABC51C9B0D348ECBCF9C0E46F7B885857D71"
        },
        {
          "tcId": 3,
          "macDataServer": {
            "partyId": "5345535892D86B3BE9C57D57E6EB4EA6"
          },
          "macDataIut": {
            "partyId": "022376FC5CBDE150D754BE6C78D2C653"
          },
          "macKey": "6A9BFC7FC2E6013CE901D59C1DF7297B61FB6B945FF1D7C55217FA5FB54FC5BB"
        },
        {
          "tcId": 4,
          "macDataServer": {
            "partyId": "F30A8967854FED4C423ABBCAC2190D65"
          },
          "macDataIut": {
            "partyId": "B1B0408807E22EB93EFEF2FAFB418EEB",
            "ephemeralData": "242FD779A30DAEFE542F6832348640A2A8FC824990CFC5E5F1DA881237C7452D"
          },
          "macKey": "950E78377B63387216C45BBF8349C4DD536B03B26BF6E4D03E855379E9FA5B79"
        }
      ]
    }
  ]
}
----