
[[vector_responses]]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[vr_top_table]]
.Vector Set Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| acvVersion| Protocol version identifier| value | No
| vsId| Unique numeric identifier for the vector set| value | No
| testGroups| Array of JSON objects that represent each test vector group. See <<vr_group_table>>.| array | No
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

[[vr_group_table]]
.Vector Set Group Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| tgId| The test group Id| value | No
| tests| Array of JSON objects that represent each test vector group.  See <<vr_tc_table>>. | array | No
|===

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors.  Several algorithms *SHALL* require the client to send back group level properties in their response.  This structure helps accommodate that.

[[vr_tc_table]]
.Vector Set Test Case Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| tcId| The test case Id| value | No
| tag| The tag generated as a part of key confirmation (from the IUT perspective). | value | No
|===

[[app-results-ex]]
=== Example Test Results JSON Object

The following is a example JSON object for test results sent from the crypto module to the ACVP server.

[source,json]
----                         
{
  "vsId": 0,
  "algorithm": "KAS-KC",
  "revision": "Sp800-56",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "tag": "35FA16A8F7CE4DD6"
        },
        {
          "tcId": 2,
          "tag": "7FD1AF7F1FF82F6C"
        },
        {
          "tcId": 3,
          "tag": "A1ABD89925631AC1"
        },
        {
          "tcId": 4,
          "tag": "BAABCDE5BFA9F3FA"
        }
      ]
    }
  ]
}
----