[#properties]
=== Property Registration

The {spec-algorithm} mode capabilities are advertised as JSON objects within a root "algorithm" object.

A registration *SHALL* use these properties:

.Registration Properties
|===
| JSON Value| Description| JSON Type| Valid Values

| algorithm | The algorithm under test | value | KAS-KDF
| mode | The mode under test | value | HKDF
| revision | The algorithm testing revision to use. | value | "Sp800-56Cr1"
| prereqVals | Prerequisite algorithm validations | array of prereqAlgVal objects | See <<prereq_algs>>
| fixedInfoPattern | The pattern used for fixedInfo construction. | string | See <<fixedinfopatcon>>
| encoding | The encoding type to use with fixedInfo construction.  Note concatenation is currently supported.  ASN.1 should be coming. | array of string | concatenation 
| hmacAlg | The HMAC modes supported by the KDF. | array of string | See <<hmacAlg>>
| macSaltMethods | How the salt is determined (default being all 00s, random being a random salt). | array of string | default, random
| z | The domain of values representing the min/max lengths of Z the implementation can support. | Domain
| l | The largest DKM the implementation can produce (up to a max of 2048). | number
|===

[[prereq_algs]]
==== Prerequisite Algorithms for KAS KDF Validations

Some algorithm implementations rely on other cryptographic primitives. For example, IKEv2 uses an underlying SHA algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

.Prerequisite Algorithms
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | a prerequisite algorithm | value | DRBG, HMAC, SHA
| valValue | algorithm validation number | value | actual number or "same"
| prereqAlgVal | prerequisite algorithm validation | object with algorithm and valValue properties| see above
|===

[[fixedinfopatcon]]
==== FixedInfoPatternConstruction

IUTs *MUST* be capable of specifying how the FixedInfo is constructed for the KDF construction. Note that for the purposes of testing against the ACVP system, both uPartyInfo and vPartyInfo are *REQUIRED* to be registered within the fixed info pattern.

Pattern candidates:

* literal[0123456789ABCDEF]
  ** uses the specified hex within "[]". literal[0123456789ABCDEF]
substitutes "0123456789ABCDEF" in place of the field

* uPartyInfo
  ** uPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* vPartyInfo
  ** vPartyId { || ephemeralKey } { || ephemeralNonce } { || dkmNonce } { || c }
    *** "optional" items such as ephemeralKey *MUST* be included when available for ACVP testing.

* context
  ** Random value chosen by ACVP server to represent the context.

* algorithmId
  ** Random value chosen by ACVP server to represent the
algorithmId.

* label
  ** Random value chosen by ACVP server to represent the label.

* l
  ** The length of the derived keying material in bits, *MUST* be represented in 32 bits for ACVP testing.

Example (Note that party U is the server in this case "434156536964", party V is the IUT "a1b2c3d4e5"):

* "concatenation" :
"literal[123456789CAFECAFE]||uPartyInfo||vPartyInfo"

Evaluated as:

* "123456789CAFECAFE434156536964a1b2c3d4e5"

[[hmacAlg]]
==== Valid HMAC Functions

The following hash functions MAY be advertised by an ACVP compliant client under the 'hmacAlg' property

* SHA1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512

=== Registration Example

.Registration JSON Example
[source,json]
----
{
  "algorithm": "KAS-KDF",
  "mode": "HKDF",
  "revision": "Sp800-56Cr1",
  "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
  "encoding": [
    "concatenation"
  ],
  "hmacAlg": [
    "SHA2-224",
    "SHA2-256",
    "SHA2-384",
    "SHA2-512",
    "SHA2-512/224",
    "SHA2-512/256",
    "SHA3-224",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512"
  ],
  "macSaltMethods": [
    "default",
    "random"
  ],
  "l": 1024,
  "z": [
    {
      "min": 224,
      "max": 65336,
      "increment": 8
    }
  ]
}
----