= ACVP IANA Registry
:doctype: internet-draft
:docnumber: draft-ietf-acvp-iana-01
:abbrev: ACVP IANA
:ipr: trust200902
:submission-type: independent
:intended-series: informational
:area: Internet
:revdate: 2019-06-05
:initials: A.V.
:lastname: Vassilev
:fullname: Apostol Vassilev
:organization: National Institute of Standards and Technology
:street: 100 Bureau Drive
:city: Gaithersburg
:code: 20899
:country: United States of America
:email: apostol.vassilev@nist.gov
:docfile: draft-vassilev-acvp-iana.adoc
:role: editor
:mn-document-class: ietf
:mn-output-extensions: xml,rfc,txt,html
:area: General
:keyword: acvp, crypto


[abstract]
== Abstract

This document defines a set of IANA registries for supported cryptographic algorithm test specifications in the Automated Cryptographic Validation Protocol (ACVP) <<ACVP>>. This document also shows how to extend the capabilities of ACVP with testing for new cryptographic algorithms.

== Introduction

The Automated Cryptographic Validation Protocol (ACVP) <<ACVP>> defines a mechanism to automatically validate the cryptographic algorithm implementations of software or hardware cryptographic modules. The ACVP specification defines how a cryptographic module communicates with a validation authority server, including cryptographic capabilities negotiation, session management, authentication, test vector processing and more.  The ACVP specification does not define algorithm-specific JSON constructs for performing the cryptographic validation.  A series of ACVP-related sub-specifications define the constructs for testing individual cryptographic algorithms, see for example <<Sub-symmetric>>. Each such sub-specification addresses a specific algorithm or a class of cryptographic algorithms. This document defines the IANA registry for the supported algorithm test specifications that work with ACVP. The registry defined here provides the binding between the protocol and the supported algorithm test extensions.

[[namespaces]]
== IANA namespaces

There are three namespaces envisioned for extensions to the ACVP:

* ACVP - the approved algorithms for testing with one or more validation authorities
* EXPERIMENTAL - candidate algorithms for approval.
* LOCAL - locally supported algorithms, not guaranteed for interoperability. Algorithms in this namespace cannot be registered with IANA.

TBD

[[algoTaxonomy]]
== Algorithm Registry

Each entry in the algorithm registry must record the following fields:

*  Name: a URN segment that conforms to the pattern {namespace}-{algorithm}. The keywords are defined as follows:
** {namespace}: one of the options from <<namespaces>>.
** {algorithm}: a required US-ASCII string that conforms to the URN syntax requirements (see <<RFC8141>>). This string must be unique within the corresponding namespace.
* Revision: the revision identifier for the test specification of a particular algorithm. A required US-ASCII string that conforms to the URN syntax requirements (see <<RFC8141>>).
* Reference: A static link to the specification and section where the definition of the parameter can be found.

[[table_algorithms]]
=== Initial Algorithm Registry Names

[cols="<,^,^"]
// . Algorithm Registry
|===
| Name | Revision | Reference

| "ACVP-AES-ECB" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CBC" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-OFB" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CFB1" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CFB8" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CFB128" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CTR" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-GCM" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CCM" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-XPN" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-CMAC" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-GMAC" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-KW" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-KWP" | "1.0" | <<Sub-symmetric>>
| "ACVP-AES-XTS" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-ECB" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-CBC" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-OFB" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-CFB1" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-CFB8" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-CFB64" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-CTR" | "1.0" | <<Sub-symmetric>>
| "ACVP-TDES-KW" | "1.0" | <<Sub-symmetric>>
|===

== Requirements Language

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted in <<RFC2119>>.

[[Acknowledgements]]
== Acknowledgements

Many thanks to David Waltermire for his helpful comments to get us started on the right path.

[[IANA]]
== IANA Considerations

This memo includes several requests to IANA.

[[IANA2]]
=== ACVP URN Sub-namespace

IANA should add an entry to the "IETF URN Sub-namespace for Registered Protocol Parameter Identifiers" registry located at https://www.iana.org/assignments/params/ as per <<RFC3553>>.

The entry should be as follows:

* Registered Parameter Identifier: ACVP
* Specification: this document
* Repository: ACVP URN Parameters (see <<ACVPParams>>)

[[ACVPParams]]
=== ACVP URN Parameters

A new top-level registry should be created, titled "Automated Cryptographic Validation Protocol (ACVP) URN Parameters". Registration in the "ACVP URN Parameters" registry is via the Specification Required policy <<RFC8126>>.  Registration requests must be sent to both the ACVP Working Group mailing list (acvp@ietf.org) and IANA.  IANA will forward registration requests to the Designated Expert.

Each entry in this subregistry must record the following fields:

* Name: A required US-ASCII string that conforms to the URN syntax requirements (see <<RFC8141>>). This string MUST be constructed according to the specification in <<algoTaxonomy>>. Note: entries from the namespace "LOCAL" SHALL be forbidden from this table.
* Revision: A required US-ASCII string that conforms to the URN syntax requirements (see <<RFC8141>>). The combination {Name}-{Revision} for each entry MUST be unique for the entire subregistry.
* Reference: A static link to the specification and section where the definition of the parameter can be found.

This repository SHALL have as initial values the entries in <<table_algorithms>>.

[[Security]]
== Security Considerations

Security considerations are addressed by the ACVP specification.

[bibliography]
== Normative References

* [[[RFC2119,RFC 2119]]]
* [[[RFC3553,RFC 3553]]]
* [[[RFC8126,RFC 8126]]]
* [[[RFC8141,RFC 8141]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01

[%bibitem]
=== ACVP Symmetric Algorithm JSON Specification
id:: Sub-symmetric
docid::
  id::: ACVP-Symmetric

// <reference anchor="Sub-symmetric">
//   <front>
//     <title>ACVP Symmetric Algorithm JSON Specification</title>

//     <author initials="C." surname="Celi">
//       <organization>NIST</organization>
//     </author>

//     <date year="2018"></date>
//   </front>
// </reference>

