
[[supported_algs]]
== Supported Block Cipher Algorithms

The following block cipher algorithm and test revision pairs *MAY* be advertised by the ACVP compliant cryptographic module (algorithm / revision):

* ACVP-AES-ECB / "1.0"
* ACVP-AES-CBC / "1.0"
* ACVP-AES-CBC-CS1 / "1.0"
* ACVP-AES-CBC-CS2 / "1.0"
* ACVP-AES-CBC-CS3 / "1.0"
* ACVP-AES-OFB / "1.0"
* ACVP-AES-CFB1 / "1.0"
* ACVP-AES-CFB8 / "1.0"
* ACVP-AES-CFB128 / "1.0"
* ACVP-AES-CTR / "1.0"
* ACVP-AES-FF1 / "1.0"
* ACVP-AES-FF3-1 / "1.0"
* ACVP-AES-GCM / "1.0"
* ACVP-AES-GCM-SIV / "1.0"
* ACVP-AES-XPN / "1.0"
* ACVP-AES-CCM / "1.0"
* ACVP-AES-XTS / "1.0"
* ACVP-AES-XTS / "2.0"
* ACVP-AES-KW / "1.0"
* ACVP-AES-KWP / "1.0"
* ACVP-TDES-ECB / "1.0"
* ACVP-TDES-CBC / "1.0"
* ACVP-TDES-CBCI / "1.0"
* ACVP-TDES-CFB1 / "1.0"
* ACVP-TDES-CFB8 / "1.0"
* ACVP-TDES-CFB64 / "1.0"
* ACVP-TDES-CFBP1 / "1.0"
* ACVP-TDES-CFBP8 / "1.0"
* ACVP-TDES-CFBP64 / "1.0"
* ACVP-TDES-OFB / "1.0"
* ACVP-TDES-OFBI / "1.0"
* ACVP-TDES-CTR / "1.0"
* ACVP-TDES-KW / "1.0"

Multiple testing revisions of the same algorithm allow a validation server to improve testing over time without breaking functionality of existing clients. In the case of symmetric block cipher algorithms, multiple revisions of ACVP-AES-XTS exist and *MAY* individually be provided by a server. The revision numbers of "1.0" and "2.0" indicate a progression among the tests. In this case, the "2.0" tests are fully capable of running the "1.0" implementation of ACVP-AES-XTS. More discussion can be found within <<cap_ex>>.

[[conformances]]
=== Supported Conformances

The following conformances *MAY* be advertised by the ACVP compliant cryptographic module:

* ACVP-AES-CCM conformance "ECMA" which expands upon AES-CCM and adheres to <<ECMA>>. This conformance changes the supported sizes to accomodate the specific sizes required by the use-case of the algorithm.

* ACVP-AES-CTR conformance "RFC3686".  This conformance ensures the IV is generated with the LSB[32] of the IV representing the integer "1".  This conformance also requires the additional registration property of "ivGenMode" which states if the IUT does external or internal IV generation.