[bibliography]
== References

* [[[RFC2119,RFC 2119]]]
* [[[RFC8174,RFC 8174]]]

* [[[FIPS-197,NIST FIPS 197]]]
* [[[SP800-38A,NIST SP 800-38A]]]

* [[[SP800-38C,NIST SP 800-38C]]]
* [[[SP800-38D,NIST SP 800-38D]]]
* [[[SP800-38E,NIST SP 800-38E]]]
* [[[SP800-38F,NIST SP 800-38F]]]
* [[[SP800-38Gr1,NIST SP 800-38G Rev. 1]]]
* [[[SP800-67r2,NIST SP 800-67 Rev. 2]]]
* [[[RFC3686,RFC 3686]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01


[%bibitem]
=== AES-GCM-SIV Nonce Misuse-Resistant Authenticated Encryption
id:: AES-GCM-SIV
docid::
  id::: AES-GCM-SIV
contributor::
contributor.role:: author
contributor.person.name.initial:: S.
contributor.person.name.surname:: Gueron
contributor.person.affiliation.organization.name:: University of Haifa and Amazon Web Services
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Langley
contributor.person.affiliation.organization.name:: Google LLC
contributor::
contributor.role:: author
contributor.person.name.initial:: Y.
contributor.person.name.surname:: Lindell
contributor.person.affiliation.organization.name:: Bar Ilan University
contributor::
contributor.role:: publisher
contributor.organization.name:: University of Haifa and Amazon Web Services, Google LLC, and Bar Ilan University
contributor.organization.abbreviation:: UH-AWS-G-BIU
date::
date.type:: published
date.value:: 2018


[%bibitem]
=== SP800-38A Addendum Recommendation for Block Cipher Modes of Operation: Three Variants of Ciphertext Stealing for CBC Mode
id:: SP800-38A-Add
docid::
  id::: SP800-38A-Add
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2010

[%bibitem]
=== ECMA-368 High Rate Ultra Wideband PHY and MAC Standard
id:: ECMA
docid::
  id::: ECMA
link::
link.type:: src
link.content:: https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-368.pdf

[%bibitem]
=== IEEE 1619-2007 — IEEE Standard for Cryptographic Protection of Data on Block-Oriented Storage Devices
id:: AES-XTS
docid::
  id::: IEEE 1619-2007
contributor::
contributor.role:: author
contributor.person.name.initial:: T.
contributor.person.name.surname:: Thompson
date::
date.type:: published
date.value:: 4 March 2008
link::
link.type:: src
link.content:: https://standards.ieee.org/standard/1619-2007.html
