[bibliography]
== References

* [[[RFC2119,RFC 2119]]]
* [[[RFC8174,RFC 8174]]]

[%bibitem]
=== Automatic Cryptographic Validation Protocol
id:: ACVP
docid::
  id::: ACVP
contributor::
contributor.role:: author
contributor.person.name.initial:: B.
contributor.person.name.surname:: Fussell
contributor.person.affiliation.organization.name:: Cisco
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Vassilev
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: author
contributor.person.name.initial:: H.
contributor.person.name.surname:: Booth
contributor.person.affiliation.organization.name:: National Institute of Standards and Technology
contributor.person.affiliation.organization.abbreviation:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2019-07-01


[%bibitem]
=== AES-GCM-SIV Nonce Misuse-Resistant Authenticated Encryption
id:: AES-GCM-SIV
docid::
  id::: AES-GCM-SIV
contributor::
contributor.role:: author
contributor.person.name.initial:: S.
contributor.person.name.surname:: Gueron
contributor.person.affiliation.organization.name:: University of Haifa and Amazon Web Services
contributor::
contributor.role:: author
contributor.person.name.initial:: A.
contributor.person.name.surname:: Langley
contributor.person.affiliation.organization.name:: Google LLC
contributor::
contributor.role:: author
contributor.person.name.initial:: Y.
contributor.person.name.surname:: Lindell
contributor.person.affiliation.organization.name:: Bar Ilan University
contributor::
contributor.role:: publisher
contributor.organization.name:: University of Haifa and Amazon Web Services, Google LLC, and Bar Ilan University
contributor.organization.abbreviation:: UH-AWS-G-BIU
date::
date.type:: published
date.value:: 2018

[%bibitem]
=== The XTS-AES Tweakable Block Cipher
id:: AES-XTS
docid::
  id::: AES-XTS
contributor::
contributor.role:: author
contributor.person.name.surname:: IEEE Std
contributor.person.affiliation.organization.name:: IEEE
contributor::
contributor.role:: publisher
contributor.organization.name:: Institute of Electrical and Electronics Engineers, Inc.
contributor.organization.abbreviation:: IEEE
date::
date.type:: published
date.value:: 2008

[%bibitem]
=== Specification for the Advanced Encryption Standard (AES)
id:: FIPS-197
docid::
  id::: FIPS-197
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2001

[%bibitem]
=== SP800-38A Recommendation for Block Cipher Modes of Operation: Methods and Techniques
id:: SP800-38A
docid::
  id::: SP800-38A
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2001

[%bibitem]
=== SP800-38A Addendum Recommendation for Block Cipher Modes of Operation: Three Variants of Ciphertext Stealing for CBC Mode
id:: SP800-38A-Add
docid::
  id::: SP800-38A-Add
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2010

[%bibitem]
=== SP800-38C Recommendation for Block Cipher Modes of Operation: The CCM Mode for Authentication and Confidentiality
id:: SP800-38C
docid::
  id::: SP800-38C
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2004

[%bibitem]
=== SP800-38D Recommendation for Block Cipher Modes of Operation: Galois/Counter Mode (GCM) and GMAC
id:: SP800-38D
docid::
  id::: SP800-38D
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2007

[%bibitem]
=== SP800-38E Recommendation for Block Cipher Modes of Operation: The XTS-AES Mode for Confidentiality on Storage Devices
id:: SP800-38E
docid::
  id::: SP800-38E
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2010

[%bibitem]
=== SP800-38F Recommendataion for Block Cipher Modes of Operation: Methods for Key Wrapping
id:: SP800-38F
docid::
  id::: SP800-38F
contributor::
contributor.role:: author
contributor.person.name.initial:: M.
contributor.person.name.surname:: Dworkin
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2012-12

[%bibitem]
=== SP800-67r2 Recommendation for the Triple Data Encryption Algorithm (TDEA) Block Cipher
id:: SP800-67r2
docid::
  id::: SP800-67r2
contributor::
contributor.role:: author
contributor.person.name.initial:: E.
contributor.person.name.surname:: Barker
contributor.person.affiliation.organization.name:: NIST
contributor::
contributor.role:: publisher
contributor.organization.name:: National Institute of Standards and Technology
contributor.organization.abbreviation:: NIST
date::
date.type:: published
date.value:: 2017

[%bibitem]
=== ECMA-368 High Rate Ultra Wideband PHY and MAC Standard
id:: ECMA
docid::
  id::: ECMA
link::
link.type:: src
link.content:: https://www.ecma-international.org/publications/files/ECMA-ST/ECMA-368.pdf
