[#prerequisites]
=== Prerequisites

An X-WING implementation relies on underlying cryptographic primitives.  Required prerequisite algorithm implementation *MUST* be validated either separately or as part of the same submission.  ACVP provides a mechanism for specifying prerequisite algorithm validation.

Prerequisites, if applicable, *MUST* be submitted in the registration using the `prereqVals` JSON property array within each element of the `algorithms` array. Each element in the `prereqVals` array *MUST* contain the following properties:

.Prerequisite Properties
|===
| JSON Property | Description | JSON Type

| algorithm | a prerequisite algorithm | string
| valValue | algorithm validation number | string
|===

A "valValue" of "same" *SHALL* indicate that the prerequisite is satisfied by another algorithm capability included in the same registration.

An example description of prerequisites within a single algorithm capability exchange looks like this:

[source,json]
----
{
"prereqVals": [
  {
    "algorithm": "Alg1",
    "valValue": "Val-1234"
  },
  {
    "algorithm": "Alg2",
    "valValue": "same"
  }
 ]
}
----
