
[[vector_responses]]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[vr_top_table]]
.Vector Set Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| acvVersion| Protocol version identifier| value | No
| vsId| Unique numeric identifier for the vector set| value | No
| testGroups| Array of JSON objects that represent each test vector group. See <<vr_group_table>>.| array | No
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

[[vr_group_table]]
.Vector Set Group Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| tgId| The test group Id| value | No
| tests| Array of JSON objects that represent each test vector group.  See <<vr_tc_table>>. | array | No
|===

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors.  Several algorithms *SHALL* require the client to send back group level properties in their response.  This structure helps accommodate that.

[[vr_tc_table]]
.Vector Set Test Case Response JSON Object
|===
| JSON Value| Description| JSON type | Optional

| tcId| The test case Id| value | No
| testPassed| Used in VAL test types, should the KAS/KTS negotiation have succeeded? | boolean | Yes
| ephemeralPublicKeyIutX| The IUT's ephemeral public key X value. | value | Yes
| ephemeralPublicKeyIutY| The IUT's ephemeral public key Y value. | value | Yes
| staticPublicKeyIutX| The IUT's static public key X value. | value | Yes
| staticPublicKeyIutX| The IUT's static public key Y value. | value | Yes
| dkmNonceIut| The IUT's nonce used in static schemes for Key Confirmation. | value | Yes
| ephemeralNonceIut| The IUT's ephemeral nonce used in some schemes. | value | Yes
| dkm| The derived keying material. | value | Yes
| tag| The tag generated as a part of key confirmation (from the IUT perspective). | value | Yes
|===

[[app-results-ex]]
=== Example Test Results KAS-ECC JSON Object

The following is an example JSON object for KAS-ECC test results sent from the crypto module to the ACVP server.

[source,json]
---- 
[
  {
    "acvVersion": "version"
  },
  {
    "vsId": 0,
    "algorithm": "KAS-ECC",
    "revision": "Sp800-56Ar3",
    "testGroups": [
      {
        "tgId": 1,
        "tests": [
          {
            "staticPublicIutX": "ED9CF3FE1B79D014F7FF60DFDBFC19457C4F3EBEB0BB10B5",
            "staticPublicIutY": "5CA8819BC0D39E67AE9AB4747DC563ADA1AE1E9DBA12C272",
            "tcId": 1,
            "dkmNonceIut": "215D9AB3A371B395802FD0FCD97815EDFC468DC631735BAEEA0F18498EFC3B52BBABD2B953DE7B64EF20D899093B031D",
            "dkm": "56505307C7F11F4640C96D863FA3634120F2B2CAB262AE29B1CD26252BC1537E84DF3EB75C1E240983B599B30690F9B0",
            "tag": "CE39683069F0DA7624F72086FB4B2B8E"
          }
        ]
      },
      {
        "tgId": 3,
        "tests": [
          {
            "tcId": 21,
            "testPassed": true
          }
        ]
      }
    ]
  }
]
----