[[eccComp]]
== ECC CDH Component Test

The ECC CDH Component Test for SP800-56Ar3

[[eccCompCap]]
=== ECC CDH Component Capabilities JSON Values

Each algorithm capability advertised is a self-contained JSON object using the following values.


[[eccComp_caps_table]]
.KAS ECC Component Capabilities JSON Values
|===
|JSON Value|Description|JSON type|Valid Values|Optional
|algorithm|The algorithm under test|value|KAS-ECC|No
|mode|The algorithm mode|value|CDH-Component|No
|revision|The algorithm testing revision to use.|value|"Sp800-56Ar3"|No
|prereqVals|Prerequisite algorithm validations|array of prereqAlgVal objects|See <<prereq_algs>>|No
|function| Type of function supported| array| See <<supported_functions>>| Yes
|curve|Array of supported curves|array|P-224, P-256, P-384, P-521, K-233, K-283, K-409, K-571, B-233, B-283, B-409, B-571|No
|===

[[app-eccComponent-reg-ex]]
==== Example KAS ECC CDH-Component Capabilities JSON Object

The following is a example JSON object advertising support for KAS ECC CDH-Component.

[source,json]
----
{
	"algorithm": "KAS-ECC",
	"mode": "CDH-Component",
	"revision": "Sp800-56Ar3",
	"prereqVals": [{
		"algorithm": "ECDSA",
		"valValue": "123456"
	}],
	"function": ["keyPairGen"],
	"curve": ["P-224", "K-233", "B-233"]
}
----

[[eccCompVectors]]
=== ECC CDH Component TestVectors JSON Values

[[eccComp_vector_table]]

.KAS ECC CDH Component TestVectors JSON Values
|===
| JSON Value| Description| JSON type| Valid Values| Optional

| algorithm| The algorithm under test| value| KAS-ECC| No
| mode| The algorithm mode under test| value| CDH-Component| No
| revision| The algorithm testing revision to use.| value| "Sp800-56Ar3"| No
| testGroups| Array of individual test group JSON objects, which are defined in <<eccCompTestGroup>>| Array| Array of test group information| No
|===

[[eccCompTestGroup]]
==== ECC CDH Component TestGroup JSON Values

[[eccComp_testGroup_table]]

.KAS ECC CDH Component TestGroup JSON Values
|===
| JSON Value| Description| JSON type| Valid Values| Optional

| testType| The test type expected within the group. AFT is the only valid value for ECC Component.| value| AFT| No
| curve| The curve used in the test group| value| P-224, P-256, P-384, P-521, K-233, K-283, K-409, K-571, B-233, B-283, B-409, B-571| No
| tests| Array of individual test vector JSON objects, which are defined in <<eccCompTestCase>>| array|  | No 
|===

[[eccCompTestCase]]
==== ECC CDH Component TestCase JSON Values

[[eccComp_testCase_table]]
.KAS ECC CDH Component TestCase JSON Values
|===
| JSON Value| Description| Valid Values| Optional

| tcId| Numeric identifier for the test case, unique across the entire vector set.| value| No
| publicServerX| The X coordinate of the server's public key| value| Yes
| publicServerY| The Y coordinate of the server's public key| value| Yes
| publicIutX| The X coordinate of the iut's public key| value| No
| publicIutY| The Y coordinate of the iut's public key| value| No
| z| The shared secret Z| value| No
|===

[[app-eccComponent-vs-ex]]
==== Example KAS ECC CDH-Component Test Vectors JSON Object

The following is a example JSON object for KAS ECC CDH-Component test vectors sent from the ACVP server to the crypto module.

[source,json]
----
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1750,
		"algorithm": "KAS-ECC",
		"mode": "CDH-Component",
		"revision": "Sp800-56Ar3",
		"testGroups": [{
				"tgId": 1,
				"testType": "AFT",
				"curve": "P-192",
				"tests": [{
					"tcId": 1,
					"publicServerX": "CAEF2CBA796BB7FC143D3EAED698C26AAE6F6F79DF3974EE",
					"publicServerY": "03ED6D7A90637629DBCEBFF4A2D1D771D9D4CF9F0D88CE90"
				}]
			},
			{
				"tgId": 2,
				"testType": "AFT",
				"curve": "K-163",
				"tests": [{
					"tcId": 26,
					"publicServerX": "048C46D674E1218D0BD3C9FCD120ECE8B4DB7310E7",
					"publicServerY": "ED3EEDB656E035C779081090BE44B743E857E3B4"
				}]
			},
			{
				"tgId": 3,
				"testType": "AFT",
				"curve": "B-163",
				"tests": [{
					"tcId": 51,
					"publicServerX": "8EE7C8F08BF47B21CA2FE911B721651B90E52391",
					"publicServerY": "0461DF3646E95598EAE4F5C6A634E71006ABC6FE1F"
				}]
			}
		]
	}
]
----

[[cdh_vector_responses]]
=== KAS CDH-Component Test Vector Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

[[vr_cdh_top_table]]
==== CDH Component Vector Set Response JSON Object

.CDH Component Vector Set Response JSON Object
|===
| JSON Value| Description| JSON type

| acvVersion| Protocol version identifier| value
| vsId| Unique numeric identifier for the vector set| value
| testGroups| Array of JSON objects that represent each test vector group. See <<vr_cdh_group_table>>| array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

[[vr_cdh_group_table]]
==== CDH Component Vector Set Group Response JSON Object

.CDH Component Vector Set Group Response JSON Object
|===
| JSON Value| Description| JSON type

| tgId| The test group Id| value
 tests| The tests associated to the group specified in tgId| value
|===

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each DRBG test vector.

[[vs_tr_table]]
==== CDH Component Test Case Results JSON Object

.CDH Component Test Case Results JSON Object
|===
| JSON Value| Description| JSON type| Optional

| tcId| Numeric identifier for the test case, unique across the entire vector set.| value| No
| publicIutX| x value of the IUT public key | value| No
| publicIutY| x value of the IUT public key | value| No
| z| Computed shared secret Z| value| No
|===

[[app-eccComponent-results-ex]]
=== Example KAS ECC CDH Component Test Results JSON Object

The following is a example JSON object for KAS ECC CDH Component test results sent from the crypto module to the ACVP server.

[source,json]
----                        
[{
		"acvVersion": "1.0"
	},
	{
		"vsId": 1750,
		"testGroups": [{
				"tgId": 1,
				"tests": [{
					"tcId": 1,
					"publicIutX": "DB9FBC84CBAD3EED42C31CDBF2882041634D040219C3E47A",
					"publicIutY": "9BD672733BCCEF2BD805E97FF9BBFE0FFC003BEEEF56868B",
					"z": "8BEAEA60DFAC075F9F25A5CFEA39818D98D3EA4B9D4C34A8"
				}]
			},
			{
				"tgId": 2,
				"tests": [{
					"tcId": 26,
					"publicIutX": "058C593D1D4E8238102BDE6B497218D92F8EDD2997",
					"publicIutY": "0437682E4608984EFC7FB619FB260EF27CAF704D7B",
					"z": "075D9A831E0665521D613AEAA59B8C8CDFBAC8C683"
				}]
			},
			{
				"tgId": 3,
				"tests": [{
					"tcId": 51,
					"publicIutX": "04128CD094F6988AA26DA2B100A71A31214CC9C50B",
					"publicIutY": "01A3A88C9F0987E488922573D0A31D300532F0B268",
					"z": "07EC896621BF1703EB7567196ED1DE5742C4695990"
				}]
			}
		]
	}
]
----