
[#properties]
=== Property Registration

The ANS x9.63 KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

=== Registration Example

A registration *SHALL* use these properties

.ANS x9.63 KDF Registration JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ansix9.63"
| revision | ACVP Test version | string | "1.0"
| prereqVals | Prerequisites of the algorithm | object | See <<prerequisites>>
| hashAlg | SHA functions supported. The digest size of at least one of the hash functions must be within the bounds of the fieldSize | array| See <<valid-sha>>
| keyDataLength | Key length minimum and maximum | array | 128-4096
| fieldSize | Minimum and Maximum field size in bits | array | Any non-empty subset of {224, 233, 256, 283, 384, 409, 521, 571}
| sharedInfoLength | Minimum and Maximum sharedinfo size in bits | domain | Min: 0, Max: 1024
|===

An example registration within an algorithm capability exchange looks like this

----
"capability_exchange":
[
  {
    "algorithm": "kdf-components",
    "mode": "ansix9.63",
    "revision": "1.0",
    "sharedInfoLength": [
      0,
      1024
    ],
    "fieldSize": [
      224,
      521
    ],
    "keyDataLength": [
      256,
      1024
    ],
    "hashAlg": [
      "sha2-224",
      "sha2-256",
      "sha2-384",
      "sha2-512"
    ]
  }
]
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property

* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
