
[#properties]
=== Property Registration

The ANS x9.63 KDF mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

=== Registration Example

A registration *SHALL* use these properties

.ANS x9.63 KDF Registration JSON Values
|===
| JSON Value | Description | JSON type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "kdf-components"
| mode | Mode of the algorithm to be validated | string | "ansix9.63"
| revision | ACVP Test version | string | "1.0"
| prereqVals | Prerequisites of the algorithm | object | See <<prerequisites>>
| hashAlg | SHA functions supported. The digest size of at least one of the hash functions must be within the bounds of the fieldSize | array| See <<valid-sha>>
| keyDataLength | Both the Minimum and the Maximum supported derived key lengths in bits | array | 128-4096
| fieldSize | The Minimum and Maximum supported elliptic curve field sizes in bits | array | Any one or two element subset of {224, 233, 256, 283, 384, 409, 521, 571}
| sharedInfoLength | Both the Minimum and Maximum sharedinfo sizes in bits | array | 0-1024
|===

NOTE: For the keyDataLength, fieldSize, and sharedInfoLength parameters, if the Minimum equals the Maximum, the array should only include the single value. Otherwise, the array should include two values, the one being the Minimum and the other being the Maximum.

An example registration within an algorithm capability exchange looks like this

----
"capability_exchange":
[
  {
    "algorithm": "kdf-components",
    "mode": "ansix9.63",
    "revision": "1.0",
    "sharedInfoLength": [
      0,
      1024
    ],
    "fieldSize": [
      224,
      521
    ],
    "keyDataLength": [
      256,
      1024
    ],
    "hashAlg": [
      "sha2-224",
      "sha2-256",
      "sha2-384",
      "sha2-512"
    ]
  }
]
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hashAlg' property. SHA-1 is not supported as section 5.6.2 of ANSI X9.63-2011 requires "An Approved hash function that offers 112 bits of security or more shall be used, i.e. an Approved hash function whose output is 224 bits or more."

* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512
