[[tgjs]]
=== Test Groups

The testGroups element at the top level in the test vector JSON object is an array of test	groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped	together. The Test Group JSON object contains meta data that applies to all test vectors within	the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group JSON Object
|===
| JSON Value | Description | JSON type

| tgId | Test group identifier | integer
| testType | Test operations to be performed | string
| hashAlg | The hash algorithm used | string
| fieldSize | The field length used in bits | integer
| sharedInfoLength | The shared info length used in bits | integer
| keyDataLength | The encryption key length used in bits | integer
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.Test Case JSON Object
|===
| JSON Value | Description | JSON type

| tcId | Test case idenfitier | integer
| z | Shared secret | hex
| sharedInfo | Shared information | hex
|===

Here is an abbreviated yet fully constructed example of the prompt

----
{
  "vsId": 1,
  "algorithm": "kdf-components",
  "mode": "ansix9.63",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "hashAlg": "SHA2-224",
      "sharedInfoLength": 0,
      "keyDataLength": 256,
      "fieldSize": 224,
      "testType": "AFT",
      "tests": [
        {
          "tcId": 1,
          "z": "7FF8AF7C976DE5F66D3ADE7C8245DEF8D...",
          "sharedInfo": ""
        },
        {
          "tcId": 2,
          "z": "2231A38A21FF8E3540030160D18C88D1E...",
          "sharedInfo": ""
        }
      ]
    }
  ]
}
----
