
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

----
{
	"acvVersion": "version",
	"vsId": 1,
	"testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

----
{
	"tgId": 1,
	"tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| keyData | The outputted key | hex
|===

Here is an abbreviated example of the response

----
{
  "vsId": 1,
  "algorithm": "kdf-components",
  "mode": "ansix9.63",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "keyData": "D4C3A166720F803EE1B9DE4B3B4C0..."
        },
        {
          "tcId": 2,
          "keyData": "2E56419465934408D61CF09B1B886..."
        }
      ]
    }
  ]
}
----
