
[#properties]
=== Property Registration

The {spec-algorithm} mode capabilities are advertised as JSON objects within the 'capabilities_exchange' property.

=== Registration Example

A registration *SHALL* use these properties

.PBKDF Algorithm Capabilities JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "PBKDF"
| revision | ACVP Test version | string | "1.0"
| prereqVals | Prerequisites of the algorithm | object | See <<prerequisites>>
| capabilities | Array of capabilities | array | Each object in the array contains the below properties
| iterationCount | Number of hash interations | domain | Min: 1, Max: 10000000
| keyLen | The length of the output key in bits | domain | Min: 112, Max: 4096
| passwordLen | The length of the password in bytes (characters) | domain | Min: 8, Max: 128
| saltLen | The length of the salt in bits | domain | Min: 128, Max: 4096
| hmacAlg | The supported hash algorithms used for HMAC | array | See <<valid-sha>>
|===

An example registration within an algorithm capability exchange looks like this

[source,json]
----
{
  "algorithm":"PBKDF",
  "revision":"1.0",
  "prereqVals":[
    {
      "algorithm":"SHA",
      "valValue":"same"
    }
  ],
  "capabilities": [
    {
      "iterationCount":[
        {
          "min":10,
          "max":1000,
          "increment":1
        }
      ],
      "keyLen":[
        {
          "min":8,
          "max":4096,
          "increment":8
        }
      ],
      "passwordLen":[
        {
          "min":8,
          "max":128,
          "increment":1
        }
      ],
      "saltLen":[
        {
          "min":128,
          "max":4096,
          "increment":8
        }
      ],
      "hmacAlg":[
        "SHA-1",
        "SHA2-224",
        "SHA2-256",
        "SHA2-384",
        "SHA2-512",
        "SHA3-224",
        "SHA3-256",
        "SHA3-384",
        "SHA3-512"
      ]
    }
  ]
}
----

[#valid-sha]
==== Valid Hash Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hmacAlg' property

* SHA-1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512
