[[tgjs]]
=== Test Groups

The testGroups element at the top level in the test vector JSON object is an array of test	groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped	together. The Test Group JSON object contains meta data that applies to all test vectors within	the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group JSON Object
|===
| JSON Values | Description | JSON Type

| tgId | Test group identifier | integer
| hmacAlg | The hash algorithm used in HMAC | string
| testType | Describes the operation the client should perform on the tests data | string
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' the group is addressing.

=== Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.Test Case JSON Object
|===
| JSON Values | Description | JSON Type

| tcId | Test case idenfitier | integer
| keyLen | Length of the output key | integer
| salt | Salt value | hex
| password | Password value | string
| iterationCount | Number of iterations | integer
|===

Here is an abbreviated yet fully constructed example of the prompt

[source,json]
----
{
  "vsId": 1,
  "algorithm": "PBKDF",
  "revision": "1.0",
  "testGroups": [
    {
      "tgId": 1,
      "testType": "AFT",
      "hmacAlg": "SHA2-224",
      "tests": [
        {
          "tcId": 1,
          "keyLen": 143,
          "salt": "BC902BA1EB3BD8519B68022F0FC15600D5D27A",
          "password": "FSLuCqOV",
          "iterationCount": 955
        },
        {
          "tcId": 2,
          "keyLen": 188,
          "salt": "8120C1DED77061BC5ED637DD51174F12",
          "password": "HCmKuigqgFlqpJv",
          "iterationCount": 269
        }
      ]
    }
  ]
}
----
