[#properties]
=== Property Registration

The {spec-algorithm} mode capabilities are advertised as JSON objects within a root "algorithm" object.

A registration *SHALL* use these properties:

.Registration Properties
|===
| JSON Value| Description| JSON Type| Valid Values

| algorithm| The algorithm under test| value| KDA
| mode| The mode under test| value| TwoStep
| revision| The algorithm testing revision to use.| value| "Sp800-56Cr1" or "Sp800-56Cr2"
| prereqVals| Prerequisite algorithm validations| array of prereqAlgVal objects| See <<prereq_algs>>
| capabilities | The two step configuration objects | array of <<twostepkdf>> | See <<twostepkdf>>
| z | The length(s) of the shared secret, Z, the IUT supports in bits. | Domain | Min: 224, Max: 65536, Increment: 8
| usesHybridSharedSecret | Whether the IUT uses a hybrid shared secret. Only applicable for <<SP800-56Cr2>>. This property is required for "SP800-56Cr2" testing. Omit this property for "SP800-56Cr1" testing. | Boolean | true or false
| auxSharedSecretLen | The length(s) of the auxiliary shared secret, T, the IUT supports in bits. Only applicable for <<SP800-56Cr2>>. This property is required for IUTs that implement a hybrid shared secret. Omit this property for "SP800-56Cr1" testing and for "SP800-56Cr2" testing without a hybrid shared secret. | Domain | Min: 112, Max: 65536, Increment: 8
| l | The length (in bits) of the largest derived keying material the implementation can produce (up to a max of 2048). | number | Min: 112; Max: 2048
| performMultiExpansionTests | Should multi expansion runs of the KDA be tested (in addition to the single expansion tests)? Only applicable for <<SP800-56Cr2>> | boolean | true, false
|===

[[prereq_algs]]
==== Prerequisite Algorithms for KDA Validations

Some algorithm implementations rely on other cryptographic primitives. For example, IKEv2 uses an underlying SHA algorithm. Each of these underlying algorithm primitives must be validated, either separately or as part of the same submission. ACVP provides a mechanism for specifying the required prerequisites:

.Prerequisite Algorithms
|===
| JSON Value | Description | JSON Type | Valid Values

| algorithm | a prerequisite algorithm | value | CMAC, DRBG, HMAC, SHA
| valValue | algorithm validation number | value | actual number or "same"
| prereqAlgVal | prerequisite algorithm validation | object with algorithm and valValue properties| see above
|===

[[twostepkdf]]
==== Two Step KDA Capabilities

.TwoStepCapabilities Options
|===
| JSON Value | Description | JSON Type | Valid Values

| macSaltMethod | How the salt is determined (default being all 00s, random being a random salt). | array of string | default, randombased auxiliary functions.
| fixedInfoPattern | The pattern used for fixedInfo construction. | string | See <<fixedinfopatcon>>
| encoding | The encoding type to use with fixedInfo construction.  Note concatenation is currently supported.  ASN.1 should be coming. | array of string | concatenation 
| kdfMode | The strategy for running the KDA. | string | counter, feedback, double pipeline iteration
| macMode | The macMode supported by the KDA. | array of string | CMAC-AES128, CMAC-AES192, CMAC-AES256, HMAC-SHA-1, HMAC-SHA2-224, HMAC-SHA2-256, HMAC-SHA2-384, HMAC-SHA2-512, HMAC-SHA2-512/224, HMAC-SHA2-512/256, HMAC-SHA3-224, HMAC-SHA3-256, HMAC-SHA3-384, HMAC-SHA3-512
| fixedDataOrder | The counter locations supported by the KDA. | array of string| none, before fixed data, after fixed data, before iterator
| counterLength | The counter lengths supported for the KDA. | array of integer | Any non-empty subset of {0, 8, 16, 24, 32}
| supportedLengths | The supported derivation lengths. | domain| Registered value(s) must support the 'l' value provided.
| supportsEmptyIv | The KDA supports an empty IV (feedback mode). | boolean | true, false
| requiresEmptyIv | The KDA requires an empty IV (feedback mode). | boolean | true, false
|===

NOTE: The 'fixedDataOrder' options "none" and "before iterator" are not valid for "counter" KDF. The 'fixedDataOrder' option "middle fixed data" is not valid for "feedback" nor "double pipeline iteration" KDF.

NOTE: A 'counterLength' of 0 describes that there is no counter used. The 0 option is not valid for "counter"  KDF.

NOTE: When 'counterLength' contains a value of "0", 'fixedDataOrder' must contain a value of "none" and vice versus.

NOTE: This capabilities object is very similar to the capability object from SP800-108.

[[fixedinfopatcon]]
==== FixedInfoPatternConstruction

IUTs *MUST* be capable of specifying how the FixedInfo is constructed for the KDA construction. Note that for the purposes of testing against the ACVP system, both uPartyInfo and vPartyInfo are *REQUIRED* to be registered within the fixed info pattern.

Pattern candidates:

* literal[0123456789ABCDEF]
  ** uses the specified hex within "[]". literal[0123456789ABCDEF]
substitutes "0123456789ABCDEF" in place of the field

* uPartyInfo
  ** uPartyId { || ephemeralData }
    *** For the purposes of the testing defined in this specification, the uPartyInfo value
    used to create the fixedInfo that is input to the key derivation function *SHALL* take the form of "uPartyId { || ephemeralData }". Because the KDA is being tested in isolation of the specific schemes it may be used with, ephemeralData is used in place of "{ || ephemeralKey } { || ephemeralNonce } { || dkmNonce }"
    *** For a given test case, a partyId value (see <<fixedInfo>>) *SHALL* always be given. ephemeralData values (see <<fixedInfo>>) may be provided or omitted.

* vPartyInfo
  ** vPartyId { || ephemeralData }
    *** For the purposes of the testing defined in this specification, the vPartyInfo value
    used to create the fixedInfo that is input to the key derivation function *SHALL* take the form of "vPartyId { || ephemeralData }". Because the KDA is being tested in isolation of the specific schemes it may be used with, ephemeralData is used in place of "{ || ephemeralKey } { || ephemeralNonce } { || dkmNonce }"
    *** For a given test case, a partyId value (see <<fixedInfo>>) *SHALL* always be given. ephemeralData values (see <<fixedInfo>>) may be provided or omitted.

* context
  ** Random value chosen by ACVP server to represent the context.

* algorithmId
  ** Random value chosen by ACVP server to represent the
algorithmId.

* label
  ** Random value chosen by ACVP server to represent the label.

* l
  ** The length of the derived keying material in bits, *MUST* be represented in 32 bits for ACVP testing.

Example (Note that party U is the server in this case "434156536964", party V is the IUT "a1b2c3d4e5"):

* "concatenation" :
"literal[123456789CAFECAFE]||uPartyInfo||vPartyInfo"

Evaluated as:

* "123456789CAFECAFE434156536964a1b2c3d4e5"

=== Registration Example

.Registration JSON Example SP800-56Cr1
[source,json]
----
{
  "algorithm": "KDA",
  "mode": "TwoStep",
  "revision": "Sp800-56Cr1",
  "prereqVals": [
    {
      "algorithm": "DRBG",
      "valValue": "123456"
    },
    {
      "algorithm": "SHA",
      "valValue": "123456"
    },
    {
      "algorithm": "HMAC",
      "valValue": "123456"
    }
  ],
  "capabilities": [
    {
      "macSaltMethods": [
        "random",
        "default"
      ],
      "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
      "encoding": [
        "concatenation"
      ],
      "kdfMode": "feedback",
      "macMode": [
        "HMAC-SHA3-224",
        "HMAC-SHA2-512"
      ],
      "supportedLengths": [
        512
      ],
      "fixedDataOrder": [
        "after fixed data",
        "before iterator"
      ],
      "counterLength": [
        32
      ],
      "requiresEmptyIv": false,
      "supportsEmptyIv": false
    }
  ],
  "l": 2048,
  "z": [
    512
  ]
}
----

.Registration JSON Example SP800-56Cr2
[source,json]
----
{
  "algorithm": "KDA",
  "mode": "TwoStep",
  "revision": "Sp800-56Cr2",
  "l": 512,
  "z": [
    {
      "min": 224,
      "max": 65536,
      "increment": 8
    }
  ],
  "usesHybridSharedSecret": true,
  "auxSharedSecretLen": [
    {
      "min": 112,
      "max": 65536,
      "increment": 8
    }
  ],
  "performMultiExpansionTests": true,
  "capabilities": [
    {
      "macSaltMethods": [
        "random",
        "default"
      ],
      "fixedInfoPattern": "uPartyInfo||vPartyInfo||l",
      "encoding": [
        "concatenation"
      ],
      "kdfMode": "feedback",
      "macMode": [
        "HMAC-SHA3-224",
        "HMAC-SHA2-512",
        "HMAC-SHA2-512/224"
      ],
      "customKeyInLength": 0,
      "supportedLengths": [
        512
      ],
      "fixedDataOrder": [
        "after fixed data",
        "before iterator"
      ],
      "counterLength": [
        32
      ],
      "requiresEmptyIv": false,
      "supportsEmptyIv": false
    }
  ]
}
----
