[#responses]
== Test Vector Responses

After the ACVP client downloads and processes a vector set, it *MUST* send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response Properties
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Test Group Response Properties
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

The testCase section is used to organize the ACVP client response in a similar manner to how it receives vectors.  Several algorithms *SHALL* require the client to send back group level properties in their response.  This structure helps accommodate that.

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Response Properties
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer
| testPassed | Was the provided `dkm` valid? Only valid for the "VAL" test type. | boolean
| dkm | The derived keying material. Provided by the IUT for "AFT" test type test cases. | hex
| dkms | The derived keying materials. Provided by the IUT for "AFT" test type test cases. For multi expansion groups. | array of hex

|===

Here is an abbreviated example of the response

=== Example Test Vectors Response JSON
.Example Response JSON
[source,json]
----
{
  "vsId": 0,
  "algorithm": "KDA",
  "mode": "TwoStep",
  "revision": "Sp800-56Cr1",
  "isSample": true,
  "testGroups": [
    {
      "tgId": 1,
      "tests": [
        {
          "tcId": 1,
          "dkm": "F30FA60BE892E9506BB1D7F0F69130A1F9142083E7EA64076D1ECDF5103571858FB742F94D96015EE0C747F3AB719A4EE00582064D58C111737BE2E7EEB53CC0"
        },
        {
          "tcId": 2,
          "dkm": "F6BF05D035D95C05B694DADE4DA41D05DC83E6CA100BFB1F13E24639C7DE5AE6B1ED0FECC1860F2246FF62624B805BFE3F15C3BD0639E13FBD69215FC75D066F"
        },
        {
          "tcId": 3,
          "dkm": "D7DC1B2E454D66529F82999006D67B2595D3862C81DB318B75DC005C888F294A652FBC35336CC5BD4510CE9CD38B7216596BAA65D6652D70A127D85767DB3818"
        },
        {
          "tcId": 4,
          "dkm": "677D6B89F0E747EBA608180A711D5964EAAC73690F72365E871D98AD0440DC6645312773651981B0A9C483D01A8783F52A443650ADE9E7924AAA57D8B9AB9111"
        },
        {
          "tcId": 5,
          "dkm": "875FADC0885DB1B0F0D2C38A27CC1169C4F5F4474F539A302169A99EA00689C587CE6B9873CFE681DAC6B02B91D6E47A8B1C53C3A45DAC54B06CC242FCCD5351"
        }
      ]
    },
    {
      "tgId": 33,
      "tests": [
        {
          "tcId": 161,
          "testPassed": true
        },
        {
          "tcId": 162,
          "testPassed": false
        },
        {
          "tcId": 163,
          "testPassed": true
        },
        {
          "tcId": 164,
          "testPassed": true
        },
        {
          "tcId": 165,
          "testPassed": true
        }
      ]
    }
  ]
}
----