
[#testtypes]
== Test Types and Test Coverage

This section describes the design of the tests used to validate {spec-algorithm} implementations.

=== Test Types

There is only one test type: functional tests. Each has a specific value to be used in the testType field. The testType field definition is:

* "AFT" - Algorithm Functional Test. These tests can be processed by the client using a normal 'derive_key' operation. AFTs cause the implementation under test to exercise normal operations on a single block, multiple blocks, or partial blocks. In all cases, random data is used. The functional tests are designed to verify that the logical components of the key deriviation process are operating correctly.


=== Test Coverage

The tests described in this document have the intention of ensuring an implementation is conformant to <<RFC8446>>.

[[coverage]]
==== Requirements Covered

* RFC8446 - 7.1 Key Schedule.  This section of the document encapsulates the bulk of ACVP testing; any functions involved in the computation of the TLS v1.3 KDF *SHALL BE* tested as a part of the vector set.  Note that message construction that is defined by the protocol for messages such as ClientHello, ServerHello, etc *SHALL NOT* be within the scope of ACVP testing.
* RFC8446 - 4.4.1 The Transcript Hash.  The transcript hash is used within section 7.1 for deriving keying material and as such *SHALL BE* tested as a part of ACVP testing.

[[not-coverage]]
==== Requirements Not Covered

* RFC8446 - ACVP testing for the TLS v1.3 KDF is done to ensure proper implementation of the KDF portion of the RFC; as such TLS protocol specific pieces are not tested.  Protocol specific construction of messages such as the ClientHello, ServerHello, etc *SHALL NOT* be within the scope of ACVP testing.
