
[#properties]
=== Property Registration

[#registration]
=== Registration Example

A registration *SHALL* use these properties

.TLS Registration JSON Values
|===
| JSON Property | Description | JSON Type | Valid Values

| algorithm | Name of the algorithm to be validated | string | "TLS-v1.3"
| mode | Mode of the algorithm to be validated | string | "KDF"
| revision | ACVP Test version | string | "RFC8446"
| hmacAlg | HMAC functions supported | array | See <<valid-hmac>>
| runningMode | The supported key exchange modes for the KDF https://tools.ietf.org/html/rfc8446#section-2 | array | See <<valid-runningMode>>
|===

[#valid-hmac]
==== Valid HMAC Functions

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'hmacAlg' property

* SHA1
* SHA2-224
* SHA2-256
* SHA2-384
* SHA2-512
* SHA2-512/224
* SHA2-512/256
* SHA3-224
* SHA3-256
* SHA3-384
* SHA3-512

[#valid-runningMode]
==== Valid Running Modes

The following hash functions *MAY* be advertised by an ACVP compliant client under the 'runningMode' property

* PSK
* DHE
* PSK-DHE

An example registration within an algorithm capability exchange looks like this

[align=left,alt=,type=]
[source, json]
----
{
  "algorithm": "TLS-v1.3",
  "mode": "KDF",
  "revision": "RFC8446",
  "hmacAlg": [
    "SHA1",
    "SHA2-224",
    "SHA2-256",
    "SHA2-384",
    "SHA2-512",
    "SHA2-512/224",
    "SHA2-512/256",
    "SHA3-224",
    "SHA3-256",
    "SHA3-384",
    "SHA3-512"
  ]
}
----

