
[[tgjs]]
=== Test Groups

The testGroups element at the top level in the test vector JSON object is an array of test  groups. Test vectors are grouped into similar test cases to reduce the amount of data transmitted in the vector set. For instance, all test vectors that use the same key size would be grouped together. The Test Group JSON object contains meta data that applies to all test vectors within the group. The following table describes the {spec-algorithm} JSON elements of the Test Group JSON object

.Test Group JSON Object
|===
| JSON Value | Description | JSON Type

| tgId | Test group identifier | integer
| testType | Test operations to be performed | string
| hmacAlg | SHA version used | string
| runningMode | The key exchange mode used | string
| tests | Array of individual test cases | array
|===

The 'tgId', 'testType' and 'tests' objects *MUST* appear in every test group element communicated from the server to the client as a part of a prompt. Other properties are dependent on which 'testType' (see <<testtypes>>) the group is addressing.

=== Test Cases

Each test group contains an array of one or more test cases. Each test case is a JSON object that represents a single test vector to be processed by the ACVP client. The following table describes the JSON elements for each {spec-algorithm} test vector.

.Test Case JSON Object
|===
| JSON Value | Description | JSON Type

| tcId | Test case identifier | integer
| psk | Random pre-shared key, included for PSK and PSK-DHE running modes. | hex
| dhe | Random Diffie-Hellman shared secret, included for DHE and PSK-DHE running modes. | hex
| helloClientRandom | Randomly generated Client Hello message | hex
| helloServerRandom | Randomly generated Server Hello message | hex
| finishedClientRandom | Randomly generated Client Finished message | hex
| finishedServerRandom | Randomly generated Server Finished message | hex
|===

Note that when the PSK or DHE are not included in the test case, it is assumed they are the digest size of the group's hash set to zero.  As an example, for a test group using SHA2-256, with a running mode of "DHE", the "PSK" would be represented by a BitString of 256 bits or 32 bytes, all being "0".

Here is an abbreviated yet fully constructed example of the prompt.

[align=left,alt=,type=]
[source, json]
----
{
    "vsId": 1,
    "algorithm": "TLS-v1.3",
    "mode": "KDF",
    "revision": "RFC8446",
    "testGroups": [
        {
            "tgId": 1,
            "testType": "AFT",
            "hmacAlg": "SHA2-256",
            "runningMode": "PSK-DHE",
            "tests": [{
                "tcId": 1,
                "psk": "C2A39E5D172C7D147B5FD3752E4C0840EDDF7C5684B00E7B1AA20B7F56CF64F1EE05",
                "dhe": "EE6ADDBC8BDF014254051D78D7A0ECE35AAB230024647E871B375C257E23FC814235",
                "helloClientRandom": "7613AA5EAC7D233CCFF764C95D22B6BB026C087DF017E04C5AF6F0E2C1C9E3FA134F",
                "helloServerRandom": "A1CDA1FC4A72BF85FAEC964AF1CBB421BA1FD683513C24D11EE0B0092190C729ECD4",
                "finishedClientRandom": "F77C6488E63463FEDACA4CEF38F66E1957BDCB1F9A6719029F75590687487AF7F235",
                "finishedServerRandom": "9B562F22963D4A9C96DA93A1E3AA5F88A48CA7A0EA92D293AA7C72AD9A71A4DF911B"
            }]
        }
    ]
}
----
