
[#responses]
== Responses

After the ACVP client downloads and processes a vector set, it must send the response vectors back to the ACVP server. The following table describes the JSON object that represents a vector set response.

.Vector Set Response JSON Object
|===
| JSON Property | Description | JSON Type

| acvVersion | The version of the protocol | string
| vsId | The vector set identifier | integer
| testGroups | The test group data | array
|===

An example of this is the following

[align=left,alt=,type=]
[source, json]
----
{
    "acvVersion": "version",
    "vsId": 1,
    "testGroups": [ ... ]
}
----

The testGroups section is used to organize the ACVP client response in a similar manner to how it receives vectors. Several algorithms *SHALL* require the client to send back group level properties in their response. This structure helps accommodate that.

.Vector Set Group Response JSON Object
|===
| JSON Property | Description | JSON Type

| tgId | The test group identifier | integer
| tests | The test case data | array
|===

An example of this is the following

[align=left,alt=,type=]
[source, json]
----
{
    "tgId": 1,
    "tests": [ ... ]
}
----

The following table describes the JSON object that represents a test case response for a {spec-algorithm}.

.Test Case Results JSON Object
|===
| JSON Property | Description | JSON Type

| tcId | The test case identifier | integer


| clientEarlyTrafficSecret | The client early traffic secret. `Derive-Secret(., "c e traffic", ClientHello)` | hex
| serverEarlyTrafficSecret | The server early traffic secret. `Derive-Secret(., "s e traffic", ClientHello)` | hex

| clientHandshakeTrafficSecret | The client handshake traffic secret. `Derive-Secret(., "c hs traffic", ClientHello...ServerHello)` | hex
| serverHandshakeTrafficSecret | The server handshake traffic secret. `Derive-Secret(., "s hs traffic", ClientHello...ServerHello)` | hex

| clientApplicationTrafficSecret | The client application traffic secret. `Derive-Secret(., "c ap traffic", ClientHello...server Finished)` | hex
| serverApplicationTrafficSecret | The server application traffic secret. `Derive-Secret(., "s ap traffic", ClientHello...server Finished)` | hex
| exporterMasterSecret | The exporter master secret. `Derive-Secret(., "exp master", ClientHello...server Finished)` | hex
| resumptionMasterSecret | The resumption master secret. `Derive-Secret(., "res master", ClientHello...client Finished)` | hex
|===

Here is an abbreviated example of the response

[align=left,alt=,type=]
[source, json]
----
{
  "vsId": 1,
  "testGroups": [{
    "tgId": 1,
    "tests": [{
      "tcId": 1,
      "clientEarlyTrafficSecret": "889A0D6D2FEE8A4354FC0B46E1D29BD56425D5BF4C392B35611C8396F79A3155",
      "earlyExporterTrafficSecret": "FB91D4B12909086664C55DDAC27AE05ABE5C6F1A75608CA684D5A4C3060CDC12",
      "clientHandshakeTrafficSecret": "C029A02F8BA8EA6B1E6C288060A26865CFFA6E9AC5034DB5EC6AB0813E90A3BD",
      "serverHandshakeTrafficSecret": "EE099247305B84196773FADCAA3A9953655FD127921FA4B392FDC3A891F3F28F",
      "clientApplicationTrafficSecret": "FB2CB3F715EC90A396A2241B561F89462E486DCCE294ABA7356B23A7BE6D1199",
      "serverApplicationTrafficSecret": "8FE3438CAA0BFD48AC0D7022F618DA971491C3060567256B342E23D3CA3454E6",
      "exporterMasterSecret": "0349DD92F3B5D85238E46526923F97FB1529CA8CD33BB37A1658E7003F9B272D",
      "resumptionMasterSecret": "890B83EA14D193DF236F904B8190144A7F1025F8C7CEA8BB099664F261356019"
    }]
  }]
}
----
