name: build-documents

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/metanorma/metanorma-nist:latest
      credentials:
        username: metanorma-ci
        password: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: /config/fonts
          key: metanorma-nist-fonts
          restore-keys: metanorma-nist-fonts

      - uses: metanorma/metanorma-build-scripts/gh-rubygems-setup-action@main
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

      - uses: metanorma/metanorma-build-scripts/docker-gem-install@main

      - uses: actions-mn/cli/site-gen@main
        with:
          agree-to-terms: true

      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: site

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v1
        with:
          name: site

      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_DEPLOY_KEY }}
          publish_dir: ./site
          publish_branch: nist-pages
          force_orphan: true
          enable_jekyll: true
          user_name: ${{ github.actor }}
          user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
          commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"

      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ github.token }}
          expire-in: 0
